Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-09, with the labels that each got.

#399 [VAS] BUG 8521 fixe probative value issue
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.service.ts
Labels: bug, small, VAS

#395 [CEA] TULEAP 24684 : Agency REF create - validation doublons name
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
Labels: bug, small, CEA

#407 [VAS] Téléchargement des rapports DIPs
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookService.java
  commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookServiceTest.java
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
Labels: enhancement, small, VAS

#396 [CEA] TULEAP 24209 : Fix search rules queries and rule type filter
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dsl/VitamQueryHelper.java
Labels: bug, small, CEA

#412 [VAS] Item 8655 : Add roles to Ingest_App_Profile
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
Labels: bug, small, VAS

#414 [VAS] BUG 8656 : Dans l' APP Recherche, sur le panneau d'information …
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#415 [VAS] Item 8651 : fixe R16 Bugs
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/rest/RestApi.java
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalRestClient.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/service/IngestExternalService.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestInternalRestClient.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  ui/ui-frontend-common/src/app/modules/components/editable-field/editable-level-input/editable-level-input.component.html
  ui/ui-frontend-common/src/app/modules/components/editable-field/level-input/level-input.component.html
  ui/ui-frontend-common/src/app/modules/components/header/header.component.html
  ui/ui-frontend-common/src/app/modules/components/header/menu/menu-application-tile/menu-application-tile.component.html
  ui/ui-frontend-common/src/app/modules/components/header/menu/menu.component.html
  ui/ui-frontend-common/src/app/modules/components/header/select-tenant-dialog/select-tenant-dialog.component.html
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/ingest/src/app/core/api/ingest-api.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-frontend/projects/referential/src/app/app.module.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.module.ts
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/service/IngestService.java
Labels: VAS, Cherry-Pick

#418 [VAS] Bug 8448 : Disable merge_index_apache task in reverse role
  deployment/roles/reverse/tasks/main.yml
Labels: bug, small, VAS

#424 [VAS] Ticket 8448 : Disable merge_index_apache task in reverse role
  deployment/roles/reverse/tasks/main.yml
Labels: bug, small, VAS, Cherry-Pick

#419 Cea fix rules and external params customer init
  deployment/roles/vitamui/files/customer-init.yml
Labels: small, CEA

#422 [CEA] Fix customer_init Import/Export Rules
  deployment/roles/vitamui/files/customer-init.yml
Labels: small, Cherry-Pick, CEA

#425 [VAS] Bug 8045 : Correct VitamUI bugs
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/logbookmanagement/LogbookManagementOperationInternalService.java
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/sass/_tooltip.scss
  ui/ui-frontend/projects/referential/src/app/core/api/operation-api.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.component.ts
Labels: bug, small, VAS

#426 [VAS] Vas 6966: revert cea app pr21
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceTest.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-edit-permission/context-edit-permission.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-information-tab/context-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context.component.ts
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
Labels: bug, small, VAS

#428 [VAS] Bug 8651 : correct r16 bugs
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/UnitExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/31_update_referential_ui_contexts.js.j2
  deployment/scripts/mongod/2.0.0/32_add_filling_plan_access_role_to_profiles.js.j2
  ui/ui-frontend-common/src/app/modules/components/header/header.component.html
  ui/ui-frontend-common/src/app/modules/components/header/select-language/select-language.component.html
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-list/context-list.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-list/ontology-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-list/security-profile-list.component.html
Labels: bug, small, VAS

#427 [VAS] Item 8507 add tls protocols version on SMTP Server on CAS
  deployment/environments/group_vars/all/infra.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
Labels: bug, small, VAS, Don't delete branch

#429 [VAS] Fixe archive referential redirection issue
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
  ui/ui-frontend/projects/referential/src/app/core/api/operation-api.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-information-tab/logbook-management-operation-information-tab.component.html
Labels: bug, small, VAS

#431 [VAS] Item 8681 : CP odt generator
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/enums/Extension.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestInternalRestClient.java
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestODTGenerator.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/exception/IngestFileGenerationException.java
  pom.xml
Labels: small, VAS, Cherry-Pick

#437 Set up version from 4.5.0-SNAPSHOT to 5.0-SNAPSHOT
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: small

#436 Set up version from 4.5.0-SNAPSHOT to 5.rc.1-SNAPSHOT on master 5.rc.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: small

#439 [VAS] story #8529 Update pipeline for new naming convention
  Jenkinsfile
Labels: small

#441 Fix bump pom from 5.0 snapshot to 5.rc.1 snapshot on master 5.rc.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: small

#444 Set up version from 4.0.4-SNAPSHOT to 4.0.5-SNAPSHOT
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: small

#443 [VAS] Bug : 8601 : correct search bug with title and description
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/DescriptionDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ResultsDto.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/models/unit.interface.ts
Labels: bug, small, VAS

#434 [CEA] Fix FileFormat update with empty mimeType and extensions
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
Labels: bug, small, CEA

#435 [CEA] Set rule description to mandatory
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
Labels: bug, small, CEA

#442 [CEA] Fix translations in referentials
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/locale/messages.en.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.fr.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.xlf
Labels: bug, small, CEA

#448 [VAS] ITEM 8658 : modify filter types behavior on search results
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: enhancement, small, VAS

#447 [VAS] BUG 7428 : Return empty string when ua don't have parent
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, small, VAS

#453 Story 8676 cea erreur ansible installation vitamui master 4.0.x
  deployment/README.rst
  deployment/roles/browser/tasks/main.yml
  deployment/vitamui.yml
  deployment/vitamui_extra.yml
Labels: small, VAS, Cherry-Pick

#450 [VAS] BUG 8161 : correct Archive-search DSL query
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
Labels: bug, small, VAS

#454 bug cea installation vitamui
  deployment/README.rst
  deployment/roles/browser/tasks/main.yml
  deployment/roles/reverse/tasks/main.yml
  deployment/vitamui.yml
  deployment/vitamui_extra.yml
Labels: small

#456 [Vas] Vas item 8666 create external param profile when creating tenant
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/TenantCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceIntegTest.java
  deployment/roles/vitamui/files/customer-init.yml
Labels: enhancement, small, VAS

#451 [VAS] BUG 8586 : correct progress bar issue
  ui/ui-frontend-common/src/app/modules/components/common-progress-bar/common-progress-bar.component.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
Labels: bug, small, VAS

#459 [VAS] Bug 8527 : Minors bugs on accession register
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dsl/VitamQueryHelper.java
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
Labels: bug, small, VAS

#458 [VAS] BUG 8678 : Correct Download button title
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
Labels: bug, small, VAS

#460 [VAS] Bug 8660 - Make application EXTERNAL_PARAM_PROFILE_APP multi tenant
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
  deployment/scripts/mongod/2.0.0/38_update_external_params_profiles_app_multi_tenant_flag.js.j2
Labels: bug, small, VAS

#461 [VAS] Add playbook and role to generate host_vars with 2 networks.
  deployment/generate_hostvars_for_2_network_interfaces.yml
  deployment/roles/generate_hostvars_for_2_network_interfaces/tasks/main.yml
Labels: enhancement, small, VAS, Highlight

#463 [VAS] Small improvements on ansible
  deployment/ansible.cfg
  deployment/environments/group_vars/all/consul_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/service_state/tasks/main.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
Labels: small, VAS

#464 [Vas] Story #7978 multi instances UI with reverse nginx
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/reverse/files/apache/page/css/app.css
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.svg
  deployment/roles/reverse/files/apache/page/css/material-icons.css
  deployment/roles/reverse/files/apache/page/css/styles.css
  deployment/roles/reverse/files/nginx/proxy_params
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/tasks/main.yml
  deployment/roles/reverse/tasks/nginx.yml
  deployment/roles/reverse/tasks/nginx/configure_nginx.yml
  deployment/roles/reverse/tasks/nginx/configure_vitamui_vhost.yml
  deployment/roles/reverse/tasks/nginx/nginx.yml
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
  deployment/roles/reverse/templates/apache/httpd_config
  deployment/roles/reverse/templates/apache/page/css/app.css
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.svg
  deployment/roles/reverse/templates/apache/page/css/material-icons.css
  deployment/roles/reverse/templates/apache/page/css/styles.css
  deployment/roles/reverse/templates/nginx/conf.d/proxy_vhosts.conf.j2
  deployment/roles/reverse/templates/nginx/conf.d/upstream.j2
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/reverse/templates/nginx/conf.d/vitam_proxy.conf.j2.BAK
  deployment/roles/reverse/templates/nginx/nginx.conf.j2
  deployment/roles/reverse/templates/nginx/ssl/ssl.conf.j2
Labels: bug, enhancement, small, VAS, Highlight

#471 CP R16 - Fix wrong serviceca certificate in reverse apache.
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/reverse/templates/apache/httpd_config
Labels: bug, small, VAS, Cherry-Pick

#470 Fix wrong serviceca certificate in reverse apache.
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/reverse/templates/apache/httpd_config
Labels: bug, small, VAS

#472 [VAS] add more corrections
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-internal/pom.xml
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.ts
Labels: bug, VAS, Cherry-Pick

#469 [Vas] Item 8660: add forgotten roles for profile app_external_params_profils
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/39_update_external_params_profiles_app_multi_tenant_flag.js.j2
Labels: bug, small, VAS

#475 correct audit create issue
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.ts
Labels: VAS, Cherry-Pick

#476 [VAS] Bug 8665 : Fix position behavior on search requests
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug, small, VAS

#478 [VAS] BUG 8233 : add download binary object types
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/model/ObjectQualifierTypeEnum.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-archive-search/src/test/resources/data/vitam_got_textcontent.json
Labels: bug, small, VAS

#484 [VAS] Fix typo in reverse nginx and ui-identity-admin.
  deployment/roles/reverse/templates/nginx/conf.d/upstream.j2
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
Labels: bug, small, VAS

#486 [VAS] Item 8679, 8736 : Password configuration i18n
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/InitPasswordConstraintsConfiguration.java
  cas/cas-server/src/main/resources/overriden_messages.properties
  cas/cas-server/src/main/resources/overriden_messages_de.properties
  cas/cas-server/src/main/resources/overriden_messages_en.properties
  cas/cas-server/src/main/resources/overriden_messages_fr.properties
  cas/cas-server/src/main/resources/templates/casLoginView.html
  cas/cas-server/src/main/resources/templates/fragments/pwdupdateform.html
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/pm/IamPasswordManagementServiceTest.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/commons/security/client/config/password/PasswordConfiguration.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/commons/security/client/password/PasswordValidator.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/PasswordValidatorTest.java
  commons/commons-security/src/test/resources/cas-server-application-test.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/environments/vitamui_extra_vars.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  docs/fr/exploitation/sections/procedure.md
  docs/fr/installation/sections/procedure.md
Labels: enhancement, small, VAS

#479 [VAS] Bug 8725 : Fix producers fetching on app audit
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/AccessionRegisterSummaryInternalRestClient.java
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit.service.ts
Labels: bug, small, VAS

#488 [VAS] Bug-8660- Fix wrong tenant on creating external params profile
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
Labels: bug, small, VAS
