Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-07, with the labels that each got.

#328 [CEA] : Fix absence de message quand on passe d'un onglet à l'autre sans enregistrer
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-preview.component.ts
Labels: CEA, bug, small

#332 [CEA] Fix : Référentiel contexte
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceTest.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-edit-permission/context-edit-permission.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-information-tab/context-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context.component.ts
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
Labels: CEA, bug, small

#335 [VAS] Bug : 8353 8354 : Gestion des opérations
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.html
Labels: VAS, bug, small

#333 [CEA] Fix : audits
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.ts
Labels: CEA, bug, small

#336 [VAS] : Bug 8354 add fixes to operation management
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.html
Labels: VAS, bug, small

#339 [VAS] Bug : 8316, 7711 fixe ingest search issue
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dsl/VitamQueryHelper.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
Labels: VAS, bug, small

#340 Add missing hosts_browse in inventory files.
  deployment/environments/hosts.example
  deployment/environments/hosts.local
  deployment/environments/hosts.vitam
  deployment/environments/hosts.vitamui
Labels: VAS, bug, small

#341 [VAS] Bug 8365 : Bug critique - Les imports d'arbres et de plan de classement sont tagués à tort comme des SIP standards
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
Labels: VAS, bug, small

#342 [VAS] Cherry-Pick - Bug 8365 : Bug critique - Les imports d'arbres et de plan de classement sont tagués à tort comme des SIP standards
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
Labels: Cherry-Pick, VAS, bug

#337 [CEA] Fix on rules search and update
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dsl/VitamQueryHelper.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
Labels: CEA, bug, small

#338 [CEA] : téléchargement de rapport vide
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/logbook/LogbookInternalRestClient.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/util/RestUtils.java
  commons/commons-rest/src/test/java/fr/gouv/vitamui/commons/rest/util/RestUtilsTest.java
Labels: CEA, bug, small

#346 [CEA] Import des règles de gestion avec corrections des mises à jour/suppressions
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/ReferentialExternalWebClientFactory.java
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/RuleExternalRestClient.java
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/RuleExternalWebClient.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/config/ApiReferentialServerConfig.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/RuleExternalService.java
  api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/RuleExternalServiceTest.java
  api/api-referential/referential-external/src/test/resources/data/import_rules_valid.csv
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ReferentialInternalWebClientFactory.java
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/RuleInternalRestClient.java
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/RuleInternalWebClient.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/RuleInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/scripts/mongod/1.0.0/307_iam_ref.js.j2
  deployment/scripts/mongod/1.0.0/310_security_ref.js.j2
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/back/steps/referential/fileFormat/ApiReferentialExternalFileFormatCreationSteps.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/back/steps/referential/rule/ApiReferentialExternalRuleCreationSteps.java
  integration-tests/src/test/resources/data/import_rules_invalid.csv
  integration-tests/src/test/resources/data/import_rules_valid.csv
  integration-tests/src/test/resources/features/back/referential/rule/ExternalRuleCreation.feature
  ui/ui-frontend/projects/referential/src/app/core/api/rule-api.service.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.service.ts
  ui/ui-frontend/projects/referential/src/app/shared/vitamui-import-dialog/referential.enum.ts
  ui/ui-frontend/projects/referential/src/app/shared/vitamui-import-dialog/vitamui-import-dialog.component.html
  ui/ui-frontend/projects/referential/src/app/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/config/ReferentialContextConfiguration.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/RuleController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/service/RuleService.java
Labels: CEA, small

#344 [CEA] Problème d'affichage du profil de sécurité
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-preview/security-profile-permissions-tab/security-profile-permissions-tab.component.ts
Labels: CEA, bug, small

#345 [VAS] Add external param to init customer on iam-internal
  api/api-iam/iam-internal/src/main/config/customer-init.yml
Labels: VAS, small

#343 [VAS] Fix fatal context imports
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/converter/ContextDtoConverterUtil.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamContextService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamContextServiceTest.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/utils/ReferentialDtoBuilder.java
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
Labels: VAS, bug, small

#355 [VAS] Bug : fixe referential applications issue
  ui/ui-frontend/projects/archive-search/ngsw-config.json
  ui/ui-frontend/projects/ingest/ngsw-config.json
  ui/ui-frontend/projects/referential/ngsw-config.json
  ui/ui-frontend/projects/referential/src/app/app.module.ts
Labels: VAS, bug, small

#356 [vas] Debian packaging (CP R16)
  Jenkinsfile
  cots/vitamui-logstash/Makefile
  cots/vitamui-logstash/pom.xml
  cots/vitamui-logstash/templates/after-install.sh
  cots/vitamui-logstash/templates/before-remove.sh
  cots/vitamui-mongo-express/Makefile
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongo-express/templates/after-install.sh
  cots/vitamui-mongo-express/templates/before-remove.sh
  cots/vitamui-mongod/Makefile
  cots/vitamui-mongod/pom.xml
  cots/vitamui-mongod/templates/after-install.sh
  cots/vitamui-mongod/templates/before-remove.sh
  cots/vitamui-nginx/Makefile
  cots/vitamui-nginx/pom.xml
  cots/vitamui-nginx/templates/after-install.sh
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
  pom.xml
  tools/packaging/Makefile
  tools/packaging/templates/after-install.sh
  tools/packaging/templates/after-remove.sh
  tools/packaging/templates/before-remove.sh
  ui/ui-identity/pom.xml
Labels: Cherry-Pick

#357 [CEA] CP 326, 328, 329, 330, 331, 337, 338, 344
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dsl/VitamQueryHelper.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
  api/api-referential/referential-internal/src/main/config/referential-internal-application-dev.yml
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/logbook/LogbookInternalRestClient.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/util/RestUtils.java
  commons/commons-rest/src/test/java/fr/gouv/vitamui/commons/rest/util/RestUtilsTest.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.scss
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-preview/security-profile-permissions-tab/security-profile-permissions-tab.component.ts
  ui/ui-referential/src/main/resources/ui-referential-application.yml
Labels: CEA, Cherry-Pick, small

#360 Fix external parameter profile attachment
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
Labels: VAS, small

#362 story #8432 added DIN and DEX documentations
  docs/fr/exploitation/_toc.rst
  docs/fr/exploitation/index.md
  docs/fr/exploitation/metadata.yaml
  docs/fr/exploitation/sections/annexes.md
  docs/fr/exploitation/sections/introduction.md
  docs/fr/exploitation/sections/procedure.md
  docs/fr/installation/_toc.rst
  docs/fr/installation/images/vitam-contexts.png
  docs/fr/installation/images/vitamui-consul-1.png
  docs/fr/installation/images/vitamui-consul-2.png
  docs/fr/installation/images/vitamui-context.png
  docs/fr/installation/images/vitamui-login.png
  docs/fr/installation/index.md
  docs/fr/installation/metadata.yaml
  docs/fr/installation/sections/annexes.md
  docs/fr/installation/sections/introduction.md
  docs/fr/installation/sections/prerequis.md
  docs/fr/installation/sections/procedure.md
Labels: documentation, small

#361 [XEL] Upgrade npm version to 7
  pom.xml
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: Xelians, small

#374 [VAS] add option for build front module after upgrade npm
  pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-frontend-common/install_from_repo.sh
  ui/ui-frontend-common/install_local.sh
  ui/ui-frontend/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-referential/pom.xml
Labels: VAS, bug, small

#367 [CEA]: File format import - conf de la taille max du fichier importé et gestion du timeout
  api/api-referential/referential-external/src/main/config/referential-external-application-dev.yml
  api/api-referential/referential-internal/src/main/config/referential-internal-application-dev.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
  ui/ui-referential/src/main/config/ui-referential-application-recette.yml
  ui/ui-referential/src/main/resources/ui-referential-application.yml
Labels: CEA, bug, small

#370 [VAS] Fix wrong external profile app name in customer init
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: VAS, bug, small

#376 [VAS] Item 8359 : correction suite recette métier
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/IngestContractDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
  ui/ui-frontend-common/src/app/modules/logbook/logbook.module.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-list/ingest-contract-list.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
Labels: VAS, bug, small

#375 [CEA] CP 367 (File format import - conf de la taille max du fichier importé et gestion du timeout)
  api/api-referential/referential-external/src/main/config/referential-external-application-dev.yml
  api/api-referential/referential-internal/src/main/config/referential-internal-application-dev.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
  ui/ui-referential/src/main/config/ui-referential-application-recette.yml
  ui/ui-referential/src/main/resources/ui-referential-application.yml
Labels: CEA, Cherry-Pick, bug, small
