Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-11, with the labels that each got.

#511 [Vas] Vas bugs list : 7516,8095,8288,8431,8510,8723,8737,8741,8754
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  cas/cas-server/src/main/resources/static/css/cas.css
  ui/ui-frontend-common/icomoon-selection.json
  ui/ui-frontend-common/src/app/modules/models/profile/access-contract.interface.ts
  ui/ui-frontend-common/src/sass/_badge.scss
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
  ui/ui-frontend-common/src/sass/variables/_colors.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.ts
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.ts
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.service.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/portal/src/sass/styles.scss
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-list/file-format-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-list/ontology-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, VAS

#530 [VAS] CP5RC - Update nginx vhost configuration for ingest.
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/reverse/tasks/nginx/configure_nginx.yml
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/reverse/templates/nginx/nginx.conf.j2
Labels: bug, VAS, Cherry-Pick

#538 Fix Upgrade build context jenkinsfile step node and npm remove
  Jenkinsfile
Labels: bug, small

#540 [Vas] Item 9009 : Adapt archive search by appraisal rules to new Vitam model for master 5 rc
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-final-action-elimination-rules-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-final-action-keep-rules-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-inherited-only-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-inherited-or-scoped-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-no-rules-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-waiting-to-recalculate-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/interval-date-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/one-date-query.txt
Labels: small, VAS

#541 fixe download bdx issue (#527)
  api/api-ingest/ingest-internal/src/main/config/ingest-internal-application-dev.yml
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-ingest/ingest-internal/src/test/resources/ingest-internal-application.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick

#542 fixe download bdx issue (#527)
  api/api-ingest/ingest-internal/src/main/config/ingest-internal-application-dev.yml
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-ingest/ingest-internal/src/test/resources/ingest-internal-application.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick

#532 [VAS] Item 8673 order filling holding scheme trees
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/fillingholding/expected_query.json
Labels: enhancement, small, VAS

#533 [VAS] - Doc - Upgrade PKI on Vitam Virtual Machine
  tools/vitamui-conf-dev/README.md
Labels: documentation, enhancement, small, VAS

#543 [Vas] Item 9009 : Adapt archive search by appraisal rules to new Vitam model
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-final-action-elimination-rules-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-final-action-keep-rules-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-inherited-only-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-inherited-or-scoped-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-no-rules-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/identifier-waiting-to-recalculate-rule-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/interval-date-query.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/one-date-query.txt
Labels: small, VAS

#544 [Vas] Bug fix Upgrade build context jenkinsfile step node and npm remove
  Jenkinsfile
Labels: bug, VAS, Cherry-Pick

#545 [Vas] Item-7392- DOC- add documentation for managing api iam timout
  docs/fr/exploitation/sections/procedure.md
Labels: documentation, small, VAS

#537 [VAS] BUG 9025 : delete illegal characters from manifest document
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  cas/cas-server/src/main/resources/static/css/cas.css
  ui/ui-ingest/src/main/resources/application-dev.yml
  ui/ui-ingest/src/main/resources/dev/keystore_ui-referential.jks
Labels: bug, small, VAS

#555 [VAS] BUG : 9087 fixe header font-style
  ui/ui-frontend-common/src/styles.scss
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.scss
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.scss
  ui/ui-frontend/projects/ingest/src/sass/_date-filter.scss
  ui/ui-frontend/projects/ingest/src/sass/styles.scss
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.scss
Labels: bug, small, VAS

#551 [VAS] PROD : 8903 : correct referential applications creation button issue
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, VAS

#535 [VAS] ITEM 7516 : correct authentication redirection issue
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/enums/AttachmentType.java
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/files/ui/assets/logo_USER.png
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  ui/ui-archive-search/src/main/resources/application-dev.yml
  ui/ui-archive-search/src/main/resources/application-recette.yml
  ui/ui-archive-search/src/main/resources/assets/logo_USER.png
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/config/UIPropertiesImpl.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/property/UIProperties.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/ApplicationService.java
  ui/ui-frontend-common/src/app/modules/account/account.component.ts
  ui/ui-frontend-common/src/app/modules/components/header/user-photo/user-photo.component.html
  ui/ui-frontend-common/src/app/modules/components/header/user-photo/user-photo.component.ts
  ui/ui-frontend-common/src/app/modules/models/app.configuration.interface.ts
  ui/ui-frontend-common/src/app/modules/models/customer/graphic-identity.interface.ts
  ui/ui-frontend-common/src/app/modules/models/customer/theme/attachmentType.enum.ts
  ui/ui-frontend-common/src/app/modules/models/customer/theme/themeDataType.enum.ts
  ui/ui-frontend-common/src/app/modules/startup.service.ts
  ui/ui-frontend-common/src/app/modules/theme.service.ts
  ui/ui-identity/src/main/config/ui-identity-application-recette.yml
  ui/ui-identity/src/main/resources/application-dev.yml
  ui/ui-identity/src/main/resources/assets/logo_USER.png
  ui/ui-ingest/src/main/resources/application-dev.yml
  ui/ui-ingest/src/main/resources/application-recette.yml
  ui/ui-ingest/src/main/resources/assets/logo_USER.png
  ui/ui-portal/src/main/config/ui-portal-application-recette.yml
  ui/ui-portal/src/main/resources/application-dev.yml
  ui/ui-portal/src/main/resources/assets/logo_USER.png
  ui/ui-referential/src/main/config/ui-referential-application-recette.yml
  ui/ui-referential/src/main/resources/application-dev.yml
  ui/ui-referential/src/main/resources/assets/logo_USER.png
Labels: bug, small, VAS
