Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-05, with the labels that each got.

#276 CP : update apps categories
  deployment/scripts/mongod/2.0.0/02_TRTL_449_update_application_categories_ref.js
Labels: Cherry-Pick, VAS

#274 [VAS] Bug- 7558: add space in alert message
  ui/ui-frontend/projects/ingest/src/app/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
Labels: VAS, bug, small

#281 [VAS] update apps categories
  deployment/scripts/mongod/2.0.0/02_TRTL_449_update_application_categories_ref.js
  deployment/scripts/mongod/2.0.0/08_update_context_application_category.js
Labels: VAS, small

#279 [XEL] Bugfixes
  deployment/scripts/mongod/2.0.0/05_TRTL-859_update_account_app_category_ref.js
  deployment/scripts/mongod/2.0.0/06_TRTL-895_update_system_customer_read_only_ref.js
  ui/ui-frontend/projects/identity/src/app/customer/customer.component.html
Labels: Xelians, small

#282 [VAS] BUG 8007 APP Recherche : correction de libellés
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: VAS, bug, small

#284 [Vas] Item 7654 - add default settings for backup/ restore and debian settings
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: VAS, small

#283 [VAS] Item-7974 disable TLS 1.0 version
  api/api-archive-search/archive-search-external/src/main/config/archive-search-external-application-dev.yml
  api/api-iam/iam-external/src/main/config/iam-external-application-dev.yml
  api/api-ingest/ingest-external/src/main/config/ingest-external-application-dev.yml
  api/api-referential/referential-external/src/main/config/referential-external-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-archive-search/src/main/config/ui-archive-search-application-recette.yml
  ui/ui-archive-search/src/test/resources/ui-archive-search-application.yml
  ui/ui-identity/src/main/config/ui-identity-application-dev.yml
  ui/ui-identity/src/main/config/ui-identity-application-recette.yml
  ui/ui-identity/src/test/resources/ui-identity-application.yml
  ui/ui-ingest/src/main/config/ui-ingest-application-dev.yml
  ui/ui-ingest/src/main/config/ui-ingest-application-recette.yml
  ui/ui-ingest/src/test/resources/ui-ingest-application.yml
  ui/ui-portal/src/main/config/ui-portal-application-dev.yml
  ui/ui-portal/src/main/config/ui-portal-application-recette.yml
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
  ui/ui-referential/src/main/config/ui-referential-application-recette.yml
  ui/ui-referential/src/test/resources/ui-referential-application.yml
Labels: VAS, small

#275 [VAS] Bug- 7977: Fix path traversal bug
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalWebClient.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestInternalWebClient.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
Labels: VAS, bug, small

#255 [VAS] item 8016 : upgrade Spring framework
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/MongoDbConfig.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/TestMongoConfig.java
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/config/MongoDbConfig.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/converter/ExternalParametersConverter.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/converter/UserConverter.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/TestMongoConfig.java
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  api/api-referential/referential-external/pom.xml
  api/api-security/security-internal/pom.xml
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/config/MongoDbConfig.java
  api/api-security/security-internal/src/test/java/fr/gouv/vitamui/security/server/TestMongoConfig.java
  commons/commons-api/pom.xml
  commons/commons-api/src/test/java/fr/gouv/vitamui/commons/api/logger/FakeLoggerTest.java
  commons/commons-logbook/src/test/java/fr/gouv/vitamui/commons/logbook/TestMongoConfig.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/config/MongoConfig.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/config/TestMongoConfig.java
  integration-tests/pom.xml
  pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: VAS, small

#288 [VAS] Vas item 8155 fix underscore vulnerabilities
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: VAS, small

#290 VAS: corrections bugs graphiques sur les app utilisateurs et organisa…
  ui/ui-frontend-common/src/sass/material/_modal.scss
  ui/ui-frontend/projects/identity/src/app/customer/customer.component.scss
Labels: VAS, bug, small

#291 [VAS] : add DAT VitamUI
  docs/DAT/DAT-VITAMUI.pdf
  docs/DAT/docs/dat_vitamui/index.md
Labels: VAS, documentation, small

#292 [VAS] Bug 7332 : Pouvoir agir sur la taille du panneau d'arborescence de l'app recherche
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend-common/src/app/modules/directives/resize-sidebar/resize-sidebar.directive.spec.ts
  ui/ui-frontend-common/src/app/modules/directives/resize-sidebar/resize-sidebar.directive.ts
  ui/ui-frontend-common/src/app/modules/directives/resize-sidebar/resize-sidebar.module.ts
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.scss
Labels: VAS, bug, small

#293 [VAS] design fixes and filing holding trees initialization
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/search-criteria-list.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: VAS, small

#295 [VAS] Item 7021 - Règles de formattage de code et documentation associée
  ui/ui-frontend-common/.prettierignore
  ui/ui-frontend-common/.prettierrc
  ui/ui-frontend/.prettierignore
  ui/ui-frontend/.prettierrc
  ui/ui-frontend/README.md
Labels: VAS, documentation, small

#297 [VAS] BUG 7332 : Correction sur la position de la barre permettant de…
  ui/ui-frontend-common/src/app/modules/directives/resize-sidebar/resize-sidebar.directive.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
Labels: VAS, bug, small

#298 [VAS] Vas bug 7561: Inclure les UA sans rattachement et corriger une erreur de design
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.scss
Labels: VAS, bug, small

#299 [VAS] BUG 7091 : App referential correction sur l'affichage des profi…
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.css
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-edit-permission/security-profile-edit-permission.component.scss
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-preview/security-profile-permissions-tab/security-profile-permissions-tab.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-preview/security-profile-permissions-tab/security-profile-permissions-tab.component.scss
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-preview/security-profile-permissions-tab/security-profile-permissions-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile.component.ts
Labels: VAS, bug, small

#301 [VAS] add serviceId to ingest app
  deployment/scripts/mongod/2.0.0/10_insert_serviceid_to_ingest_application_ref.js
Labels: VAS, bug, small

#302 [VAS] Vas bug 7561: Inclure les UA sans rattachement et corriger une erreur de design
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
Labels: VAS, bug, small
