Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-08, with the labels that each got.

#382 Add missing hosts_browse in inventory files.
  deployment/environments/hosts.example
  deployment/environments/hosts.local
  deployment/environments/hosts.vitam
  deployment/environments/hosts.vitamui
Labels: Cherry-Pick, small

#386 [VAS] Fix master 4.0.x build
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend-common/src/app/modules/application.service.ts
  ui/ui-frontend-common/src/app/modules/externalParameters.enum.ts
  ui/ui-frontend-common/src/app/modules/externalParameters.service.ts
  ui/ui-frontend-common/src/app/modules/index.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.html
Labels: bug, small, VAS

#387 [VAS] Bug 8511 : Droits suite à l'attribution d'un Paramétrages externes avec un nouveau profil
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/dao/ExternalParamProfileRepository.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/dao/ExternalParamProfileCustomRepositoryTest.java
Labels: small, VAS

#389 [VAS] BUG 8382 : fixe operation management bugs
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation.component.scss
  ui/ui-frontend/projects/referential/src/sass/_tooltip.scss
Labels: bug, small, VAS

#388 [VAS] Item 8342 : add new profils to archive-search application
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/VitamuiRoles.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/28_update_create_profiles_archive_search.js.j2
  deployment/scripts/mongod/2.0.0/29_new_update_archive_search_context.js.j2
  ui/ui-frontend-common/src/app/modules/vitamui-roles.enum.ts
Labels: enhancement, small, VAS

#390 [VAS] BUG 8095 : fixe download manifest and LP issues
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.css
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
Labels: bug, small, VAS

#384 [VAS] Item 8434 - add other DescriptionLevel for archive units search
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#394 [Vas] Bug 8434: Wrong Description level added
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
Labels: bug, small, VAS

#401 [Vas] Item 8568 bump dependencies
  pom.xml
Labels: dependencies, small, VAS

#397 [VAS] BUG 7446 : add role to get the filling plan access
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/UnitExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/31_update_referential_ui_contexts.js.j2
  deployment/scripts/mongod/2.0.0/32_add_filling_plan_access_role_to_profiles.js.j2
  deployment/scripts/mongod/2.0.0/33_update_admin_externalParameters_value.js.j2
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-list/context-list.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-list/ontology-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-list/security-profile-list.component.html
Labels: bug, small, VAS

#402 [XELIANS] Prise en compte du type d'instance lors du lancement du CRON logbook
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/instance/InstanceConfiguration.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/instance/InstanceService.java
  commons/commons-api/src/test/java/fr/gouv/vitamui/commons/api/instance/InstanceServiceTest.java
  commons/commons-logbook/src/main/java/fr/gouv/vitamui/commons/logbook/config/LogbookSchedulingConfiguration.java
  commons/commons-logbook/src/test/java/fr/gouv/vitamui/commons/logbook/config/LogbookSchedulingConfigurationTest.java
Labels: enhancement, small, Xelians

#406 [Vas] Item 8308 search multiple guids values
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#393 [CEA] TULEAP 20350 : Agency REF update tab validation fix
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.ts
Labels: bug, small, CEA
