Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-06, with the labels that each got.

#307 Define specific names for vitamui services to avoid conflict with vitam services when using the same consul cluster.
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
Labels: VAS, bug, small

#304 Vas 7019 acces rapide outils vitam UI
  deployment/environments/group_vars/all/mongo_express_vars.yml
  deployment/roles/browser/tasks/main.yml
  deployment/roles/reverse/tasks/main.yml
  deployment/roles/reverse/tasks/merge_index_apache.yml
  deployment/vitamui_extra.yml
Labels: small

#308 become the access tool compliant for all partners
  deployment/roles/reverse/tasks/merge_index_apache.yml
Labels: small

#313 Vas 7019 acces rapide outils vitam UI fix2
  deployment/roles/reverse/tasks/merge_index_apache.yml
Labels: small

#322 [Vas] Bug - Correction suite au PR Xelians : Adjustment portal design #312
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
Labels: VAS, bug, small

#310 [VAS] ITEM 8263 : add facet common component
  deployment/scripts/mongod/2.0.0/24_update_logbook_operation_tooltip.js.j2
  ui/ui-frontend-common/src/app/modules/components/logbook-operation-facet/logbook-operation-facet.component.html
  ui/ui-frontend-common/src/app/modules/components/logbook-operation-facet/logbook-operation-facet.component.scss
  ui/ui-frontend-common/src/app/modules/components/logbook-operation-facet/logbook-operation-facet.component.spec.ts
  ui/ui-frontend-common/src/app/modules/components/logbook-operation-facet/logbook-operation-facet.component.ts
  ui/ui-frontend-common/src/app/modules/components/logbook-operation-facet/logbook-operation-facet.module.ts
  ui/ui-frontend-common/src/app/modules/models/operation/facet-colors.enum.ts
  ui/ui-frontend-common/src/app/modules/models/operation/facet-details.interface.ts
  ui/ui-frontend-common/src/app/modules/models/operation/index.ts
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
Labels: VAS, small

#311 Add Scroll pagination to Logbook Management Operation
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation.module.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: VAS, small

#325 [VAS] Mise à jour de la version de Vitam en 4.0.1
  pom.xml
Labels: VAS, dependencies, small

#326 [CEA] Fix admin-dsl screen
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.scss
Labels: CEA, bug, small

#329 [CEA] : Fix extensions file format
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
Labels: CEA, bug, small

#330 [CEA] Fix consultation journal des opérations de type vide
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
Labels: CEA, bug, small

#331 [CEA]: File format import - conf de la taille max du fichier importé
  api/api-referential/referential-internal/src/main/config/referential-internal-application-dev.yml
  ui/ui-referential/src/main/resources/ui-referential-application.yml
Labels: CEA, bug, small
