Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-04, with the labels that each got.

#230 [VAS] item 7570 : Generate ODT report for each Ingest uploaded
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/enums/Extension.java
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestODTGenerator.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/exception/IngestFileGenerationException.java
  pom.xml
Labels: VAS

#236 [Vas] Item 7686 : Modification sur les groupes de profils pour permettre l'attribution à un utilisateur du contrat d'accès par défaut
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/common/utils/EntityFactory.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/config/ApiIamServerConfig.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/dao/ExternalParametersRepository.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/domain/ExternalParameters.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/InitVitamTenantService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalServiceIntegrationTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CustomerCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/TenantCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/InitVitamTenantServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/utils/IamServerUtilsTest.java
  deployment/roles/vitamui/files/customer-init.yml
Labels: VAS, small

#240 [VAS] bug 7985 : Ajout d'une nouvelle application external_params pour permettre l'attribution à un utilisateur du contrat d'accès par défaut #236
  deployment/scripts/mongod/2.0.0/06_add_external_application.js.j2
Labels: VAS, bug, small

#238 [VAS] item 7735 multi instantiate vitamui micro services
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  deployment/scripts/mongod/1.0.0/315_security.populate_certificates_ref.js.j2
Labels: VAS

#245 [VAS] item 7558: Fix recharting bugs
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.scss
Labels: VAS, bug, small

#250 [VAS] fix contract issue
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
Labels: VAS, small

#247 [VAS] item 7975 : update json-Sanitizer and Bouncy Castle Provider
  pom.xml
Labels: VAS, dependencies, small

#248 [VAS] Bug : fix start and end Date issue
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: VAS, bug, small

#253 Vas bug 8050 contrat entrée
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
Labels: VAS, small

#251 Ticket 7973: Fix ansible inventory files.
  deployment/environments/hosts.example
  deployment/environments/hosts.local
Labels: bug, small

#254 Fix ansible inventory files. (#251)
  deployment/environments/hosts.example
  deployment/environments/hosts.local
Labels: bug, small

#237 [XEL] Add distributed tracing jaeger
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-external/src/main/config/iam-external-application-dev.yml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-internal/src/main/config/iam-internal-application-dev.yml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-external/src/main/config/referential-external-application-dev.yml
  api/api-referential/referential-internal/pom.xml
  api/api-referential/referential-internal/src/main/config/referential-internal-application-dev.yml
  api/api-security/security-internal/pom.xml
  api/api-security/security-internal/src/main/config/security-internal-application-dev.yml
  cas/cas-server/pom.xml
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  pom.xml
  tools/docker/jaeger/jaeger-docker-compose.yml
  ui/ui-identity/pom.xml
  ui/ui-identity/src/main/config/ui-identity-application-dev.yml
  ui/ui-portal/pom.xml
  ui/ui-portal/src/main/config/ui-portal-application-dev.yml
  ui/ui-referential/pom.xml
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
Labels: Xelians, small

#244 [VAS] item 6675 ingest error details
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/event-display-helper.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.css
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.module.ts
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
Labels: VAS, small

#246 [VAS] item 7657 : analyse regroupement des services
  docs/Regroupement des services VitamUI.md
Labels: VAS, documentation, small

#241 [XEL] Add aggregation capability
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalServiceTest.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/client/AbstractResourceClientService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AggregationRequestOperator.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/RequestParamDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/RequestParamGroupDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ResultsDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/service/BaseReadService.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/domain/AggregationResultValue.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/repository/VitamUIRepository.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/repository/impl/VitamUIRepositoryImpl.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/service/VitamUIReadService.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/PersonRepositoryTests.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BasePaginatingAndSortingRestClient.java
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/ParameterizedTypeReferenceFactory.java
Labels: Xelians, small

#257 [VAS] CP : analyse regroupement des services
  docs/Regroupement des services VitamUI.md
Labels: VAS, small

#258 [VAS] item 8009 : sanitize APIs
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/LogbookExternalController.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/ProfileExternalController.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/SubrogationExternalController.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/GroupInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/IdentityProviderInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/LogbookInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/OwnerInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/ProfileInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/SubrogationInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/TenantInternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/UserInternalController.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/FileFormatExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/IngestContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SecurityProfileExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AgencyInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/FileFormatInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/IngestContractInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/OntologyInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/OperationInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/RuleInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/SecurityProfileInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/CertificateCrudController.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/ContextController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/AccessContractTempController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/AccountController.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/LogbookController.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/SubrogationController.java
  ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/rest/OwnerController.java
  ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/rest/ProfileController.java
  ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/rest/UserController.java
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OperationController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/RuleController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/SecurityProfileController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/UnitController.java
Labels: VAS, small

#263 [VAS] Bug 7095: Modification du message d'erreur import CSV
  ui/ui-frontend-common/src/app/modules/vitamui-http-interceptor.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/shared/vitamui-snack-bar/vitamui-snack-bar.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/shared/vitamui-snack-bar/vitamui-snack-bar.module.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: VAS, bug, small

#264 [VAS] Bug 7095: Correction du cleaner CSV
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ExportSearchResultParam.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
Labels: VAS, bug, small

#269 [VAS] Bug 7095: Bug double clé dans une MAP
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ExportSearchResultParam.java
Labels: VAS, bug, small

#270 [VAS] Bug- 7558: add space in message
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
Labels: VAS, bug, small

#268 [VAS] Item 8097 : Ajout de la configuration Jaeger dans les modules VAS
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-external/src/main/config/archive-search-external-application-dev.yml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/archive-search-internal/src/main/config/archive-search-internal-application-dev.yml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-external/src/main/config/ingest-external-application-dev.yml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/ingest-internal/src/main/config/ingest-internal-application-dev.yml
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  docs/Jaeger.md
  ui/ui-archive-search/pom.xml
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-ingest/pom.xml
  ui/ui-ingest/src/main/config/ui-ingest-application-dev.yml
Labels: VAS, small

#271 [VAS] Item 7588 : update apps categories
  deployment/scripts/mongod/2.0.0/02_TRTL_449_update_application_categories_ref.js
Labels: VAS, small
