Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-12, with the labels that each got.

#558 [VAS] item 7960 system customer color
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-colors-input/input-color/input-color.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.html
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/graphic-identity-tab/graphic-identity/graphic-identity-form/graphic-identity-form.component.html
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/graphic-identity-tab/graphic-identity/graphic-identity-form/graphic-identity-form.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/graphic-identity-tab/graphic-identity/graphic-identity.component.html
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/graphic-identity-tab/graphic-identity/graphic-identity.component.ts
Labels: enhancement, small, VAS, Security

#552 [VAS] item 8925 Bump Spring Core, Spring Boot, Spring Security
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/ApiArchivesSearchInternalApplicationTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/TestMongoConfig.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/config/ApiArchiveSearchInternalServerConfigTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/config/SearchCriteriaHistoryInternalServerConfigTest.java
  api/api-iam/iam-external/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/TestMongoConfig.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/config/ApiIamServerConfigTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
  api/api-ingest/ingest-internal/src/test/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfigTest.java
  api/api-referential/referential-external/src/main/resources/application-dev.yml
  api/api-referential/referential-internal/src/main/resources/application-dev.yml
  api/api-security/security-internal/pom.xml
  api/api-security/security-internal/src/main/resources/application-dev.yml
  api/api-security/security-internal/src/test/java/fr/gouv/vitamui/security/server/ApiSecurityApplicationTest.java
  commons/commons-logbook/src/test/java/fr/gouv/vitamui/commons/logbook/TestMongoConfig.java
  commons/commons-mongo/pom.xml
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/TestMongoConfig.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/dao/CustomSequenceRepositoryTest.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/dao/PersonRepositoryPaginatedNestedObjectsTests.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/dao/PersonRepositoryTests.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/BaseApiErrorController.java
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  pom.xml
  ui/ui-archive-search/src/main/resources/application-dev.yml
  ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/rest/ApiErrorController.java
  ui/ui-identity/src/main/resources/application-dev.yml
  ui/ui-ingest/src/main/resources/application-dev.yml
  ui/ui-portal/pom.xml
  ui/ui-portal/src/main/resources/application-dev.yml
  ui/ui-referential/pom.xml
  ui/ui-referential/src/main/resources/application-dev.yml
Labels: enhancement, VAS, Highlight, Security

#554 [VAS] item 8568 : Bump antisamy version
  cas/cas-server/pom.xml
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/logger/VitamUILoggerFactory.java
  commons/commons-api/src/test/java/fr/gouv/vitamui/commons/api/logger/VitamUILoggerImplWithoutConfigurationTest.java
  commons/commons-security/src/main/resources/esapi/antisamy-esapi.xml
  commons/commons-security/src/main/resources/esapi/antisamy.xsd
  pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-identity/src/main/resources/application-dev.yml
  ui/ui-identity/src/main/resources/dev/keystore_ui-referential.jks
  ui/ui-ingest/pom.xml
  ui/ui-referential/pom.xml
Labels: enhancement, dependencies, small, VAS, Security

#569 [VAS] fixe ui-identity dev conf
  ui/ui-identity/src/main/resources/application-dev.yml
Labels: small, VAS, Security

#563 [XEL] Correction des conflits d'écriture dans la base de donnée
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/application/service/ApplicationInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/config/ApiIamServerConfig.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/group/service/GroupInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/idp/service/IdentityProviderInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/owner/service/OwnerInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/profile/service/ProfileInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/subrogation/service/SubrogationInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/application/service/ApplicationInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalServiceIntegrationTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/group/service/GroupInternalServiceIntegrationTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/group/service/GroupInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/service/IdentityProviderInternalIntegrationTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/idp/service/IdentityProviderInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/owner/service/OwnerInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/owner/service/OwnerInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/profile/service/ProfileInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/profile/service/ProfileInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CasControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CustomerCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/GroupInternalControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/ProfileCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/SubrogationCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/TenantCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/UserControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/subrogation/service/InternalSubrogationServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/subrogation/service/SubrogationInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalServiceTest.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/certificate/service/CertificateCrudService.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/config/ApiSecurityServerConfig.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/context/service/ContextService.java
  api/api-security/security-internal/src/test/java/fr/gouv/vitamui/security/server/rest/CertificateCrudControllerTest.java
  api/api-security/security-internal/src/test/java/fr/gouv/vitamui/security/server/rest/ContextControllerTest.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/CustomSequencesConstants.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/config/MongoConfig.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/repository/VitamUISequenceRepository.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/repository/impl/VitamUIRepositoryImpl.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/service/OperationService.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/service/SequenceGeneratorService.java
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/service/VitamUICrudService.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/dao/CustomSequenceRepositoryTest.java
Labels: bug, small, Xelians

#559 [VAS] ITEM 8762 : correct download report issue
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookService.java
  commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookServiceTest.java
Labels: bug, small, VAS

#570 [VAS] Vas cp 8921 download big files on master 5.rc.x
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalWebClientFactory.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/config/ApiArchiveServerConfig.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchivesSearchExternalService.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClient.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalWebClientFactory.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveSearchInternalWebClient.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveSearchInternalWebClientFactory.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ArchiveSearchInternalServerConfig.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/provisioning/service/ProvisioningInternalServiceTest.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseWebClient.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseWebClientFactory.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/configuration/RestClientConfiguration.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/config/ArchiveSearchContextConfiguration.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
Labels: bug, VAS, Cherry-Pick

#571 [VAS] bug 9063: front sorting trees holding and filling scheme
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small

#566 [VAS][CP5RC] ITEM 7516 : correct authentication redirection issue
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/enums/AttachmentType.java
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/files/ui/assets/logo_USER.png
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-archive-search/src/main/config/ui-archive-search-application-recette.yml
  ui/ui-archive-search/src/main/resources/assets/logo_USER.png
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/config/UIPropertiesImpl.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/property/UIProperties.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/ApplicationService.java
  ui/ui-frontend-common/src/app/modules/account/account.component.ts
  ui/ui-frontend-common/src/app/modules/components/header/user-photo/user-photo.component.html
  ui/ui-frontend-common/src/app/modules/components/header/user-photo/user-photo.component.ts
  ui/ui-frontend-common/src/app/modules/models/app.configuration.interface.ts
  ui/ui-frontend-common/src/app/modules/models/customer/graphic-identity.interface.ts
  ui/ui-frontend-common/src/app/modules/models/customer/theme/attachmentType.enum.ts
  ui/ui-frontend-common/src/app/modules/models/customer/theme/themeDataType.enum.ts
  ui/ui-frontend-common/src/app/modules/startup.service.ts
  ui/ui-frontend-common/src/app/modules/theme.service.ts
  ui/ui-identity/src/main/config/ui-identity-application-dev.yml
  ui/ui-identity/src/main/resources/assets/logo_USER.png
  ui/ui-ingest/src/main/config/ui-ingest-application-dev.yml
  ui/ui-ingest/src/main/config/ui-ingest-application-recette.yml
  ui/ui-ingest/src/main/resources/assets/logo_USER.png
  ui/ui-portal/src/main/config/ui-portal-application-dev.yml
  ui/ui-portal/src/main/resources/assets/logo_USER.png
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
  ui/ui-referential/src/main/resources/assets/logo_USER.png
Labels: bug, small, VAS, Cherry-Pick

#567 [VAS][CPR16] ITEM 7516 : correct authentication redirection issue
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/enums/AttachmentType.java
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/files/ui/assets/logo_USER.png
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-archive-search/src/main/config/ui-archive-search-application-recette.yml
  ui/ui-archive-search/src/main/resources/assets/logo_USER.png
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/config/UIPropertiesImpl.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/property/UIProperties.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/ApplicationService.java
  ui/ui-frontend-common/src/app/modules/account/account.component.ts
  ui/ui-frontend-common/src/app/modules/components/header/user-photo/user-photo.component.html
  ui/ui-frontend-common/src/app/modules/components/header/user-photo/user-photo.component.ts
  ui/ui-frontend-common/src/app/modules/models/app.configuration.interface.ts
  ui/ui-frontend-common/src/app/modules/models/customer/graphic-identity.interface.ts
  ui/ui-frontend-common/src/app/modules/models/customer/theme/attachmentType.enum.ts
  ui/ui-frontend-common/src/app/modules/models/customer/theme/themeDataType.enum.ts
  ui/ui-frontend-common/src/app/modules/startup.service.ts
  ui/ui-frontend-common/src/app/modules/theme.service.ts
  ui/ui-identity/src/main/config/ui-identity-application-dev.yml
  ui/ui-identity/src/main/resources/assets/logo_USER.png
  ui/ui-ingest/src/main/config/ui-ingest-application-dev.yml
  ui/ui-ingest/src/main/config/ui-ingest-application-recette.yml
  ui/ui-ingest/src/main/resources/assets/logo_USER.png
  ui/ui-portal/src/main/config/ui-portal-application-dev.yml
  ui/ui-portal/src/main/resources/assets/logo_USER.png
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
  ui/ui-referential/src/main/resources/assets/logo_USER.png
Labels: bug, small, VAS, Cherry-Pick

#564 [VAS] [CPR16] : 8903 : correct referential applications creation button issue
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.ts
Labels: bug, small, VAS, Cherry-Pick

#562 [VAS] [CP5RC] : 8903 : correct referential applications creation button issue
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-create/rule-create.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#574 [VAS][CPR16] ITEM 8762 : correct download report issue
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookService.java
  commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookServiceTest.java
Labels: bug, small, VAS, Cherry-Pick

#577 [VAS] 9063: front sorting trees holding and filling scheme
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, VAS, Cherry-Pick

#581 Add default value for disable_internet_repositories_install
  deployment/environments/vitamui_extra_vars.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
Labels: small

#583 [VAS] CPR16 - Add default value for disable_internet_repositories_install
  deployment/environments/vitamui_extra_vars.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
Labels: small, VAS, Cherry-Pick

#560 [VAS][CP5RC] item 9087 : fixe header font-style
  ui/ui-frontend-common/src/styles.scss
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.scss
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.scss
  ui/ui-frontend/projects/ingest/src/sass/_date-filter.scss
  ui/ui-frontend/projects/ingest/src/sass/styles.scss
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.scss
Labels: bug, small, VAS, Cherry-Pick

#580 [VAS][5RC] fixe rules application issue
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rule/RuleConverter.java
Labels: bug, small, VAS

#579 [Vas] Fix wrong version of Vitam librairy
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/owner/service/OwnerInternalServiceIntegTest.java
  pom.xml
Labels: dependencies, small, VAS

#576 [VAS] BUG 9267 : correct download bdx error
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS

#582 [VAS] CP5RC - Add default value for disable_internet_repositories_install
  deployment/environments/vitamui_extra_vars.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
Labels: small, VAS, Cherry-Pick

#584 [VAS][CPR16] BUG 9267 correct download bdx error
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#585 [VAS][CP5RC] BUG : 9267 correct download bdx issue
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#586 [VAS][CP5RC] ITEM : 8431 correct portal police style
  ui/ui-frontend/projects/portal/src/sass/styles.scss
Labels: bug, small, VAS, Cherry-Pick

#588 [VAS] Story #9296: Update conf_permission to ReadOnly.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: enhancement, small, VAS, Security

#587 [VAS] [5RC] : add delete icon to referential applications
  ui/ui-frontend-common/icomoon-selection.json
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-list/file-format-list.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-list/ontology-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
Labels: bug, small, VAS, Cherry-Pick

#589 [CP 5RC] [VAS] Story #9296: Update conf_permission to ReadOnly.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: small, VAS, Cherry-Pick, Security

#590 [CP R16] [VAS] Story #9296: Update conf_permission to ReadOnly.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: small, VAS, Cherry-Pick, Security

#591 [VAS]-CP- Rename OPI Guid label on archive search screen
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: small, VAS, Cherry-Pick

#597 [Vas] CP- mondatory cherry pick for master 4 (PR 537)
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
Labels: bug, small, VAS, Cherry-Pick

#595 story #9289 Fix missing modules and logs directory for Debian Apache reverse
  deployment/roles/reverse/tasks/apache/apache.yml
Labels: bug, small

#599 story #9289 Fix missing modules and logs directory for Debian reverse (CP 5rc)
  deployment/roles/reverse/tasks/apache/apache.yml
Labels: bug, small, Cherry-Pick

#600 story #9289 Fix missing modules and logs directory for Debian reverse (CP R16)
  deployment/roles/reverse/tasks/apache/apache.yml
Labels: bug, small, Cherry-Pick

#598 [Vas] Bug 9299 - Add other description levels on master-4.0.X
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug, small, VAS
