Repository ProgrammeVitam/vitam-ui, pull requests merged in 2021-03, with the labels that each got.

#213 [VAS] Bug 7564 liste des dernières applications utilisée
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-archive-search/src/main/config/ui-archive-search-application-recette.yml
  ui/ui-frontend/projects/archive-search/src/app/app-routing.module.ts
  ui/ui-frontend/projects/ingest/src/app/app-routing.module.ts
Labels: VAS, small

#214 [VAS] Item 7389 Fix Maven Check Vulnerabilities
  Jenkinsfile
  pom.xml
Labels: VAS, small

#218 [VAS] Bug 7600 fix JDO issue
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/event-type-color-class.pipe.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
Labels: VAS, small

#215 [VAS] Bug 7580 update customer issue
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalService.java
  ui/ui-frontend/projects/identity/src/app/core/api/customer-api.service.ts
Labels: VAS, small

#216 [VAS] Bug 7558 Fix recharting bugs
  deployment/roles/init_ingest_app_bdd/templates/ingest/01_ingest.js.j2
  deployment/scripts/mongod/1.0.0/212_application_ref.js.j2
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend-common/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.component.html
  ui/ui-frontend-common/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.component.ts
  ui/ui-frontend-common/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.module.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/app.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.html
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.scss
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.html
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.scss
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-preview.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit.component.html
  ui/ui-frontend/projects/referential/src/app/context/context.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-preview.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile.component.html
  ui/ui-frontend/projects/referential/src/locale/messages.en.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.fr.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.xlf
Labels: VAS, small

#219 [VAS] item 7570 : Génération d'un fichier de type ODT pour chaque Ingest uploadé
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/rest/RestApi.java
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalRestClient.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/service/IngestExternalService.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestInternalRestClient.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestODTGenerator.java
  ui/ui-frontend/projects/ingest/src/app/core/api/ingest-api.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/service/IngestService.java
Labels: VAS, small

#220 [VAS] item 7547 Téléchargement du binaire de l'UA - Changement du nom
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ArchiveSearchInternalServerConfig.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/config/ApiArchiveSearchInternalServerConfigTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/doc/SwaggerJsonFileGenerationTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalControllerTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: VAS, small

#221 [VAS] Bug 7558 Fix recharting bugs suite
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/identity/src/locale/messages.en.xlf
  ui/ui-frontend/projects/identity/src/locale/messages.fr.xlf
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.scss
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
  ui/ui-frontend/projects/ingest/src/locale/messages.en.xlf
  ui/ui-frontend/projects/ingest/src/locale/messages.fr.xlf
  ui/ui-frontend/projects/ingest/src/locale/messages.xlf
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-list/access-contract-list.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-update/access-contract-node-update.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-list/ingest-contract-list.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.html
  ui/ui-frontend/projects/referential/src/locale/messages.en.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.fr.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.xlf
Labels: VAS, small

#223 [VAS] Bug : fixe bdr download issue
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
Labels: VAS, small

#225 [VAS] Item Vas 7560 doc for deleting apps
  docs/Exploitation.md
  docs/Personnalisation applications.md
Labels: VAS, documentation, small

#226 [VAS] Vas bug 7558 fix recharting bugs
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.html
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.scss
  ui/ui-frontend/projects/ingest/src/sass/_date-filter.scss
Labels: VAS, small

#227 [CEA] Multiple bugfixs
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/AccessContractDto.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/IngestContractService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessContractModelDto.java
  deployment/scripts/mongod/2.0.0/05_update_ingest_contract_profiles.js
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit.service.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-edit-permission/context-edit-permission.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-information-tab/context-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-list/file-format-list.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-list/file-format-list.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-preview/security-profile-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/shared/vitamui-import-dialog/referential.enum.ts
  ui/ui-frontend/projects/referential/src/app/shared/vitamui-import-dialog/vitamui-import-dialog.component.html
  ui/ui-frontend/projects/referential/src/app/shared/vitamui-import-dialog/vitamui-import-dialog.component.ts
  ui/ui-frontend/projects/referential/src/locale/messages.en.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.fr.xlf
  ui/ui-frontend/projects/referential/src/locale/messages.xlf
Labels: small

#228 [VAS] Bug corriger les dates au niveau du bordereau
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestODTGenerator.java
Labels: VAS, bug, small

#231 [CEA] Multiple bugfixs
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/IngestContractDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessContractDto.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-preview.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-preview.component.ts
  ui/ui-frontend/projects/vitamui-library/src/sass/icons/font-vitamui-icons.zip
  ui/ui-frontend/projects/vitamui-library/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend/projects/vitamui-library/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend/projects/vitamui-library/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend/projects/vitamui-library/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend/projects/vitamui-library/src/sass/icons/vitamui-icons.css
Labels: small

#234 Update iteritems() function to items() to be fully compatible with Python 2 & 3
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: small

#232 [VAS] strory 7739 : update reset password expiration
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/pm/ResetPasswordController.java
  deployment/environments/group_vars/all/infra.yml
  deployment/environments/vitamui_extra_vars.yml
Labels: VAS, small

#233 [VAS] Bug 7959 : fix get start and end date
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestODTGenerator.java
Labels: VAS, bug, small
