Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-07, with the labels that each got.

#870 [VAS] 9979 : clean code api-ingest
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalRestClient.java
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalRestClientFactory.java
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestExternalWebClient.java
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestStreamingExternalRestClient.java
  api/api-ingest/ingest-external-client/src/main/java/fr/gouv/vitamui/ingest/external/client/IngestStreamingExternalRestClientFactory.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/service/IngestExternalService.java
  api/api-ingest/ingest-external/src/test/java/fr/gouv/vitamui/ingest/external/server/rest/ApiIngestControllerTest.java
  api/api-ingest/ingest-external/src/test/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalControllerTest.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestInternalRestClient.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestInternalWebClient.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestStreamingInternalRestClient.java
  api/api-ingest/ingest-internal-client/src/main/java/fr/gouv/vitamui/ingest/internal/client/IngestStreamingInternalRestClientFactory.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  api/api-ingest/ingest-internal/src/test/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalControllerTest.java
Labels: java, small, VAS, Security

#869 [VAS] 9979 : clean code api-archive-search
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchStreamingExternalRestClient.java
  api/api-archive-search/archive-search-external-client/src/test/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClientTest.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/SearchCriteriaHistoryExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/SearchCriteriaHistoryExternalService.java
  api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchApiControllerTest.java
  api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/SearchCriteriaHistoryInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/service/RulesUpdateCommonService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/searchcriteria/service/SearchCriteriaHistoryInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/config/ApiArchiveSearchInternalServerConfigTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/config/SearchCriteriaHistoryInternalServerConfigTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/service/RulesUpdateCommonServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/searchcriteria/converter/SearchCriteriaHistoryConverterTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/searchcriteria/dao/SearchCriteriaHistoryRepositoryTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/searchcriteria/service/SearchCriteriaHistoryServiceIntegTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/searchcriteria/service/SearchCriteriaHistoryServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchArchiveSearchUnitExportCsvInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchStorageRuleQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/utils/Utils.java
Labels: java, small, VAS, Security

#859 [VAS] : 9979 : clean code correct Angular TUs
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/reclassification/reclassification.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.service.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/profile/profile-detail/information-tab/information-tab.component.spec.ts
Labels: small, VAS, Highlight, Security

#858 [VAS] Feature/9984 update documentation to manage the remote connection to deployed Vitam env
  tools/vitamui-conf-dev/README.md
  tools/vitamui-conf-dev/images/extract-cert.png
Labels: documentation, VAS

#871 [VAS] 10046 : checkmarx VitamUI
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/LogbookInternalController.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/cas/service/CasServiceIntegrationTest.java
  api/api-iam/iam-internal/src/test/resources/credentialsRepository/userCredentials.json
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/FileFormatExternalWebClient.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AgencyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/FileFormatInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/OperationInternalController.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/CertificateCrudController.java
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/ContextController.java
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/InitContextConfiguration.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/BaseWebflowActionTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolverTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/pm/IamPasswordManagementServiceTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/CheckMfaTokenActionTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/CustomDelegatedClientAuthenticationActionTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/DispatcherActionTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/TriggerChangePasswordActionTest.java
  cas/cas-server/src/test/resources/credentialsRepository/resolverUserCredentials.json
  cas/cas-server/src/test/resources/credentialsRepository/userCredentials.json
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/PasswordValidatorTest.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SanityCheckerTest.java
  commons/commons-security/src/test/resources/credentialsRepository/userCredentials.json
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/utils/RandomObjectFiller.java
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/utils/TestUtils.java
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/VitamUIUtils.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/LogbookController.java
  ui/ui-frontend/projects/demo/src/app/demo/component-demo/css/css.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-edit-permission/context-edit-permission.component.html
  ui/ui-frontend/projects/referential/src/app/context/context-list/context-list.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-list/ingest-contract-list.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-list/security-profile-list.component.html
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/AgencyController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OntologyController.java
Labels: enhancement, small, VAS, Security

#873 [VAS] 10149 : show filing plan and holding schema complete name
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/tree-node/filing-holding-node.component.html
Labels: enhancement, small, VAS

#872 [VAS] 8645 : fix some update mgt rules issues
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/VitamUiRuleCategoryActionDeletion.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/converter/RuleOperationsConverter.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/converter/RuleOperationsConverterTest.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#876 [VAS] Bug 10161: lien vers journal des operation depuis ingest KO
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  ui/ui-frontend-common/src/app/modules/startup.service.ts
Labels: bug, small, VAS, OPS REVIEW

#878 [VAS] BUG 10193 : show unit rules in lateral panel
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.ts
Labels: bug, small, VAS

#880 [VAS] Bug 10123: ouverture de la modale de creation d'un service agent
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
Labels: bug, small, VAS

#881 [VAS] 10204 : check existing emails domain
  ui/ui-frontend/projects/identity/src/app/core/customer.service.spec.ts
  ui/ui-frontend/projects/identity/src/app/core/customer.service.ts
Labels: bug, small, VAS

#882 [CPR16][VAS] 10204 : check existing emails domain
  ui/ui-frontend/projects/identity/src/app/core/customer.service.spec.ts
  ui/ui-frontend/projects/identity/src/app/core/customer.service.ts
Labels: bug, small, VAS, Cherry-Pick

#883 [CP5X][VAS] 10204 : check existing emails domain
  ui/ui-frontend/projects/identity/src/app/core/customer.service.spec.ts
  ui/ui-frontend/projects/identity/src/app/core/customer.service.ts
Labels: bug, small, VAS, Cherry-Pick

#888 [VAS] bug 10222 et 10169 calcule facettes VitamUI [Sans Squash des commits]
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug, small, VAS

#885 [VAS] : change log to debug to avoid pollution
  api/api-security/security-internal/src/main/java/fr/gouv/vitamui/security/server/rest/ContextController.java
Labels: small, VAS

#877 [VAS] Bug 10171: reclassement des ua bloqué à cause du sanitizer [Sans Squash des commits]
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/SearchCriteriaDto.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/UnitExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SanityCheckerTest.java
  commons/commons-security/src/test/resources/audit_action_json_with_exists_key.json
  commons/commons-security/src/test/resources/audit_action_json_with_in_or_query_keys.json
  commons/commons-security/src/test/resources/probative_action_json_with_fields_projection_roots_keys.json
  commons/commons-security/src/test/resources/reclassification_action_json_with_action_add_pull_keys.json
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/OperationController.java
Labels: bug, java, small, VAS

#893 Story 10188 enable checkmarx sca
  Jenkinsfile
Labels: small, OPS REVIEW

#890 [VAS] Story #10212: Enable fact_caching & gathering smart.
  deployment/.gitignore
  deployment/ansible-vitamui/pre_install.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/ansible.cfg
  deployment/roles/bootstrap_ansible/tasks/main.yml
  deployment/roles/bootstrap_ansible/vars/main.yml
Labels: small, VAS, OPS REVIEW

#895 [VAS] CP V5 - Story #10212: Enable fact_caching & gathering smart.
  deployment/.gitignore
  deployment/ansible-vitamui/pre_install.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/ansible.cfg
  deployment/roles/bootstrap_ansible/tasks/main.yml
  deployment/roles/bootstrap_ansible/vars/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#896 [VAS] CP 5RC - Story #10212: Enable fact_caching & gathering smart.
  deployment/.gitignore
  deployment/ansible-vitamui/pre_install.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/ansible.cfg
  deployment/roles/bootstrap_ansible/tasks/main.yml
  deployment/roles/bootstrap_ansible/vars/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#897 [VAS] CP R16 - Story #10212: Enable fact_caching & gathering smart.
  deployment/.gitignore
  deployment/ansible-vitamui/pre_install.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/ansible.cfg
  deployment/roles/bootstrap_ansible/tasks/main.yml
  deployment/roles/bootstrap_ansible/vars/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW
