Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-02, with the labels that each got.

#521 [Xelians]SONAR dependencies verification report publication
  pom.xml
Labels: enhancement, small, Xelians

#624 [VAS] ITEM 8101 : add computed inherited rules function
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchivesSearchExternalService.java
  api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClient.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/access/UnitService.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/44_update_archive_administrator_profile_to_add_computed_inherited_role.js.j2
  deployment/scripts/mongod/2.0.0/45_update_archive_search_context_add_computed_inherited_role.js.j2
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/rest/SearchCriteriaHistoryControllerTest.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-frontend-common/src/app/modules/vitamui-roles.enum.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS, Highlight

#645 [VAS] Item 9011: Control AccessContract write permissions for mass update unit rules
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/update_rules_async_response.json
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/AccessContractExternalController.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/AccessContractExternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/AccessContractInternalController.java
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/accesscontract/AccessContractInternalRestClient.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/44_new_update_archive_search_context_to_add_rule_access_contracts.js.j2
  deployment/scripts/mongod/2.0.0/45_update_archive_administrator_profile_to_add_computed_inherited_role.js.j2
  deployment/scripts/mongod/2.0.0/46_update_archive_search_context_add_computed_inherited_role.js.j2
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/AccessContractController.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/AccessContractService.java
  ui/ui-frontend-common/src/app/modules/api/access-contract-api.service.ts
  ui/ui-frontend-common/src/app/modules/models/profile/access-contract.interface.ts
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#633 OIDC authn delegation
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/CustomTokenValidator.java
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilder.java
  api/api-iam/iam-commons/src/test/java/fr/gouv/vitamui/iam/common/utils/CustomTokenValidatorTest.java
  api/api-iam/iam-commons/src/test/java/fr/gouv/vitamui/iam/common/utils/IamDtoBuilder.java
  api/api-iam/iam-commons/src/test/java/fr/gouv/vitamui/iam/common/utils/IdentityProviderHelperTest.java
  api/api-iam/iam-commons/src/test/java/fr/gouv/vitamui/iam/common/utils/Pac4jClientBuilderTest.java
  api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/rest/TenantExternalControllerTest.java
  api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/utils/ApiIamServerUtils.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/group/service/GroupInternalServiceIntegrationTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/SubrogationCrudControllerTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/subrogation/service/InternalSubrogationServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/converter/TenantConverterTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalServiceIntegTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/utils/IamServerUtilsTest.java
  cas/cas-server/pom.xml
  cas/cas-server/src/main/java/org/apereo/cas/web/DefaultDelegatedClientAuthenticationWebflowManager.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/back/steps/iam/subrogation/ApiIamExternalSubrogationCreationSteps.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/back/steps/iam/tenant/ApiIamExternalTenantCreationSteps.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/common/CommonSteps.java
  integration-tests/src/test/java/fr/gouv/vitamui/utils/FactoryDto.java
  pom.xml
Labels: enhancement, small, VAS

#651 [9313] Fix some graphic bugs
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/sass/styles.scss
Labels: bug, small, VAS

#647 [VAS] Item 8690 - get exact archive unit count when threshold reached and manage popups
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/SearchCriteriaDto.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/elimination/expected_query.json
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/exception/UnexpectedSettingsException.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/converter/VitamUIErrorConverter.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtils.java
  ui/ui-frontend-common/src/app/modules/vitamui-http-interceptor.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/models/search.criteria.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#648 [VAS] ITEM 8526 : add holding and filling shemes in archive search results and add archive unitType as new search criteria
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/search_query_with_object_and_unit_type.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/search_query_with_object_parameter.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/search_query_with_unit_type.json
  ui/ui-frontend-common/icomoon-selection.json
  ui/ui-frontend-common/src/app/modules/models/criteria/criteria.enums.ts
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-list/file-format-list.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-list/ontology-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.html
Labels: enhancement, small, VAS, Highlight

#658 [Vas] Bug 8630 Handle calculating total track hit when launching other actions
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, small, VAS

#662 [VAS] BUG 9530 , 9331 correct title style
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.html
Labels: bug, small, VAS

#665 CP R16 - story #9431: Convert files present in docs/DAT/docs/dat_vitamui in Sphinx format
  docs/DAT/README.md
  docs/fr/architecture/README.md
  docs/fr/architecture/conf.py
  docs/fr/architecture/images/Vitam_Logo-CMJN.png
  docs/fr/architecture/images/dat_archi_cas.png
  docs/fr/architecture/images/dat_cas_1.png
  docs/fr/architecture/images/dat_cas_2.png
  docs/fr/architecture/images/dat_cas_3.png
  docs/fr/architecture/images/dat_cas_4.png
  docs/fr/architecture/images/dat_chaine_deploiement.png
  docs/fr/architecture/images/dat_level.png
  docs/fr/architecture/images/dat_pki_1.png
  docs/fr/architecture/images/dat_session_1.png
  docs/fr/architecture/images/dat_zoning.png
  docs/fr/architecture/images/journalisation_architecture.png
  docs/fr/architecture/images/journalisation_transaction.png
  docs/fr/architecture/index.rst
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, small

#664 CP 5RC - story #9431: Convert files present in docs/DAT/docs/dat_vitamui in Sphinx format
  docs/DAT/README.md
  docs/fr/architecture/README.md
  docs/fr/architecture/conf.py
  docs/fr/architecture/images/Vitam_Logo-CMJN.png
  docs/fr/architecture/images/dat_archi_cas.png
  docs/fr/architecture/images/dat_cas_1.png
  docs/fr/architecture/images/dat_cas_2.png
  docs/fr/architecture/images/dat_cas_3.png
  docs/fr/architecture/images/dat_cas_4.png
  docs/fr/architecture/images/dat_chaine_deploiement.png
  docs/fr/architecture/images/dat_level.png
  docs/fr/architecture/images/dat_pki_1.png
  docs/fr/architecture/images/dat_session_1.png
  docs/fr/architecture/images/dat_zoning.png
  docs/fr/architecture/images/journalisation_architecture.png
  docs/fr/architecture/images/journalisation_transaction.png
  docs/fr/architecture/index.rst
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, small

#666 CP 5RC - DAT markdown lint & typo fixes
  docs/fr/architecture/README.md
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, small, Cherry-Pick

#667 CP R16 - DAT markdown lint & typo fixes
  docs/fr/architecture/README.md
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, small, Cherry-Pick

#655 [VAS] CP 5RC - Story 8339: Iam internal instance primary conf
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  docs/fr/architecture/sections/implementation.md
  docs/fr/exploitation/sections/procedure.md
Labels: bug, small, VAS, Cherry-Pick

#656 CP 5RC - Fix vulnerability cas server on 5 RC (#646)
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/CustomSendTokenAction.java
  cas/cas-server/src/main/resources/overriden_messages_fr.properties
  cas/cas-server/src/main/resources/templates/casAccountBadConfigurationView.html
  cas/cas-server/src/main/resources/templates/casAccountDisabledView.html
  cas/cas-server/src/main/resources/templates/casAccountLockedView.html
  cas/cas-server/src/main/resources/templates/casAuthenticationBlockedView.html
  cas/cas-server/src/main/resources/templates/casExpiredPassView.html
  cas/cas-server/src/main/resources/templates/casLoginView.html
  cas/cas-server/src/main/resources/templates/casLogoutView.html
  cas/cas-server/src/main/resources/templates/casPac4jStopWebflow.html
  cas/cas-server/src/main/resources/templates/casPasswordUpdateSuccessView.html
  cas/cas-server/src/main/resources/templates/casPropagateLogoutView.html
  cas/cas-server/src/main/resources/templates/casPwdView.html
  cas/cas-server/src/main/resources/templates/casResetPasswordErrorView.html
  cas/cas-server/src/main/resources/templates/casResetPasswordSendInstructionsView.html
  cas/cas-server/src/main/resources/templates/casServiceErrorView.html
  cas/cas-server/src/main/resources/templates/casSimpleMfaLoginView.html
  cas/cas-server/src/main/resources/templates/casSmsCodeExpiredView.html
  cas/cas-server/src/main/resources/templates/casSmsMissingPhoneView.html
  cas/cas-server/src/main/resources/templates/error.html
  cas/cas-server/src/main/resources/templates/error/401.html
  cas/cas-server/src/main/resources/templates/error/403.html
  cas/cas-server/src/main/resources/templates/error/404.html
  cas/cas-server/src/main/resources/templates/error/405.html
  cas/cas-server/src/main/resources/templates/error/423.html
  cas/cas-server/src/main/resources/templates/fragments/pwdupdateform.html
Labels: bug, small, Cherry-Pick, Security

#668 [VAS] Bug 9546: double check on descriptive metadata permission
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, small, VAS

#672 [VAS] Story #9555: Fix nginx configuration to properly handle reload.
  deployment/roles/reverse/handlers/main.yml
  deployment/roles/reverse/tasks/nginx/configure_vitamui_vhost.yml
  deployment/roles/reverse/tasks/nginx/nginx.yml
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
  deployment/roles/reverse/templates/nginx/ssl/reverse.key_pass.j2
  deployment/roles/reverse/vars/main.yml
Labels: bug, small, VAS

#673 [VAS] CP 5RC - Story #9555: Fix nginx configuration to properly handle reload.
  deployment/roles/reverse/handlers/main.yml
  deployment/roles/reverse/tasks/nginx/configure_vitamui_vhost.yml
  deployment/roles/reverse/tasks/nginx/nginx.yml
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
  deployment/roles/reverse/templates/nginx/ssl/reverse.key_pass.j2
  deployment/roles/reverse/vars/main.yml
Labels: bug, small, VAS, Cherry-Pick

#674 [VAS] CP R16 - Story #9555: Fix nginx configuration to properly handle reload.
  deployment/roles/reverse/handlers/main.yml
  deployment/roles/reverse/tasks/nginx/configure_vitamui_vhost.yml
  deployment/roles/reverse/tasks/nginx/nginx.yml
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
  deployment/roles/reverse/templates/nginx/ssl/reverse.key_pass.j2
  deployment/roles/reverse/vars/main.yml
Labels: bug, small, VAS, Cherry-Pick

#669 [VAS] ITEM 8640 : delete archive unit DUA rules
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/ruleAction.interface.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS, Highlight

#681 [VAS] Add schema for iam database.
  docs/fr/architecture/images/VitamUI-iam_database.drawio
  docs/fr/architecture/images/VitamUI-iam_database.png
  docs/fr/architecture/sections/architecture.md
Labels: documentation, enhancement, small, VAS

#683 CP 5RC - [VAS] Add schema for iam database.
  docs/fr/architecture/images/VitamUI-iam_database.drawio
  docs/fr/architecture/images/VitamUI-iam_database.png
  docs/fr/architecture/sections/architecture.md
Labels: documentation, enhancement, small, VAS, Cherry-Pick

#684 CP R16 - [VAS] Add schema for iam database.
  docs/fr/architecture/images/VitamUI-iam_database.drawio
  docs/fr/architecture/images/VitamUI-iam_database.png
  docs/fr/architecture/sections/architecture.md
Labels: documentation, enhancement, small, VAS, Cherry-Pick

#682 [VAS] BUG 9580 : fix search archive unit with and without objects
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/search_query_with_object_and_unit_type.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/search_query_with_object_parameter.json
Labels: small, VAS
