Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-05, with the labels that each got.

#786 Add github pull request template
  .github/pull_request_template.md
Labels: small, VAS

#789 [VAS] ITEM 9438 : manage access rules category (add, delete and update)
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAccessMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/access/expected-search-query-with-rule-identifier-and-rule-startDate.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/access/expected-search-query-with-rule-identifier.txt
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/exception/InvalidCreateOperationVitamUIException.java
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/update-unit-management-rule.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/block-category-inheritance/block-category-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/unlock-category-inheritance/unlock-category-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/management-rules-validator.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/management-rules-shared-data.service.ts
Labels: enhancement, small, VAS, Highlight

#792 [VAS] BUG 9588 : correct save criterias close form issue
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
Labels: bug, small, VAS

#787 [VAS-9848] appliquer le tri lors de l'export CSV
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/AccessionRegisterDetailExternalRestClient.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/AccessionRegisterDetailExternalService.java
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/AccessionRegisterDetailInternalRestClient.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterSummaryInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ConverterConfig.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterInternalController.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/AccessionRegisterInternalServiceTest.java
  api/api-referential/referential-internal/src/test/resources/actual.json
  api/api-referential/referential-internal/src/test/resources/expected.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl01.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl02.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl03.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl04.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl05.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl06.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl07.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl08.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/request-with-acquisitionInformations-full.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/request-with-acquisitionInformations-variant-1.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/request-with-acquisitionInformations-variant-2.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/request-with-acquisitionInformations-variant-3.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/request-with-all-params.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/request-without-acquisitionInformations.json
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessionRegisterDetailsSearchStatsDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessionRegisterSearchDto.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BasePaginatingAndSortingRestClient.java
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/VitamUIUtils.java
  commons/commons-utils/src/test/java/fr/gouv/vitamui/commons/utils/VitamUIUtilsTest.java
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/models/accession-register-export-csv.interface.ts
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/AccessionRegisterController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/service/AccessionRegisterDetailService.java
Labels: javascript, java, VAS

#793 [VAS] Bug 9760- Fix regression bug on facets
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
Labels: bug, small

#796 [VAS] Bug 9786: change show download button for operation report
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/app/modules/models/logbook/index.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/logbook-operation.interface.ts
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
Labels: bug, javascript, small, VAS

#791 [VAS] Bug 9790: Set ingest status for list and preview
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/api-event.interface.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/event.interface.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/ingest-list.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/event.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-event-detail/ingest-event-detail.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-event-detail/ingest-event-detail.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.module.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-frontend/projects/ingest/src/app/models/logbook-event.interface.ts
Labels: bug, javascript, small, VAS

#799 [VAS][CP5RC] Bug 9786 : change show download button for operation report
  ui/ui-frontend-common/src/app/modules/models/logbook/index.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/logbook-operation.interface.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
Labels: javascript, small, VAS

#798 [VAS][CPR16] Bug 9786 : change show download button for operation report
  ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/index.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/logbook-operation.interface.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
Labels: VAS

#802 [VAS] BUG: Correct bugs on search application
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#804 [VAS] : correct logbook operations issues
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/LogbookExternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/LogbookInternalController.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/LogbookController.java
Labels: small, VAS

#808 [VAS] Bug 9959: ingest list doesn't load
  ui/ui-frontend/projects/ingest/src/app/app.module.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
Labels: bug, small, VAS
