Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-08, with the labels that each got.

#886 Feature/vas 10226 enable access logs
  cas/cas-server/pom.xml
  cas/pom.xml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/logback.xml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  pom.xml
Labels: enhancement, small, VAS

#902 VAS-10144: update collect service to adapt it after vitam evolution
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
Labels: bug, small

#901 item#10180 Consulter le détail d'un projet depuis un panneau latéral
  api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectProjectDto.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/ProjectExternalService.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectConverter.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.css
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.service.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: enhancement, VAS

#903 item #10144 Delete fake DSL query and use Search query created from the Collect F…
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/archivesearch/ArchiveSearchCollectInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
Labels: bug, small

#906 [VAS] Story 10238: integrate icons for referential apps
  ui/ui-frontend/projects/portal/src/assets/app-icons/AGENCIES_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/FILE_FORMATS_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/HOLDING_FILLING_SCHEME_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/RULES_APP.svg
Labels: enhancement, small, VAS

#905 [VAS] Story 10237: integrate icons for ingest & consul apps
  ui/ui-frontend/projects/portal/src/assets/app-icons/ACCESSION_REGISTER_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ARCHIVE_SEARCH_MANAGEMENT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/COLLECT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/INGEST_APP.svg
Labels: javascript, small, VAS

#894 Story 9852: download transfer DIP
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-constants.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
Labels: VAS

#904 item#9879 Add profil for consulting rules
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/6.rc.0/07_add_consult_rules_profil.js.j2
  ui/ui-frontend-common/src/app/modules/utils/role.enum.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.ts
Labels: enhancement, VAS, OPS REVIEW

#909 [VAS] Story 10243: integrate icons for security and rights apps and add fix for previous integration
  ui/ui-frontend/projects/portal/src/assets/app-icons/ACCESSION_REGISTER_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ACCESS_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/AGENCIES_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ARCHIVE_SEARCH_MANAGEMENT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/COLLECT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/FILE_FORMATS_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/HOLDING_FILLING_SCHEME_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/INGEST_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/INGEST_MANAGEMENT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/RULES_APP.svg
Labels: small, VAS

#911 [VAS] Story 10244: integrate icons for Supervision & Audits
  ui/ui-frontend/projects/portal/src/assets/app-icons/AUDIT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/DSL_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/LOGBOOK_MANAGEMENT_OPERATION_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/LOGBOOK_OPERATION_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/PROBATIVE_VALUE_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/SECURE_APP.svg
Labels: small, VAS

#912 [VAS] Story 10245: integrate icons for technical administration
  ui/ui-frontend/projects/portal/src/assets/app-icons/CONTEXTS_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ONTOLOGY_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/SECURITY_PROFILES_APP.svg
Labels: enhancement, small, VAS

#913 [VAS] Story 10246: integrate icons for CINES
  ui/ui-frontend/projects/portal/src/assets/app-icons/MANAGEMENT_CONTRACT_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/PASTIS_APP.svg
Labels: enhancement, small, VAS

#914 [VAS] 10292 : correct rules management application issues
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.ts
Labels: bug, small, VAS

#908 [VAS] Story 10230: blank ingest
  ui/ui-frontend/projects/ingest/src/app/core/common/ingest-type.enum.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.html
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.component.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.html
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.ts
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-constants.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
Labels: javascript, small, VAS

#915 [VAS] Item 9979: clean code, small refacto on audit
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit.service.ts
  ui/ui-frontend/projects/referential/src/app/core/api/operation-api.service.ts
  ui/ui-frontend/projects/referential/src/app/models/audit.interface.ts
Labels: javascript, small, VAS

#916 [VAS] Add interactive mode to select steps when building dev branches.
  Jenkinsfile
Labels: small, VAS, OPS REVIEW

#922 CP V5 - [VAS] Bug 9304: send nodes selected for audit
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#923 CP 5RC - [VAS] Bug 9304: send nodes selected for audit
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#921 CP R16 - [VAS] Bug 9304: send nodes selected for audit
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#919 [VAS] Bug 9304: send nodes selected for audit
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
Labels: bug, javascript, small, VAS

#928 [VAS] : 9105 : add more translate key for operations categories
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-information-tab/logbook-management-operation-information-tab.component.html
Labels: bug, small, VAS

#918 CP 5RC - [VAS] Add interactive mode to select steps when building dev branches.
  Jenkinsfile
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#931 CP V5 - [VAS] Support #10004: Remove useless auto_tenant.
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#932 CP 5RC - [VAS] Support #10004: Remove useless auto_tenant.
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#933 CP R16 - [VAS] Support #10004: Remove useless auto_tenant.
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#917 CP V5 - [VAS] Add interactive mode to select steps when building dev branches.
  Jenkinsfile
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#929 Minor cleanup Jenkinsfile.
  Jenkinsfile
Labels: small, VAS, OPS REVIEW

#925 [VAS] 9979 : add angular tests on referential applications
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.spec.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.spec.ts
  ui/ui-frontend/projects/referential/src/app/context/context-list/context-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/context/context-list/context-list.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-permission-tab/context-permission-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.validators.spec.ts
Labels: VAS, Highlight, Security

#937 [VAS] 9711 : add translate keys for mass update operation
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
Labels: bug, small, VAS

#934 [VAS] 9572 : add more translate for compute inherited rules operations
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
Labels: enhancement, small, VAS

#939 [VAS] 9941 : change unlock rule category inheritance design
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/unlock-category-inheritance/unlock-category-inheritance.component.html
Labels: bug, small, VAS

#940 [VAS] Story #10298: Fix wrong default root_path.
  deployment/ansible-vitamui-exploitation/uninstall.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/browser/tasks/main.yml
  deployment/roles/browser/templates/httpd-offer-view.conf.j2
  deployment/roles/init_app_bdd/tasks/referential.yml
  deployment/roles/init_archive_search_app_bdd/tasks/archive-search.yml
  deployment/roles/init_ingest_app_bdd/tasks/ingest.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_common/vars/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/mongo_init/tasks/main.yml
  deployment/roles/mongodb_migration_v5/tasks/reconfig.yml
  deployment/roles/mongodb_set_feature_compatibility/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/ui.yml
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  deployment/roles/vitamui/vars/main.yml
Labels: small, VAS, OPS REVIEW

#941 Fix master_4.0.x build issues
  ui/ui-frontend/projects/identity/src/app/core/customer.service.spec.ts
Labels: bug, small, VAS

#920 CP R16 - [VAS] Add interactive mode to select steps when building dev branches.
  Jenkinsfile
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#938 VAS-10242: Force FinalAction property selection when blocking/unlocking inheritance for Appraisal & Storage rules
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.ts
Labels: enhancement, small, VAS, Highlight

#944 fix vitamui develop build issue
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.ts
Labels: bug, small, VAS

#942 [VAS] Bug 9978: date pipe format bug
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
Labels: bug, small, VAS

#945 [VAS] Bug 10322,10163: sanity check block organisation creation
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/CustomerCreationFormData.java
  commons/commons-security/src/main/resources/esapi/validation.properties
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SanityCheckerTest.java
Labels: bug, small, VAS
