Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-09, with the labels that each got.

#948 [VAS] Bug #10356: wording error
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
Labels: bug, small, VAS

#953 [VAS] 9979 : clean code VitamUI : add Angular tests
  ui/ui-frontend-common/src/app/modules/logbook/event-type-label/event-type-label.component.spec.ts
  ui/ui-frontend-common/src/app/modules/logbook/history/operation-history-tab/operation-history-tab.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/sso-tab/identity-provider-details/identity-provider-details.component.spec.ts
Labels: small, VAS, Security

#955 BUG #10348 fix disable button and fields
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
Labels: bug, small, VAS

#952 BUG #10350 fix download transfert
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
Labels: bug, small, VAS

#958 [VAS] 10210 : check domains mail existing
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/dao/CustomerRepository.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CustomerCrudControllerTest.java
Labels: bug, small, VAS, Security

#959 [CP5RC][VAS] 10210 : check domains mail existing
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/dao/CustomerRepository.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/CustomerInternalServiceTest.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/rest/CustomerCrudControllerTest.java
Labels: bug, small, VAS, Cherry-Pick

#962 VAS-10354: BUG: fix wrong size limit on archive search when rules included
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
Labels: bug, small, VAS

#956 [VAS] 10365 : add missing role to archive search profils
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/6.rc.0/10_update_archive_profiles_to_add_get_rules_role.js.j2
Labels: bug, small, VAS

#964 disable front end tests
  ui/ui-frontend/pom.xml
Labels: small, VAS

#946 [VAS] Bug 10325: use secondary colors var
  ui/ui-frontend/projects/portal/src/assets/app-icons/ACCESS_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ACCOUNTS_APP_.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/AGENCIES_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ARCHIVE_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/ARCHIVE_TYPE_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/CONTEXTS_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/INGEST_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/PROBATIVE_VALUE_APP.svg
  ui/ui-frontend/projects/portal/src/assets/app-icons/SECURITY_PROFILES_APP.svg
Labels: enhancement, small, VAS

#954 [VAS] 10316 : add more translate on audit application
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.spec.ts
Labels: enhancement, small, VAS, Highlight

#949 story #9980: search projects by query
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.ts
Labels: enhancement, small, VAS

#969 VAS-9898: fix-forgotten-settings-on-ui-portal
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
Labels: bug, small, VAS, OPS REVIEW

#970 [VAS] Support #10004: Remove profils for useless auto_tenant.
  deployment/scripts/mongod/6.rc.0/11_remove_useless_tenant2_and_profiles_attached.js.j2
Labels: enhancement, small, VAS

#971 US 10195 : Fix leaves facets search reloading
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
Labels: bug, small, VAS

#972 [VAS] Support #10004: Remove profils for useless auto_tenant.
  deployment/scripts/mongod/6.rc.0/11_remove_useless_tenant2_and_profiles_attached.js.j2
Labels: small, VAS, Cherry-Pick

#973 [VAS] Support #10004: Remove profils for useless auto_tenant.
  deployment/scripts/mongod/6.rc.0/11_remove_useless_tenant2_and_profiles_attached.js.j2
Labels: small, VAS, Cherry-Pick

#978 Correct search project criteria and sanityCheck path bugs
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectInternalController.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SafeFileChecker.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SafeFileCheckerTest.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectController.java
Labels: bug, small

#947 [VAS] Bug #9753: show total of elements in search
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelperTest.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/PaginatedValuesDto.java
  ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts
  ui/ui-frontend-common/src/app/modules/vitamui-table/infinite-scroll-table.ts
  ui/ui-frontend-common/src/app/modules/vitamui-table/paginated-response.interface.ts
  ui/ui-frontend-common/src/app/modules/vitamui-table/search.service.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
Labels: bug, javascript, java, small, VAS

#951 [VAS] Story #10230: add download ATR
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/access/LogbookService.java
  ui/ui-frontend-common/src/app/modules/models/logbook/api-event.interface.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/logbook-operation.interface.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, VAS

#980 [VAS] Bug #9074: show correct end date for ingest
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-information-tab/logbook-management-operation-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.ts
Labels: bug, javascript, VAS

#981 [VAS] Story #10354: clean code sur la recherche
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-search-helper.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-elimination.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/update-unit-management-rule.service.ts
Labels: bug, javascript, small, VAS

#983 [VAS] 10402 : correct referential internal java tests
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl01.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl02.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl03.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl04.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl05.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl06.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl07.json
  api/api-referential/referential-internal/src/test/resources/json/access-register/dsl08.json
Labels: bug, small, VAS

#984 [VAS] : 10402 : correct vitamui issues
  cas/cas-server/src/main/resources/static/css/cas.css
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-permission-tab/context-permission-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-permission-tab/context-permission-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.spec.ts
Labels: small, VAS

#986 [VAS-10402] Fix issue on icones generation on PR #675
  ui/ui-frontend-common/icomoon-selection.json
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
Labels: bug, small, VAS

#967 VAS-9979: Bump thymeleaf-spring5 from 3.0.12.RELEASE to 3.0.13.RELEAS…
  cots/vitamui-mongo-express/package-lock.json
  cots/vitamui-mongo-express/package.json
  pom.xml
Labels: enhancement, dependencies, small, VAS

#990 [VAS] ITEM 10378 : correct applications positions
  deployment/scripts/mongod/6.rc.0/20_update_applications_ingest_and_consultation_positions.js.j2
Labels: bug, small, VAS

#993 [VAS] Support #10004 et #10399 : Remove profils for useless auto_tenant.
  deployment/scripts/mongod/6.rc.0/11_remove_useless_tenant2_and_profiles_attached.js.j2
Labels: small, VAS, OPS REVIEW
