Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-12, with the labels that each got.

#1121 [bug] Update unitary tests
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectObjectGroupController.java
  ui/ui-collect/src/test/java/fr/gouv/vitamui/collect/service/ProjectObjectGroupServiceTest.java
Labels: bug, small, VAS

#1123 Bug/vas 10767 fix archive search and identity bug
  ui/ui-frontend/projects/archive-search/src/app/app.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/identity/src/app/app.module.ts
Labels: bug, small, VAS

#1122 Feature/vas item 10766 fonts google
  cas/cas-server/src/main/config/sass/_font-styles.scss
  cas/cas-server/src/main/config/sass/cas.scss
  cas/cas-server/src/main/resources/static/css/cas.css
  cas/cas-server/src/main/resources/static/css/fontStyles/mulishLatin.woff2
  cas/cas-server/src/main/resources/static/css/fontStyles/mulishLatinExt.woff2
  ui/ui-frontend-common/src/sass/base/_base.scss
  ui/ui-frontend-common/src/sass/base/fontsGoogle/mulishFontsGoogleLatin.woff2
  ui/ui-frontend-common/src/sass/base/fontsGoogle/mulishFontsGoogleLatinExt.woff2
Labels: bug, small, VAS

#1127 [VAS] : 10667 get all management rules
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/config/converter/RuleConverter.java
  commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/converter/RuleConverterTest.java
Labels: bug, small, VAS

#1129 [VAS] correct vitamUI build
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: small, VAS

#1128 bug/vas-10771-fix-bugs-on-external-params-updating
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalparamprofile/service/ExternalParamProfileInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/ExternalParamProfileInternalController.java
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.html
Labels: bug, small, VAS, Highlight

#1124 [VAS][PASTIS] some corrections
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/profile/ProfileInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ArchivalProfileUnitInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ProfileInternalController.java
  ui/ui-frontend/projects/pastis/src/app/core/services/archive-profile-api.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, small, VAS

#1132 Bump pom from 5.1 snapshot to 5.2 snapshot on master 5.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: OPS REVIEW

#1091 rename profiles for customer init applications : GROUPS, ACCOUNTS, PROFILES, USERS
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
Labels: enhancement, small, VAS

#1104 [VAS][10622] : active front TUs on all projects
  ui/ui-archive-search/pom.xml
  ui/ui-collect/pom.xml
  ui/ui-frontend-common/package.json
  ui/ui-frontend/angular.json
  ui/ui-frontend/package.json
  ui/ui-frontend/pom.xml
  ui/ui-frontend/projects/referential/karma.conf.ci.js
  ui/ui-frontend/projects/referential/karma.conf.js
  ui/ui-ingest/pom.xml
Labels: enhancement, small, VAS, Security

#1136 fix wrong behaviour on computing facets
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug, small, VAS

#1139 [VAS] : 10790 upgrade vitamui profiles with missing roles
  deployment/scripts/mongod/2.0.0/51_migration_roles_reclassification_updaterules_inheritesrules_script.js.j2
  deployment/scripts/mongod/2.0.0/53_migration_role_update_desc_unit_metadata_script.js.j2
  deployment/scripts/mongod/2.0.0/56_migration_archive_search_profiles_roles.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1140 [VAS][CP5X] : 10790 upgrade vitamui profiles with missing roles (#1139)
  deployment/scripts/mongod/2.0.0/51_migration_roles_reclassification_updaterules_inheritesrules_script.js.j2
  deployment/scripts/mongod/2.0.0/53_migration_role_update_desc_unit_metadata_script.js.j2
  deployment/scripts/mongod/2.0.0/56_migration_archive_search_profiles_roles.js.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1137 [VAS] Bug #10698: PASTIS errors on pua update
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaFromJSON.java
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/archivalprofileunit/ArchivalProfileUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/exception/InternalServerException.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/converter/VitamUIErrorConverter.java
  ui/ui-frontend-common/src/app/modules/startup.service.ts
  ui/ui-frontend/projects/pastis/src/app/models/vitam-ui-exception-response.model.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile-options/save-profile-options.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
Labels: bug, VAS

#1142 fixe VitamUI build issue
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.spec.ts
Labels: bug, small, VAS

#1151 CP V5 - Story #10841: Fix Start/Stop playbooks for VitamUI.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
  deployment/roles/service_state/defaults/main.yml
  deployment/roles/service_state/tasks/main.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1150 Story #10841: Fix Start/Stop playbooks for VitamUI.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
  deployment/roles/service_state/defaults/main.yml
  deployment/roles/service_state/tasks/main.yml
Labels: bug, small, VAS, OPS REVIEW
