Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-10, with the labels that each got.

#995 VAS-10354: fix-bug-on-showing-facets
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-search-helper.service.ts
Labels: bug, small, VAS

#992 [VAS] 10163 : correct superAdmin profiles
  deployment/scripts/mongod/6.rc.0/30_update_superadmin_customer_profile.js.j2
Labels: bug, small, VAS, Security, OPS REVIEW

#988 [VAS] : 10385 : add more translate and filter with reply transfer operation
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-constants.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.scss
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
Labels: enhancement, small, VAS, Highlight

#998 item#10326 Add missed spring data conf for collect internal
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
Labels: small, VAS

#989 story#10288 : Hide items that are not yet functional in the Collect APP
  ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.html
  ui/ui-frontend-common/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.css
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#997 [VAS] 8567 add ontologies to archive and collect project
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/app/modules/models/index.ts
  ui/ui-frontend-common/src/app/modules/models/ontology/index.ts
  ui/ui-frontend-common/src/app/modules/models/ontology/ontology.interface.ts
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/ontologies/ontologies.json
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/collect/src/assets/ontologies/ontologies.json
Labels: bug, VAS

#999 [VAS] bugs archive search and collect
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/confirm-action/confirm-action.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/confirm-action/confirm-action.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/confirm-action/confirm-action.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-list/confirm-action/confirm-action.module.ts
Labels: bug, small, VAS

#1003 story #10261 fix api
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
Labels: small, VAS

#1004 VAS-9979: Bump thymeleaf-spring5 from 3.0.12.RELEASE to 3.0.15
  pom.xml
Labels: bug, small, VAS

#1001 [VAS] Story #10341: leaves navigation with only results
  ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/node.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-facets.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/classification-tree/classification-tree.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/lib/models/description-level.enum.ts
Labels: enhancement, javascript, VAS

#1011 [VAS][CP5X] 9752 : update ingest report title
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#1012 [VAS][CP5RCX] 9752 : update ingest report title
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#1013 [VAS][CP40X] 9752 : update ingest report title
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#1010 [VAS] 9752 : update ingest report title
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS

#1017 [VAS] Bug #10432: change snackbar traductions
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.service.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.service.ts
  ui/ui-frontend/projects/referential/src/app/context/context.service.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-list/file-format-list.component.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format.service.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.service.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.service.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.service.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile.service.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, javascript, VAS

#1009 [10437] : correct error exceptions message traductions
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/app/modules/vitamui-http-interceptor.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
Labels: bug, small, VAS

#1019 [VAS] Bug #9826: contract entry reattachment empty
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
Labels: bug, javascript, small, VAS

#1021 [VAS][CP5RCX] Bug #9826: contract entry reattachment empty
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#1018 [VAS] 10221 : correct object criteria translate issue
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
Labels: bug, small, VAS

#1014 clean code on disabling front end test & managing exception handling
  Jenkinsfile
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
  ui/ui-frontend/pom.xml
Labels: bug, small

#1026 [9978] : change dateTime behaviour to support all web navigators
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/package.json
Labels: bug, small, VAS, Highlight

#1031 Bug/Vas-10525: fix some issues on ingest list page
  ui/ui-frontend/projects/ingest/src/app/app.module.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
Labels: bug, small, VAS

#1030 [VAS] BUG story #10521 - Fix prerequisite role to allow nginx usage o…
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
Labels: bug, small, OPS REVIEW

#1025 story #10383 BUG- Collecte- Changement de l'intitulé des wizard de la…
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, small, VAS, Highlight

#1035 [9978] [CP5RX]: change dateTime behaviour to support all web navigators (#1026)
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/confirm-action/confirm-action.module.ts
Labels: bug, small, VAS, Cherry-Pick

#1034 [9978] [CP5RCX] : change dateTime behaviour to support all web navigators (#1026)
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/confirm-action/confirm-action.module.ts
Labels: bug, small, VAS, Cherry-Pick

#1033 [VAS] 10137 : add transfer translate
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: bug, small, VAS

#1039 fixe syntaxe issue
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/confirm-action/confirm-action.module.ts
Labels: bug, small, VAS

#1042 bug/VAS-9979: exlclude duplicated dependencies on thymeleaf
  cas/cas-server/pom.xml
Labels: bug, dependencies, small, VAS

#1036 Bug/Vas-10525:replace ngx-filesize lib that has error by implemented …
  ui/ui-frontend-common/src/app/modules/pipes/filesize.pipe.ts
  ui/ui-frontend-common/src/app/modules/pipes/pipes.module.ts
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/ingest/src/app/core/common/ingest-list.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/upload-tracking/upload-tracking.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/upload-tracking/upload-tracking.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/upload-tracking/upload-tracking.module.ts
  ui/ui-frontend/projects/referential/src/app/app.module.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.module.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-information-tab/securisation-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-information-tab/securisation-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-preview.module.ts
Labels: bug, small, VAS

#1041 [VAS] Story 10181 - update metadata using csv (fix build)
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
Labels: enhancement, small, VAS, Highlight

#1040 [VAS] Bug #10431: change message on rule suppression
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/confirm-action/confirm-action.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/confirm-action/confirm-action.component.ts
Labels: bug, javascript, small, VAS

#1007 [VAS] : 10309 Add AU tree attachment component
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
  deployment/scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2
  deployment/scripts/mongod/6.rc.0/05_update_contexts_with_collect_roles.js.j2
  ui/ui-collect/src/main/resources/application-dev.yml
  ui/ui-commons/pom.xml
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/config/AutoConfigurationService.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/config/UICommonsAutoConfiguration.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/config/UIPropertiesImpl.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/property/UIProperties.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/rest/UnitController.java
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/service/UnitService.java
  ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/config/UICommonsAutoConfigurationTest.java
  ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/rest/ApplicationControllerTest.java
  ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/rest/SecurityControllerTest.java
  ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/rest/SubrogationControllerTest.java
  ui/ui-commons/src/test/java/fr/gouv/vitamui/ui/commons/rest/UserControllerTest.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/classification-tree/classification-tree.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/classification-tree/classification-tree.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/classification-tree/classification-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.handler.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-identity/src/main/resources/application-dev.yml
  ui/ui-identity/src/test/resources/application.yml
  ui/ui-ingest/src/main/resources/application-dev.yml
  ui/ui-ingest/src/test/resources/application.yml
  ui/ui-portal/src/main/resources/application-dev.yml
  ui/ui-portal/src/test/resources/application.yml
  ui/ui-referential/src/main/resources/application-dev.yml
  ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/service/UnitServiceTest.java
  ui/ui-referential/src/test/resources/application.yml
Labels: enhancement, VAS, Highlight

#1047 [VAS] item#10309 Add missing method for collect service
  ui/ui-frontend/projects/vitamui-library/src/lib/api/search-unit-api.service.ts
Labels: bug, small, VAS

#1046 [VAS] Bug #10422: add resolver on certain apps
  ui/ui-frontend/projects/referential/src/app/app-routing.module.ts
Labels: bug, javascript, small, VAS

#1048 Pic add planification for builds
  Jenkinsfile
Labels: small, OPS REVIEW

#1049 [VAS] 10434 : add control on legalStatus
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: bug, small, VAS

#1051 [VAS] 9979 clean collect front tests
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: small, VAS, Security

#1052 BUG/VAS-9979: remove cas duplicated dependencies 'thymleaf'
  cas/cas-server/pom.xml
Labels: bug, small, VAS

#1057 CP 5RC - [VAS] 10316 : add more translate on audit application
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.spec.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#1056 [VAS] 10533 fixe translate issue
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
Labels: bug, small, VAS

#1055 CP V5 - [VAS] Bug #10422: add resolver on certain apps (#1046)
  ui/ui-frontend/projects/referential/src/app/app-routing.module.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#1054 CP 5RC - [VAS] Bug #10422: add resolver on certain apps (#1046)
  ui/ui-frontend/projects/referential/src/app/app-routing.module.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#1053 [VAS] Bug #10167: Bug accession register search
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
Labels: bug, javascript, small, VAS

#1061 [VAS] Bug #9753: Bug accession register total number in facets
  ui/ui-frontend-common/src/app/modules/components/logbook-operation-facet/logbook-operation-facet.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
Labels: bug, javascript, small, VAS

#1059 [VAS][CP5RCX] 10533 fixe translate issue
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.html
Labels: bug, small, VAS, Cherry-Pick

#1060 correct build issue
  .gitignore
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-information-tab/securisation-information-tab.component.spec.ts
Labels: small, VAS

#1062 [VAS] [CP5X] 10163 : correct superAdmin profiles (#992)
  deployment/scripts/mongod/5.x/11_remove_useless_tenant2_and_profiles_attached.js.j2
  deployment/scripts/mongod/5.x/30_update_superadmin_customer_profile.js.j2
Labels: bug, small, VAS, Cherry-Pick

#1063 [VAS] [CP5RCX] 10163 : correct superAdmin profiles (#992)
  deployment/scripts/mongod/5.rc.x/11_remove_useless_tenant2_and_profiles_attached.js.j2
  deployment/scripts/mongod/5.rc.x/30_update_superadmin_customer_profile.js.j2
Labels: bug, small, VAS, Cherry-Pick

#1066 Bug/VAS-10594: rollback upgrading thymleaf
  cas/cas-server/pom.xml
  pom.xml
Labels: bug, dependencies, small, VAS
