Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-03, with the labels that each got.

#680 Fix CAS authn delegation when proxy
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/AppConfig.java
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/util/Utils.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/IamSurrogateAuthenticationServiceTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/UserAuthenticationHandlerTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolverTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/pm/IamPasswordManagementServiceTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/provider/ProvidersServiceTest.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/DispatcherActionTest.java
Labels: small, VAS

#686 [VAS] Story #9566: Migration vitamui profile from R16
  deployment/scripts/mongod/2.0.0/35_delete_archive_search_profiles.js.j2
  deployment/scripts/mongod/2.0.0/36_create_new_archive_search_profiles.js.j2
  deployment/scripts/mongod/2.0.0/41_add_search_with_rules_role_to_old_system_archive_profile.js.j2
Labels: bug, small

#677 [VAS] CP 5RC - Story #9566 : Migration vitamui profile from R16
  deployment/scripts/mongod/2.0.0/35_delete_archive_search_profiles.js.j2
  deployment/scripts/mongod/2.0.0/36_create_new_archive_search_profiles.js.j2
  deployment/scripts/mongod/2.0.0/41_add_search_with_rules_role_to_old_system_archive_profile.js.j2
Labels: bug, small, VAS, Cherry-Pick

#688 [VAS] Story #9558 - Add redirection for agent connect in apache configuration
  deployment/environments/group_vars/all/jvm_opts.yml
  deployment/roles/reverse/templates/apache/httpd_config
Labels: enhancement, small, VAS

#689 [VAS] Story #9602: Remove unexisting elements in R16 for externalParameters.
  deployment/environments/group_vars/all/mongodb_vars.yml
  deployment/scripts/mongod/2.0.0/33_update_admin_externalParameters_value.js.j2
Labels: bug, small, VAS

#676 [VAS] Story #9602: Create missing profiles during upgrade and migrate old ones.
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  deployment/scripts/mongod/1.0.0/316_application_ref.js.j2
  deployment/scripts/mongod/2.0.0/04_add_default_external_parameters_profile.js.j2
  deployment/scripts/mongod/2.0.0/10_update_external_param_profile.js
  deployment/scripts/mongod/2.0.0/20_logbook_operation_management_application.js.j2
  deployment/scripts/mongod/2.0.0/22_update_ui_referential_context.js.j2
  deployment/scripts/mongod/2.0.0/23_update_ui_referential_context.js.j2
  deployment/scripts/mongod/2.0.0/33_update_admin_externalParameters_value.js.j2
  deployment/scripts/mongod/2.0.0/47_create_new_profiles_during_upgrade.js.j2
  deployment/scripts/mongod/2.0.0/48_migrate_archivesearch_profiles.js.j2
  deployment/scripts/mongod/2.0.0/49_add_missing_role_in_contexts.js.j2
Labels: bug, small, VAS, OPS REVIEW

#692 [VAS] CP 5RC - Story #9602: Create missing profiles during upgrade and migrate old ones.
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
  deployment/scripts/mongod/1.0.0/316_application_ref.js.j2
  deployment/scripts/mongod/2.0.0/04_add_default_external_parameters_profile.js.j2
  deployment/scripts/mongod/2.0.0/10_update_external_param_profile.js
  deployment/scripts/mongod/2.0.0/20_logbook_operation_management_application.js.j2
  deployment/scripts/mongod/2.0.0/22_update_ui_referential_context.js.j2
  deployment/scripts/mongod/2.0.0/23_update_ui_referential_context.js.j2
  deployment/scripts/mongod/2.0.0/33_update_admin_externalParameters_value.js.j2
  deployment/scripts/mongod/2.0.0/47_create_new_profiles_during_upgrade.js.j2
  deployment/scripts/mongod/2.0.0/48_migrate_archivesearch_profiles.js.j2
  deployment/scripts/mongod/2.0.0/49_add_missing_role_in_contexts.js.j2
Labels: bug, VAS, Cherry-Pick, OPS REVIEW

#693 [VAS] fixe us 9602 issue with customers creation
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
Labels: small, VAS

#695 [VAS] Story #9607: Add upgrade documentation for Vitam-UI.
  deployment/environments/group_vars/all/vault-mongodb.yml
  deployment/environments/group_vars/all/vault-mongodb.yml.example
  docs/fr/migration/index.md
  docs/fr/migration/upgrade_v5.md
  docs/fr/migration/upgrade_v5rc.md
Labels: documentation, small, VAS

#700 [VAS] correct mongo script
  deployment/scripts/mongod/2.0.0/51_migration_roles_reclassification_updaterules_inheritesrules_script.js.j2
Labels: small, VAS

#702 [VAS] Story #9602: Switch back admin_group to ARCHIVE_SEARCH_MANAGEMENT_APP-ADMIN profile.
  deployment/scripts/mongod/2.0.0/49_switch_admin_group_to_archivesearch-admin_profile.js.j2
Labels: small, VAS, OPS REVIEW

#703 [VAS] CP5RC - Story #9602: Switch back admin_group to ARCHIVE_SEARCH_MANAGEMENT_APP-ADMIN profile.
  deployment/scripts/mongod/2.0.0/49_switch_admin_group_to_archivesearch-admin_profile.js.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#691 [VAS] BUG 9567 : add get access contract to archive profiles
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/50_add_get_access_contract_role_to_archive_profiles.js.j2
Labels: small, VAS, OPS REVIEW

#704 [VAS] Item 8538: Update archival unit descriptive metadata
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/UnitDescriptiveMetadataDto.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchivesSearchExternalService.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClient.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_1.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_2.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_3.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_4.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_5.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_6.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/query_7.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/updateUnits/response.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/update_unit_descriptive_metadata_response.json
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/52_update_archive_search_context_to_add_unit_descriptive_metadata_update_role.js.j2
  deployment/scripts/mongod/2.0.0/53_migration_role_update_desc_unit_metadata_script.js.j2
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-frontend-common/ui-frontend-common-2.1.31.tgz
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/unitDescriptiveMetadata.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, VAS, Highlight, OPS REVIEW

#707 [VAS] Story 9639: Fix RP for internal deployments.
  deployment/roles/reverse/templates/apache/httpd_config
Labels: small, VAS, OPS REVIEW

#697 [VAS] CP5RC - Story #9639: Update mongo_express configuration.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/group_vars/all/mongo_express_vars.yml
  deployment/environments/group_vars/all/vault-mongodb.yml
  deployment/environments/group_vars/all/vault-mongodb.yml.example
  deployment/environments/hosts-ui.example
  deployment/roles/mongo-express/handlers/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo-express/templates/env.sh.j2
  deployment/roles/mongo-express/templates/service-componentid.json.j2
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/templates/apache/httpd_config
Labels: enhancement, small, VAS, Cherry-Pick, OPS REVIEW

#698 [VAS] CPR16 - Story #9639: Update mongo_express configuration.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/group_vars/all/mongo_express_vars.yml
  deployment/environments/group_vars/all/vault-mongodb.yml
  deployment/environments/group_vars/all/vault-mongodb.yml.example
  deployment/environments/hosts-ui.example
  deployment/roles/mongo-express/handlers/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo-express/templates/env.sh.j2
  deployment/roles/mongo-express/templates/service-componentid.json.j2
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/templates/apache/httpd_config
Labels: enhancement, small, VAS, Cherry-Pick, OPS REVIEW

#706 [VAS] Add Contributors
  CONTRIBUTORS.md
Labels: small, VAS

#708 Update Contributors (#706)
  CONTRIBUTORS.md
Labels: documentation, small

#705 [VAS] fixe css design
  deployment/scripts/mongod/2.0.0/51_migration_roles_reclassification_updaterules_inheritesrules_script.js.j2
  ui/ui-frontend/projects/archive-search/src/app/app.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/sass/styles.scss
Labels: small, VAS

#711 [VAS] ITEM 9287 : add rule measurement to lateral panel
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rules.constants.ts
Labels: enhancement, small, VAS

#717 [VAS][PROD] BUG : 9073 correct search with originating agency name
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-commons/src/test/java/fr/gouv/vitamui/archive/search/dsl/VitamQueryHelperTest.java
  api/api-archive-search/archive-search-commons/src/test/resources/data/query_with_identifier_criteria.json
  api/api-archive-search/archive-search-commons/src/test/resources/data/query_with_identifier_name_criteria.json
  api/api-archive-search/archive-search-commons/src/test/resources/data/query_with_list_of_names_criteria.json
  api/api-archive-search/archive-search-commons/src/test/resources/data/query_with_one_name_criteria.json
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalService.java
Labels: bug, small, VAS

#714 [VAS][CPR16] BUG 8602 show the correct originating agency value
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/models/unit.interface.ts
Labels: bug, small, VAS, Cherry-Pick

#715 [VAS][CP5RC] BUG 8602 : show the correct originating agency value
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/models/unit.interface.ts
Labels: bug, small, VAS, Cherry-Pick

#719 [VAS] BUG 9715: add more correction on update archive unit rules
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/appraisal/expected-search-query-with-rule-identifier-and-rule-startDate.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/appraisal/expected-search-query-with-rule-identifier.txt
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: small, VAS

#724 [VAS] item 9665 : update external parameter information name
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerService.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/tenant/service/TenantInternalService.java
Labels: enhancement, small, VAS

#723 [VAS] Bug 9700: Fix management rules filters and facets bugs
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/SearchCriteriaDto.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#722 [VAS] bug 9101 9098 update archive application profiles description
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/47_create_new_profiles_during_upgrade.js.j2
  deployment/scripts/mongod/2.0.0/54_update_archive_search_application_informations.js.j2
  deployment/scripts/mongod/2.0.0/55_update_archive_search_proles_description.js.j2
Labels: bug, small, VAS

#725 [VAS] Bug 9352-9608 : bugs registre des fonds
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dsl/VitamQueryHelper.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/AccessionRegisterStatsDto.java
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/AccessionRegisterDetailExternalRestClient.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessionRegisterExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/AccessionRegisterDetailExternalService.java
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/AccessionRegisterDetailInternalRestClient.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterStatsHelper.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterConverter.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/summary/AccessionRegisterSummaryInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterInternalController.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/SwaggerJsonFileGenerationTest.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/rest/AccessionRegisterDetailInternalControllerTest.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/AccessionRegisterInternalServiceTest.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessionRegisterDetailsSearchStatsDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/PaginatedValuesDto.java
  pom.xml
  ui/ui-frontend-common/src/app/modules/components/vitamui-interval-date-picker/vitamui-interval-date-picker.component.ts
  ui/ui-frontend-common/src/app/modules/vitamui-table/paginated-response.interface.ts
  ui/ui-frontend-common/src/app/modules/vitamui-table/search.service.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-facets/accession-register-facets.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/core/api/accession-register-detail-api.service.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/AccessionRegisterController.java
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/service/AccessionRegisterDetailService.java
Labels: bug, VAS

#727 Bug/item 9700 fix mgt rules and facets bugs
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: small, VAS

#731 Bug/item 9700 fix mgt rules and facets bugs
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: small, VAS

#733 [VAS][CP5RC] cp bug 9101 9098 5rcx
  api/api-iam/iam-internal/src/main/config/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/47_create_new_profiles_during_upgrade.js.j2
  deployment/scripts/mongod/2.0.0/54_update_archive_search_application_informations.js.j2
  deployment/scripts/mongod/2.0.0/55_update_archive_search_proles_description.js.j2
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#735 [VAS][CP5RC] cp correct mongo script 5rc
  deployment/scripts/mongod/2.0.0/55_update_archive_search_proles_description.js.j2
Labels: bug, small, VAS, Cherry-Pick

#728 [VAS] fix vault mongo_express variable and consul reload handler
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/group_vars/all/vault-mongodb.yml
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/handlers/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/defaults/main.yml
  deployment/roles/mongo/handlers/main.yml
  deployment/roles/mongo/tasks/main.yml
Labels: small, VAS, OPS REVIEW

#729 [VAS] CP R16: fix vault mongo_express variable and consul reload handler
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/group_vars/all/vault-mongodb.yml
  deployment/environments/group_vars/all/vault-mongodb.yml.example
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/handlers/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/defaults/main.yml
  deployment/roles/mongo/handlers/main.yml
  deployment/roles/mongo/tasks/main.yml
Labels: small, VAS, OPS REVIEW

#730 [VAS] CP 5RC: fix vault mongo_express variable and consl reload handler
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/group_vars/all/vault-mongodb.yml
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/handlers/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/defaults/main.yml
  deployment/roles/mongo/handlers/main.yml
  deployment/roles/mongo/tasks/main.yml
Labels: small, VAS, OPS REVIEW

#737 [VAS] Disable unsecure TLSv1.1
  api/api-archive-search/archive-search-external/src/main/resources/application-dev.yml
  api/api-iam/iam-external/src/main/resources/application-dev.yml
  api/api-ingest/ingest-external/src/main/resources/application-dev.yml
  api/api-referential/referential-external/src/main/resources/application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/reverse/templates/nginx/ssl/ssl.conf.j2
  ui/ui-archive-search/src/main/resources/application-dev.yml
  ui/ui-archive-search/src/main/resources/application-recette.yml
  ui/ui-archive-search/src/test/resources/application.yml
  ui/ui-identity/src/main/resources/application-dev.yml
  ui/ui-identity/src/test/resources/application.yml
  ui/ui-ingest/src/main/resources/application-dev.yml
  ui/ui-ingest/src/main/resources/application-recette.yml
  ui/ui-ingest/src/test/resources/application.yml
  ui/ui-portal/src/main/resources/application-dev.yml
  ui/ui-referential/src/main/resources/application-dev.yml
  ui/ui-referential/src/test/resources/application.yml
Labels: small, VAS, Security, OPS REVIEW

#739 [VAS] Bug : Regression recherche par GUID régistre des fonds
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
Labels: bug, small, VAS

#738 [VAS] CP R16 - BUG 9073: correct search with originating agency name
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveInternalServiceTest.java
  ui/ui-frontend/package-lock.json
Labels: bug, small, VAS, Cherry-Pick

#741 [VAS] CP 5RC - Disable unsecure TLSv1.1
  api/api-archive-search/archive-search-external/src/main/config/archive-search-external-application-dev.yml
  api/api-iam/iam-external/src/main/config/iam-external-application-dev.yml
  api/api-ingest/ingest-external/src/main/config/ingest-external-application-dev.yml
  api/api-referential/referential-external/src/main/config/referential-external-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/reverse/templates/nginx/ssl/ssl.conf.j2
  ui/ui-archive-search/src/main/config/ui-archive-search-application-dev.yml
  ui/ui-archive-search/src/main/config/ui-archive-search-application-recette.yml
  ui/ui-archive-search/src/test/resources/ui-archive-search-application.yml
  ui/ui-identity/src/main/config/ui-identity-application-dev.yml
  ui/ui-identity/src/test/resources/ui-identity-application.yml
  ui/ui-ingest/src/main/config/ui-ingest-application-dev.yml
  ui/ui-ingest/src/main/config/ui-ingest-application-recette.yml
  ui/ui-ingest/src/test/resources/ui-ingest-application.yml
  ui/ui-portal/src/main/config/ui-portal-application-dev.yml
  ui/ui-referential/src/main/config/ui-referential-application-dev.yml
  ui/ui-referential/src/test/resources/ui-referential-application.yml
Labels: small, VAS, Cherry-Pick, Security

#740 [VAS] Bug 9729 : Fix update unit metadata
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/scripts/mongod/2.0.0/53_migration_role_update_desc_unit_metadata_script.js.j2
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/archive-unit-validator.service.ts
Labels: bug, small, VAS, OPS REVIEW

#743 [VAS] FIX BUG 9292: Remove useless referential-external-client parameters from ui components.
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
Labels: small, VAS, OPS REVIEW

#744 [VAS] Bug 9729 : Fix update unit metadata and fix build
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.spec.ts
Labels: small, VAS

#747 [VAS] Bug-9743 Fix regression on file downloading
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
Labels: bug, small, VAS

#749 Fix for OPI request
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
Labels: bug, small, VAS

#752 [VAS] upgrade Vitam version to 6.rc.0-SNAPSHOT
  pom.xml
Labels: dependencies, VAS

#755 [VAS] Story 9679: Default disabling of Vitam services at system startup.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/vars/main.yml
Labels: small, VAS, OPS REVIEW

#756 [VAS] CP V5 - Story 9679: Default disabling of Vitam services at system startup.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/vars/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#757 [VAS] CP 5RC: Story 9679: Default disabling of Vitam services at system startup.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/vars/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#758 [VAS] CP R16 - Story 9679: Default disabling of Vitam services at system startup.
  deployment/environments/group_vars/all/vitam_vars.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/defaults/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/vars/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW
