Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-01, with the labels that each got.

#606 [VAS] [CP5RC] Update component_type for cas_server from external to ui.
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/tasks/ui.yml
Labels: small, VAS, Cherry-Pick

#607 [VAS] [CPR16] Update component_type for cas_server from external to ui.
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/tasks/ui.yml
Labels: small, VAS, Cherry-Pick

#602 story #9331 Use Sphinx for technical documentation
  docs/fr/exploitation/Makefile
  docs/fr/exploitation/_static/css/theme.css
  docs/fr/exploitation/_toc.rst
  docs/fr/exploitation/conf.py
  docs/fr/exploitation/images/Vitam_Logo-CMJN.png
  docs/fr/exploitation/index.md
  docs/fr/exploitation/index.rst
  docs/fr/exploitation/sections/procedure.md
  docs/fr/installation/Makefile
  docs/fr/installation/_static/css/theme.css
  docs/fr/installation/_toc.rst
  docs/fr/installation/conf.py
  docs/fr/installation/images/Vitam_Logo-CMJN.png
  docs/fr/installation/index.md
  docs/fr/installation/index.rst
  docs/fr/installation/sections/annexes.md
  docs/fr/installation/sections/password_configurations.md
  docs/fr/installation/sections/procedure.md
Labels: documentation, enhancement, small

#605 [VAS] [R16] Fix wrong repository configuration.
  deployment/environments/group_vars/all/repositories.yml
  deployment/environments/vitamui_extra_vars.yml
Labels: bug, small

#604 [VAS] [5RC] Fix wrong repository configuration.
  deployment/environments/group_vars/all/repositories.yml
  deployment/environments/vitamui_extra_vars.yml
Labels: bug, small

#622 Fix Vitamui Build: due to Infinite loop in a malicious package
  ui/ui-frontend/package.json
Labels: bug, small, VAS, Don't delete branch

#623 Cherry-pick : Fix Vitamui Build: due to Infinite loop in a malicious package (#622)
  ui/ui-frontend/package.json
Labels: bug, VAS, Cherry-Pick, Don't delete branch

#616 Convert files present in docs/DAT/docs/dat_vitamui in Sphinx format
  docs/DAT/README.md
  docs/fr/architecture/README.md
  docs/fr/architecture/conf.py
  docs/fr/architecture/images/Vitam_Logo-CMJN.png
  docs/fr/architecture/images/dat_archi_cas.png
  docs/fr/architecture/images/dat_cas_1.png
  docs/fr/architecture/images/dat_cas_2.png
  docs/fr/architecture/images/dat_cas_3.png
  docs/fr/architecture/images/dat_cas_4.png
  docs/fr/architecture/images/dat_chaine_deploiement.png
  docs/fr/architecture/images/dat_level.png
  docs/fr/architecture/images/dat_pki_1.png
  docs/fr/architecture/images/dat_session_1.png
  docs/fr/architecture/images/dat_zoning.png
  docs/fr/architecture/images/journalisation_architecture.png
  docs/fr/architecture/images/journalisation_transaction.png
  docs/fr/architecture/index.rst
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, enhancement, small

#612 [VAS] ITEM 8641 : add DUA rule property to Archive Units
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#615 [VAS] [CP R16] Item 8944: Access contrat status change issue
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.service.ts
Labels: bug, VAS, Cherry-Pick

#613 [VAS] Item 8944: Access contrat status change issue
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.service.ts
Labels: bug, small, VAS

#618 Fix inventory typo on DIN.
  docs/fr/installation/sections/procedure.md
Labels: documentation, small, VAS

#625 CP 5RC - Fix inventory typo on DIN.
  docs/fr/installation/sections/procedure.md
Labels: documentation, small, Cherry-Pick

#626 CP R16 - Fix inventory typo on DIN.
  docs/fr/installation/sections/procedure.md
Labels: documentation, small, Cherry-Pick

#620 [VAS] BUG 9119 delete elimination identifier with rule criterias
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#610 [VAS] BUG 8754 : fixe search archive unit with start and end dates
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
Labels: bug, small, VAS

#619 [VAS] BUG 9120 8911 save search criteria issue
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/CriteriaValue.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/search-criteria-list.component.html
Labels: bug, small, VAS

#513 [VAS] Update component_type for cas_server from external to ui.
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/vitamui/tasks/ui.yml
Labels: bug, small, VAS

#601 [VAS] Item 8331 : Remove advanced filter preservation
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dsl/VitamQueryHelper.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/AccessionRegisterDetailDto.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/AccessionRegisterDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/summary/AccessionRegisterSummaryInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessionRegisterDetailsSearchStatsDto.java
  ui/ui-frontend-common/src/app/modules/components/search-bar-with-sibling-button/search-bar-with-sibling-button.component.ts
  ui/ui-frontend-common/src/app/modules/models/access-register/accession-register-detail.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.scss
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, VAS

#594 [Vas] Item 9300 - Upgrade librairies to have same versions as cas-server
  pom.xml
Labels: enhancement, dependencies, small, VAS

#627 [VAS][CP5RCX] : BUG 8754 fixe search archive unit with start and end dates
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
Labels: bug, small, VAS, Cherry-Pick

#629 [VAS][CPR16] BUG 8754 : fixe search with dates issue
  .run/2 - Security-Internal.run.xml
  .run/4 - IAM-External.run.xml
  .run/6 - UI-Portal back.run.xml
  .run/7 - UI-Identity back.run.xml
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dsl/VitamQueryHelper.java
Labels: bug, small, VAS, Cherry-Pick

#631 [VAS][CP5RCX] : BUG 8911 : show save search title
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/search-criteria-list.component.html
Labels: bug, small, VAS, Cherry-Pick

#632 [VAS][CP5RCX] : Bug 9120 : remove criteria search
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/CriteriaValue.java
Labels: bug, small, VAS, Cherry-Pick

#634 DAT - Markdown lint.
  docs/fr/architecture/README.md
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, enhancement, small, VAS

#636 Story #7963: Fix consul resolution for mongo-vitamui when deployed on 2 networks
  deployment/roles/mongo/templates/service-componentid.json.j2
Labels: bug, small, VAS

#639 CPR16 - Story #7963: Fix consul resolution for mongo-vitamui when deployed on 2 networks.
  deployment/roles/mongo/templates/service-componentid.json.j2
Labels: bug, small, VAS, Cherry-Pick

#635 Fix typo on DAT.
  docs/fr/architecture/sections/architecture.md
  docs/fr/architecture/sections/gestion.md
  docs/fr/architecture/sections/implementation.md
  docs/fr/architecture/sections/intro_objectifs.md
  docs/fr/architecture/sections/orientations_techniques.md
Labels: documentation, small, VAS
