Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-06, with the labels that each got.

#813 [VAS][CP5X] Bug 9786 : change show download button for operation report #799
  ui/ui-frontend-common/src/app/modules/models/logbook/index.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/logbook-operation.interface.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-list/logbook-operation-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#812 [VAS][CP5X] Bug 9790: Set ingest status for list and preview (#791)
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/api-event.interface.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/event.interface.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/ingest-list.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/event.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-event-detail/ingest-event-detail.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-event-detail/ingest-event-detail.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.module.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-frontend/projects/ingest/src/app/models/logbook-event.interface.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#805 [VAS][CPR16] Bug 9790: Set ingest status for list and preview (#791)
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  ui/ui-frontend-common/src/app/modules/api/logbook-api.service.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/api-event.interface.ts
  ui/ui-frontend-common/src/app/modules/models/logbook/event.interface.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/ingest-list.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/event.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-event-detail/ingest-event-detail.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-event-detail/ingest-event-detail.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.module.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-frontend/projects/ingest/src/app/models/logbook-event.interface.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#822 [VAS] Bug - 9982: add forgotten referential-external settings on ui modules components
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
Labels: bug, small, VAS

#818 [VAS] ITEM : 9978 : correct VitamUI dates issue
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.html
Labels: bug, small, VAS

#823 [VAS][CP5RCX] ITEM : 9978 : correct vitamui dates issue (#818)
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.html
Labels: bug, small, VAS, Cherry-Pick

#824 [VAS][CP5X] ITEM : 9978 : correct vitamui dates issue (#818)
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.html
Labels: bug, small, VAS, Cherry-Pick

#831 [VAS] 9684 : correct some words
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#828 [VAS] ITEM 8645 : Block and unlock a rule inheritance
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/VitamUiRuleCategoryAction.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/VitamUiRuleCategoryActionDeletion.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/converter/RuleOperationsConverter.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/converter/RuleOperationsConverterTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/appraisal/expected-search-query-with-appraisal-inheritance-and-prevent-rule-identifier.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/appraisal/expected-search-query-with-appraisal-prevent-rule-identifier.txt
  api/api-archive-search/archive-search-internal/src/test/resources/data/queries/appraisal/expected-search-query-with-appraisal-prevent-rules-identifiers-list.txt
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/config/VitamClientConfig.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-update-property/add-update-property.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/block-rules-inheritance/block-rules-inheritance.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/block-rules-inheritance/block-rules-inheritance.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/block-rules-inheritance/block-rules-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/ruleAction.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/archive-unit-validator.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/management-rules-validator.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, VAS, Highlight

#825 [VAS] Bug 9848: wrong data in access register export
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/VitamUIUtils.java
  commons/commons-utils/src/test/java/fr/gouv/vitamui/commons/utils/VitamUIUtilsTest.java
Labels: bug, small, VAS

#819 [VAS] Feature- 9979- Vitmaui clean code
  tools/vitamui-conf-dev/README.md
  ui/ui-frontend/package.json
Labels: documentation, dependencies, small, VAS

#837 [VAS] Various fixes for mongo scripts.
  deployment/scripts/mongod/1.0.0/213_cas_services_ref.js.j2
  deployment/scripts/mongod/6.rc.0/01_add_consult_agencies_profil.js.j2
  deployment/scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2
  deployment/scripts/mongod/6.rc.0/02_application_ref.js.j2
  deployment/scripts/mongod/6.rc.0/03_update_cas_services_with_collect_application.js.j2
  deployment/scripts/mongod/6.rc.0/04_collect_demo.js.j2
  deployment/scripts/mongod/6.rc.0/04_update_certificates_collection_with_collect_certificate.js.j2
  deployment/scripts/mongod/6.rc.0/05_update_contexts_with_collect_roles.js.j2
  deployment/scripts/mongod/6.rc.0/06_add_role_TRANSFER_REQUEST.js.j2
Labels: small, VAS, OPS REVIEW

#834 [VAS] 10006- upgrade dependencies for : gson, jackson, xerces, esapi, antisamy
  pom.xml
Labels: dependencies, small, VAS

#839 [VAS] Small fix for mongo script.
  deployment/scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2
Labels: small, VAS, OPS REVIEW

#838 [VAS] Feature 9979: Add name to pom for some projects
  api/api-archive-search/pom.xml
  api/api-collect/pom.xml
  api/api-ingest/pom.xml
Labels: small, VAS

#842 [VAS] 10006 upgrade antisamy version
  commons/commons-security/src/main/resources/esapi/antisamy-esapi.xml
  commons/commons-security/src/main/resources/esapi/antisamy.xsd
Labels: enhancement, small, VAS, Security

#844 item #9817 Optimize on subscribers and manage disabled buttons
  ui/ui-frontend-common/src/app/modules/utils/role.enum.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
Labels: small, VAS

#840 Make messageIdentifier field required, fix some words typos
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: small, VAS

#829 Feature/vas 9798 upgrade mongo to v5 on vitamui
  Jenkinsfile
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/TestMongoConfig.java
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/TestMongoConfig.java
  api/api-security/security-internal/src/test/java/fr/gouv/vitamui/security/server/TestMongoConfig.java
  cas/cas-server/pom.xml
  commons/commons-logbook/src/test/java/fr/gouv/vitamui/commons/logbook/TestMongoConfig.java
  commons/commons-mongo/pom.xml
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/TestMongoConfig.java
  cots/vitamui-mongod/Makefile
  deployment/ansible-vitamui-migration/migration_mongodb_44.yml
  deployment/ansible-vitamui-migration/migration_mongodb_50.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/init-replica.js.j2
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_init/vars/main.yml
  deployment/roles/mongodb_migration_v44/tasks/main.yml
  deployment/roles/mongodb_migration_v44/tasks/update_packages_mongod.yml
  deployment/roles/mongodb_migration_v44/vars/main.yml
  deployment/roles/mongodb_migration_v5/files/reconfig.js
  deployment/roles/mongodb_migration_v5/tasks/main.yml
  deployment/roles/mongodb_migration_v5/tasks/reconfig.yml
  deployment/roles/mongodb_migration_v5/tasks/upgrade_pkg.yml
  deployment/roles/mongodb_set_feature_compatibility/tasks/main.yml
  deployment/roles/mongodb_set_feature_compatibility/templates/set_feature_compatibility.js.j2
  docs/fr/migration/upgrade_v6rc.md
  pom.xml
Labels: enhancement, dependencies, VAS, OPS REVIEW

#847 Feature/vas 10006 bump dependencies on v5 rc
  commons/commons-security/src/main/resources/esapi/antisamy-esapi.xml
  commons/commons-security/src/main/resources/esapi/antisamy.xsd
  pom.xml
  ui/ui-frontend/package.json
Labels: small, VAS, Cherry-Pick

#846 Feature/vas 10006 bump dependencies on v5
  commons/commons-security/src/main/resources/esapi/antisamy-esapi.xml
  commons/commons-security/src/main/resources/esapi/antisamy.xsd
  pom.xml
  ui/ui-frontend/package.json
Labels: dependencies, small, VAS, Cherry-Pick

#851 [VAS] Feature 9816: manage storage rules search and related facet (fix some bugs)
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/storage-rule-search/storage-rule-search.component.html
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#853 [VAS] BUG 9978: fix issue on vitamui dates
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
Labels: bug, small, VAS

#854 [VAS][CP V5] 9978: fix issue on vitamui dates
  ui/ui-frontend-common/src/app/modules/pipes/datetime.pipe.ts
Labels: bug, small, VAS, Cherry-Pick

#857 item#10121 disable upatable agencies informations fields + enhance cs…
  ui/ui-frontend-common/src/app/modules/utils/role.enum.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/sass/styles.scss
Labels: bug, small, VAS

#852 [VAS] Feature 9979: Clean code - update licence
  LICENSE.txt
Labels: enhancement, small, VAS

#841 [VAS] US 10010: upgrade mongo express vitamui
  commons/commons-mongo/pom.xml
  cots/vitamui-mongo-express/Makefile
  cots/vitamui-mongo-express/package-lock.json
  cots/vitamui-mongo-express/package.json
Labels: small, VAS

#860 [VAS] 10001 / 10007 correct text issues
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#864 [VAS][CP5RCX] Bug 9940: apply sort on arborescence in contract creation
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: bug, small, VAS, Cherry-Pick

#863 [VAS][CP5X] Bug 9940: apply sort on arborescence in contract creation
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: bug, small, VAS, Cherry-Pick

#862 [VAS][CP4X] Bug 9940: apply sort on arborescence in contract creation
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: bug, small, VAS, Cherry-Pick

#867 [VAS][CP5X] Bug 9826: patch entry contract with empty attachment
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/core/api/ingest-contract-api.service.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
Labels: bug, small, VAS, Cherry-Pick

#866 [VAS][CP5RCX] Bug 9826: patch entry contract with empty attachment
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/core/api/ingest-contract-api.service.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
Labels: bug, small, VAS, Cherry-Pick

#865 [VAS][CP4X] Bug 9826: patch entry contract with empty attachment
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/core/api/ingest-contract-api.service.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
Labels: bug, small, VAS, Cherry-Pick

#861 [VAS] Bug 9826: patch entry contract with empty attachment
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/core/api/ingest-contract-api.service.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.ts
Labels: bug, small, VAS

#833 [VAS] Bug 9940: apply sort on arborescence in contract creation
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: bug, small, VAS

#848 [VAS] Item 9920 : [SEDACCORD] Fix collect service url
  api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectListProjectDto.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/CollectProjectConverter.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/project/ProjectInternalService.java
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
  ui/ui-frontend/projects/collect/src/app/core/core.module.ts
Labels: small, VAS, OPS REVIEW
