Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-11, with the labels that each got.

#1072 Feature/VAS-10622: fix unit test for vitamui builds and activate tests on pipeline for V5-RC
  Jenkinsfile
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
Labels: bug, dependencies, small, VAS

#1071 Feature/VAS-10622: fix unit test for vitamui builds and activate tests on pipeline for V5
  Jenkinsfile
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
Labels: bug, dependencies, javascript, small, VAS

#1069 [VAS] Bug #10632: Bug affichage de l'arborescence
  ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/node.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
Labels: bug, javascript, small, VAS

#1074 [VAS] BUG : 10170 picto type archive
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
Labels: bug, small, VAS

#1079 [VAS] 8567 : delete duplicated ontologies
  ui/ui-frontend/projects/archive-search/src/assets/ontologies/ontologies.json
  ui/ui-frontend/projects/collect/src/assets/ontologies/ontologies.json
Labels: bug, small, VAS

#1081 item#10645 Delete return button in second step when creating project
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
Labels: small, VAS

#1080 Bug/VAS-10622: Fix unit tests on referential module and add filesize pipe
  ui/ui-frontend-common/src/app/modules/pipes/filesize.pipe.ts
  ui/ui-frontend-common/src/app/modules/pipes/pipes.module.ts
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/ingest/src/app/core/common/ingest-list.ts
  ui/ui-frontend/projects/ingest/src/app/shared/upload-tracking/upload-tracking.component.html
  ui/ui-frontend/projects/ingest/src/app/shared/upload-tracking/upload-tracking.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/shared/upload-tracking/upload-tracking.module.ts
  ui/ui-frontend/projects/referential/src/app/app.module.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.module.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-information-tab/securisation-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-information-tab/securisation-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-preview.module.ts
Labels: bug, small, VAS

#1078 [VAS] Bug/vas-10222: Fix computing facets on big results count
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/ArchiveSearchConsts.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  ui/ui-frontend-common/src/app/modules/models/operation/facet-details.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/search.criteria.ts
Labels: bug, small, VAS

#1083 fixe vitamui build issue : fileSize module
  ui/ui-frontend/projects/collect/src/app/collect/collect.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project.module.ts
Labels: small, VAS, Security

#1085 bug/vas-10222: fix referentials build bug
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
Labels: bug, small, VAS

#1084 [VAS] 10651 : correct rules application profiles issue
  ui/ui-frontend-common/src/app/modules/vitamui-roles.enum.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.ts
Labels: bug, small, VAS

#1088 [VAS] correct vitamui build issue
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.spec.ts
Labels: small, VAS

#1086 Bug/vas 10222 computefacets on v6 rc
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
  ui/ui-frontend-common/src/app/modules/models/operation/facet-details.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-dissemination-rules-facets/search-dissemination-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-reuse-rules-facets/search-reuse-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-facets.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/archive-search-consts-enum.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/search.criteria.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/archive-search-rules-facets.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/archive-search-rules-facets.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/search-dissemination-rules-facets/search-dissemination-rules-facets.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/search-reuse-rules-facets/search-reuse-rules-facets.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/archive-search-rules-facets/search-storage-rules-facets/search-storage-rules-facets.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/archive-search-consts-enum.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-facets.service.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-list/logbook-management-operation-list.component.ts
Labels: VAS, Highlight

#1090 bug/vas-10169: handle issue on facets when inheritence not launched
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
Labels: bug, small, VAS

#1089 bug/vas-10552: add forgotten threshold value
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.ts
  ui/ui-identity/src/main/resources/application-dev.yml
Labels: bug, small, VAS

#1094 [VAS] 10655 : add new role to collect profile
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
Labels: bug, small, VAS

#1092 BUG 10656 fix typo
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: small, VAS

#1097 [VAS] : 10663 : collect project creation issue
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
Labels: bug, small, VAS

#1096 BUG 10664 fix project name
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-resolver.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transactions.component.html
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transactions.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transactions.service.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
Labels: bug, small, VAS

#1099 [VAS] Bug #10502: Bug download collect
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectObjectGroupInternalService.java
  api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/ProjectObjectGroupInternalServiceTest.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/FileInfoDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/QualifiersDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ResultsDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/VersionsDto.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectObjectGroupController.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/service/ProjectObjectGroupService.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
Labels: bug, small, VAS

#1100 bug/vas-10545: handle threshold for DIP export, Mgt rules update, elimination, and elimination analysis
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ExportDipCriteriaDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/TransferRequestDto.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchivesSearchExternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/dtos/SearchCriteriaDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, VAS, Highlight

#1105 [VAS] small fix for pastis
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
Labels: bug, javascript, small, VAS

#1106 [VAS] small fix after debug
  api/api-security/security-client/src/main/java/fr/gouv/vitamui/security/client/ContextRestClient.java
Labels: small, VAS, Security

#1111 [VAS] : 10749 : add pastis service with new Id
  deployment/scripts/mongod/1.0.0/220_cas_services_pastis_ref.js.j2
Labels: bug, small, Security

#1118 bugs #10760: add timeout (4h) to vitamui build pipeline
  Jenkinsfile
Labels: OPS REVIEW

#1115 [VAS] Bug #10632: reload leaves count on new search
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
Labels: bug, javascript, small, VAS

#1116 Bug/Vas-10748: fix a bug on customer creation on code validation
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/CustomerDto.java
Labels: bug, small, VAS, Highlight

#1119 [VAS] 10357 : add reclassification step translate
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: bug, small, VAS
