Repository ProgrammeVitam/vitam-ui, pull requests merged in 2022-04, with the labels that each got.

#762 [VAS] ITEM 9787 : correct springshell security issue
  pom.xml
Labels: enhancement, dependencies, small, VAS, Security

#761 [VAS] story #9751 Rework Vitam reverse update task
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/templates/apache/page/index_debug.html.j2
  deployment/roles/reverse/templates/apache/page/index_links.html.j2
Labels: VAS, OPS REVIEW

#742 update sonar url
  Jenkinsfile
Labels: enhancement, small, VAS

#769 [VAS] story #9751 Rework Vitam reverse update task (CP V5) (#761)
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/templates/apache/page/index_debug.html.j2
  deployment/roles/reverse/templates/apache/page/index_links.html.j2
Labels: Cherry-Pick

#778 [Vas] Item 9787 Patch cas to 6.4.6.3 for prevent Spring shell vulnerabilities
  pom.xml
Labels: enhancement, small, VAS, Security

#776 CP 5RC - [VAS] story #9751 Rework Vitam reverse update task (#761)
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/templates/apache/page/index_debug.html.j2
  deployment/roles/reverse/templates/apache/page/index_links.html.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#777 CP R16 - [VAS] story #9751 Rework Vitam reverse update task (#761)
  deployment/roles/reverse/tasks/apache/merge_index_apache.yml
  deployment/roles/reverse/templates/apache/page/index_debug.html.j2
  deployment/roles/reverse/templates/apache/page/index_links.html.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#774 [VAS] Feature 9774 archive search service refactoring
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/SearchCriteriaDto.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ArchiveSearchInternalServerConfig.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ExportDipInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchArchiveSearchUnitExportCsvInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAccessMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search-resolver.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/access-rule-search/access-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/appraisal-rule-search/appraisal-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/reclassification/reclassification.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/search-criteria-list.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-list/search-criteria-list.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/title-and-description-criteria-search/title-and-description-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-search-helper.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-elimination.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-export.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/compute-inherited-rules.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/update-unit-management-rule.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/archive-unit-validator.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/archive-shared-data.service.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/core/archive-shared-data.service.ts
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
Labels: enhancement, VAS

#746 [VAS] US 9778 : Bumps lodash ini logback-core
  cots/vitamui-mongo-express/package-lock.json
  pom.xml
Labels: dependencies, small, VAS

#780 [Vas] Item 9787 : Upgrade spring test to 5.3.18
  cas/cas-server/pom.xml
Labels: small, VAS

#779 [VAS] Feature/vas 9760 manage access facets
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ExportDipInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchArchiveSearchUnitExportCsvInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchEliminationInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalServiceTest.java
  ui/ui-frontend-common/src/app/modules/models/operation/facet-colors.enum.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/archive-search-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-access-rules-facets/search-access-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-rules-facets/search-appraisal-rules-facets/search-appraisal-rules-facets.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-facets.service.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-facets.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/search.criteria.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: enhancement, VAS
