Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-01, with the labels that each got.

#1144 [CINES] fix pour packager l'executable pastis standalone
  api/api-pastis/pastis-commons/src/main/resources/pua_validation/valid_pua.json
  api/api-pastis/pastis-external/src/main/resources/pua_validation/valid_pua.json
  api/api-pastis/pastis-standalone/README.md
  api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
  api/api-pastis/pastis-standalone/src/main/resources/standalone/startup.service.ts
  api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
Labels: bug, small, CINES

#1146 story/vas-10792: handle permission on updating units depending on acc…
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, enhancement, VAS, Cherry-Pick, Highlight

#1156 story/vas-10792: handle permission on updating units depending on acc…
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, VAS, Cherry-Pick, Highlight

#1157 [VAS][10829] update jackson-databind and commons-text version
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchArchiveSearchUnitExportCsvInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalServiceTest.java
  pom.xml
Labels: enhancement, small, VAS, Highlight, Security

#1162 [CP6RCX][CINES] fix pastis standalone packaging (#1144)
  api/api-pastis/pastis-commons/src/main/resources/pua_validation/valid_pua.json
  api/api-pastis/pastis-external/src/main/resources/pua_validation/valid_pua.json
  api/api-pastis/pastis-standalone/README.md
  api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
  api/api-pastis/pastis-standalone/src/main/resources/standalone/startup.service.ts
  api/api-pastis/pastis-standalone/src/main/resources/standalone/theme.service.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
Labels: bug, small, Cherry-Pick, CINES

#1163 story#10869: fix archiveProfile mapping
  api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectTransactionDto.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/TransactionConverter.java
  api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/converters/TransactionConverterTest.java
  ui/ui-frontend-common/src/app/modules/models/collect/transaction.ts
Labels: bug, small, VAS

#1167 Fix unit test error on Vitamui build
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/update-units-metadata/update-units-metadata.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.spec.ts
Labels: bug, small, VAS

#1158 [VAS] Story #10829: clean code
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/model/ObjectQualifierType.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/service/ProjectObjectGroupService.java
  ui/ui-collect/src/test/java/fr/gouv/vitamui/collect/service/ProjectObjectGroupServiceTest.java
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile-options/save-profile-options.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/select-notice/select-notice.component.ts
Labels: small, VAS, clean Code

#1171 [VAS] 10879: add roles for the profile consultation ingest
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/6.rc.0/35_add_consult_ingest_contract_profil.js.j2
Labels: bug, small, VAS

#1172 bug 10887 File Format : missing disabled buttons
  ui/ui-frontend-common/src/app/modules/utils/role.enum.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.ts
Labels: bug, small, VAS

#1166 Bug/vas-10850: handle Cas server templates to prevent XSS injections
  cas/cas-server/src/main/resources/templates/casPwdView.html
  cas/cas-server/src/main/resources/templates/layout.html
  cas/cas-server/src/main/resources/templates/login/casLoginView.html
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/security/SecurityConfig.java
Labels: bug, VAS, Security

#1168 Bug/vas 10850 prevent xss injection on cas server v5 rc
  cas/cas-server/src/main/resources/templates/casLoginView.html
  cas/cas-server/src/main/resources/templates/casPwdView.html
  cas/cas-server/src/main/resources/templates/layout.html
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/security/SecurityConfig.java
Labels: bug, javascript, VAS, Security

#1169 Bug/vas 10850 prevent xss injection on cas server v5 x
  cas/cas-server/src/main/resources/templates/casPwdView.html
  cas/cas-server/src/main/resources/templates/layout.html
  cas/cas-server/src/main/resources/templates/login/casLoginView.html
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/security/SecurityConfig.java
Labels: bug, javascript, VAS, Security

#1170 Bug/vas 10850 prevent xss injection on cas server v6 rc
  cas/cas-server/src/main/resources/templates/casPwdView.html
  cas/cas-server/src/main/resources/templates/layout.html
  cas/cas-server/src/main/resources/templates/login/casLoginView.html
  ui/ui-commons/src/main/java/fr/gouv/vitamui/ui/commons/security/SecurityConfig.java
Labels: bug, javascript, VAS, Security

#1174 [vas] bug 10895 fix bug calcul heritage
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.html
Labels: bug, small, VAS

#1165 story 10791 the profile roles documentation
  docs/DAT/DAT_VITAMUI.pdf
  docs/DAT/docs/dat_vitamui/architecture/profils_roles.md
Labels: documentation, small, VAS, OPS REVIEW

#1178 [VAS] 10891 : download object with extension
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ObjectData.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/VersionsDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/model/ObjectQualifierTypeEnum.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-archive-search/src/test/resources/data/vitam_got_binarymaster_with_uri.json
  ui/ui-archive-search/src/test/resources/data/vitam_got_dissemination.json
  ui/ui-archive-search/src/test/resources/data/vitam_got_full_with_thumbs.json
Labels: bug, small, VAS, Support

#1177 [VAS] 10891 : download object with extension
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ObjectData.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/VersionsDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/model/ObjectQualifierTypeEnum.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-archive-search/src/test/resources/data/vitam_got_binarymaster_with_uri.json
  ui/ui-archive-search/src/test/resources/data/vitam_got_dissemination.json
  ui/ui-archive-search/src/test/resources/data/vitam_got_full_with_thumbs.json
Labels: bug, small, VAS, Support

#1164 Story #10829: Small cleaning for Ansible.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/environments/group_vars/all/consul_vars.yml
  deployment/environments/group_vars/all/elasticsearch_log_vars.yml
  deployment/environments/group_vars/all/jvm_opts.yml
  deployment/environments/group_vars/all/logstash_vars.yml
  deployment/environments/group_vars/all/mongo_express_vars.yml
  deployment/environments/group_vars/all/mongodb_vars.yml
  deployment/environments/group_vars/all/vault-keystores.yml
  deployment/environments/group_vars/all/vault-keystores.yml.example
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/browser/tasks/main.yml
  deployment/roles/checks/tasks/check_java.yml
  deployment/roles/consul/defaults/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/logstash/defaults/main.yml
  deployment/roles/logstash/handlers/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/templates/logstash.yml.j2
  deployment/roles/logstash/templates/service-logstash.json.j2
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo-express/templates/service-componentid.json.j2
  deployment/roles/mongo/defaults/main.yml
  deployment/roles/mongo/handlers/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/service-componentid.json.j2
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/mongodb_migration_v5/tasks/upgrade_pkg.yml
  deployment/roles/reverse/templates/apache/httpd_config
  deployment/roles/rsyslog/tasks/main.yml
  deployment/roles/uninstall/tasks/vitam-service.yml
  deployment/roles/vitamui/handlers/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/vars/main.yml
Labels: OPS REVIEW

#1179 CP 6RC - Story #10829: Small cleaning for Ansible.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/environments/group_vars/all/consul_vars.yml
  deployment/environments/group_vars/all/elasticsearch_log_vars.yml
  deployment/environments/group_vars/all/jvm_opts.yml
  deployment/environments/group_vars/all/logstash_vars.yml
  deployment/environments/group_vars/all/mongo_express_vars.yml
  deployment/environments/group_vars/all/mongodb_vars.yml
  deployment/environments/group_vars/all/vault-keystores.yml
  deployment/environments/group_vars/all/vault-keystores.yml.example
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/browser/tasks/main.yml
  deployment/roles/checks/tasks/check_java.yml
  deployment/roles/consul/defaults/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/logstash/defaults/main.yml
  deployment/roles/logstash/handlers/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/templates/logstash.yml.j2
  deployment/roles/logstash/templates/service-logstash.json.j2
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo-express/templates/service-componentid.json.j2
  deployment/roles/mongo/defaults/main.yml
  deployment/roles/mongo/handlers/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/service-componentid.json.j2
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongo_configure/vars/main.yml
  deployment/roles/mongodb_migration_v5/tasks/upgrade_pkg.yml
  deployment/roles/reverse/templates/apache/httpd_config
  deployment/roles/rsyslog/tasks/main.yml
  deployment/roles/uninstall/tasks/vitam-service.yml
  deployment/roles/vitamui/handlers/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/vars/main.yml
Labels: VAS, Cherry-Pick, OPS REVIEW

#1184 [VAS] 10828 : pastis translate (#1176)
  ui/ui-frontend/angular.json
  ui/ui-frontend/projects/pastis/ngsw-config.json
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
Labels: bug, small, VAS, Cherry-Pick

#1187 [VAS][CP5X] Bug #10167: Bug accession register search
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessRegisterVitamQueryHelper.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessionRegisterSearchDto.java
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/models/accession-register-export-csv.interface.ts
Labels: VAS, Cherry-Pick

#1189 [VAS] Bug #10891: download bloc because of mimetype
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
Labels: bug, small, VAS, Cherry-Pick

#1190 [VAS] 10901 : add more object sanitizing
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/VitamUIUtils.java
  ui/ui-identity/src/main/java/fr/gouv/vitamui/identity/rest/ProviderController.java
Labels: enhancement, small, VAS, Highlight, Security

#1192 [VAS] Bug #10891: download bloc because of mimetype
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.html
Labels: bug, small, VAS, Cherry-Pick
