Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-02, with the labels that each got.

#1182 story 10661 Generalization of blocking / unblocking actions
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.ts
Labels: enhancement, small, VAS, Highlight

#1194 [VAS] Story #10840: tests fix
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/model/ObjectQualifierType.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/service/ProjectObjectGroupService.java
Labels: bug, java, small, VAS

#1196 [VAS] Story #10840: new tests fix
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
Labels: bug, javascript, small, VAS

#1175 Bug/Vas-10899: add more check to secure api cross path traversal vuln…
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
Labels: bug, small, VAS, Security

#1195 Feature/vas item 10900 validate vitamui dto
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/LogbookExternalService.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/external/server/rest/IngestExternalController.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalController.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/ProfileDto.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AgencyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ArchivalProfileUnitExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/FileFormatExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/RuleExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/SecurityProfileExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/AgencyInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/OperationInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ProfileInternalController.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SanityCheckerTest.java
  commons/commons-security/src/test/resources/ingest_search_complexe_key.json
  ui/ui-ingest/src/main/java/fr/gouv/vitamui/ingest/rest/IngestController.java
  ui/ui-pastis/src/main/java/fr/gouv/vitamui/pastis/rest/ProfileController.java
  ui/ui-pastis/src/test/java/fr/gouv/vitamui/pastis/rest/ProfileControllerTest.java
  ui/ui-pastis/src/test/java/fr/gouv/vitamui/pastis/service/ProfileServiceTest.java
Labels: enhancement, small, VAS, Security

#1197 [VAS] Story #10898: XXE vulnerability in pastis app
  api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/config/ApiPastisServerConfig.java
  api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
  api/api-pastis/pastis-external/src/test/java/fr/gouv/vitamui/pastis/server/service/PastisServiceTest.java
  api/api-pastis/pastis-external/src/test/resources/profiles/test-xxe.xml
Labels: bug, java, VAS, Security

#1199 [VAS] Bug #10967: use onChange to update ingest details
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
Labels: bug, javascript, small, VAS

#1200 [VAS][CP5] Bug #10967: use onChange to update ingest details
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
Labels: bug, javascript, small, VAS, Cherry-Pick

#1202 fix bug on logstash service name
  deployment/roles/logstash/templates/service-logstash.json.j2
Labels: bug, small, VAS, OPS REVIEW

#1203 fix bug on logstash service name
  deployment/roles/logstash/templates/service-logstash.json.j2
Labels: bug, small, VAS, OPS REVIEW

#1205 [VAS] fix VitamUI build
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
Labels: bug, small, VAS

#1204 [VAS] Bug #10976: object metadata preview correction
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, javascript, small, VAS

#1208 [VAS] Bug #10976: use object group in object
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
Labels: bug, javascript, small, VAS

#1193 [VAS] Story #10829: clean code
  ui/ui-frontend/projects/portal/src/app/components/application-list/application-list.component.html
Labels: small, VAS, clean Code

#1183 story 9854 partitioning access to ingest
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/client/AbstractResourceClientService.java
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dsl/VitamQueryHelper.java
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/AccessContractResponseDto.java
  api/api-ingest/ingest-commons/src/main/java/fr/gouv/vitamui/ingest/common/dto/AccessContractVitamDto.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/config/ApiIngestInternalServerConfig.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/AccessContractConverter.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/AccessContractInternalService.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestExternalParametersService.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestInternalService.java
Labels: enhancement, VAS, Highlight

#1185 Feature/vas-10993 migrate spring
  pom.xml
Labels: small, VAS, Security, clean Code

#1212 [VAS] BUG:10888 - fix: internal server error in file formats viewer
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-preview.component.html
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
  ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/rest/FileFormatControllerTest.java
Labels: bug, javascript, java, small, VAS

#1214 Story #10922 : check schema of object group"
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: enhancement, small, VAS, Highlight

#1209 [VAS] Bug 10699: update on any modification
  ui/ui-frontend/projects/pastis/src/app/models/archival-profile-unit.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-common-models.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-description.model.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
Labels: bug, javascript, small, VAS

#1216 [VAS] 11009 : add vitamui as master on tenant 1
  deployment/environments/group_vars/all/vitam_vars.yml
Labels: bug, small, VAS, OPS REVIEW

#1218 story #11012 updated and adapt technical documentation structure
  docs/fr/README.md
  docs/fr/architecture/_static/css/theme.css
  docs/fr/installation/index.rst
  docs/fr/migration/_static/css/theme.css
  docs/fr/migration/images/Vitam_Logo-CMJN.png
  docs/fr/migration/index.md
  docs/fr/migration/index.rst
  docs/fr/migration/upgrade_v5rc.md
Labels: documentation, small, VAS, OPS REVIEW

#1221 [CP5RCX][VAS] 11009 : add vitamui as master on tenant 1
  deployment/environments/group_vars/all/vitam_vars.yml
Labels: bug, small, VAS, Cherry-Pick

#1219 [CP6RCX][VAS] 11009 : add vitamui as master on tenant 1
  deployment/environments/group_vars/all/vitam_vars.yml
Labels: bug, small, VAS, Cherry-Pick

#1220 [CP5X][VAS] 11009 : add vitamui as master on tenant 1
  deployment/environments/group_vars/all/vitam_vars.yml
Labels: bug, small, VAS, Cherry-Pick

#1213 [VAS][BUG_10364] title troncation archive search
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
Labels: bug, small, VAS

#1227 update library version
  cots/vitamui-mongo-express/Makefile
  cots/vitamui-mongo-express/package-lock.json
  cots/vitamui-mongo-express/package.json
  cots/vitamui-mongod/Makefile
Labels: javascript, small, VAS

#1210 [VAS] clean code : use same unit between angular apps
  ui/ui-frontend-common/src/app/modules/models/units/index.ts
  ui/ui-frontend-common/src/app/modules/models/units/unit-api.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.handler.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/search-response.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/unit.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/archive-shared-data.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.handler.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/models/search-response.interface.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-shared-data.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/models/index.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/models/unitDescriptiveMetadata.interface.ts
Labels: javascript, small, VAS, clean Code

#1230 [VAS] 11024 : change collect log level [dev]
  api/api-collect/collect-internal/src/main/resources/application-dev.yml
Labels: small, VAS, clean Code

#1222 [CP5X][VAS] Bug 10888 - fix: internal server error in file formats viewer (…
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-preview.component.html
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
  ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/rest/FileFormatControllerTest.java
Labels: bug, small, VAS, Cherry-Pick

#1223 [CP5RCX] [VAS] Bug 10888 - fix: internal server error in file formats viewer (…
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-preview.component.html
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
  ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/rest/FileFormatControllerTest.java
Labels: bug, small, VAS, Cherry-Pick

#1224 [CP6RCX][VAS] Bug 10888 - fix: internal server error in file formats viewer (…
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/CommonConstants.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-preview.component.html
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
  ui/ui-referential/src/test/java/fr/gouv/vitamui/referential/rest/FileFormatControllerTest.java
Labels: bug, small, VAS, Cherry-Pick

#1232 [VAS] fix vitamUI build
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
Labels: small, VAS

#1217 Feature/10995 set additionnal properties true in management section
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
Labels: bug, javascript, small, VAS

#1233 [VAS] bug 10995: node management without additionnal properties set i…
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
Labels: bug, javascript, VAS, Cherry-Pick

#1228 update library version mongo-express to fix build
  cots/vitamui-mongo-express/package-lock.json
  cots/vitamui-mongo-express/package.json
Labels: small, VAS, Cherry-Pick

#1225 [VAS] 10984 create ingest contract issue
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/ManagementContractController.java
Labels: bug, small, VAS
