Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-07, with the labels that each got.

#1403 Bug 11596: Revert modifications on mongo script from Bug/Vas-11487.
  deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1400 CP V6 - Bug 11537: fix access to collect and management contract
  deployment/scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2
  deployment/scripts/mongod/6.rc.0/24_update_hasTenantList_application_COLLECT_APP.js.j2
  deployment/scripts/mongod/v6.0/22_create_application_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1399 Bug 11537: fix access to collect and management contract
  deployment/scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2
  deployment/scripts/mongod/6.rc.0/24_update_hasTenantList_application_COLLECT_APP.js.j2
  deployment/scripts/mongod/v6.0/22_create_application_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1402 CP 6RC - Bug 11537: fix access to collect
  deployment/scripts/mongod/6.rc.0/02_add_collect_module_application.js.j2
  deployment/scripts/mongod/6.rc.0/24_update_hasTenantList_application_COLLECT_APP.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1335 Story #11293 pastis standalone
  api/api-pastis/pastis-standalone/build.sh
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis-standalone/run.sh
  api/api-pastis/pastis-standalone/src/main/assembly/packaging-zip.xml
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/config/PastisConfiguration.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
  api/api-pastis/pastis-standalone/src/main/resources/application.yml
  api/api-pastis/pastis-standalone/src/main/resources/standalone/angular.json
  api/api-pastis/pastis-standalone/src/main/resources/standalone/app.configuration.interface.ts
  api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
  pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/angular.json
  ui/ui-frontend/package.json
  ui/ui-frontend/pom.xml
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
  ui/ui-frontend/projects/pastis/src/app/core/classes/pastis-configuration.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/standalone-startup.service.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/standalone-theme.service.ts
  ui/ui-frontend/projects/pastis/src/assets/config/config-standalone.json
  ui/ui-frontend/projects/pastis/src/assets/config/config-vitam-ui.json
  ui/ui-frontend/projects/pastis/src/environments/environment.dev.ts
  ui/ui-frontend/projects/pastis/src/environments/environment.interface.ts
  ui/ui-frontend/projects/pastis/src/environments/environment.prod.ts
  ui/ui-frontend/projects/pastis/src/environments/environment.rec.ts
  ui/ui-frontend/projects/pastis/src/environments/environment.standalone.ts
  ui/ui-frontend/projects/pastis/src/environments/environment.ts
Labels: enhancement, javascript, java, VAS

#1365 Story 10410: update labels, css and layouts for external params app
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/service/ExternalParametersService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/ExternalParametersServiceTest.java
  ui/ui-frontend-common/src/app/modules/components/common-progress-bar/common-progress-bar.component.html
  ui/ui-frontend-common/src/app/modules/components/common-progress-bar/common-progress-bar.component.scss
  ui/ui-frontend-common/src/sass/_button.scss
  ui/ui-frontend-common/src/sass/material/_modal.scss
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.css
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.css
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: enhancement, small, VAS

#1353 Story 11422: Pastis - update CodeListVersionss tag for rng profil generation
  api/api-pastis/pastis-commons/generated_test.xml
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/jaxb/BaliseXML.java
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/RNGConstants.java
  api/api-pastis/pastis-commons/src/main/resources/profiles_new/Profil_seda_pastis_mvp.rng
  api/api-pastis/pastis-commons/src/test/resources/manifests/jsonProfile.json
  api/api-pastis/pastis-commons/src/test/resources/manifests/rngProfile.rng
  api/api-pastis/pastis-commons/src/test/resources/profiles/profile_ok.rng
  api/api-pastis/pastis-commons/src/test/resources/rng/Profil_seda_pastis_mvp.rng
Labels: bug, VAS

#1410 Align vitam.version to proper release on 5RC.
  pom.xml
Labels: small, VAS, OPS REVIEW

#1413 [VAS]: Bug-11356: fix build on V5-RC
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
Labels: bug, small, VAS, Cherry-Pick

#1407 [VAS] Story 11591: name harmonization
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.component.html
  ui/ui-frontend/projects/identity/src/app/group/group.component.html
  ui/ui-frontend/projects/identity/src/app/hierarchy/hierarchy.component.html
  ui/ui-frontend/projects/identity/src/app/profile/profile.component.html
  ui/ui-frontend/projects/identity/src/app/user/user.component.html
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-breadcrumb-components/pastis-title-breadcrumb/pastis-title-breadcrumb.component.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.html
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit.component.html
  ui/ui-frontend/projects/referential/src/app/context/context.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.html
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile.component.html
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: javascript, VAS

#1378 CP 6RC - bug/vas-11487: fix download bug
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-collect/collect-internal-client/src/test/java/fr/gouv/vitamui/collect/internal/client/CollectInternalRestClientTest.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectObjectGroupInternalController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectObjectGroupController.java
Labels: bug, small, VAS, Cherry-Pick

#1422 CP V6 [VAS] Story 11637: deployment - make errors readable
  deployment/filter_plugins/cert_to_str_filter.py
Labels: small, VAS, Cherry-Pick, clean Code

#1420 CP V5 [VAS] Story 11637: deployment - make errors readable
  .gitignore
  deployment/filter_plugins/cert_to_str_filter.py
Labels: small, VAS, Cherry-Pick, OPS REVIEW, clean Code

#1421 CP V6RC [VAS] Story 11637: deployment - make errors readable
  .gitignore
  deployment/filter_plugins/cert_to_str_filter.py
Labels: small, VAS, Cherry-Pick, clean Code

#1431 [VAS] Bug 11541: filing holding tree not retrieved
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, VAS

#1429 V6 [VAS] Bug 11541: filing holding tree not retrieved
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, VAS

#1430 V6RC [VAS] Bug 11541: filing holding tree not retrieved
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, VAS

#1428 V5 [VAS] Bug 11541: filing holding tree not retrieved
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, VAS
