Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-04, with the labels that each got.

#1297 [VAS] Story 10917: Update nginx configuration.
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/reverse/files/nginx/proxy_params
  deployment/roles/reverse/handlers/main.yml
  deployment/roles/reverse/tasks/nginx/configure_nginx.yml
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/reverse/templates/nginx/nginx.conf.j2
  deployment/roles/reverse/templates/nginx/ssl/ssl.conf.j2
Labels: VAS, OPS REVIEW

#1300 [VAS]: Bug-11356: fix puppeteer version issue
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
Labels: bug, dependencies, javascript, small, VAS

#1302 [VAS] add new VitamUI contributors
  CONTRIBUTORS.md
Labels: small, VAS, clean Code

#1295 [VAS] 10829: Disable prometheus dependencies in vitamui to fix hard disk full issue
  pom.xml
Labels: enhancement, dependencies, small, VAS, clean Code

#1305 Story 11359: Update default portal title and message.
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: small, VAS, OPS REVIEW

#1303 [VAS] Story 11313: Add DMV V6.
  docs/fr/migration/upgrade_v6.md
Labels: documentation, small, VAS

#1310 [VAS] Story 11378: Add new parameter force_vitamui_version
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo-express/vars/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/vitamui/tasks/main.yml
  docs/fr/migration/upgrade_v5.md
  docs/fr/migration/upgrade_v6.md
Labels: documentation, small, VAS, OPS REVIEW

#1312 CP 6RC - [VAS] Story 11378: Add param force_vitamui_version during vitamui package installation.
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/vars/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo-express/vars/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/vars/main.yml
  deployment/roles/vitamui/tasks/main.yml
  docs/fr/migration/upgrade_v5.md
Labels: bug, documentation, small, VAS, Cherry-Pick

#1314 Bug/vas 11356 fix vitamui build
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
Labels: dependencies, small, VAS

#1299 [VAS] 11330 : add sanity on html injection
  api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
  api/api-collect/collect-external/src/test/java/fr/gouv/vitamui/collect/external/server/rest/ProjectArchiveUnitExternalControllerTest.java
  api/api-iam/iam-external/src/test/java/fr/gouv/vitamui/iam/external/server/rest/TenantExternalControllerTest.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SafeFileChecker.java
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SafeFileCheckerTest.java
  commons/commons-security/src/test/java/fr/gouv/vitamui/commons/security/SanityCheckerTest.java
  commons/commons-security/src/test/resources/bad_json.json
  commons/commons-security/src/test/resources/good_json_sanity.json
  commons/commons-security/src/test/resources/object_with_correct_values.json
  commons/commons-security/src/test/resources/object_with_html_tag.json
  commons/commons-security/src/test/resources/object_with_xml_tag.json
  ui/ui-frontend/projects/identity/src/app/user/user.service.ts
  ui/ui-identity/src/test/java/fr/gouv/vitamui/identity/rest/UserControllerTest.java
Labels: bug, small, VAS, Security

#1311 [VAS] 11340 : clean audit collect toggle
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
  ui/ui-frontend/projects/identity/src/app/user/user-create/user-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.scss
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio/vitamui-radio.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio/vitamui-radio.component.scss
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio/vitamui-radio.component.ts
Labels: bug, javascript, VAS, clean Code

#1298 [VAS] Bug 11305 10529 9960: accession register fixes
  ui/ui-frontend-common/src/app/modules/models/access-register/accession-register-status.ts
  ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
  ui/ui-frontend/projects/referential/src/app/models/accession-register-export-csv.interface.ts
Labels: bug, VAS

#1294 Story 10885: Fix search criteria label after rule management update
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-search-helper.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/search.criteria.ts
Labels: bug, small, VAS

#1321 CP 6RC - [VAS] Bug 10529: accession register transfer_reply fix
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-advanced-search/accession-register-advanced-search.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-list/accession-register-list.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.html
  ui/ui-frontend/projects/referential/src/app/models/accession-register-export-csv.interface.ts
Labels: bug, small, Cherry-Pick

#1319 [VAS] 11330: change error message
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/identity/src/app/user/user-create/user-create.component.ts
  ui/ui-frontend/projects/identity/src/app/user/user-preview/user-information-tab/user-information-tab.component.ts
  ui/ui-frontend/projects/identity/src/app/user/user.service.ts
Labels: bug, small, VAS

#1307 BUG 11323 FIX BUG update project
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-list/project-list.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.service.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
Labels: bug, small, VAS
