Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-06, with the labels that each got.

#1351 [VAS]Bug/11461: update access contract usage on collect
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/classification-tree/classification-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/classification-tree/classification-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
Labels: bug, small, VAS

#1360 [Fixes] Story #10858 display physical objects
  api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
Labels: bug, small, VAS

#1364 story 11507: fix bug track total hits
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
Labels: bug, java, small, VAS

#1363 CP V6 [VAS] Bug 11519: collect problems after access contract fixes
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/config/ApiReferentialServerConfig.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/service/ExternalParametersService.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small, VAS, Cherry-Pick

#1368 Remove CheckMarx step.
  Jenkinsfile
Labels: small, VAS, OPS REVIEW

#1369 CP V6 - Remove CheckMarx step.
  Jenkinsfile
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1370 CP 6RC - Remove CheckMarx step.
  Jenkinsfile
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1371 CP V5 - Remove CheckMarx step.
  Jenkinsfile
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1366 [VAS] Bug 11519: collect filing plan not loading because of access contract fixes
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: bug, javascript, small, VAS

#1367 [VAS] Bug 11519: collect filing plan not loading because of access contract fixes
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: bug, javascript, small, VAS

#1361 story #11488: Fix message when creating a profile with a description…
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ExternalParamProfileDto.java
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.service.ts
Labels: bug, small, VAS

#1379 bug/vas-11487: fix download bug
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectObjectGroupController.java
Labels: bug, small, VAS

#1377 bug/vas-11487: fix download bug
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectObjectGroupController.java
Labels: bug, small, VAS, Cherry-Pick

#1381 Story #11444 : migration scaleway - build & deploy vitam-ui
  Jenkinsfile
  Jenkinsfile.origin
  deployment/ansible.cfg
  deployment/environments/group_vars/all/ansible_options.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
  pom.xml
Labels: VAS, OPS REVIEW

#1336 Story 11472: Fix profile creation for management contract app.
  deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1382 CP V6 - Story 11472: Fix profile creation for management contract app.
  deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#1385 Fix Certificate deployment for ansible > 2.10
  deployment/roles/vitamui/tasks/main.yml
Labels: small, VAS, OPS REVIEW

#1386 CP V6 - Fix Certificate deployment for ansible > 2.10
  deployment/roles/vitamui/tasks/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1388 CP V5 - Fix Certificate deployment for ansible > 2.10
  deployment/roles/vitamui/tasks/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1389 Fix Certificate deployment for ansible > 2.10
  deployment/roles/vitamui/tasks/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1390 CP V6 - Story 11444: migration scaleway - build & deploy vitam-ui
  Jenkinsfile
  Jenkinsfile.origin
  deployment/ansible.cfg
  deployment/environments/group_vars/all/ansible_options.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
  pom.xml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1392 CP V5 - Story 11444: migration scaleway - build & deploy vitam-ui
  Jenkinsfile
  Jenkinsfile.origin
  deployment/ansible.cfg
  deployment/environments/group_vars/all/ansible_options.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1391 CP 6RC - Story 11444: migration scaleway - build & deploy vitam-ui
  Jenkinsfile
  Jenkinsfile.origin
  deployment/ansible.cfg
  deployment/environments/group_vars/all/ansible_options.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
  pom.xml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1393 CP 5RC - Story 11444: migration scaleway - build & deploy vitam-ui
  Jenkinsfile
  Jenkinsfile.origin
  deployment/ansible.cfg
  deployment/environments/group_vars/all/ansible_options.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1394 Bug/Vas-11472: fix mgt contract creation script
  deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS

#1395 CP V6: Bug/Vas-11472: fix mgt contract creation script
  deployment/scripts/mongod/v6.0/21_create_profile_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS

#1383 Bug/Vas-11487: fix downloading objects bug
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/ProjectObjectGroupInternalController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/ProjectObjectGroupController.java
Labels: bug, small, VAS

#1396 Bug/Vas-11472: fix mgt contract creation script
  deployment/scripts/mongod/v6.0/24_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS

#1397 CP-V6: Bug/Vas-11472: fix mgt contract creation script
  deployment/scripts/mongod/v6.0/24_add_profile_id_for_MANAGEMENT_CONTRACT_APP.js.j2
Labels: bug, small, VAS

#1398 Bug 11537: avoid reset tenant in startup service CP v6
  ui/ui-frontend-common/src/app/modules/components/navbar/tenant-menu/tenant-menu.service.ts
  ui/ui-frontend-common/src/app/modules/startup.service.ts
  ui/ui-frontend-common/src/app/modules/vitamui-http-interceptor.ts
Labels: bug, small, VAS, Cherry-Pick
