Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-12, with the labels that each got.

#1559 CP V6 - Story 11979: Fix for cluster replicaset deployement & add is_small parameter.
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/mongo/tasks/check_auth.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/init-replica.js.j2
  deployment/roles/mongo_init/tasks/main.yml
Labels: VAS, Cherry-Pick, OPS REVIEW

#1560 CP 6RC - Story 11979: Fix for cluster replicaset deployement & add is_small parameter.
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/mongo/tasks/check_auth.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/init-replica.js.j2
  deployment/roles/mongo_init/tasks/main.yml
Labels: VAS, Cherry-Pick, OPS REVIEW

#1554 [VAS] Story #11870: add signing policy form in ingest contract preview
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend-common/src/app/modules/components/application/application-card/application-card.component.html
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend-common/src/sass/material/_extended-preview-tab.scss
  ui/ui-frontend-common/src/sass/material/_preview-tab.scss
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.scss
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.module.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.scss
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.ts
Labels: enhancement, javascript, small, VAS

#1567 Bug #12071: Fix mongo arbiter check in replicaset members.
  deployment/roles/mongo/templates/init-replica.js.j2
Labels: bug, VAS, OPS REVIEW

#1570 [VAS] remove portal underline
  ui/ui-frontend-common/src/app/modules/components/application/application-card/application-card.component.scss
Labels: bug, javascript, small, VAS

#1574 CP 6RC - Bug #12074: Fix mongo isWritablePrimary check.
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/mongo/tasks/check_auth.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/init-replica.js.j2
  deployment/roles/mongo/templates/local-user.js.j2
  deployment/roles/mongo_init/tasks/check_auth.yml
  deployment/roles/mongo_init/tasks/main.yml
Labels: VAS, Cherry-Pick, OPS REVIEW

#1562 Story #11742: Remove useless vitam-consul package.
  deployment/roles/consul/handlers/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/templates/vitam-consul.service.j2
  deployment/roles/consul/vars/main.yml
Labels: VAS, OPS REVIEW

#1572 Story #11852 fix: add no_log flag to local dev extra vars
  tools/docker/mongo/mongo_vars_dev.yml
Labels: small, VAS, clean Code

#1579 CP v7.0.x - story #11852 fix(dev-tools): add no_log flag to local dev extra vars …
  tools/docker/mongo/mongo_vars_dev.yml
Labels: Cherry-Pick

#1580 CP v6.x - story #11852 fix(dev-tools): add no_log flag to local dev extra vars …
  tools/docker/mongo/mongo_vars_dev.yml
Labels: Cherry-Pick

#1581 CP v6.rc.x - story #11852 fix(dev-tools): add no_log flag to local dev extra vars …
  tools/docker/mongo/mongo_vars_dev.yml
Labels: Cherry-Pick

#1547 CP v7.1 - story #11558 fix(ci): pastis standalone build step
  Jenkinsfile
  api/api-pastis/pastis-standalone/pom.xml
Labels: small, VAS, Cherry-Pick, OPS REVIEW

#1578 Story #11929: Signing DEB & RPM packages & Reorganize package delivery
  packaging/GPG-KEY-vitam
  packaging/assembly-deb.xml
  packaging/assembly-deployment.xml
  packaging/assembly-full.xml
  packaging/assembly-rpm.xml
  packaging/assembly.xml
  packaging/pom.xml
Labels: OPS REVIEW

#1582 Story #12096: Fix service registration when colocalisation with consul server.
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: bug, small, VAS, OPS REVIEW

#1584 CP 7.0 - Story #12096: Fix service registration when colocalisation with consul server.
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1583 CP V6 - Story #12096: Fix service registration when colocalisation with consul server.
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1585 CP 6RC - Story #12096: Fix service registration when colocalisation with consul server.
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1586 CP V5 - Story #12096: Fix service registration when colocalisation with consul server.
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1587 CP 7.0 - Story #11929: Signing DEB & RPM packages & Reorganise package delivery
  packaging/GPG-KEY-vitam
  packaging/assembly-deb.xml
  packaging/assembly-deployment.xml
  packaging/assembly-full.xml
  packaging/assembly-rpm.xml
  packaging/assembly.xml
  packaging/pom.xml
Labels: Cherry-Pick, OPS REVIEW

#1589 CP6RC - Story #11929: Signing DEB & RPM packages & Reorganize package delivery
  packaging/GPG-KEY-vitam
  packaging/assembly-deb.xml
  packaging/assembly-deployment.xml
  packaging/assembly-full.xml
  packaging/assembly-rpm.xml
  packaging/assembly.xml
  packaging/pom.xml
Labels: Cherry-Pick, OPS REVIEW

#1590 CPV5 - Story #11929: Signing DEB & RPM packages & Reorganize package delivery
  packaging/GPG-KEY-vitam
  packaging/assembly-deb.xml
  packaging/assembly-deployment.xml
  packaging/assembly-full.xml
  packaging/assembly-rpm.xml
  packaging/assembly.xml
  packaging/pom.xml
Labels: Cherry-Pick, OPS REVIEW

#1576 Bugs #12085 style(metadata): multiple quick fixes
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-viewer/archive-unit-viewer.component.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.scss
  ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/components/list/list.component.html
  ui/ui-frontend-common/src/app/modules/object-viewer/components/list/list.component.scss
  ui/ui-frontend-common/src/app/modules/object-viewer/components/list/list.component.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/components/primitive/primitive.component.html
  ui/ui-frontend-common/src/app/modules/object-viewer/services/date-display.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/mock-schema.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-strategy-display-object.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-strategy-display-object.service.ts
Labels: javascript, VAS, clean Code

#1577 bugs #12086 feat(collect): add archive unit descriptions to lateral panel
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/v7.1/03_update_collect_profiles_with_schema_roles.js.j2
  deployment/scripts/mongod/v7.1/04_add_roles_for_collect_app.js.j2
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
Labels: bug, enhancement, javascript, java, small, VAS, OPS REVIEW
