Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-09, with the labels that each got.

#1456 bugs #11641 fix: permanent loading at exact count load
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug, javascript, small, VAS

#1436 CP-V6: Story-11459: Add java options for stopping services on OutOfMemoryError
  deployment/roles/vitamui/templates/java_opts.j2
Labels: enhancement, small, VAS, Cherry-Pick, OPS REVIEW

#1435 CP-V5: Story-11459: Add java options for stopping services on OutOfMemoryError
  deployment/roles/vitamui/templates/java_opts.j2
Labels: enhancement, small, VAS, Cherry-Pick, OPS REVIEW

#1434 CP-V5-RC:Story-11459: Add java options for stopping services on OutOfMemoryError
  deployment/roles/vitamui/templates/java_opts.j2
Labels: enhancement, small, VAS, Cherry-Pick, OPS REVIEW

#1433 Story-11459: Add java options for stopping services on OutOfMemoryError
  deployment/roles/vitamui/templates/java_opts.j2
Labels: enhancement, small, VAS, OPS REVIEW

#1447 [VAS] Story 11586: add signed document policy in ingest contract creation
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/IngestContractDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
  ui/ui-frontend-common/src/app/modules/models/ingest-contract/ingest-contract.ts
  ui/ui-frontend-common/src/app/modules/models/nodes/node.utils.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend-common/src/sass/material/_button-toggle-group.scss
  ui/ui-frontend-common/src/sass/material/_modal.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-by-mgt-rules/storage-rule-search/storage-rule-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/storage-rule-search/storage-rule-search.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.scss
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-list/ingest-contract-list.component.ts
  ui/ui-frontend/projects/referential/src/sass/styles.scss
Labels: enhancement, javascript, VAS

#1458 [VAS] fix frontend common build
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.spec.ts
Labels: small, VAS

#1415 [VAS]:bug-11607: remove sanitize check on provider dtos
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/IdentityProviderInternalController.java
Labels: VAS

#1462 Story 10070: Deliver Consul systemd script with ansible.
  deployment/roles/consul/handlers/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/templates/sysconfig.j2
  deployment/roles/consul/templates/vitam-consul.service.j2
Labels: small, VAS, OPS REVIEW

#1463 Story 10070: Fix sysconfig for consul service.
  deployment/roles/consul/tasks/main.yml
  deployment/roles/consul/templates/sysconfig.conf.j2
  deployment/roles/consul/templates/vitam-consul.service.j2
Labels: small, VAS, OPS REVIEW

#1464 Story 11676: Fix ansible.cfg configuration since removing mitogen.
  deployment/ansible.cfg
  tools/docker/mongo/ansible.cfg
Labels: small, VAS, OPS REVIEW

#1467 BUG #11777 fix download boredereau
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS

#1470 [VAS] Bug 11792: change forbidden behavior
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/SignaturePolicyDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.scss
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
Labels: bug, small, VAS

#1469 story #11485 fix(pastis-standalone): fix profile uploading
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
Labels: bug, java, small, VAS

#1472 [VAS] Bug 11792: fix for build
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
Labels: bug, javascript, small

#1471 BUG #11527: add disabled mode to action buttons
  ui/ui-frontend/projects/pastis/src/app/models/profile-description.model.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
Labels: bug, small, VAS

#1474 bugs #11641 fix(archive-unit-count): reset properly trackTotalHits lo…
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.spec.ts
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.ts
Labels: bug, javascript, small, VAS

#1468 Story 11791: Fix mongo scripts for multi-instance of components ui-collect & ui-pastis.
  deployment/scripts/mongod/1.0.0/211_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/215_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/219_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/224_security.populate_certificates_pastis.js.j2
  deployment/scripts/mongod/6.rc.0/04_update_certificates_collection_with_collect_certificate.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1475 CP V6 bug 11777 fix download bordereau
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#1476 CP 6RC BUG #11777 fix download boredereau
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/service/IngestGeneratorODTFile.java
Labels: bug, small, VAS, Cherry-Pick

#1473 [VAS] Bug 10410: update view on external param
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.scss
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.css
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/thresholds-tab/thresholds-tab.component.html
Labels: VAS

#1465 [VAS] Story 8084: remove tree nodes from orphans node
  ui/ui-frontend-common/src/app/modules/models/nodes/filing-holding-scheme.handler.spec.ts
  ui/ui-frontend-common/src/app/modules/services/index.ts
  ui/ui-frontend-common/src/app/modules/services/leaves-tree.service.spec.ts
  ui/ui-frontend-common/src/app/modules/services/leaves-tree.service.ts
  ui/ui-frontend-common/src/app/modules/services/search-archive-units.interface.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
Labels: bug, small

#1479 BUG #11527: add disabled mode to action buttons (#1471)
  ui/ui-frontend/projects/pastis/src/app/models/profile-description.model.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
Labels: bug, small, VAS, Cherry-Pick

#1477 CP V6 - Story 11791: Fix mongo scripts for multi-instance of components ui-collect & ui-pastis.
  deployment/scripts/mongod/1.0.0/211_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/215_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/219_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/224_security.populate_certificates_pastis.js.j2
  deployment/scripts/mongod/6.rc.0/04_update_certificates_collection_with_collect_certificate.js.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1478 CP 6RC - Story 11791: Fix mongo scripts for multi-instance of components ui-collect & ui-pastis.
  deployment/scripts/mongod/1.0.0/211_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/215_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/219_security.populate_certificates_ref.js.j2
  deployment/scripts/mongod/1.0.0/224_security.populate_certificates_pastis.js.j2
  deployment/scripts/mongod/6.rc.0/04_update_certificates_collection_with_collect_certificate.js.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1483 Bugs #11802 fix(archive-search): error workflow on only default thresholds
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
Labels: bug, java, VAS

#1487 CP 5RC - VAS/Bug-11469: fix wrong messages for elimination analysis
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#1485 [CP-V6-RC]- VAS/Bug-11469: fix wrong messages for elimination analysis
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-elimination.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#1484 [CP-V6]- VAS/Bug-11469: fix wrong messages for elimination analysis
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-elimination.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#1482 VAS/Bug-11469: fix wrong messages for elimination analysis
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-elimination.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS

#1486 CP V5 - VAS/Bug-11469: fix wrong messages for elimination analysis
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#1489 Bug/Vas-11802: fix unit test failed on previous PR
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalServiceTest.java
Labels: bug, small, VAS

#1488 [VAS] Bug 11702: pastis enable external identifier for PUA and PA
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  ui/ui-frontend/projects/pastis/src/app/core/services/popup.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-response.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-type.enum.ts
  ui/ui-frontend/projects/pastis/src/app/profile/create-notice-choice/create-notice-choice.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/create-profile/create-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/select-notice/select-notice.component.ts
  ui/ui-pastis/src/main/resources/application-dev.yml
Labels: bug, enhancement, VAS

#1460 [CP-V6]- Bug/vas 11649 handle wrong stats on accession register v6
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
Labels: bug, small, VAS, Cherry-Pick

#1490 [VAS] build fix
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation.component.spec.ts
Labels: small, VAS

#1461 Bug/Vas-11649: handle wrong stats on accession register
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
Labels: bug, small, VAS

#1493 BUG #11623 export csv ko
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, VAS

#1496 [VAS] bug 11702: checkfor PA external id to
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, small, VAS

#1452 Story 11567: Make Vitamui deployment compatible with Almalinux 9
  deployment/roles/mongo_common/tasks/main.yml
Labels: VAS, OPS REVIEW

#1499 CPV6 - Story 11567: Make Vitamui deployment compatible with Almalinux 9
  deployment/roles/mongo_common/tasks/main.yml
Labels: VAS, Cherry-Pick, OPS REVIEW

#1495 Story 11789: Fix parameterized audit threshold
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
  api/api-referential/referential-internal/src/test/resources/audit/AUDIT_FILE_CONSISTENCY.json
  api/api-referential/referential-internal/src/test/resources/audit/AUDIT_FILE_EXISTING.json
  api/api-referential/referential-internal/src/test/resources/audit/AUDIT_FILE_INTEGRITY.json
  api/api-referential/referential-internal/src/test/resources/audit/AUDIT_FILE_RECTIFICATION.json
Labels: bug, java, small

#1494 CP V6 - [VAS] Bug 11702: pastis enable external identifier for PUA and PA
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  ui/ui-frontend/projects/pastis/src/app/core/services/popup.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-response.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-type.enum.ts
  ui/ui-frontend/projects/pastis/src/app/profile/create-notice-choice/create-notice-choice.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/create-profile/create-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/select-notice/select-notice.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.spec.ts
  ui/ui-pastis/src/main/resources/application-dev.yml
Labels: bug, small, VAS, Cherry-Pick

#1497 CP 6RC - [VAS] Bug 11702: pastis enable external identifier for PUA and PA
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  ui/ui-frontend/projects/pastis/src/app/core/services/popup.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-response.ts
  ui/ui-frontend/projects/pastis/src/app/models/profile-type.enum.ts
  ui/ui-frontend/projects/pastis/src/app/profile/create-notice-choice/create-notice-choice.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/create-profile/create-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/select-notice/select-notice.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.spec.ts
  ui/ui-pastis/src/main/resources/application-dev.yml
Labels: bug, small, VAS, Cherry-Pick
