Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-10, with the labels that each got.

#1504 Feature/vas-11788: rename signature policy fields
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/SignaturePolicyDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractConverter.java
  ui/ui-frontend-common/src/app/modules/models/ingest-contract/ingest-contract.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
Labels: enhancement, VAS

#1500 bugs #11641 fix(archive-unit-count): bad counter feedback on exclusio…
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.html
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, javascript, VAS

#1505 [VAS] bug 11726: add role ROLE_GET_AUDITS
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/7.0/01_add_GET_OPERATION_ROLE_to_AUDIT_APP.js.j2
  docs/fr/architecture/sections/architecture.md
Labels: bug, small

#1503 [VAS] Bug 11535: rename access contract error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessContractExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
Labels: bug, small

#1509 CP V6 - [VAS] Bug 11535: rename access contract error (#1503)
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AccessContractExternalController.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
Labels: bug, Cherry-Pick

#1508 CP V6RC - [VAS] Bug 11535: rename access contract error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
Labels: bug, Cherry-Pick

#1506 CP V5 - [VAS] Bug 11535: rename access contract error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
Labels: bug, Cherry-Pick

#1507 Story #11821: Fix audit multiquery and angular audit-create component
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
Labels: bug

#1510 [VAS] Bug 11726: fix operations role update in script
  deployment/scripts/mongod/7.0/01_add_GET_OPERATION_ROLE_to_AUDIT_APP.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1498 bugs #11817 fix(pastis): refactor notice class to avoid security issues
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
Labels: bug, java, VAS

#1513 Story 11821 fix dslquery with JsonNode
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/operation/OperationInternalServiceTest.java
Labels: bug, java, small, VAS

#1520 Story #11567: Fix mongo-tools for AlmaLinux.
  deployment/roles/mongo_common/tasks/main.yml
  deployment/roles/mongodb_upgrade_package/tasks/main.yml
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
Labels: OPS REVIEW

#1524 story_11633 fix build
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-list/management-contract-list.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: small, VAS
