Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-03, with the labels that each got.

#1239 story 11010 Unable to change the status of an entry contract
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
Labels: bug, small, VAS

#1240 vas-10842 fix update project
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, VAS

#1238 Story 10660 Generalization of blocking / unblocking rules inheritance
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.ts
Labels: enhancement, VAS, Highlight

#1243 VAS 11202 fix bug update project
  ui/ui-frontend-common/src/app/modules/models/collect/transaction.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, VAS

#1247 fix collect unit test
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/update-units-metadata/update-units-metadata.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.spec.ts
Labels: bug, small, VAS

#1246 VAS 11064 fix show project
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, VAS

#1252 [VAS][5X] correct buid issue
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
Labels: bug, small, VAS

#1257 [VAS][CP5RCX] correct buid issue
  ui/ui-referential/src/main/java/fr/gouv/vitamui/referential/rest/FileFormatController.java
Labels: bug, small, VAS

#1255 [CP5X][VAS] Story 11206 : Cleanup jenkins workspace
  Jenkinsfile
Labels: small, VAS, Cherry-Pick

#1254 [CP6RCX][VAS] Story 11206 : Cleanup jenkins workspace
  Jenkinsfile
Labels: small, VAS, Cherry-Pick

#1253 [VAS] Upgrade library commons.fileupload.version to 1.5
  pom.xml
Labels: dependencies, small, VAS, Security

#1259 [VAS] Story 10843: back button position
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
Labels: enhancement, javascript, small

#1248 [VAS] Bug 11027: create vitam referential process
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/IngestContractService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamContextService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamSecurityProfileService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/AccessContractService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/ManagementContractService.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/management-contract/validators/management-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS, Security

#1250 [VAS] Story 10965: Allow minor upgrade for MongoDB.
  deployment/ansible-vitamui-migration/migration_mongodb_50.yml
Labels: small, VAS, OPS REVIEW

#1245 CPV5 - Story 10965: fix mongodb migration
  cots/vitamui-mongod/Makefile
  deployment/environments/hosts-ui.example
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/restore-mongod.js.j2
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_common/tasks/main.yml
  deployment/roles/mongo_common/vars/main.yml
  deployment/roles/mongo_init/vars/main.yml
  deployment/scripts/mongod/0.0.0/0_set_feature_compatibility.js.j2
Labels: VAS, Cherry-Pick, OPS REVIEW

#1261 [VAS] 11267 :correct showing object details
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/JsonUtils.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.ts
Labels: bug, small, VAS

#1260 [VAS] Bug 11273: input size missing
  ui/ui-frontend-common/src/sass/material/_select.scss
Labels: bug, javascript, small, VAS

#1268 [CP5X][VAS] Story 11265: search units with ontology fields (#1258)
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/search_query_with_ontology_field_type_date.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/search_query_with_ontology_field_type_text.json
Labels: bug, small, VAS, Cherry-Pick

#1267 [CP5RCX][VAS] Story 11265: search units with ontology fields (#1258)
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
Labels: bug, small, VAS, Cherry-Pick

#1266 [CP6RCX][VAS] Story 11265: search units with ontology fields (#1258)
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchAppraisalMgtRulesQueryBuilderServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/search_query_with_ontology_field_type_date.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/search_query_with_ontology_field_type_text.json
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, small, VAS, Cherry-Pick

#1265 [CP5X][VAS] Bug 11027: create vitam referential process (#1248)
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/IngestContractService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamContextService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamSecurityProfileService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/AccessContractService.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS, Cherry-Pick

#1263 [CP6RCX][VAS] Bug 11027: create vitam referential process (#1248)
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/IngestContractService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamContextService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamSecurityProfileService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/administration/AccessContractService.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.component.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS, Cherry-Pick

#1269 [BUG] story 11256 error when defining filtering by rule in an access
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.ts
Labels: bug, small

#1272 Story 11013: fix scroll bar on profil group creation popin
  ui/ui-frontend/projects/identity/src/app/shared/profiles-form/profiles-form.component.html
  ui/ui-frontend/projects/identity/src/app/shared/profiles-form/profiles-form.component.scss
Labels: bug, small, VAS

#1273 [VAS] 11302 : check vitam referential items
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/validators/management-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS

#1276 [CP5RCX][VAS] 11302: check vitam referential items (#1273)
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS, Cherry-Pick

#1275 [CP5X][VAS] 11302: check vitam referential items (#1273)
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS, Cherry-Pick

#1274 [CP6RCX][VAS] 11302: check vitam referential items (#1273)
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile-create/security-profile-create.validators.ts
Labels: bug, small, VAS, Cherry-Pick

#1270 [BUG] story 11272 Checking the same code in two blocks
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/management-rules-validator.service.ts
Labels: bug, small

#1282 [VAS] 8567 : add new ontology fields
  ui/ui-frontend/projects/archive-search/src/assets/ontologies/ontologies.json
  ui/ui-frontend/projects/collect/src/assets/ontologies/ontologies.json
Labels: bug, small, VAS

#1278 BUG 11290 add unit création
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalService.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, VAS

#1281 [VAS]-11255: retrieve mgt rules for collect unit
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/RulesUpdateCommonService.java
  api/api-archive-search/archive-search-commons/src/test/java/fr/gouv/vitamui/archives/search/common/RulesUpdateCommonServiceTest.java
  api/api-archive-search/archive-search-commons/src/test/resources/data/expected_search_UA_query_without_filter.json
  api/api-archive-search/archive-search-commons/src/test/resources/data/expected_search_UA_query_without_filter_and_projection.json
  api/api-archive-search/archive-search-commons/src/test/resources/data/search_UA_query.json
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ArchiveSearchInternalServerConfig.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/service/RulesUpdateCommonServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchArchiveSearchUnitExportCsvInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalServiceTest.java
  api/api-collect/collect-external-client/src/main/java/fr/gouv/vitamui/collect/external/client/CollectTransactionExternalRestClient.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionArchiveUnitExternalController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/service/TransactionArchiveUnitExternalService.java
  api/api-collect/collect-external/src/test/java/fr/gouv/vitamui/collect/external/server/rest/ProjectArchiveUnitExternalControllerTest.java
  api/api-collect/collect-internal-client/src/main/java/fr/gouv/vitamui/collect/internal/client/CollectTransactionInternalRestClient.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/rest/TransactionArchiveUnitInternalController.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/rest/TransactionController.java
  ui/ui-collect/src/main/java/fr/gouv/vitamui/collect/service/TransactionService.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/api/transaction-api.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: enhancement, javascript, java, VAS

#1280 BUG 11039 fix 404 in referential
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BaseCrudRestClient.java
Labels: bug, small, VAS

#1286 [VAS]:feature/10829: add maven names
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pom.xml
Labels: small, VAS, clean Code

#1289 [VAS] 10828 : add translate key for pastis app
  api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/app/modules/application-id.enum.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
Labels: bug, small, VAS

#1290 [VAS]:feature/10255: fix unit tests
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/common/RulesUpdateCommonService.java
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchArchiveSearchUnitExportCsvInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchMgtRulesInternalServiceTest.java
  api/api-collect/collect-external-client/pom.xml
  api/api-collect/collect-internal-client/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-referential/referential-external/pom.xml
  cas/cas-server/pom.xml
  pom.xml
Labels: small, VAS

#1287 BUG 11317 fix update project
  ui/ui-frontend-common/src/app/modules/models/collect/transaction.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/update-units-metadata/update-units-metadata.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, VAS

#1283 [VAS] Bug 11306: create project modal fixes
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, small, VAS

#1291 [VAS] 10829 delete unused code
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchAgenciesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchFacetsInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchRulesInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchFieldsQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchivesSearchManagementRulesQueryBuilderService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
Labels: small, VAS, clean Code

#1292 [CP6RCX][VAS] 10828 : add translate key for pastis app (#1289)
  api/api-pastis/pastis-standalone/src/main/resources/standalone/package.json
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
Labels: bug, small, VAS, Cherry-Pick

#1296 [CP6RCX][VAS] 11013 : fix scroll bar on profil group creation popin
  ui/ui-frontend/projects/identity/src/app/shared/profiles-form/profiles-form.component.html
  ui/ui-frontend/projects/identity/src/app/shared/profiles-form/profiles-form.component.scss
Labels: bug, small, VAS, Cherry-Pick
