Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-08, with the labels that each got.

#1423 Disable daily trigger for develop.
  Jenkinsfile
Labels: small, VAS, OPS REVIEW

#1427 [CP - 6.x] Story #11542 (style): add all fr translations from Vitam messages
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: VAS, Cherry-Pick

#1426 [CP - 6.rc.x] Story #11542 (style): add all fr translations from Vitam messages
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: VAS, Cherry-Pick

#1425 [CP - 5.x] Story #11542 (style): add all fr translations from Vitam messages
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: VAS, Cherry-Pick

#1437 [VAS] : start translation simplification
  ui/ui-frontend-common/src/assets/shared-i18n/README.md
Labels: javascript, small

#1440 [VAS] Story 10410: update design
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.css
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.scss
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-create/external-param-profile-create.component.ts
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.scss
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile-detail/information-tab/information-tab.component.ts
Labels: javascript, small, VAS

#1438 [VAS] Bug 11702: pastis 500 on check and show id
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ProfileExternalController.java
  ui/ui-frontend/projects/pastis/src/app/core/services/popup.service.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, small, VAS

#1443 [VAS] : fix build
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.spec.ts
Labels: javascript, small, VAS

#1409 story #11496 fix(archive-search): missing search for trackTotalHits + bug #11641 fix(ui-frontend-common): archive-unit-count component state
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.html
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-count/archive-unit-count.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, javascript, small, VAS

#1448 CP V5 - [VAS] Bug 11487: download blocked because context was lost
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
Labels: bug, javascript, small, VAS, Cherry-Pick

#1449 Revert "Fix bump pom from 5.3 snapshot to 5.4 snapshot on master 5.x"
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: OPS REVIEW

#1451 CP V5 - [VAS] Bug 11487: download blocked because context was lost - conflict
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
Labels: bug, javascript, small, VAS, Cherry-Pick

#1453 Revert "Fix bump pom from 5.3 snapshot to 5.4 snapshot on master 5.x"
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: OPS REVIEW

#1454 Fix bump pom from 5.3 snapshot to 5.4 snapshot on master 5.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-logstash/pom.xml
  cots/vitamui-mongo-express/pom.xml
  cots/vitamui-mongod/pom.xml
  cots/vitamui-nginx/pom.xml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
  ui/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-commons/pom.xml
  ui/ui-frontend-common/pom.xml
  ui/ui-frontend/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: OPS REVIEW
