Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-05, with the labels that each got.

#1327 Story #11404 (archive-search|collect): fix search rule position display
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-saver/search-criteria-saver.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-saver/search-criteria-saver.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, small, VAS

#1324 CP V6 - [VAS] Bug 9960: accession register bug filter
  ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
Labels: bug, small, Cherry-Pick

#1329 [VAS] Story 11404: fix tests
  .gitignore
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/search-criteria-saver/search-criteria-saver.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/search-criteria-saver/search-criteria-saver.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small

#1318 Bug/VAS-11415: fix bug on upload project in collect
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small

#1330 Bug/VAS-11415: fix bug on upload project in collect on V6
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, VAS, Cherry-Pick

#1323 CP 6RC - [VAS] Bug 9960: accession register bug filter
  ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
Labels: bug, small, Cherry-Pick

#1325 CP V6 - [VAS] Story 11340: Bug audit selector
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
  ui/ui-frontend/projects/identity/src/app/user/user-create/user-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.scss
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio-group/vitamui-radio-group.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio/vitamui-radio.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio/vitamui-radio.component.scss
  ui/ui-frontend/projects/vitamui-library/src/lib/components/vitamui-radio/vitamui-radio.component.ts
Labels: bug, small, Cherry-Pick

#1328 story #11387 fix(referential): fix bad behavior in usage and service…
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.ts
Labels: bug, small, VAS

#1332 STORY 11396 translation commonization
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: enhancement, VAS, Highlight

#1344 [VAS] Bug 11465: can not select ontology in collect app
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: bug, javascript, small, VAS

#1342 [BUG] story 11256 error when defining filtering by rule in an access contract on V6-RC
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.ts
Labels: bug, small, VAS, Cherry-Pick

#1350 CP V5 - Bug/11356: Fix build vitamui due to library lodash
  ui/ui-frontend-common/package.json
  ui/ui-frontend/package.json
Labels: bug, dependencies, small, VAS, Cherry-Pick

#1345 [VAS] Bug 10529: add OpType TRANSFER_REPLY in accession register details
  ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.statics.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-constants.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, javascript, small, VAS

#1346 CP 6RC - [VAS] Bug 10529: add OpType TRANSFER_REPLY in accession register details
  ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.statics.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-constants.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: VAS, Cherry-Pick

#1347 CP 6 - [VAS] Bug 10529: add OpType TRANSFER_REPLY in accession register details
  ui/ui-frontend-common/src/app/modules/models/access-register/register-value-event-model.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operation/accession-register-operation.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.statics.spec.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-operations-list/accession-register-operations-list.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-constants.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: VAS, Cherry-Pick

#1337 story #10858 (archive-search|collect): add GOT physical objects display
  ui/ui-frontend-common/src/app/modules/archive/archive.module.ts
  ui/ui-frontend-common/src/app/modules/archive/components/physical-archive-viewer/physical-archive-viewer.component.html
  ui/ui-frontend-common/src/app/modules/archive/components/physical-archive-viewer/physical-archive-viewer.component.scss
  ui/ui-frontend-common/src/app/modules/archive/components/physical-archive-viewer/physical-archive-viewer.component.spec.ts
  ui/ui-frontend-common/src/app/modules/archive/components/physical-archive-viewer/physical-archive-viewer.component.ts
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: enhancement, javascript, VAS

#1352 VAS-10858: fix build error
  ui/ui-frontend-common/src/app/modules/archive/components/physical-archive-viewer/physical-archive-viewer.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.spec.ts
Labels: bug, small, VAS

#1348 CP V5 - [VAS]Bug/11461: update access contract usage on archive search
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
  api/api-archive-search/archive-search-external-client/src/test/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClientTest.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClient.java
  api/api-archive-search/archive-search-internal-client/src/test/java/fr/gouv/archive/internal/client/ArchiveInternalRestClientTest.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ArchiveSearchInternalServerConfig.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/service/RulesUpdateCommonService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/searchcriteria/converter/SearchCriteriaHistoryConverter.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ExternalParametersService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rulesupdate/service/RulesUpdateCommonServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ExternalParametersServiceTest.java
  api/api-ingest/ingest-internal/pom.xml
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/BasePaginatingAndSortingRestClient.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/dip-request-create/dip-request-create.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/reclassification/reclassification.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/archive-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/archive-unit-validator.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
Labels: bug, VAS, Cherry-Pick, Security

#1357 Bug/Vas-11404: fix build error
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.module.ts
Labels: bug, small, VAS
