Repository ProgrammeVitam/vitam-ui, pull requests merged in 2023-11, with the labels that each got.

#1530 [VAS] Bug 11904: transaction status not updated on collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, VAS

#1529 Story 11250: Clean systemd mongo services.
  cots/vitamui-mongod/templates/vitamui-mongod.service
  deployment/roles/mongodb_migration_v5/tasks/reconfig.yml
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
  docs/fr/migration/index.rst
Labels: OPS REVIEW

#1531 BUG # 11893 fix ihm management contract
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.scss
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#1457 story #11605 feat: add pastis standalone pipeline
  Jenkinsfile
  api/api-pastis/pastis-standalone/pom.xml
  ui/ui-frontend-common/package.json
Labels: java, small, VAS, OPS REVIEW

#1536 story #11852 test: reduce podam log flood
  api/api-collect/collect-internal-client/src/test/resources/logback-test.xml
  api/api-collect/collect-internal/src/test/resources/logback-test.xml
Labels: small, VAS, clean Code

#1532 feature/vas-11915: update log level in the case of not found file
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
Labels: small, VAS

#1538 fix wrong rebase
  ui/ui-frontend-common/package.json
Labels: small, VAS

#1540 Story 11250 - fix(dev-tools): upgrade mongo version
  api/api-iam/iam-external/src/main/resources/application-dev.yml
  api/api-referential/referential-external/src/main/resources/application-dev.yml
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
  tools/docker/mongo/mongo_vars_dev.yml
  tools/docker/mongo/replica-set/000_replicaset_dev.js
  tools/docker/mongo/start_dev.sh
  tools/docker/mongo/start_docker_cluster.sh
  ui/ui-frontend/projects/identity/src/assets/config-dev.json
  ui/ui-frontend/projects/portal/src/assets/config-dev.json
  ui/ui-frontend/projects/referential/src/assets/config-dev.json
Labels: small, OPS REVIEW

#1545 [CP - v7.0.x] - #11605 - Pastis standalone pipeline
  Jenkinsfile
  api/api-pastis/pastis-standalone/pom.xml
  ui/ui-frontend-common/package.json
Labels: small, VAS, Cherry-Pick

#1537 DS 11927: Bind to the proper host for VitamUI services in consul.
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: small, CEA, OPS REVIEW

#1542 CP V6 - DS 11927: Bind to the proper host for VitamUI services in consul.
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: small, Cherry-Pick, CEA, OPS REVIEW

#1543 CP 6RC - DS 11927: Bind to the proper host for VitamUI services in consul.
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: small, Cherry-Pick, CEA, OPS REVIEW

#1544 CP V5 - DS 11927: Bind to the proper host for VitamUI services in consul.
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: small, Cherry-Pick, CEA, OPS REVIEW

#1546 Story #11558 fix(ci): pastis standalone build step
  Jenkinsfile
  api/api-pastis/pastis-standalone/pom.xml
Labels: bug, small, VAS

#1551 Story 11558: Fix build for pastis-standalone.
  Jenkinsfile
Labels: small, VAS, OPS REVIEW

#1549 CP V6 - build: remove @types/moment
  ui/ui-frontend-common/package.json
Labels: small, VAS, Cherry-Pick

#1550 CP 6RC - build: remove @types/moment
  ui/ui-frontend-common/package.json
Labels: small, VAS, Cherry-Pick

#1552 CP V5 - build: remove @types/moment
  ui/ui-frontend-common/package.json
Labels: small, VAS, Cherry-Pick

#1533 [CP-V7] feature/vas-11915: update log level in the case of not found file
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
Labels: small, VAS, Cherry-Pick

#1534 [CP-V6] feature/vas-11915: update log level in the case of not found file
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/OntologyServiceReader.java
Labels: small, VAS, Cherry-Pick

#1526 CP V5RC - [VAS] Bug 11535: rename access contract error
  .gitignore
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamUIAccessContractServiceTest.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
Labels: Cherry-Pick

#1555 CP 5RC - build: remove @types/moment
  ui/ui-frontend-common/package.json
Labels: small, VAS, Cherry-Pick

#1557 CP 7.0 - Story 11979: Fix for cluster replicaset deployement & add is_small parameter.
  deployment/ansible-vitamui/mongo.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/mongo/tasks/check_auth.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/init-replica.js.j2
  deployment/roles/mongo_init/tasks/main.yml
Labels: small, VAS, Cherry-Pick, OPS REVIEW
