Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-03, with the labels that each got.

#1662 Story #12354: Deliver bootstrap_repo to handle gpgcheck
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/bootstrap_repo/files/GPG-KEY-vitam
  deployment/roles/bootstrap_repo/tasks/main.yml
  deployment/roles/bootstrap_repo/templates/vitamui-source-list.j2
  deployment/roles/bootstrap_repo/templates/vitamui.repo.j2
Labels: OPS REVIEW

#1663 Story #12345: Upgrade Consul from version 1.17.3 to 1.18.0
  deployment/roles/consul/vars/main.yml
Labels: OPS REVIEW

#1661 Story #12403: Minor upgrade of MongoDB to version 7.0.6
  deployment/ansible-vitamui-migration/migration_mongodb_70.yml
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: VAS, OPS REVIEW

#1660 Story #12413: ldap compatibility with api gateway
  deployment/roles/nginx_webapp/templates/frontend/config.json.j2
  deployment/roles/reverse/tasks/nginx/configure_nginx.yml
  deployment/roles/reverse/templates/nginx/proxy_params.j2
  ui/ui-frontend-common/src/app/modules/authentication/authentication-interceptor.ts
  ui/ui-frontend-common/src/app/modules/models/app.configuration.interface.ts
Labels: OPS REVIEW

#1656 Fix #12373: remove dependency to Apache Shiro
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalService.java
Labels: small

#1671 Story #12406: Add Filebeat component
  deployment/ansible-vitamui/filebeat.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/files/modules/nginx.yml
  deployment/roles/filebeat/files/modules/system.yml
  deployment/roles/filebeat/handlers/main.yml
  deployment/roles/filebeat/tasks/add_inputs.yml
  deployment/roles/filebeat/tasks/add_modules.yml
  deployment/roles/filebeat/tasks/install.yml
  deployment/roles/filebeat/tasks/main.yml
  deployment/roles/filebeat/tasks/uninstall.yml
  deployment/roles/filebeat/templates/filebeat.yml.j2
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/logstash.yml
  deployment/roles/filebeat/templates/modules/mongodb.yml
  deployment/roles/filebeat/vars/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/templates/conf.d/filebeat-to-logstash.conf.j2
  deployment/roles/mongo/templates/mongod.conf.j2
Labels: OPS REVIEW

#1666 Story #12422: return the access contrat of the actual tenant
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalServiceTest.java
Labels: java, small

#1670 CP V7.0 - Story #12422: return the access contrat of the actual tenant
  .gitignore
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalServiceTest.java
  ui/ui-frontend/.gitignore
Labels: Cherry-Pick

#1669 CP V6 - Story #12422: return the access contrat of the actual tenant
  .gitignore
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalServiceTest.java
  ui/ui-frontend/.gitignore
Labels: Cherry-Pick

#1668 CP V6RC - Story #12422: return the access contrat of the actual tenant
  .gitignore
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalServiceTest.java
  ui/ui-frontend/.gitignore
Labels: Cherry-Pick

#1667 CP V5 - Story #12422: return the access contrat of the actual tenant
  .gitignore
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/externalParameters/service/ExternalParametersInternalServiceTest.java
  ui/ui-frontend/.gitignore
Labels: Cherry-Pick

#1683 Fix #12406: Small fixes for Filebeat
  deployment/ansible-vitamui/filebeat.yml
  deployment/ansible-vitamui/rsyslog.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/environments/hosts-ui.example
Labels: OPS REVIEW

#1687 Fix #12514: fix mapping for Collect CSV export
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: small

#1688 Fix #12457: call expects id, not identifier
  ui/ui-frontend/projects/pastis/src/app/core/services/archive-profile-api.service.ts
Labels: small

#1689 Bugs #12552 config(gateway): fix archive unit update api rewrite
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, small, VAS

#1672 Story #12142 Repeatable input
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverter.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverterTest.java
  ui/ui-frontend-common/src/app/modules/components/common-tooltip/common-tooltip.directive.ts
  ui/ui-frontend-common/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.html
  ui/ui-frontend-common/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.scss
  ui/ui-frontend-common/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.spec.ts
  ui/ui-frontend-common/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.ts
  ui/ui-frontend-common/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.module.ts
  ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/object-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/object-editor.module.ts
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend-common/src/sass/_button.scss
  ui/ui-frontend-common/src/sass/_editable-field.scss
  ui/ui-frontend-common/src/sass/_input.scss
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/starter-kit/mock-api/mock/me.js
  ui/ui-frontend/projects/starter-kit/mock-api/routes.json
  ui/ui-frontend/projects/starter-kit/src/app/components/buttons/buttons.component.html
  ui/ui-frontend/projects/starter-kit/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/starter-kit/src/app/components/inputs/inputs.component.scss
  ui/ui-frontend/projects/starter-kit/src/app/components/inputs/inputs.component.ts
Labels: enhancement, javascript, java, VAS

#1693 Fix #12556: archive search - search by management rule
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  ui/ui-frontend/proxy-gateway.conf.js
Labels: small

#1696 Fix: do not fail when downloading DIP with no filename set in content-disposition header
  ui/ui-frontend-common/src/app/modules/utils/download.utils.ts
Labels: small

#1692 story #12532 feat(collect-object-groups): add persistent identifiers …
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.html
Labels: javascript, small, VAS

#1701 Fix #12537: ensure that there are no duplicated CAS services in Mongo
  deployment/scripts/mongod/v7.1/039_enable_oidc_code_grant_type_on_archive_search_service_ref.js.j2
  deployment/scripts/mongod/v7.1/040_enable_oidc_code_grant_type_on_pastis_service_ref.js.j2
  deployment/scripts/mongod/v7.1/041_enable_oidc_code_grant_type_on_ingest_service_ref.js.j2
  deployment/scripts/mongod/v7.1/042_enable_oidc_code_grant_type_on_collect_service_ref.js.j2
Labels: small, OPS REVIEW

#1702 Fix #12589: default portal homepage should show tenant and language selection
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: small, OPS REVIEW

#1703 Fix #12511: fix incorrect mapping on Collect document download
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: small

#1684 Story #12448: set apiPath to path if absent
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverter.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverterTest.java
Labels: bug

#1694 Bug #12446: ontology creation does not return error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/OntologyDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/OntologyInternalServiceTest.java
Labels: bug

#1690 Story #11852 - Redirection du flux vers l'API Gateway
  api/api-pastis/pastis-external/src/main/resources/application-dev.yml
  ui/ui-frontend/package.json
  ui/ui-frontend/proxy-gateway-next.conf.js
Labels: enhancement, small, VAS

#1713 Story #12443: Update merge_index for VitamUI
  deployment/ansible-vitamui-extra/vitamui_extra.yml
  deployment/environments/hosts-ui.example
  deployment/roles/merge_index_apache/tasks/main.yml
  deployment/roles/merge_index_apache/templates/index_debug.html.j2
  deployment/roles/merge_index_apache/templates/index_links.html.j2
Labels: OPS REVIEW

#1716 Story #12443: Update proper Vitam group for reverse.
  deployment/ansible-vitamui-extra/vitamui_extra.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
Labels: small, OPS REVIEW

#1699 Fix #12508: correctly save collect transactions
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
Labels: bug, small, VAS

#1700 Fix #12349: avoid null problem with accession register detail pane
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register-preview/accession-register-detail/accession-register-detail.component.ts
Labels: bug, small, VAS

#1712 bug #12572: fix http save criteria
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
Labels: bug, small, VAS

#1718 Bugs #12516: hide STATIC_ATTACHEMENT unit in collect archives list
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug

#1715 bug #12592: fix error 500 when unselectcontract management
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, VAS

#1706 CP 6.x - item #12158: fix unable to deselect management contract in ingest contract
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, Cherry-Pick

#1704 CP 7.0 - item #12158: fix unable to deselect management contract in ingest contract
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, Cherry-Pick

#1719 Cleanup #11963: remove useless attribute
  ui/ui-frontend/projects/ingest/src/app/core/api/ingest-api.service.ts
Labels: small

#1720 Bugs: fix file name parameter name for collect update AU metadata
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
Labels: bug, small

#1721 Bug #12596: show attachment nodes if there is result and no facets
  ui/ui-frontend-common/src/app/modules/components/vitamui-tree-node/vitamui-tree-node.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small

#1727 Bug #12416: handle i18n Title/Description
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/DescriptionDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/ResultsDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/TitleDto.java
  ui/ui-frontend-common/src/app/modules/index.ts
  ui/ui-frontend-common/src/app/modules/models/nodes/filing-holding-scheme.handler.ts
  ui/ui-frontend-common/src/app/modules/models/units/unit.interface.ts
  ui/ui-frontend-common/src/app/modules/pipes/pipes.module.ts
  ui/ui-frontend-common/src/app/modules/pipes/unitI18n.pipe.spec.ts
  ui/ui-frontend-common/src/app/modules/pipes/unitI18n.pipe.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, javascript, java, VAS

#1724 CP V6 - bug #12592: fix error 500 when unselectcontract management
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, Cherry-Pick

#1723 CP V7 bug #12592: fix error 500 when unselectcontract management
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, Cherry-Pick
