Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-01, with the labels that each got.

#1598 bugs #12085 fix(metadata): missing label in nested arrays
  ui/ui-frontend-common/src/app/modules/object-viewer/services/display-rule-helper.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/display-rule-helper.service.ts
Labels: bug, javascript, small, VAS

#1593 [VAS] Story #12095: add modal unsaved modifications
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
Labels: bug, small

#1600 Fix #12272: apply same (as Transfer) modifications on DIP
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/ExportDipCriteriaDto.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ExportDipInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ExportDipInternalServiceTest.java
Labels: small, VAS

#1563 Story #11851: clean code
  .gitignore
  README.md
  tools/docker/mongo/start_dev.sh
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/pom.xml
Labels: clean Code

#1608 feature/vas-11937: upgrade jquery
  cas/cas-server/pom.xml
  pom.xml
Labels: dependencies, small, VAS

#1616 fix: client break due to VersionsModel changes
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
Labels: bug, small, VAS

#1610 add tests to getorix module
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/GetorixDepositInternalService.java
  api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/GetorixDepositInternalServiceTest.java
  api/api-collect/collect-internal/src/test/resources/dataGetorix/vitam_units_response.json
  api/api-collect/collect-internal/src/test/resources/dataGetorix/vitam_units_response_with_unitups_list.json
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/probativevalue/ProbativeValueInternalService.java
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/create-getorix-deposit/create-getorix-deposit.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-advise-preview/getorix-deposit-advise-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-deposit-upload-object.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-deposit-upload-object.component.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-leaves-tree/getorix-leaves-tree.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-leaves-tree/getorix-leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-tree-node/getorix-tree-node.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-tree-plan-schema/getorix-tree-plan-schema.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/getorix-deposit-upload-object/getorix-tree-plan-schema/getorix-tree-plan-schema.component.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/services/getorix-deposit-shared-data.service.spec.ts
  ui/ui-frontend/projects/collect/src/app/getorix-deposit/services/getorix-deposit-shared-data.service.ts
Labels: enhancement, Highlight, VGX

#1617 Story #12300: distinct confirmation messages for DIP export and transfert
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/transfer-request-modal/transfer-request-modal.component.ts
Labels: enhancement, javascript, small

#1611 Story #12165 fix: do not use detected hostname in CAS ticket name
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
Labels: bug, small, OPS REVIEW

#1615 CP 7.0 - Story #12165 fix: do not use detected hostname in CAS ticket name
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#1614 CP V6 - Story #12165 fix: do not use detected hostname in CAS ticket name
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#1613 CP 6RC - Story #12165 fix: do not use detected hostname in CAS ticket name
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#1612 CP V5 - Story #12165 fix: do not use detected hostname in CAS ticket name
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#1607 Story #12091 fix Ingest Contract signed document control type modification
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-preview.component.ts
Labels: bug, javascript, small

#1619 Bug #12139: persistent identifier authority is either 5 or 9 digits long
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-create/management-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-identification-tab/management-contract-identification-tab.component.ts
Labels: bug, small

#1602 Story #11851: clean code
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
Labels: small, VAS, clean Code

#1601 [Backport 7.0.x] Story #11851: clean code
  .gitignore
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: small, VAS, Cherry-Pick, clean Code

#1603 [Backport 6.x] Story #11851: clean code
  .gitignore
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: small, VAS, Cherry-Pick, clean Code

#1620 feature/vas-11937: upgrade jquery in messages
  cas/cas-server/src/main/resources/overriden_messages.properties
Labels: dependencies, small, VAS

#1597 Story #12063: Automatically send SIP from collecte to Vitam
  api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectProjectDto.java
  ui/ui-frontend-common/src/app/modules/models/collect/project.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: enhancement, javascript, java, VAS

#1621 [CP-V7] feature/vas-11937: upgrade jquery
  cas/cas-server/pom.xml
  cas/cas-server/src/main/resources/overriden_messages.properties
  pom.xml
Labels: small, VAS, Cherry-Pick

#1622 [CP-V6] feature/vas-11937: upgrade jquery to 1.13.2
  cas/cas-server/src/main/resources/overriden_messages.properties
  pom.xml
Labels: small, VAS, Cherry-Pick

#1623 [CP-V6-RC] feature/vas-11937: upgrade jquery to 1.13.2
  cas/cas-server/src/main/resources/overriden_messages.properties
  pom.xml
Labels: small, VAS, Cherry-Pick

#1624 item #12158: fix unable to deselect management contract in ingest contract
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.html
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, VAS

#1631 Story #11987: update schema response model
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/SchemaElementCreateDto.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverter.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaService.java
  ui/ui-frontend-common/src/app/modules/object-viewer/models/schema-element.model.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/mock-schema.service.ts
Labels: small, VAS
