Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-10, with the labels that each got.

#2079 CP v7.1 : bug #13206 : signed document non downloadable
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
Labels: bug, small, Cherry-Pick

#2080 CP V7.1 - bug #13117 : csv file export fail
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/file-types.enum.ts
Labels: bug, small, Cherry-Pick

#2085 CP 7.1 : bug #13178 : checkbox rule recalculation on delete rule criteria
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: Cherry-Pick

#2082 CP V7.1 - Bugs #13232: report failed ontology deletion
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/OntologyInternalServiceTest.java
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.service.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small, Cherry-Pick

#2081 Bugs #13232: report failed ontology deletion
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ontology/OntologyInternalService.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/OntologyInternalServiceTest.java
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.service.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2087 Bugs #13481: correctly escape the json schema in the notice
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaFromJSON.java
Labels: bug, small

#2089 CP V7.0 - Bugs #13481: correctly escape the json schema in the notice
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaFromJSON.java
Labels: bug, small, Cherry-Pick

#2098 Bugs #13480 #13486: fix JSON Schema generation for array properties with enum or pattern
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadataDetails.java
Labels: bug

#2099 CP V7.1 - Bugs #13480 #13486: fix JSON Schema generation for array properties with enum or pattern
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadataDetails.java
Labels: bug, Cherry-Pick

#2100 CP V7.0 - Bugs #13480 #13486: fix JSON Schema generation for array properties with enum or pattern
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadataDetails.java
Labels: bug, Cherry-Pick

#2101 CP V6 - Bugs #13480 #13486: fix JSON Schema generation for array properties with enum or pattern
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/pua/PuaMetadataDetails.java
Labels: bug, Cherry-Pick

#2103 Story #13438: access contract DTO typo
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessContractDto.java
Labels: small

#2091 Story #13474: Retrieving timestamp from log's date_time field instead of writing's date.
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/apache.yml.j2
  deployment/roles/filebeat/templates/modules/logstash.yml.j2
  deployment/roles/filebeat/templates/modules/mongodb.yml.j2
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
  deployment/roles/vitamui/templates/logback.xml.j2
Labels: VAS, OPS REVIEW

#2107 bug #13206 : dowloadable documents collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
Labels: bug, small

#2110 Story #13011: access contract tab translate keys
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.ts
Labels: small

#2109 CP 7.1 - bug #13206 : non-downloadable signed documents for collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
Labels: bug, small, Cherry-Pick

#2111 Bug #13501: Read all files when drag&drop instead of stopping at 100
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
Labels: bug

#2112 CP 7.1 - Bug #13501: Read all files when drag&drop instead of stopping at 100
  ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
Labels: bug

#2113 CP 7.0 - Bug #13501: Read all files when drag&drop instead of stopping at 100
  ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
Labels: bug

#2114 CP 6.x - Bug #13501: Read all files when drag&drop instead of stopping at 100
  ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
Labels: bug

#2118 Story #13234: Upgrade Elastic Suite because of multiple CVE
  deployment/roles/logstash/defaults/main.yml
Labels: small, VAS, Security, OPS REVIEW

#2117 Story #13234: Upgrade Elastic Suite because of multiple CVE
  deployment/roles/logstash/defaults/main.yml
Labels: small, VAS, Security, OPS REVIEW

#2116 bugs #13494 fix(pastis): create PA
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ProfileInternalController.java
Labels: bug, java, small, VAS

#2073 bugs #13454 fix(pastis): wrong metamodel usage at edition
  .run/core/Pastis - UI - Standalone.run.xml
  .run/core/Pastis Standalone - UI - Frontend.run.xml
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/pastis/src/app/core/services/breadcrumb.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/file.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
  ui/ui-frontend/projects/pastis/src/app/main/main.component.ts
  ui/ui-frontend/projects/pastis/src/app/models/file-node.ts
  ui/ui-frontend/projects/pastis/src/app/models/seda-data.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/attributes/attributes.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.scss
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree/file-tree.service.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-pua-control/add-pua-control.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/upload-profile/upload-profile.component.ts
Labels: bug, javascript, VAS

#2120 Bugs #13496: fix incorrect 'type' property in seda model
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.1.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
  api/api-pastis/pastis-external/src/main/resources/pua_validation/archiveUnitSeda.json
Labels: bug

#2122 Bugs #13493: disable signature tab components in read-only mode
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.ts
Labels: bug

#2123 CP V7.1 - Bugs #13493: disable signature tab components in read-only mode
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-signature-tab/ingest-contract-signature-tab.component.ts
Labels: bug, Cherry-Pick

#2119 bug #13505 : downloadable documents on archive search
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
Labels: bug, small

#2062 Story #13302: Added ability to select Vitam's components to deploy in legacy mode
  Jenkinsfile.containers
  deployment/roles/consul/templates/vitam-container-consul.service.j2
  deployment/roles/docker/tasks/Debian.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/tasks/add_inputs.yml
  deployment/roles/filebeat/tasks/add_modules.yml
  deployment/roles/filebeat/tasks/install.yml
  deployment/roles/filebeat/templates/filebeat.service.j2
Labels: OPS REVIEW

#2126 Bug #13179: Force using index with name idx_token_date on token collection
  deployment/scripts/mongod/v7.1/002_TRV-389_add_index_on_updatedDate_field_of_tokens_collection_ref.js
Labels: bug, small

#2128 Story #13302: Fix consul startup in production cluster mode
  deployment/roles/consul/templates/vitam-container-consul.service.j2
Labels: bug, small, OPS REVIEW

#2129 Story #13302: Fix filebeat package installation.
  deployment/roles/filebeat/tasks/install.yml
Labels: bug, small, OPS REVIEW

#2124 Story #13502: prevent dl on persistent id search if access contract prevents it
  api/api-gateway/src/main/resources/application-dev.yml
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/rest/RestApi.java
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  docs/fr/architecture/sections/architecture.md
  docs/swagger/api-external/referential-external/index.html
  docs/swagger/api-internal/referential-internal/index.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.ts
  ui/ui-frontend/projects/archive-search/src/app/core/management-rules-shared-data.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.service.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-list/access-contract-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-list/access-contract-list.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-information-tab/access-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-update/access-contract-node-update.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-update/access-contract-node-update.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-write-access-tab/access-contract-write-access-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-write-access-tab/access-contract-write-access-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.ts
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-create/context-edit-permission/context-edit-permission.component.ts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-permission-tab/context-permission-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/core/api/access-contract-api.service.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-check-tab/securisation-check-tab.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/api/access-contract-api.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/api/access-contract-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/services/access-contract.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/services/index.ts
Labels: bug, small

#2134 Story #13302: Fix Consul DNS resolution in cluster mode for Almalinux
  deployment/roles/consul/templates/vitam-container-consul.service.j2
  deployment/roles/docker/tasks/main.yml
Labels: bug, OPS REVIEW

#2137 bugs #13514 fix(pastis): spinner issues with save actions
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/archive-profile-saver.service.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/archive-unit-profile-saver.service.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, javascript, VAS

#2145 bugs #13485 fix(pastis): logout feature
  ui/ui-frontend/projects/pastis/src/app/pastis/pastis.module.ts
Labels: bug, javascript, VAS

#2143 CP V7.1 - Fix #11854: CAS minor bugfix/refacto
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/pm/IamPasswordManagementService.java
Labels: small, Cherry-Pick

#2148 Bug #13453: accesscontracts endpoint for csv import
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.ts
  ui/ui-frontend/projects/referential/src/app/shared/import-dialog/import-dialog-param.interface.ts
  ui/ui-frontend/projects/referential/src/app/shared/import-dialog/import-dialog.component.ts
Labels: bug

#2150 Bug #13572: accesscontracts creation modal title
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug

#2159 bugs #13221 fix(ontology): display string sizes on geo points and keyword types
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.ts
Labels: bug, javascript, small, VAS

#2146 Bugs #13458: metamodel fixes + get PUA metamodel from PA metamodel
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/JsonFromPUA.java
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/service/PuaPastisValidator.java
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
  api/api-pastis/pastis-commons/src/main/resources/pua_validation/archiveUnitSeda.json
  api/api-pastis/pastis-commons/src/test/resources/pua/profile_Expected_with_management.json
  api/api-pastis/pastis-external/src/main/resources/pua_validation/archiveUnitSeda.json
Labels: bug

#2144 bug #13500 : wrong regex error messages
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-template.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-input/vitamui-input-error.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/dates.constants.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
  ui/ui-frontend/projects/vitamui-library/src/sass/base/_typography.scss
  ui/ui-frontend/projects/vitamui-library/src/sass/mixins/_fonts.scss
Labels: bug, javascript, VAS

#2170 Bug #13623: remove wrong field threshold on reclassification action
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
Labels: bug, small, VAS

#2174 [CP 7.1] Bug #13623: remove wrong field threshold on reclassification action
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
Labels: bug, small, VAS, Cherry-Pick

#2172 [CP-V6] Bug 13623 remove wrong field threshold for reclassification queries 6 x
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
Labels: bug, small, VAS, Cherry-Pick

#2171 bug #13541 : agency and rule previews, non-disabled fields
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-information-tab/rule-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-preview.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule-preview/rule-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.ts
Labels: bug

#2156 CP - 7.1 - bugs #11661 fix(collect): english translations in fr file
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: Cherry-Pick

#2152 Bug #13537: Backport fixes for container deployment.
  Jenkinsfile.containers
  deployment/roles/consul/templates/vitam-container-consul.service.j2
  deployment/roles/docker/tasks/Debian.yml
  deployment/roles/docker/tasks/main.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/tasks/add_inputs.yml
  deployment/roles/filebeat/tasks/add_modules.yml
  deployment/roles/filebeat/tasks/install.yml
  deployment/roles/filebeat/templates/filebeat.service.j2
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#2175 Bug #13453: access contract csv template incoherence
  api/api-referential/referential-external/src/main/resources/static/import-access-contracts-model.csv
Labels: bug, small

#2178 Bug #13453: access contract csv template and endpoint
  api/api-referential/referential-external/src/main/resources/static/import-access-contracts-model.csv
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.ts
  ui/ui-frontend/projects/referential/src/app/shared/import-dialog/import-dialog-param.interface.ts
Labels: bug, small

#2177 Bugs #13606 #13611 #13617 #13607 #13613 #13621 #13610 #13612 #13615 #13614: misc Pastis
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
Labels: bug

#2179 CP V7.0 - Bugs #13154: change pronom version
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamFileFormatService.java
Labels: bug, small, Cherry-Pick

#2182 Bugs #13605: add missing translations
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
Labels: bug, small

#2176 bugs #13604 fix(pastis): error feedback
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/profile/ProfileInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/ProfileInternalController.java
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, javascript, java, small, VAS

#2185 CP V7.1 - Story #13302: Fix filebeat package installation.
  deployment/roles/filebeat/tasks/install.yml
Labels: Cherry-Pick

#2186 Bugs #13654: allow profile local saving when not associated to a notice
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug

#2183 CP 7.0 - bug #13178 : checkbox rule recalculation on delete rule criteria
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2184 CP 6.0 - bug #13178 : checkbox rule recalculation on delete rule criteria
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2190 Bugs #13590: changed label for ontology 'type' field
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#1859 [BP V7.0] Bug #12827: Fix cas access-log buffering
  cas/cas-server/src/main/resources/application.properties
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: OPS REVIEW

#1860 [BP V6] Bug #12827: Fix cas access-log buffering
  cas/cas-server/src/main/resources/application.properties
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: OPS REVIEW

#2167 Bug #13572: create tenant disable button when loading
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-create/owner-create.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-create/owner-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/tenant-create/tenant-create.component.html
  ui/ui-frontend/projects/identity/src/app/customer/tenant-create/tenant-create.component.ts
Labels: small

#2189 CP - V7.1 : Story #11854 & Bug #13572 (cc): disable button when loading on create organisation and create tenant
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.html
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-create/owner-create.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-create/owner-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/tenant-create/tenant-create.component.html
  ui/ui-frontend/projects/identity/src/app/customer/tenant-create/tenant-create.component.ts
Labels: bug, small

#2198 Bugs #13768: package Pastis standalone with java 17
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis-standalone/src/main/assembly/packaging-zip.xml
Labels: bug

#2203 CP 7.1 - Fix #13237: Pastis typo, i18n & UI bugfixes
  ui/ui-frontend/projects/pastis/src/app/main/main.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/assets/css/_toaster.scss
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/pastis/src/sass/_toaster.scss
Labels: Cherry-Pick

#2196 Bug #13759: handle expiration token
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/security/IamAuthentificationService.java
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInternalServiceIntegrationTest.java
Labels: bug, small, VAS

#2204 Story #11854: Add upgrade documentation for V8.0.
  docs/fr/migration/index.rst
  docs/fr/migration/upgrade_v8_0.md
Labels: documentation, small, OPS REVIEW
