Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-09, with the labels that each got.

#2009 Bugs #13316: clear session storage on logout
  cas/cas-server/src/main/resources/templates/logout/casLogoutView.html
Labels: bug, small

#2005 story #13281 feat(pastis): add seda version to editors
  api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
  api/api-pastis/pastis-external/src/main/resources/metamodel/metamodel-2.1.json
  api/api-pastis/pastis-external/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-external/src/main/resources/metamodel/metamodel-2.3.json
  ui/ui-frontend/projects/design-system/src/app/app-routing.module.ts
  ui/ui-frontend/projects/design-system/src/app/app.component.html
  ui/ui-frontend/projects/design-system/src/app/app.module.ts
  ui/ui-frontend/projects/design-system/src/app/components/chips/chips.component.html
  ui/ui-frontend/projects/design-system/src/app/components/chips/chips.component.scss
  ui/ui-frontend/projects/design-system/src/app/components/chips/chips.component.ts
  ui/ui-frontend/projects/design-system/src/app/components/chips/chips.module.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/file.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.scss
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.scss
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/chip/chip.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/chip/chip.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/index.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
Labels: enhancement, javascript, java, small, VAS

#2006 Story#12969: clean current collect and archive-search profiles and create new profiles
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchiveUnitController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/SearchCriteriaHistoryExternalController.java
  api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/SearchCriteriaHistoryExternalControllerTest.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/CollectArchiveUnitController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectExternalController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/ProjectObjectGroupExternalController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/SearchCriteriaHistoryExternalController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionArchiveUnitExternalController.java
  api/api-collect/collect-external/src/main/java/fr/gouv/vitamui/collect/external/server/rest/TransactionExternalController.java
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/VitamuiRoles.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/v8.0/001_clean_archive_search_profiles.js.j2
  deployment/scripts/mongod/v8.0/002_update_archive_search_ui_contexts.js.j2
  deployment/scripts/mongod/v8.0/003_clean_collect_profiles.js.j2
  deployment/scripts/mongod/v8.0/004_create_new_collect_profiles_for_system.js.j2
  deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
  deployment/scripts/mongod/v8.0/006_update_collect_ui_contexts.js.j2
  docs/fr/architecture/sections/architecture.md
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/back/steps/archivesearch/ApiArchiveSearchExternalSearchCriteriaHistoryCreationSteps.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/back/steps/archivesearch/ApiArchiveSearchSearchCriteriaHistoryCoupleOfCheckSteps.java
  integration-tests/src/test/resources/features/back/archivesearch/SearchCriteriaHistoryCoupleOfChecks.feature
  integration-tests/src/test/resources/features/back/archivesearch/SearchCriteriaHistoryCreation.feature
  tools/docker/mongo/start_dev.sh
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.html
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-roles.enum.ts
Labels: enhancement, VAS, OPS REVIEW

#2014 Bugs #13269: do not order audits by _id anymore, use evDateTime DESC instead
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-list/audit-list.component.ts
Labels: bug

#2015 bugs #13331 fix: unwanted removes due to control.value mutation
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-list-input.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-list-textarea.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/data-structure.service.spec.ts
Labels: bug, javascript, small, VAS

#2011 story #13280 feat(pastis): use meta model according seda version
  api/api-pastis/pastis-external/src/main/resources/metamodel/metamodel-2.1.json
  api/api-pastis/pastis-external/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-external/src/main/resources/metamodel/metamodel-2.3.json
  ui/ui-frontend/projects/pastis/src/app/core/services/file.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
  ui/ui-frontend/projects/pastis/src/app/main/main.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/edit-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.service.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/upload-profile/upload-profile.component.ts
Labels: enhancement, javascript, VAS

#2020 bug #13069 : access contract, objects selection
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug

#2023 bug #13311 : non compliant popup
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
Labels: bug

#2024 Bug #13354: add ROLE_COLLECT_GET_ARCHIVE_BINARY role to collect app
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/v8.0/003_clean_collect_profiles.js.j2
Labels: bug, small, VAS

#2019 Story #13030: Checkmarx
  .github/workflows/build-and-test.yml
  api/api-iam/iam-internal/pom.xml
  api/api-security/security-internal/pom.xml
  commons/commons-mongo/pom.xml
  integration-tests/src/test/resources/data/i18n.zip
  pom.xml
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/pastis/src/app/app.component.html
Labels: VAS, clean Code

#2016 Bugs #13345: do not order by _id anymore
  ui/ui-frontend/projects/referential/src/app/audit/audit.service.ts
Labels: bug, small

#2031 Story #13199: clean unused settings for tenants sequences and select default tenant other than 0
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/environments/vitamui_extra_vars.yml
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
  integration-tests/src/test/resources/application-dev.yml
  integration-tests/src/test/resources/application-integration.yml
  tools/docker/mongo/mongo_vars_dev.yml
  ui/ui-frontend/projects/identity/src/app/customer/customer-create/customer-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-create/owner-create.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/tenant-create/tenant-create.component.ts
Labels: enhancement, VAS, OPS REVIEW

#2034 Story #13011: access contract fix dto
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessContractModelDto.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.ts
Labels: bug, small

#2037 Bugs #13210: log schema deletions to logbook
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2038 CP 7.1 - Bugs #13210: log schema deletions to logbook
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: bug, small, Cherry-Pick

#2040 Bug #13414: Fix nginx tokenizer for filebeat.
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
Labels: bug, small, VAS, OPS REVIEW

#2039 Bug #13377: Remove system module for filebeat if all filesets are disabled.
  deployment/roles/filebeat/tasks/add_modules.yml
  deployment/roles/filebeat/templates/modules/system.yml.j2
Labels: OPS REVIEW

#2041 CP V7.1 - Bug #13414: Fix nginx tokenizer for filebeat.
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2044 Bug #13163: Remove improper post action when upgrading -rsc packages
  tools/packaging/templates/after-remove-rsc.sh
Labels: small, VAS, OPS REVIEW

#2043 bug #13328 : terminate button status not updated when profile record updated
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
Labels: bug, small

#1951 CP V7.1 - Bug#13084: remove vitam common-private library references and use common-public
  api/api-iam/iam-internal/pom.xml
  commons/commons-logbook/pom.xml
  pom.xml
Labels: Cherry-Pick

#2032 Story #13356: clean collect and archive search profiles and add missed controls
  deployment/scripts/mongod/v8.0/003_clean_collect_profiles.js.j2
  docs/fr/architecture/sections/architecture.md
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, small, VAS

#2054 Bugs #13154: change pronom version
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamFileFormatService.java
Labels: bug, small, Cherry-Pick

#2053 Bugs #13154: change pronom version
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamFileFormatService.java
Labels: bug, small

#2049 bugs #13291 fix(metadata-editor): use multi option datepicker
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-list-date.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/list-editor/list-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/object-editor.module.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, enhancement, javascript, small, VAS

#2048 Bug #13336: download button activate depending on access contract
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/units/object-group.interface.ts
Labels: bug, javascript, small

#2042 Story #13392: Drop Consul and Prometheus accesslogs from filebeat processor.
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/tasks/add_inputs.yml
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/apache.yml.j2
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
  deployment/roles/vitamui/templates/logback.xml.j2
Labels: bug, VAS, OPS REVIEW

#2058 bug #13207 : regex length limit
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
Labels: bug, small

#2059 Story #13392: Renamed to drop_health_checks_logs variable.
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/apache.yml.j2
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
Labels: small, OPS REVIEW

#2056 Bug #13437 #13439 #13440 #13453: access contract bugs fixes
  api/api-referential/referential-external/src/main/resources/static/import-access-contracts-model.csv
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/ExportAccessContracts.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-create/ontology-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/index.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/access-contract.interface.ts
Labels: bug, small

#2057 CP V7.1 - Story #13392: Drop Consul and Prometheus accesslogs from filebeat processor.
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/tasks/add_inputs.yml
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/apache.yml.j2
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
  deployment/roles/vitamui/templates/logback.xml.j2
Labels: bug, VAS, Cherry-Pick, OPS REVIEW

#2064 bug #13206 : signed document non downloadable
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
Labels: bug, small

#2065 bugs #13256 fix: physical master download button and display
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/physical-archive-viewer/physical-archive-viewer.component.html
Labels: bug, javascript, small, VAS

#2067 Bugs #13460: allow $match operator in DSL
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
Labels: bug, small

#2068 CP 7.1 - Bugs #13460: allow $match operator in DSL
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
Labels: bug, small, Cherry-Pick

#2069 CP 7.0 - Bugs #13460: allow $match operator in DSL
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
Labels: bug, small, Cherry-Pick

#2070 CP 6 - Bugs #13460: allow $match operator in DSL
  commons/commons-security/src/main/java/fr/gouv/vitamui/common/security/SanityChecker.java
Labels: bug, small, Cherry-Pick

#2071 Bug #13359: Fix nginx configuration to allow upload on ingest or collect more than 1Go.
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
Labels: bug, small, VAS, OPS REVIEW

#2072 CP V7.1 - Bug #13359: Fix nginx configuration to allow upload on ingest or collect more than 1Go.
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2066 bugs #13279 fix: imports and method calls
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/ProfileResponseDto.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamProfileService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/profile/ProfileConverter.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/profile/ProfileInternalService.java
Labels: bug, java, small, VAS

#2074 Bug #13441: access contract fix other dto
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessContractDto.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/AccessContractsDto.java
Labels: bug, small

#2075 bug #13117 : csv file export fixes
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.component.ts
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.ts
  ui/ui-frontend/projects/referential/src/app/shared/import-dialog/import-dialog.component.ts
Labels: bug, small

#2076 Bug #13453: access contract model csv typo
  api/api-referential/referential-external/src/main/resources/static/import-access-contracts-model.csv
Labels: bug, small

#2078 bug #13332 : Metadatas _sp and _sps to remove
  ui/ui-frontend/projects/vitamui-library/src/app/modules/schema/schema.service.ts
Labels: bug, small
