Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-12, with the labels that each got.

#2262 bugs #13946 fix(edit-object): kind computing for external schema elements
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/schema/schema-element.model.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, javascript, small, VAS

#2272 Story #13845: fix tables in datepicker
  ui/ui-frontend/projects/vitamui-library/src/sass/_table.scss
Labels: small

#2277 Story #13958: download button disabled for physical object
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
Labels: bug

#2278 VP V8.0 - Story #13958: download button disabled for physical object
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/core/archive-shared-data.service.ts
Labels: bug, Cherry-Pick

#2279 CP V7.0 Bug #13592: add validators on owner forms
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.html
Labels: bug, small, VAS, Cherry-Pick

#2282 Story #13791 cc: add name in mongo docker compose
  tools/docker/mongo/mongo_dev.yml
Labels: small, clean Code

#2284 bug #13972 : metadata label not correctly loaded
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
Labels: small

#2259 Story #13901 feat(agencies): add create and update button in creation form
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: enhancement, javascript, small, VAS

#1952 CP 7.0 - Bug#13084: remove vitam common-private library references and use common-public
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/user/service/UserInfoInternalService.java
  commons/commons-logbook/pom.xml
  pom.xml
Labels: small, VAS, Cherry-Pick

#2295 Story #13803: use units size GB instead of KB in CSV generation
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
  commons/commons-utils/src/main/java/fr/gouv/vitamui/commons/utils/VitamUIUtils.java
  commons/commons-utils/src/test/java/fr/gouv/vitamui/commons/utils/VitamUIUtilsTest.java
Labels: enhancement, small, VAS

#2296 bug #14014 : datepicker fix
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
Labels: small

#2300 Story #14018: Upgrade Consul to version 1.20.1
  deployment/roles/consul/vars/main.yml
Labels: OPS REVIEW

#2302 CP V7.1 - Bug #13336: download button activate depending on access contract
  ui/ui-frontend-common/src/app/modules/archive-unit/components/physical-archive-viewer/physical-archive-viewer.component.ts
  ui/ui-frontend-common/src/app/modules/models/units/object-group.interface.ts
  ui/ui-frontend-common/src/app/modules/models/units/unit.interface.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/core/archive-shared-data.service.ts
Labels: Cherry-Pick

#2311 Cp 8.0 - bug #13330 : collect breadcrumb
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: Cherry-Pick

#2312 Cp 7.1 - bug #13330 : collect breadcrumb
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: Cherry-Pick

#2307 CP 8.0 - bug #14026 : agents services creation forbid only whitespace
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: Cherry-Pick

#2308 CP 7.1 - bug #14026 : agents services creation forbid only whitespace
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: Cherry-Pick

#2323 bug #14035 : collect - delete search criterias
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: small

#2320 bugs #14057 fix(edit-agency): functions and activities cardinality
  ui/ui-frontend/projects/referential/src/app/agency/agency.schema.ts
Labels: bug, javascript, small, VAS

#2325 bug #12093 : Archive search Object tab size
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
Labels: small

#2327 CP 7.1 - bug #12093 : Archive search Object tab size
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
Labels: small

#2326 CP 8.0 - bug #12093 : Archive search Object tab size
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
Labels: small

#2333 Story #14076: add vitamui_container_version variable
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/vitamui/templates/vitamui-container-componentid.service.j2
Labels: OPS REVIEW

#2328 CP V6 - Story #13791 cc: ensure mongo scripts are played in order
  deployment/roles/mongo_init/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2332 bugs #14029 fix: edit and view agency
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/persistent-identifier-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transactions.component.html
  ui/ui-frontend/projects/design-system/src/app/components/molecules/breadcrumbs/breadcrumbs.component.html
  ui/ui-frontend/projects/identity/src/app/customer/customer.component.html
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.component.html
  ui/ui-frontend/projects/identity/src/app/group/group.component.html
  ui/ui-frontend/projects/identity/src/app/hierarchy/hierarchy.component.html
  ui/ui-frontend/projects/identity/src/app/profile/profile.component.html
  ui/ui-frontend/projects/identity/src/app/subrogation/subrogate-user/subrogate-user.component.html
  ui/ui-frontend/projects/identity/src/app/user/user.component.html
  ui/ui-frontend/projects/ingest/src/app/holding-filling-scheme/holding-filling-scheme.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract.component.html
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.component.html
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency.template.ts
  ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.html
  ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.scss
  ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.html
  ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.scss
  ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit.component.html
  ui/ui-frontend/projects/referential/src/app/context/context.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation.component.html
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation.component.html
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
  ui/ui-frontend/projects/referential/src/app/securisation/securisation.component.html
  ui/ui-frontend/projects/referential/src/app/security-profile/security-profile.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-content-breadcrumb/vitamui-title-breadcrumb/vitamui-title-breadcrumb.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/models/edit-object.operators.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/models/display-object-service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/services/path-strategy-display-object.service.ts
Labels: bug, javascript, small, VAS

#2336 CP 7.1 - bug #14026 : Fixes following testing
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
Labels: Cherry-Pick

#2338 Story #13791 cc: show directory size in file selector
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/display-file.interface.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
Labels: bug, clean Code

#2324 CP 7.0 - Bug #14010: Add missing resolvconf's configuration for VitamUI
  deployment/roles/consul/tasks/main.yml
Labels: bug, small, VAS, OPS REVIEW

#2340 CP V6 - Bug #14010: Add missing resolvconf's configuration for VitamUI
  deployment/roles/consul/tasks/main.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2339 CP V6 - bug #14026 : agents services creation forbid only whitespace
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: Cherry-Pick

#2316 Story #13791 cc: use VitamuiHttpHeaders
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/shared/collect-upload/collect-upload.service.ts
  ui/ui-frontend/projects/design-system/src/app/components/molecules/inputs/autocomplete-multi-select-tree/design-system-autocomplete-multi-select-tree.component.ts
  ui/ui-frontend/projects/identity/src/app/external-param-profile/external-param-profile.service.ts
  ui/ui-frontend/projects/identity/src/app/hierarchy/hierarchy.service.ts
  ui/ui-frontend/projects/ingest/src/app/core/api/ingest-api.service.ts
  ui/ui-frontend/projects/ingest/src/app/core/common/upload.service.ts
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest.service.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/accession-register/accession-register.service.ts
  ui/ui-frontend/projects/referential/src/app/admin-dsl/admin-dsl.service.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.service.ts
  ui/ui-frontend/projects/referential/src/app/app.module.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit.service.ts
  ui/ui-frontend/projects/referential/src/app/context/context.service.ts
  ui/ui-frontend/projects/referential/src/app/core/api/operation-api.service.ts
  ui/ui-frontend/projects/referential/src/app/core/api/referential-import-api.service.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format.service.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-attachment-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract.service.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract.service.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.service.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/api/base-user-info-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/api/subrogation-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/api/user-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/application.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/logbook/logbook.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/rule/rule.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/schema/index.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/services/access-contract.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/services/profile.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-http-headers.enum.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-http-interceptor.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/services/metadata.service.ts
Labels: clean Code
