Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-06, with the labels that each got.

#1891 Story #11854 (clean-code): jenkinsfile pipeline parameters on first build
  Jenkinsfile
Labels: small, OPS REVIEW

#1896 Story #12813: remove link to outdated Pastis documentation
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-metadata-language/pastis-popup-metadata-language.component.html
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-metadata-language/pastis-popup-metadata-language.component.scss
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-metadata-language/pastis-popup-metadata-language.component.ts
Labels: documentation, small, VAS

#1895 Bug #12968: base url provided in module referential
  ui/ui-frontend/projects/referential/src/app/app.module.ts
Labels: bug

#1898 story #12923: add seda version 2.3 to export dip form
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/transfer-request-modal/transfer-request-modal.component.html
Labels: small, VAS

#1907 bugs #12928 fix(gateway): missing redirect to iam customers api in referential module
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, small, VAS

#1908 CP 7.1 - bugs #12928 fix(gateway): missing redirect to iam customers api in referential module
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, small, VAS, Cherry-Pick

#1909 bugs #13022 fix: rules validators behavior with empty value
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/management-rules-validator.service.ts
Labels: bug, javascript, small, VAS

#1910 CP 7.1 - bugs #13022 fix: rules validators behavior with empty value
  ui/ui-frontend/projects/archive-search/src/app/archive/validators/management-rules-validator.service.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#1890 Story #12116: Improve GitHub Actions cache management
  .ci/github-actions-settings.xml
  .ci/settings.xml
  .github/workflows/build-and-test.yml
  .github/workflows/lint.yml
  api/api-pastis/pastis-standalone/pom.xml
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/IngestContractService.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OperationExternalController.java
  pom.xml
  sonar-project.properties
Labels: VAS

#1911 story #12868:Update Access Contract APP to restrict object downloads in Search APP.
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.scss
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-preview.module.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-write-access-tab/access-contract-write-access-tab.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-write-access-tab/access-contract-write-access-tab.component.scss
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-write-access-tab/access-contract-write-access-tab.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: VAS

#1914 Story #11854 Clean code: Fix Sonar build
  .github/workflows/build-and-test.yml
  sonar-project.properties
Labels: VAS, clean Code

#1918 Story #12075: Upgrade logstash version from 7.17.20 to 8.13.4.
  deployment/roles/logstash/defaults/main.yml
Labels: small, VAS, OPS REVIEW

#1886 story #11854 chore(ui-frontend): clean package scripts
  .gitignore
  .run/5- Java CAS Server.run.xml
  .run/UI-Identity.run.xml
  .run/UI-Portal.run.xml
  .run/core/Archive Search - API - External.run.xml
  .run/core/Archive Search - API - Internal.run.xml
  .run/core/Archive Search - UI - Frontend.run.xml
  .run/core/CAS - Build.run.xml
  .run/core/CAS - Service.run.xml
  .run/core/Collect - API - External.run.xml
  .run/core/Collect - API - Internal.run.xml
  .run/core/Collect - UI - Frontend.run.xml
  .run/core/Gateway - API.run.xml
  .run/core/IAM - API - External.run.xml
  .run/core/IAM - API - Internal.run.xml
  .run/core/Identity - UI - Frontend.run.xml
  .run/core/Ingest - API - External.run.xml
  .run/core/Ingest - API - Internal.run.xml
  .run/core/Ingest - UI - Frontend.run.xml
  .run/core/Mongo - Service.run.xml
  .run/core/Pastis - API - External.run.xml
  .run/core/Pastis - API - Standalone.run.xml
  .run/core/Pastis - UI - Frontend.run.xml
  .run/core/Pastis Standalone - UI - Frontend.run.xml
  .run/core/Portal - UI - Frontend.run.xml
  .run/core/Referential - API - External.run.xml
  .run/core/Referential - API - Internal.run.xml
  .run/core/Referential - UI - Frontend.run.xml
  .run/core/Security - API - Internal.run.xml
  .run/core/Vitam UI - Library.run.xml
  .run/multirun/ARCHIVE-SEARCH.run.xml
  .run/multirun/PASTIS STANDALONE.run.xml
  .run/multirun/PASTIS.run.xml
  .run/multirun/REFERENTIAL.run.xml
  .run/multirun/VItam UI - Archive Search.run.xml
  .run/multirun/Vitam UI - Collect.run.xml
  .run/multirun/Vitam UI - Core.run.xml
  .run/multirun/Vitam UI - Identity.run.xml
  .run/multirun/Vitam UI - Ingest.run.xml
  .run/multirun/Vitam UI - Pastis.run.xml
  .run/multirun/Vitam UI - Referential.run.xml
  api/api-gateway/src/main/resources/application-dev.yml
  tools/start-mongo.sh
  ui/ui-frontend/package.json
  ui/ui-frontend/proxy-gateway.conf.js
  ui/ui-frontend/proxy.conf.js
  ui/ui-frontend/proxy.conf.json
Labels: javascript, small, VAS, clean Code
