Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-02, with the labels that each got.

#1632 Story #11851 Clean Code: do no always restart Mongo express
  tools/docker/mongo/mongo_dev.yml
Labels: small, VAS, clean Code

#1641 CP 7.0 - [VAS] Bug 11904: transaction status not updated on collect #1530
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, VAS, Cherry-Pick

#1633 Story #11851 Clean Code: fix invalid keystore for ui-identity
  ui/ui-identity/src/main/resources/dev/keystore_ui-identity-admin.jks
Labels: small, VAS, clean Code

#1618 Story #12159: Add archive unit bulk update api
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/BulkCommandDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/JsonPatchDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/MultiJsonPatchDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/OperationIdDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/UpdateArchiveUnitDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchDtoToUpdateMultiQueryConverter.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToSetActionConverter.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/JsonPatchToUnsetActionConverter.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/UpdateArchiveUnitDtoToUpdateMultiQueryConverter.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/dto/converter/UpdateMultiQueriesToBulkCommandDto.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/exception/ArchiveUnitUpdateException.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/exception/DslQueryCreateException.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/model/JsonPatch.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/model/OperationId.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/model/PatchCommand.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/model/PatchOperation.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/ArchiveUnitClient.java
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/service/ArchiveUnitService.java
  api/api-archive-search/archive-search-commons/src/test/java/fr/gouv/vitamui/archives/search/common/dto/MultiJsonPatchDtoTest.java
  api/api-archive-search/archive-search-commons/src/test/java/fr/gouv/vitamui/archives/search/common/dto/OperationIdDtoTest.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClientFactory.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveUnitClientImpl.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/config/ApiArchiveServerConfig.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchiveUnitController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchiveUnitServiceImpl.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClientFactory.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveUnitClientImpl.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/config/ConverterConfig.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveUnitController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveUnitServiceImpl.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/config/ArchiveSearchContextConfiguration.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchiveUnitController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchiveUnitServiceImpl.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/SecurityContextService.java
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/archive-unit.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/json-patch.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
Labels: enhancement, javascript, java, VAS

#1634 Story #11852 : Clean code: remove unused and insecure thymleaf dependecies
  pom.xml
Labels: dependencies, small, VAS, clean Code

#1642 Story #12351: handle mapping of string size and data type
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/SchemaElementCreateDto.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/model/DataType.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverter.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/schema/SchemaModelToSchemaElementDtoConverterTest.java
  ui/ui-frontend-common/src/app/modules/object-viewer/models/schema-element.model.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
Labels: VAS

#1644 Story #11851 clean code dependencies
  ui/ui-frontend-common/README.md
  ui/ui-frontend-common/angular.json
  ui/ui-frontend-common/e2e/protractor.conf.js
  ui/ui-frontend-common/e2e/src/app.e2e-spec.ts
  ui/ui-frontend-common/e2e/src/app.po.ts
  ui/ui-frontend-common/e2e/tsconfig.json
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend-common/package.json
  ui/ui-frontend-common/src/app/modules/vitamui-http-interceptor.ts
Labels: javascript, VAS, clean Code

#1629 Story #12338: Upgrade consul from 1.12.9 to 1.17.3
  deployment/roles/consul/vars/main.yml
Labels: OPS REVIEW

#1648 Bug #12370: keep automaticIngest when converting DTOs
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
  api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/ProjectInternalServiceTest.java
  api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverterTest.java
Labels: bug, java, small, VAS

#1645 Story #12072: ARK search for GOT
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
  api/api-archive-search/archive-search-external-client/src/main/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClient.java
  api/api-archive-search/archive-search-external-client/src/test/java/fr/gouv/vitamui/archives/search/external/client/ArchiveSearchExternalRestClientTest.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/service/ArchivesSearchExternalService.java
  api/api-archive-search/archive-search-external/src/test/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalControllerTest.java
  api/api-archive-search/archive-search-internal-client/src/main/java/fr/gouv/archive/internal/client/ArchiveInternalRestClient.java
  api/api-archive-search/archive-search-internal-client/src/test/java/fr/gouv/archive/internal/client/ArchiveInternalRestClientTest.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalController.java
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalServiceTest.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/ark/ark_id_purged_object.json
  api/api-archive-search/archive-search-internal/src/test/resources/data/ark/object_with_ark_id.json
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/access/PersistentIdentifierService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/PurgedPersistentIdentifierDto.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/dto/VersionsDto.java
  commons/commons-vitam/src/test/java/fr/gouv/vitamui/commons/vitam/api/access/PersistentIdentifierServiceTest.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/rest/ArchivesSearchController.java
  ui/ui-archive-search/src/main/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchService.java
  ui/ui-archive-search/src/test/java/fr/gouv/vitamui/archives/search/service/ArchivesSearchServiceTest.java
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/persistent-identifier-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/persistent-identifier-search.module.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/purged-persistent-identifier-modal/purged-persistent-identifier-modal.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/purged-persistent-identifier-modal/purged-persistent-identifier-modal.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/persistent-identifier-api.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/persistent-identifier-response-dto.interface.ts
Labels: enhancement, javascript, java, VAS

#1650 Story #12067: Support Debian 12
  cots/vitamui-logstash/Makefile
  cots/vitamui-logstash/pom.xml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
  pom.xml
  ui/ui-identity/pom.xml
Labels: OPS REVIEW

#1652 Story #12395: Update configuration of VitamUI's logs.
  deployment/environments/group_vars/all/jvm_opts.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/playbooks/pki/dev/certs/referential-external/referential-external.crt
  deployment/playbooks/pki/dev/certs/referential-external/referential-external.jks
  deployment/playbooks/pki/dev/certs/referential-external/referential-external.key
  deployment/playbooks/pki/dev/certs/referential-external/referential-external.pem
  deployment/playbooks/pki/dev/certs/referential-external/truststore.jks
  deployment/playbooks/pki/dev/certs/referential-internal/referential-internal.crt
  deployment/playbooks/pki/dev/certs/referential-internal/referential-internal.jks
  deployment/playbooks/pki/dev/certs/referential-internal/referential-internal.key
  deployment/playbooks/pki/dev/certs/referential-internal/referential-internal.pem
  deployment/playbooks/pki/dev/certs/referential-internal/truststore.jks
  deployment/playbooks/pki/dev/certs/ui-referential/truststore.jks
  deployment/playbooks/pki/dev/certs/ui-referential/ui-referential.crt
  deployment/playbooks/pki/dev/certs/ui-referential/ui-referential.jks
  deployment/playbooks/pki/dev/certs/ui-referential/ui-referential.key
  deployment/playbooks/pki/dev/certs/ui-referential/ui-referential.pem
  deployment/playbooks/templates/vitamui/conf/referential-external/logback.xml.j2
  deployment/playbooks/templates/vitamui/conf/referential-external/sysconfig/java_opts.j2
  deployment/playbooks/templates/vitamui/conf/referential-internal/access-external-client.conf.j2
  deployment/playbooks/templates/vitamui/conf/referential-internal/ingest-external-client.conf.j2
  deployment/playbooks/templates/vitamui/conf/referential-internal/logback.xml.j2
  deployment/playbooks/templates/vitamui/conf/referential-internal/sysconfig/java_opts.j2
  deployment/playbooks/templates/vitamui/conf/ui-referential/logback.xml.j2
  deployment/playbooks/templates/vitamui/conf/ui-referential/sysconfig/java_opts.j2
  deployment/roles/logstash/templates/jvm.options.j2
  deployment/roles/logstash/templates/log4j2.properties.j2
  deployment/roles/vitamui/defaults/main.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/logback.xml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/roles/vitamui/templates/ui-archive-search/application.yml.j2
  deployment/roles/vitamui/templates/ui-collect/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity-admin/application.yml.j2
  deployment/roles/vitamui/templates/ui-identity/application.yml.j2
  deployment/roles/vitamui/templates/ui-ingest/application.yml.j2
  deployment/roles/vitamui/templates/ui-pastis/application.yml.j2
  deployment/roles/vitamui/templates/ui-portal/application.yml.j2
  deployment/roles/vitamui/templates/ui-referential/application.yml.j2
Labels: OPS REVIEW

#1657 Story#12138: add vitamui labels for importing schema
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: enhancement, small, VAS
