Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-04, with the labels that each got.

#1731 Bugs #12627: revert recharting PR on this part of the code
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
Labels: bug

#1654 Story #11919 : add forgotten settings to manage master/slave for referentials
  api/api-iam/iam-external/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
Labels: enhancement, small, VAS, OPS REVIEW

#1711 Bugs #12595: fix non working removal of default search filters
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug, small

#1686 Story #12555: Re-enable unit tests in CI
  Jenkinsfile
  ui/ui-frontend-common/karma.conf.js
  ui/ui-frontend-common/package-lock.json
  ui/ui-frontend-common/package.json
  ui/ui-frontend/angular.json
  ui/ui-frontend/karma.conf.js
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/pom.xml
  ui/ui-frontend/projects/archive-search/karma.conf.ci.js
  ui/ui-frontend/projects/collect/karma.conf.ci.js
  ui/ui-frontend/projects/demo/karma.conf.ci.js
  ui/ui-frontend/projects/identity/karma.conf.ci.js
  ui/ui-frontend/projects/ingest/karma.conf.ci.js
  ui/ui-frontend/projects/pastis/karma.conf.ci.js
  ui/ui-frontend/projects/portal/karma.conf.ci.js
  ui/ui-frontend/projects/referential/karma.conf.ci.js
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-preview/securisation-check-tab/securisation-check-tab.component.spec.ts
  ui/ui-frontend/projects/starter-kit/karma.conf.ci.js
  ui/ui-frontend/projects/vitamui-library/karma.conf.js
  ui/ui-frontend/projects/vitamui-library/src/lib/components/confirm-action/confirm-action.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.spec.ts
Labels: bug, VAS, clean Code

#1725 Story #12443: Update merge_index for VitamUI
  deployment/ansible-vitamui-extra/vitamui_extra.yml
  deployment/environments/group_vars/all/reverse_proxy_conf.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/environments/vitamui_extra_vars.yml
  deployment/pki/scripts/lib/certs.sh
  deployment/roles/merge_index_apache/handlers/main.yml
  deployment/roles/merge_index_apache/tasks/main.yml
  deployment/roles/merge_index_apache/templates/index_debug.html.j2
  deployment/roles/merge_index_apache/templates/index_links.html.j2
  deployment/roles/merge_index_apache/templates/proxy_pass.conf.j2
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/reverse/tasks/main.yml
  deployment/roles/reverse/templates/apache/httpd_config
  deployment/roles/reverse/templates/apache/page/index_debug.html.j2
  deployment/roles/reverse/templates/apache/page/index_links.html.j2
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  docs/fr/installation/sections/procedure.md
  docs/fr/migration/upgrade_v7_1.md
Labels: OPS REVIEW

#1733 Bug #12596: remove STATIC_ATTACHEMENT from front
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#1738 Story #12345: Ultimate COTS upgrade
  deployment/ansible-vitamui-migration/migration_mongodb_70.yml
  deployment/roles/consul/vars/main.yml
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW

#1730 bug #12124: statement of probative value on signed documents
  ui/ui-frontend-common/src/app/modules/models/nodes/filing-holding-scheme.handler.spec.ts
  ui/ui-frontend-common/src/app/modules/models/units/unit.interface.ts
  ui/ui-frontend-common/src/sass/material/_modal.scss
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
  ui/ui-frontend/projects/referential/src/app/core/api/archive-api.service.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.scss
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-create/probative-value-create.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
  ui/ui-frontend/proxy-gateway.conf.js
Labels: bug, small

#1729 Story #12273: Migration to API Gateway
  deployment/ansible-vitamui-migration/migration_gateway.yml
  deployment/ansible-vitamui/app_api_gateway.yml
  deployment/ansible-vitamui/app_archive_search.yml
  deployment/ansible-vitamui/app_collect.yml
  deployment/ansible-vitamui/app_ingest.yml
  deployment/ansible-vitamui/app_pastis.yml
  deployment/ansible-vitamui/app_referential.yml
  deployment/ansible-vitamui/vitamui.yml
  deployment/ansible-vitamui/vitamui_apps.yml
  deployment/environments/hosts-ui.example
  deployment/roles/nginx_webapp/tasks/install.yml
  deployment/roles/nginx_webapp/tasks/uninstall.yml
  deployment/roles/nginx_webapp/templates/frontend/config.json.j2
  deployment/roles/reinit_services_contexts_and_certs/defaults/main.yml
  deployment/roles/reinit_services_contexts_and_certs/tasks/main.yml
  deployment/roles/reinit_services_contexts_and_certs/templates/security.js.j2
  deployment/roles/reverse/templates/nginx/conf.d/upstream.j2
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
  deployment/scripts/mongod/1.0.0/04_cas_services_ref.js.j2
  deployment/scripts/mongod/1.0.0/209_cas_services_ref.js.j2
  deployment/scripts/mongod/1.0.0/213_cas_services_ref.js.j2
  deployment/scripts/mongod/1.0.0/218_cas_services_archive_search_ref.js.j2
  deployment/scripts/mongod/1.0.0/220_cas_services_pastis_ref.js.j2
  deployment/scripts/mongod/2.0.0/015_RABB_fix_missing_collection_ref.js
  deployment/scripts/mongod/6.rc.0/03_update_cas_services_with_collect_application.js.j2
  deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
  deployment/scripts/mongod/v7.1/004_TRV-400_enable_oidc_code_grant_type_on_identity_service_ref.js.j2
  deployment/scripts/mongod/v7.1/037_enable_oidc_code_grant_type_on_referential_service_ref.js.j2
  deployment/scripts/mongod/v7.1/039_enable_oidc_code_grant_type_on_archive_search_service_ref.js.j2
  deployment/scripts/mongod/v7.1/040_enable_oidc_code_grant_type_on_pastis_service_ref.js.j2
  deployment/scripts/mongod/v7.1/041_enable_oidc_code_grant_type_on_ingest_service_ref.js.j2
  deployment/scripts/mongod/v7.1/042_enable_oidc_code_grant_type_on_collect_service_ref.js.j2
  docs/fr/migration/upgrade_v7_1.md
Labels: documentation, OPS REVIEW

#1741 Bug #12677: Fix MongoDB migration's scripts for VitamUI
  deployment/roles/assets_copy/defaults/main.yml
  deployment/roles/nginx_webapp/tasks/uninstall.yml
  deployment/scripts/mongod/2.0.0/014_REC-672_fix_portal_evaluation_order_ref.js
  deployment/scripts/mongod/v7.1/003_TRV-399_enable_oidc_code_grant_type_on_portal_service_ref.js.j2
  deployment/scripts/mongod/v7.1/004_TRV-400_enable_oidc_code_grant_type_on_identity_service_ref.js.j2
  deployment/scripts/mongod/v7.1/037_enable_oidc_code_grant_type_on_referential_service_ref.js.j2
Labels: VAS, OPS REVIEW, clean Code

#1743 Bugs #12676: fix ordering by deposit identifier
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
Labels: bug, small

#1742 Story#12363 : bump jackson to 2.17.0 to fix version conflict on cas s…
  cas/cas-server/pom.xml
Labels: dependencies, small, VAS

#1746 Bugs #12682: change label
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#1737 Bug #12656: disable form fields even when they're empty
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, javascript, VAS

#1751 Bugs #12693: avoid NPE on CSV export when there is no description
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
Labels: bug, small

#1739 Fix #12660: display internationalized md descriptives (Title_ & Description_)
  ui/ui-frontend-common/src/app/modules/archive/archive-unit-template.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.html
  ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/object-viewer.component.spec.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/display-object-helper.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-strategy-display-object.service.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, VAS

#1750 Bugs #12686: missing confirmation on close, tab change and on item change for MD
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug

#1758 Bug #12711: Fix role migration for collect_app.
  deployment/scripts/mongod/v7.1/57_migration_collect_profiles_roles.js.j2
Labels: OPS REVIEW

#1757 Bugs #12703: call expects id, not identifier
  ui/ui-frontend/projects/pastis/src/app/core/services/archival-profile-unit-api.service.ts
Labels: bug, small

#1761 Bugs #12714: operationId and actionId parameters are mixed up
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/LogbookManagementOperationExternalController.java
Labels: bug, small

#1763 Bug #12712: Fix password initialization on user creation
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: bug, small, VAS

#1755 Story #12363: Update VitamUI dependencies
  api/api-archive-search/archive-search-external/pom.xml
  api/api-pastis/pastis-commons/pom.xml
  api/api-pastis/pastis-external/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal/pom.xml
  cas/cas-server/pom.xml
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/GeneralTerminateSessionActionTest.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/identity/ServerIdentityConfiguration.java
  commons/commons-mongo/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  docs/fr/architecture/_static/css/theme.css
  docs/fr/exploitation/_static/css/theme.css
  docs/fr/installation/_static/css/theme.css
  docs/fr/migration/_static/css/theme.css
  docs/scripts/maven.sh
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/front/pages/CasPage.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/front/pages/PortalPage.java
  integration-tests/src/test/java/fr/gouv/vitamui/cucumber/front/pages/PreLoginPage.java
  pom.xml
  tools/docker/centos/Dockerfile
  tools/docker/vitamui-base/Dockerfile
Labels: enhancement, dependencies, VAS

#1736 Story #12560: multi domain organisation - CAS improvement
  cas/cas-server/README.md
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/InitPasswordConstraintsConfiguration.java
  cas/cas-server/src/main/resources/application.properties
  cas/cas-server/src/main/resources/overriden_messages.properties
  cas/cas-server/src/main/resources/overriden_messages_en.properties
  cas/cas-server/src/main/resources/overriden_messages_fr.properties
  cas/cas-server/src/main/resources/static/js/cas.js
  cas/cas-server/src/main/resources/static/js/password-checks.js
  cas/cas-server/src/main/resources/templates/casAccountBadConfigurationView.html
  cas/cas-server/src/main/resources/templates/casSmsCodeExpiredView.html
  cas/cas-server/src/main/resources/templates/casSmsMissingPhoneView.html
  cas/cas-server/src/main/resources/templates/customerForm.html
  cas/cas-server/src/main/resources/templates/delegated-authn/casDelegatedAuthnStopWebflow.html
  cas/cas-server/src/main/resources/templates/emailForm.html
  cas/cas-server/src/main/resources/templates/error.html
  cas/cas-server/src/main/resources/templates/error/401.html
  cas/cas-server/src/main/resources/templates/error/403.html
  cas/cas-server/src/main/resources/templates/error/404.html
  cas/cas-server/src/main/resources/templates/error/405.html
  cas/cas-server/src/main/resources/templates/error/423.html
  cas/cas-server/src/main/resources/templates/error/casServiceErrorView.html
  cas/cas-server/src/main/resources/templates/fragments/pwdupdateform.html
  cas/cas-server/src/main/resources/templates/layout.html
  cas/cas-server/src/main/resources/templates/login-error/casAccountDisabledView.html
  cas/cas-server/src/main/resources/templates/login-error/casAccountLockedView.html
  cas/cas-server/src/main/resources/templates/login-error/casAuthenticationBlockedView.html
  cas/cas-server/src/main/resources/templates/login-error/casExpiredPassView.html
  cas/cas-server/src/main/resources/templates/login-error/casMustChangePassView.html
  cas/cas-server/src/main/resources/templates/login/casGenericSuccessView.html
  cas/cas-server/src/main/resources/templates/logout/casLogoutView.html
  cas/cas-server/src/main/resources/templates/logout/casPropagateLogoutView.html
  cas/cas-server/src/main/resources/templates/password-reset/casPasswordUpdateSuccessView.html
  cas/cas-server/src/main/resources/templates/password-reset/casResetPasswordErrorView.html
  cas/cas-server/src/main/resources/templates/password-reset/casResetPasswordSendInstructionsView.html
  cas/cas-server/src/main/resources/templates/password-reset/casResetPasswordSentInstructionsView.html
  cas/cas-server/src/main/resources/templates/passwordForm.html
  cas/cas-server/src/main/resources/templates/simple-mfa/casSimpleMfaLoginView.html
  commons/commons-security/src/main/java/fr/gouv/vitamui/commons/security/client/config/password/PasswordConfiguration.java
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  docs/fr/exploitation/sections/procedure.md
  ui/ui-frontend/projects/starter-kit/src/environments/environment.ts
Labels: small, OPS REVIEW

#1752 bugs #12680 fix(persistent-id): wrong object version chose
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.ts
Labels: bug, javascript, small, VAS

#1766 bugs #12702 fix(archive-unit): fields order
  ui/ui-frontend-common/src/app/modules/archive/archive-unit-fields.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small, VAS

#1767 bugs #12704 (translation): update messages when deleting file format
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, javascript, small, VAS

#1764 bugs #12683 fix(archive-unit-editor): validation popin when remove consistent data bloc
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small, VAS

#1749 bugs #12679 fix(archive-unit): other metadata in display and edit mode
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-fields.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-template.service.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-template.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit.module.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-count/archive-unit-count.component.html
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-count/archive-unit-count.component.scss
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-count/archive-unit-count.component.spec.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-count/archive-unit-count.component.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.html
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.scss
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.service.spec.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.service.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/components/editor-banner/editor-banner.component.html
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/components/editor-banner/editor-banner.component.scss
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/components/editor-banner/editor-banner.component.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.component.html
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.component.scss
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.component.spec.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.component.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.service.spec.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.service.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/physical-archive-viewer/physical-archive-viewer.component.html
  ui/ui-frontend-common/src/app/modules/archive-unit/components/physical-archive-viewer/physical-archive-viewer.component.scss
  ui/ui-frontend-common/src/app/modules/archive-unit/components/physical-archive-viewer/physical-archive-viewer.component.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/index.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/models/archive-unit.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/models/json-patch.ts
  ui/ui-frontend-common/src/app/modules/archive/components/archive-unit-editor/archive-unit-editor.service.ts
  ui/ui-frontend-common/src/app/modules/components/accordion/accordion.component.html
  ui/ui-frontend-common/src/app/modules/components/accordion/accordion.component.scss
  ui/ui-frontend-common/src/app/modules/components/datepicker/datepicker.component.ts
  ui/ui-frontend-common/src/app/modules/index.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/schema.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/schema.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.html
  ui/ui-frontend-common/src/app/modules/object-viewer/components/list/list.component.html
  ui/ui-frontend-common/src/app/modules/object-viewer/components/primitive/primitive.component.html
  ui/ui-frontend-common/src/app/modules/object-viewer/models/schema-element.model.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/object-viewer.component.spec.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/display-rule-helper.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-strategy-display-object.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-strategy-display-object.service.ts
  ui/ui-frontend-common/src/app/modules/schema/mock-schema.service.ts
  ui/ui-frontend-common/src/app/modules/services/leaves-tree.service.ts
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/models/json-patch.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
Labels: bug, javascript, VAS

#1754 Bug #12710: Various OPS fixes while testing
  deployment/ansible-vitamui-migration/migration_mongodb_60.yml
  docs/fr/migration/upgrade_v7_1.md
  ui/ui-frontend/projects/identity/src/app/user/user-create/user-create.component.html
Labels: documentation, OPS REVIEW

#1769 Story #12560: change var cas_background
  deployment/environments/group_vars/all/vitamui_vars.yml
Labels: enhancement, small, VAS, OPS REVIEW

#1772 Bugs #12684: correctly reset form when we change the access contract
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-usage-and-services-tab/access-contract-usage-and-services-tab.component.ts
Labels: bug, small

#1770 bug #12554 fix : display bug on popups
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
Labels: bug, javascript, small, VAS

#1771 Story #12345: Upgrade MongoDB from version 7.0.7 to 7.0.8
  deployment/ansible-vitamui-migration/migration_mongodb_70.yml
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW

#1773 Bugs #12731: hide DYNAMIC_ATTACHEMENT_ folder from collect module's archives
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#1775 Bug #12649 : update ontology deletion message
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.service.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: small

#1778 Story #12734: Restrict port binding to the appropriate interface.
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
Labels: Security, OPS REVIEW

#1740 Story #12664: Remove useless cots packages
  Jenkinsfile
  cots/pom.xml
  cots/vitamui-mongod/Makefile
  cots/vitamui-mongod/pom.xml
  cots/vitamui-mongod/templates/after-install.sh
  cots/vitamui-mongod/templates/before-remove.sh
  cots/vitamui-mongod/templates/logrotated.mongod
  cots/vitamui-mongod/templates/mongod.conf.default
  cots/vitamui-nginx/Makefile
  cots/vitamui-nginx/pom.xml
  cots/vitamui-nginx/templates/after-install.sh
  cots/vitamui-nginx/templates/logrotated.vitamui-nginx
  cots/vitamui-nginx/templates/nginx.conf.default
  cots/vitamui-nginx/templates/vitamui-nginx.service
  deployment/roles/mongo/handlers/main.yml
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/vitamui-mongod.service.j2
  deployment/roles/mongo/vars/main.yml
  deployment/roles/mongo_configure/tasks/main.yml
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
  deployment/roles/users/defaults/main.yml
  deployment/roles/users/tasks/main.yml
  docs/fr/architecture/sections/implementation.md
Labels: OPS REVIEW

#1783 Bug #12749: Remove useless vitamuidb group and users from package installation.
  tools/packaging/templates/before-install.sh
Labels: bug, small, VAS, OPS REVIEW

#1780 Story #12738: Deliver a dedicated nginx role to allows installation of reverse and frontend apps separately
  deployment/ansible-vitamui/frontend_apps.yml
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/environments/hosts-ui.example
  deployment/roles/nginx/defaults/main.yml
  deployment/roles/nginx/handlers/main.yml
  deployment/roles/nginx/tasks/main.yml
  deployment/roles/nginx/templates/nginx.conf.j2
  deployment/roles/nginx/templates/proxy_params.j2
  deployment/roles/nginx_webapp/defaults/main.yml
  deployment/roles/nginx_webapp/tasks/install.yml
  deployment/roles/nginx_webapp/tasks/main.yml
  deployment/roles/nginx_webapp/tasks/uninstall.yml
  deployment/roles/nginx_webapp/templates/frontend/upstream_gw.j2
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/reverse/tasks/nginx/configure_nginx.yml
  deployment/roles/reverse/tasks/nginx/configure_vitamui_vhost.yml
  deployment/roles/reverse/tasks/nginx/nginx.yml
  deployment/roles/reverse/tasks/nginx/prerequisites.yml
  deployment/roles/reverse/templates/nginx/conf.d/upstream.j2
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/reverse/templates/nginx/ssl/ssl.conf.j2
Labels: OPS REVIEW

#1785 Fix #12674 for dev environment
  dev-deployment/environments/certs/client-external/clients/ui-archive-search/ui-archive-search.pem
  dev-deployment/environments/certs/client-external/clients/ui-collect/ui-collect.pem
  dev-deployment/environments/certs/client-external/clients/ui-identity-admin/ui-identity-admin.pem
  dev-deployment/environments/certs/client-external/clients/ui-identity/ui-identity.pem
  dev-deployment/environments/certs/client-external/clients/ui-ingest/ui-ingest.pem
  dev-deployment/environments/certs/client-external/clients/ui-pastis/ui-pastis.pem
  dev-deployment/environments/certs/client-external/clients/ui-portal/ui-portal.pem
  dev-deployment/environments/certs/client-external/clients/ui-referential/ui-referential.pem
Labels: bug

#1791 Fix #12513 recharting regression: re-add missing icons
  ui/ui-frontend-common/icomoon-selection.json
  ui/ui-frontend-common/import-icon.sh
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/starter-kit/src/app/components/icons/icons.component.html
  ui/ui-frontend/projects/starter-kit/src/app/components/icons/icons.component.scss
  ui/ui-frontend/projects/starter-kit/src/app/components/icons/icons.component.ts
  ui/ui-frontend/projects/starter-kit/src/app/components/icons/icons.module.ts
  ui/ui-frontend/projects/starter-kit/src/assets/i18n/en.json
  ui/ui-frontend/projects/starter-kit/src/assets/i18n/fr.json
Labels: bug, javascript, VAS, clean Code

#1789 CP 7.0 - Bug #12596 & Bug #12731
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: Cherry-Pick

#1744 Bugs #12673: allow setting a date to null
  ui/ui-frontend-common/src/app/modules/components/datepicker/datepicker.component.ts
  ui/ui-frontend-common/src/app/modules/index.ts
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/projects/starter-kit/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/starter-kit/src/app/components/inputs/inputs.component.ts
Labels: bug, small

#1787 Story #12758: Restrict webapps to only allow reverseproxy.
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
Labels: small, VAS, Security, OPS REVIEW

#1735 Story #12517: Fix and improvements for Filebeat configurations
  deployment/ansible-vitamui/filebeat.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/tasks/add_modules.yml
  deployment/roles/filebeat/templates/filebeat.yml.j2
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/apache.yml.j2
  deployment/roles/filebeat/templates/modules/logstash.yml.j2
  deployment/roles/filebeat/templates/modules/mongodb.yml
  deployment/roles/filebeat/templates/modules/mongodb.yml.j2
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
  deployment/roles/filebeat/templates/modules/system.yml.j2
  deployment/roles/logstash/templates/conf.d/filebeat-to-logstash.conf.j2
Labels: OPS REVIEW

#1782 bugs #12733 feat: add required validators
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/models/edit-object.model.ts
  ui/ui-frontend-common/src/app/modules/object-editor/object-editor.module.ts
  ui/ui-frontend-common/src/app/modules/object-editor/required.pipe.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/schema.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/models/template.model.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
Labels: bug, enhancement, javascript, VAS

#1794 Story #12560: errors on subrogation connection
  cas/cas-server/src/main/resources/templates/emailForm.html
Labels: bug, small

#1797 Bugs #11662: Fix apigw mapping and missing header on units search
  api/api-gateway/src/main/resources/application-dev.yml
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  ui/ui-frontend/proxy-gateway.conf.js
Labels: bug

#1798 Bugs #12769: avoid console exception when ingest is undefined
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-information-tab/ingest-information-tab.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-preview.component.html
Labels: bug

#1803 Bug #12770: Fix Debian 12 deployment with wrong conditionnal on version.
  deployment/roles/docker/tasks/Debian.yml
Labels: bug, small, OPS REVIEW

#1796 Bug #12743 : Not the right component for display and MD shift
  ui/ui-frontend-common/src/app/modules/object-viewer/services/schema-element-to-display-rule.service.ts
Labels: bug

#1807 Bugs #12778: change persistent identifier label
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: bug, small

#1802 Bugs #11662: add checkSecureParameter check that was removed by error
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
Labels: bug, small

#1806 Story #11619: set logo-large.svg
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/resources/application.properties
  cas/cas-server/src/main/resources/static/images/logo-large.svg
  cas/cas-server/src/main/resources/static/images/vitamui-logo-large.png
  cas/cas-server/src/main/resources/templates/customerForm.html
  cas/cas-server/src/main/resources/templates/layout.html
  cas/cas-server/src/main/resources/templates/login/casGenericSuccessView.html
  deployment/roles/assets_copy/files/logo-large.svg
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  ui/ui-frontend/projects/referential/src/assets/vitamui-logo-large.png
Labels: small, OPS REVIEW

#1799 Fix #12742: handle non-string values in repeatable input
  ui/ui-frontend-common/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small

#1795 Story #11852 clean code: speed-up CI build by preventing SWAP
  ui/ui-frontend/package.json
Labels: VAS, clean Code

#1808 bugs #12739 fix(datepicker): truncate by default time part
  ui/ui-frontend-common/src/app/modules/components/datepicker/datepicker.component.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/components/primitive/primitive.component.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small, VAS

#1805 Story #12777: Switch back certificates configuration to permit webapps in https
  deployment/pki/scripts/generate_certs.sh
  deployment/roles/nginx_webapp/tasks/install.yml
  deployment/roles/nginx_webapp/tasks/uninstall.yml
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
  deployment/roles/nginx_webapp/templates/ssl-ui.conf.j2
  deployment/roles/reinit_security_certificates/templates/security.populate_certificates.js.j2
  deployment/roles/reverse/tasks/nginx/nginx.yml
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/scripts/mongod/v7.1/000_security.populate_certificates.js.j2
  dev-deployment/environments/certs/client-external/clients/ui-archive-search/ui-archive-search.pem
  dev-deployment/environments/certs/client-external/clients/ui-ingest/ui-ingest.pem
  dev-deployment/environments/certs/client-external/clients/ui-referential/ui-referential.pem
  dev-deployment/environments/certs/server/hosts/localhost/ui-collect.pem
  dev-deployment/environments/certs/server/hosts/localhost/ui-identity-admin.pem
  dev-deployment/environments/certs/server/hosts/localhost/ui-identity.pem
  dev-deployment/environments/certs/server/hosts/localhost/ui-pastis.pem
  dev-deployment/environments/certs/server/hosts/localhost/ui-portal.pem
Labels: Security, OPS REVIEW

#1812 Bugs #12772: report should be downloadable for MASS_UPDATE operations
  api/api-gateway/src/main/resources/application-dev.yml
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
Labels: bug, small

#1793 Story #11851 clean code: add coherence check for icomoon icons
  Jenkinsfile
  cas/cas-server/src/main/resources/static/icons/fonts/vitamui-icon.eot
  cas/cas-server/src/main/resources/static/icons/fonts/vitamui-icon.svg
  cas/cas-server/src/main/resources/static/icons/fonts/vitamui-icon.ttf
  cas/cas-server/src/main/resources/static/icons/fonts/vitamui-icon.woff
  cas/cas-server/src/main/resources/static/icons/vitamui-icons.css
  tools/check_icomoon.sh
  ui/ui-frontend-common/icomoon-selection.json
  ui/ui-frontend-common/import-icon.sh
  ui/ui-frontend-common/src/app/modules/components/user-alerts/user-alerts-card/user-alerts-card.component.html
  ui/ui-frontend-common/src/app/modules/vitamui-icons.enum.ts
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.eot
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.svg
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.ttf
  ui/ui-frontend-common/src/sass/icons/fonts/vitamui-icon.woff
  ui/ui-frontend-common/src/sass/icons/vitamui-icons.css
  ui/ui-frontend/README.md
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-list/ingest-list.component.html
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.scss
  ui/ui-frontend/projects/referential/src/app/rule/rule-list/rule-list.component.ts
Labels: javascript, VAS, clean Code

#1801 CP 6.0 - Bugs #11662: Fix missing header on units search
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
Labels: bug, small, Cherry-Pick

#1800 CP 7.0 - Bugs #11662: Fix missing header on units search
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/rest/UnitInternalController.java
Labels: bug, small, Cherry-Pick

#1815 Bugs #12681: ensure that no accordion is grayed out
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, small

#1816 bugs #12780 fix: field ranking and layout
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-fields.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-template.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small, VAS

#1817 item #12771: display field if has boolean type
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/type.service.ts
Labels: bug, small, VAS

#1821 Bug #12770: Install proper jdk and limit to mandatory nodes.
  deployment/ansible-vitamui/pre_install.yml
  deployment/environments/vitamui_extra_vars.yml
  deployment/roles/checks/tasks/check_java.yml
  deployment/roles/checks/tasks/main.yml
  deployment/roles/normalize/tasks/check_java.yml
  deployment/roles/normalize/tasks/main.yml
  deployment/roles/normalize/tasks/vitamui.yml
Labels: OPS REVIEW

#1820 bugs #12786 fix: null data described as object array in schema
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small, VAS

#1819 Story #12516: hide STATIC_ATTACHMENT
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, javascript, small

#1825 bugs #12784 fix(metadata): multiple validation popin
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend/package-lock.json
Labels: bug, javascript, small, VAS

#1828 bugs #12784 fix: add missing 'e' to predicat.
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
Labels: bug, javascript, small, VAS

#1829 Story #11851 Clean Code: make starter-kit standalone + add forRoot in frontend-common
  ui/ui-frontend-common/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/archive-search/src/app/app.module.ts
  ui/ui-frontend/projects/collect/src/app/app.module.ts
  ui/ui-frontend/projects/demo/src/app/app.module.ts
  ui/ui-frontend/projects/identity/src/app/app.module.ts
  ui/ui-frontend/projects/ingest/src/app/app.module.ts
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
  ui/ui-frontend/projects/portal/src/app/app.module.ts
  ui/ui-frontend/projects/referential/src/app/app.module.ts
  ui/ui-frontend/projects/starter-kit/mock-api/_db.js
  ui/ui-frontend/projects/starter-kit/mock-api/config.json
  ui/ui-frontend/projects/starter-kit/mock-api/mock/applications.js
  ui/ui-frontend/projects/starter-kit/mock-api/mock/asset.js
  ui/ui-frontend/projects/starter-kit/mock-api/mock/conf.js
  ui/ui-frontend/projects/starter-kit/mock-api/mock/me.js
  ui/ui-frontend/projects/starter-kit/mock-api/routes.json
  ui/ui-frontend/projects/starter-kit/src/app/app-routing.module.ts
  ui/ui-frontend/projects/starter-kit/src/app/app.module.ts
  ui/ui-frontend/projects/starter-kit/src/assets/config-dev.json
  ui/ui-frontend/projects/starter-kit/src/assets/logo_USER.png
  ui/ui-frontend/projects/starter-kit/src/environments/environment.prod.ts
  ui/ui-frontend/projects/starter-kit/src/sass/login.scss
  ui/ui-frontend/projects/starter-kit/src/sass/material-custom.scss
  ui/ui-frontend/projects/starter-kit/src/sass/styles.scss
Labels: javascript, VAS, clean Code

#1786 Bug #12757: Fix reverse apache deployment.
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/reverse/files/apache/page/css/app.css
  deployment/roles/reverse/files/apache/page/css/bootstrap.min.css
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.eot
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.ijmap
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.png
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.svg
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.ttf
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.woff
  deployment/roles/reverse/files/apache/page/css/fonts/MaterialIcons-Regular.woff2
  deployment/roles/reverse/files/apache/page/css/fonts/Roboto-Regular.ttf
  deployment/roles/reverse/files/apache/page/css/material-icons.css
  deployment/roles/reverse/files/apache/page/css/styles.css
  deployment/roles/reverse/files/apache/page/images/logo.png
  deployment/roles/reverse/files/apache/page/images/logoNormal.png
  deployment/roles/reverse/files/apache/page/js/bootstrap.min.js
  deployment/roles/reverse/files/apache/page/js/jquery.min.js
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/reverse/templates/apache/httpd_config
  deployment/roles/reverse/templates/apache/page/css/app.css
  deployment/roles/reverse/templates/apache/page/css/bootstrap.min.css
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.eot
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.ijmap
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.png
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.svg
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.ttf
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.woff
  deployment/roles/reverse/templates/apache/page/css/fonts/MaterialIcons-Regular.woff2
  deployment/roles/reverse/templates/apache/page/css/fonts/Roboto-Regular.ttf
  deployment/roles/reverse/templates/apache/page/css/material-icons.css
  deployment/roles/reverse/templates/apache/page/css/styles.css
  deployment/roles/reverse/templates/apache/page/images/logo.png
  deployment/roles/reverse/templates/apache/page/images/logoNormal.png
  deployment/roles/reverse/templates/apache/page/index.html.j2
  deployment/roles/reverse/templates/apache/page/js/bootstrap.min.js
  deployment/roles/reverse/templates/apache/page/js/jquery.min.js
  deployment/roles/reverse/templates/nginx/conf.d/vhosts.conf.j2
  deployment/roles/vitamui/defaults/main.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
Labels: OPS REVIEW

#1837 bugs #12733 fix: remove error messages
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/components/list-editor/list-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
Labels: bug, javascript, small, VAS

#1823 Story #12622: Developer doc & tools for CAS delegated authentication
  cas/cas-server/README.md
  tools/docker/external-idp-cas/Dockerfile
  tools/docker/external-idp-cas/readme.md
  tools/docker/external-idp-cas/realms/import-realm.json
  tools/docker/external-idp-cas/run-dev.sh
Labels: documentation, enhancement, VAS

#1832 Story #11851 Clean Code: speedup Jenkins build
  Jenkinsfile
  ui/ui-frontend/angular.json
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/pom.xml
Labels: VAS, clean Code
