Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-08, with the labels that each got.

#1973 Bug#13197: drop old index named idx_user_email
  deployment/scripts/mongod/v7.1/60_update_cas_create_user_email_customerid_index.js.j2
Labels: small, VAS, OPS REVIEW

#1972 CP V7.1: Bug#13197: drop old index named idx_user_email
  deployment/scripts/mongod/v7.1/60_update_cas_create_user_email_customerid_index.js.j2
Labels: bug, small, VAS, Cherry-Pick

#1954 Bug #13039: front fixes
  ui/ui-frontend/projects/pastis/src/assets/i18n-old/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n-old/fr.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/sass/_button.scss
Labels: bug

#1983 story #12885: fix bug export dip
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ExportDipInternalService.java
Labels: bug, small, VAS

#1987 Story #13140: datepicker minor fix
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
Labels: bug

#1988 Story #11854 clean code: align elevation with Figma
  ui/ui-frontend/projects/vitamui-library/src/sass/mixins/_elevation.scss
Labels: clean Code

#1986 Story #11854 clean code: improve Design System
  ui/ui-frontend/projects/design-system/src/app/app.component.html
  ui/ui-frontend/projects/design-system/src/app/app.component.scss
  ui/ui-frontend/projects/design-system/src/app/app.component.spec.ts
  ui/ui-frontend/projects/design-system/src/app/app.component.ts
  ui/ui-frontend/projects/design-system/src/app/app.module.ts
  ui/ui-frontend/projects/design-system/src/app/components/arrays/arrays.component.html
  ui/ui-frontend/projects/design-system/src/app/components/colors/colors.component.html
  ui/ui-frontend/projects/design-system/src/app/components/elevations/elevations.component.html
  ui/ui-frontend/projects/design-system/src/app/components/icons/icons.component.html
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.scss
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.ts
  ui/ui-frontend/projects/design-system/src/app/components/miscellaneous/miscellaneous.component.html
  ui/ui-frontend/projects/design-system/src/app/components/progress-bar/progress-bar.component.html
  ui/ui-frontend/projects/design-system/src/app/components/tooltip/tooltip.component.html
  ui/ui-frontend/projects/design-system/src/app/components/translation/translation.component.html
  ui/ui-frontend/projects/design-system/src/app/components/typography/typography.component.html
  ui/ui-frontend/projects/design-system/src/app/design-system/design-system.component.html
Labels: clean Code

#1991 Bug #13108: allow 'none' as a valid choice for the management contract field
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
Labels: bug, small

#1993 CP 7.1 - Bug #13108: allow 'none' as a valid choice for the management contract field
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
Labels: small, Cherry-Pick

#1992 CP 7.0 - Bug #13108: allow 'none' as a valid choice for the management contract field
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
Labels: small, Cherry-Pick

#1995 Bug #12516: STATIC_ATTACHMENT
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#1996 CP V7.1 - Bug #12516: STATIC_ATTACHMENT
  ui/ui-frontend/.gitignore
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#1997 CP V7.0 - Bug #12516: STATIC_ATTACHMENT
  ui/ui-frontend/.gitignore
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#2001 Bugs #13263: fix missing seda version in api response
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/dto/profiles/Notice.java
  api/api-pastis/pastis-commons/src/main/java/fr/gouv/vitamui/pastis/common/util/NoticeUtils.java
  api/api-pastis/pastis-external/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
Labels: bug, small

#1984 Bug #13161: deactivate controle button on send
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
Labels: bug, small

#1985 CP V7.1 - Bug #13161: deactivate controle button on send
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
Labels: bug, small, Cherry-Pick

#2004 Bugs #13218: correctly handle the disabled attribute
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
Labels: bug, small
