Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-05, with the labels that each got.

#1838 Story #12517: Various fixes for Filebeat
  deployment/roles/filebeat/templates/filebeat.yml.j2
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
  deployment/roles/filebeat/templates/modules/apache.yml.j2
  deployment/roles/filebeat/templates/modules/logstash.yml.j2
  deployment/roles/filebeat/templates/modules/mongodb.yml.j2
  deployment/roles/filebeat/templates/modules/nginx.yml.j2
  deployment/roles/filebeat/templates/modules/system.yml.j2
  deployment/roles/logstash/templates/filebeat-to-logstash.conf.j2
Labels: OPS REVIEW

#1842 Story #12710: Describe new Ansible parameters in DMV.
  docs/fr/migration/upgrade_v7_1.md
Labels: documentation, OPS REVIEW

#1846 Bugs #12815: fix missing words
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#1847 Bugs #12778: uppercase title
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.html
Labels: bug, small

#1851 Bug #12825: Update consul log_level to ERROR.
  deployment/environments/group_vars/all/consul_vars.yml
  deployment/roles/consul/templates/consul.json.j2
  deployment/roles/filebeat/defaults/main.yml
Labels: bug, small, VAS, OPS REVIEW

#1852 Bug #12827: Fix cas access-log buffering
  cas/cas-server/src/main/resources/application.properties
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
Labels: OPS REVIEW

#1841 Story #12530: change fields FileFormat create dialog
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/FileFormatExternalService.java
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-create/file-format-create.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: VAS, DO_NOT_MERGE

#1858 Bug #12827: Fix CAS accesslog pattern
  cas/cas-server/src/main/resources/application.properties
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
Labels: OPS REVIEW

#1857 bugs #12733 fix(collect): disable metadata form validation
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
Labels: bug, javascript, small, VAS

#1853 Bug #12710: Fixes for upgrading VitamUI
  deployment/ansible-vitamui-migration/migration_gateway.yml
  deployment/ansible-vitamui-migration/migration_vitamui_71.yml
  deployment/ansible-vitamui/filebeat.yml
  deployment/ansible-vitamui/rsyslog.yml
  deployment/roles/filebeat/tasks/main.yml
  deployment/roles/filebeat/tasks/uninstall.yml
  deployment/roles/logstash/tasks/main.yml
  deployment/roles/logstash/templates/logstash.yml.j2
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
  deployment/roles/rsyslog/handlers/main.yml
  deployment/roles/rsyslog/tasks/install.yml
  deployment/roles/rsyslog/tasks/main.yml
  deployment/roles/rsyslog/tasks/uninstall.yml
  docs/fr/migration/upgrade_v7_1.md
Labels: documentation, OPS REVIEW

#1864 Bug/Vas-#12843 : fix bug on patch saml provider
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/rest/IdentityProviderInternalController.java
Labels: small, VAS, Cherry-Pick

#1854 Story #12736: text overflow in left pannel hover
  ui/ui-frontend-common/src/sass/base/_typography.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/identity/src/sass/_tooltip.scss
Labels: bug, small

#1867 Story #12736: fix prettier
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
Labels: small

#1868 Story #12736: overflow hidden
  ui/ui-frontend/projects/archive-search/src/sass/_tooltip-rules.scss
  ui/ui-frontend/projects/archive-search/src/sass/_tooltip.scss
  ui/ui-frontend/projects/collect/src/sass/_tooltip-rules.scss
  ui/ui-frontend/projects/collect/src/sass/_tooltip.scss
  ui/ui-frontend/projects/ingest/src/sass/_tooltip.scss
  ui/ui-frontend/projects/referential/src/sass/_tooltip.scss
Labels: bug, small

#1870 Story #12674: Disable former ui packaging.
  packaging/pom.xml
  ui/ui-archive-search/pom.xml
  ui/ui-collect/pom.xml
  ui/ui-identity/pom.xml
  ui/ui-ingest/pom.xml
  ui/ui-pastis/pom.xml
  ui/ui-portal/pom.xml
  ui/ui-referential/pom.xml
Labels: small, VAS, clean Code

#1845 Story #12524: add fields to external file format tab
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/FileFormatDto.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamFileFormatService.java
  ui/ui-frontend-common/testing/src/vitamui-common-test.module.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.scss
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/lib/models/file-format.ts
Labels: VAS, DO_NOT_MERGE

#1863 bug #12554 : Fixing buttons display bugs in confirm/save/delete dialogs
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.scss
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
Labels: bug

#1873 Bugs #12815: fix missing words - round 2
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
Labels: bug, small, VAS

#1879 Story #12530: fix labels
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: small, VAS

#1880 Story #12530: some fixes to make it work
  ui/ui-frontend/projects/referential/src/app/file-format/file-format-preview/file-format-information-tab/file-format-information-tab.component.ts
Labels: bug, small, VAS

#1844 Story #12116 CI with GitHub actions + #12302 SonarCloud
  .github/workflows/build-and-test.yml
  .github/workflows/lint.yml
  pom.xml
  sonar-project.properties
Labels: VAS, clean Code

#1877 bugs #11801 fix(standalone): add no auth module
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/ApiPastisStandaloneApplication.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/config/PastisConfiguration.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/config/WebConfig.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
  api/api-pastis/pastis-standalone/src/main/resources/application-dev.yml
  api/api-pastis/pastis-standalone/src/main/resources/application.yml
  ui/ui-frontend-common/src/app/modules/authentication/services/authenticator.service.ts
  ui/ui-frontend-common/src/app/modules/authentication/services/oidc-authenticator.service.ts
  ui/ui-frontend-common/src/app/modules/index.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/no-authentication.module.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/no-authenticator.service.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/standalone-startup.service.ts
Labels: bug, javascript, java, VAS

#1883 Bug #12909: Fix proper healthCheckUrl for consul when binding on distinct ip_admin
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
Labels: bug, VAS, OPS REVIEW

#1884 CP V7.1 - Bug #12909: Fix proper healthCheckUrl for consul when binding on distinct ip_admin
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  deployment/roles/vitamui/templates/security-internal/application.yml.j2
Labels: bug, VAS, Cherry-Pick, OPS REVIEW

#1885 CP V7.1 - bugs #11801 fix(standalone): add no auth module
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/ApiPastisStandaloneApplication.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/config/PastisConfiguration.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/config/WebConfig.java
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/controller/PastisController.java
  api/api-pastis/pastis-standalone/src/main/resources/application-dev.yml
  api/api-pastis/pastis-standalone/src/main/resources/application.yml
  ui/ui-frontend-common/src/app/modules/authentication/services/authenticator.service.ts
  ui/ui-frontend-common/src/app/modules/authentication/services/oidc-authenticator.service.ts
  ui/ui-frontend-common/src/app/modules/index.ts
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/pastis/src/app/app.module.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/no-authentication.module.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/no-authenticator.service.ts
  ui/ui-frontend/projects/pastis/src/app/standalone/standalone-startup.service.ts
Labels: Cherry-Pick

#1826 story #11852 style: update github template
  .github/pull_request_template.md
Labels: small, VAS

#1708 CP 7.0 - Bugs #12507: problem on Collect and Archive with date filters and timezones
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, Cherry-Pick

#1887 Story #11854: (clean code) jenkins file switch to parameters
  Jenkinsfile
Labels: OPS REVIEW

#1888 CP V6 - Revert "Merge pull request #1709 from ProgrammeVitam/CP_6_BUG_12507_Date_Search"
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, small, VAS, Cherry-Pick

#1889 CP 7.0 - Revert "Merge pull request #1708 from ProgrammeVitam/CP_BUG_12507_Date_Search"
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, small, VAS, Cherry-Pick
