Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-11, with the labels that each got.

#2206 bug #13111 : persistant hover on autocomplete option
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/autocomplete/vitamui-autocomplete/vitamui-autocomplete.component.html
Labels: small

#2161 Bug #13592: add validators on owner forms
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.validators.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: bug, small, VAS

#2211 Bugs #13621: Rule is not repeated and PreventRearrangement is an enum
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
Labels: bug

#2201 Bug #13336: access contract deactivate download button
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-information-tab/archive-unit-information-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/physical-archive-viewer/physical-archive-viewer.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/units/object-group.interface.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/units/unit.interface.ts
Labels: bug, enhancement, javascript, small

#2208 Bug #13572: add loading on probative value button
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/dip-request-create/dip-request-create.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.component.html
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-preview/probative-value-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value.service.ts
Labels: small

#2214 Bug #13765: Dynamic fix user uid & gid for container startup.
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/templates/vitamui-container-componentid.service.j2
Labels: bug, VAS, OPS REVIEW

#2217 Bug #13792: persistent id search empty modal
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.ts
Labels: bug, small

#2218 CP V7.1 - Bug #13792: persistent id search empty modal
  ui/ui-frontend/projects/archive-search/src/app/archive/persistent-identifier-search/found-object-modal/found-object-modal.component.ts
Labels: bug, small, Cherry-Pick

#2215 CP V7.1 - Bug #13765: Dynamic fix user uid & gid for container startup.
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/templates/vitamui-container-componentid.service.j2
Labels: bug, VAS, Cherry-Pick, OPS REVIEW

#2241 Story #13346: Fix vitam version
  bom/pom.xml
Labels: small

#2248 Bugs #13615: allow selection of SigningRole and DetachedSigningRole values
  ui/ui-frontend/projects/pastis/src/app/profile/edit-profile/file-tree-metadata/file-tree-metadata.component.ts
Labels: bug, small

#2250 Story #13624: fix Vitam UI deployment
  deployment/roles/vitamui/tasks/pastis-external.yml
  deployment/roles/vitamui/templates/pastis-external/collect-external-client.conf.j2
  deployment/roles/vitamui/templates/pastis-external/ingest-external-client.conf.j2
Labels: OPS REVIEW

#2147 CP 7.1 - bugs #13485 fix(pastis): logout feature
  ui/ui-frontend/projects/pastis/src/app/pastis/pastis.module.ts
Labels: bug, javascript, small, VAS, Cherry-Pick

#2210 Story #13791 cc: use access contract service
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-objects-details-tab/archive-unit-objects-details-tab.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/archive-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/unlock-category-inheritance/unlock-category-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-update/access-contract-node-update.component.html
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-update/access-contract-node-update.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-attachment-tab/ingest-contract-nodes-update/ingest-contract-node-update.component.html
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.service.ts
Labels: clean Code

#2251 CP V8.0 - Bug #12722: Set featureCompatibilityVersion to the proper one.
  deployment/roles/mongo_init/vars/main.yml
  deployment/scripts/mongod/0.0.0/00_set_feature_compatibility.js.j2
  deployment/scripts/mongod/0.0.0/01_init-admin-database.js.j2
  deployment/scripts/mongod/0.0.0/02_init-cas-database.js.j2
  deployment/scripts/mongod/0.0.0/03_init-iam-database.js.j2
  deployment/scripts/mongod/0.0.0/04_init-security-database.js.j2
  deployment/scripts/mongod/0.0.0/05_init-versioning.js.j2
Labels: OPS REVIEW

#2249 Bug #13791: resolve huge checkbox
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/sass/styles.scss
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/sass/styles.scss
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/vitamui-library/src/sass/_checkbox.scss
Labels: bug, small

#2243 CP V7.1 - Bug #12722: Set featureCompatibilityVersion to the proper one.
  deployment/roles/mongo_init/vars/main.yml
  deployment/scripts/mongod/0.0.0/00_set_feature_compatibility.js.j2
  deployment/scripts/mongod/0.0.0/01_init-admin-database.js.j2
  deployment/scripts/mongod/0.0.0/02_init-cas-database.js.j2
  deployment/scripts/mongod/0.0.0/03_init-iam-database.js.j2
  deployment/scripts/mongod/0.0.0/04_init-security-database.js.j2
  deployment/scripts/mongod/0.0.0/05_init-versioning.js.j2
Labels: OPS REVIEW

#2252 CP 7.0 - Bug #12722: Set featureCompatibilityVersion to the proper one.
  deployment/roles/mongo_init/vars/main.yml
  deployment/scripts/mongod/0.0.0/00_set_feature_compatibility.js.j2
  deployment/scripts/mongod/0.0.0/01_init-admin-database.js.j2
  deployment/scripts/mongod/0.0.0/02_init-cas-database.js.j2
  deployment/scripts/mongod/0.0.0/03_init-iam-database.js.j2
  deployment/scripts/mongod/0.0.0/04_init-security-database.js.j2
  deployment/scripts/mongod/0.0.0/05_init-versioning.js.j2
Labels: OPS REVIEW

#2253 CP V6 - Bug #12722: Set featureCompatibilityVersion to the proper one.
  deployment/roles/mongo_init/vars/main.yml
  deployment/scripts/mongod/0.0.0/00_set_feature_compatibility.js.j2
  deployment/scripts/mongod/0.0.0/01_init-admin-database.js.j2
  deployment/scripts/mongod/0.0.0/02_init-cas-database.js.j2
  deployment/scripts/mongod/0.0.0/03_init-iam-database.js.j2
  deployment/scripts/mongod/0.0.0/04_init-security-database.js.j2
  deployment/scripts/mongod/0.0.0/05_init-versioning.js.j2
Labels: OPS REVIEW

#2238 Story #13589: Upgrade to MongoDB 8.0.
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
  deployment/ansible-vitamui-migration/migration_mongodb_80.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  deployment/roles/mongo_init/vars/main.yml
  deployment/scripts/mongod/0.0.0/00_set_feature_compatibility.js.j2
  deployment/scripts/mongod/0.0.0/01_init-admin-database.js.j2
  deployment/scripts/mongod/0.0.0/02_init-cas-database.js.j2
  deployment/scripts/mongod/0.0.0/03_init-iam-database.js.j2
  deployment/scripts/mongod/0.0.0/04_init-security-database.js.j2
  deployment/scripts/mongod/0.0.0/05_init-versioning.js.j2
  deployment/scripts/mongod/v7.1/002_TRV-389_add_index_on_updatedDate_field_of_tokens_collection_ref.js
  deployment/scripts/mongod/v7.1/60_update_cas_create_user_email_customerid_index.js.j2
  docs/fr/migration/upgrade_v8_1.md
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW

#2209 CP 7.1: Bug #13592: add validators on owner forms
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.validators.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-preview/information-tab/information-tab.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-preview/information-tab/information-tab.component.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick

#2273 Story #13950: (temporarily?) skip dependency-check-maven plugin
  .github/workflows/build-and-test.yml
Labels: small

#2270 CP V8.0: Bug #13592: add validators on owner forms
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.validators.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-preview/information-tab/information-tab.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-preview/information-tab/information-tab.component.ts
Labels: bug, small, VAS, Cherry-Pick

#2271 Bug #13592: add validators on owner forms
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.ts
Labels: bug, small, VAS

#2266 CP V8.0 - Bug #13791: resolve huge checkbox
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/sass/styles.scss
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/sass/styles.scss
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/vitamui-library/src/sass/_checkbox.scss
Labels: bug, Cherry-Pick

#2267 CP 7.0 - Bug #13592: add validators on owner forms
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.component.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-form/owner-form.validators.ts
  ui/ui-frontend/projects/identity/src/app/customer/owner-preview/information-tab/information-tab.component.html
  ui/ui-frontend/projects/identity/src/app/customer/owner-preview/information-tab/information-tab.component.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: bug, small, VAS, Cherry-Pick
