Repository ProgrammeVitam/vitam-ui, pull requests merged in 2024-07, with the labels that each got.

#1928 CP V7.1 - Bug #12685 : hide _sps field when having one value
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.service.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-viewer/archive-unit-viewer.service.ts
Labels: bug, Cherry-Pick

#1929 CP 7.1 bugs #12792 : dashes on complementary fields
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/services/type.service.ts
  ui/ui-frontend-common/src/app/modules/pipes/empty.pipe.ts
Labels: bug, Cherry-Pick

#1931 CP 7.1 - Bugs #13001 : 500 error when saving an ingest project
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/TransactionConverter.java
  api/api-collect/collect-internal/src/test/java/fr/gouv/vitamui/collect/internal/server/service/converters/TransactionConverterTest.java
Labels: bug, Cherry-Pick

#1930 Story #11854: Small OPS Cleanup.
  deployment/ansible-vitamui-extra/vitamui_extra.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/scripts/mongod/1.0.0/318_application_ref.js.j2
  deployment/scripts/mongod/2.0.0/07_insert_serviceid_to_applications_ref.js
  deployment/scripts/mongod/2.0.0/20_logbook_operation_management_application.js.j2
  deployment/scripts/mongod/v6.0/22_create_application_MANAGEMENT_CONTRACT_APP.js.j2
Labels: small, VAS, OPS REVIEW

#1932 Story #11854: Clean code - activate source maps
  ui/ui-frontend/angular.json
Labels: small

#1935 Story #11854: Small OPS Cleanup.
  deployment/scripts/mongod/1.0.0/318_application_ref.js.j2
Labels: bug, small, VAS, OPS REVIEW

#1936 bug #13097 : ontology form fix
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.ts
Labels: bug, small, VAS

#1937 Bug #13113: Force ip_service to be set to ip_admin as mongo-express is binded on ip_admin.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, VAS

#1938 CP V7.1 - Bug #13113: Force ip_service to be set to ip_admin as mongo-express is binded on ip_admin.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1934 CP V7.1 - Story #11854: Small OPS Cleanup.
  deployment/ansible-vitamui-extra/vitamui_extra.yml
  deployment/environments/hosts-ui.example
  deployment/environments/hosts.local
  deployment/scripts/mongod/1.0.0/318_application_ref.js.j2
  deployment/scripts/mongod/2.0.0/07_insert_serviceid_to_applications_ref.js
  deployment/scripts/mongod/2.0.0/20_logbook_operation_management_application.js.j2
  deployment/scripts/mongod/v6.0/22_create_application_MANAGEMENT_CONTRACT_APP.js.j2
Labels: small, VAS, Cherry-Pick, OPS REVIEW, clean Code

#1941 Bug #12968: 500 on probative value due to order by #id
  ui/ui-frontend/projects/referential/src/app/probative-value/probative-value-list/probative-value-list.component.ts
Labels: bug, small

#1942 Bug #13132: Add missing start/stop for filebeat.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, VAS, OPS REVIEW

#1943 CP V7.1 - Bug #13132: Add missing start/stop for filebeat.
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#1944 Story #12364: improve saml documentation & #13112: upgrade external providers
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/IdentityProviderExternalService.java
  cas/cas-server/README.md
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/provider/Pac4jClientIdentityProviderDto.java
  deployment/scripts/mongod/v7.1/62_update_existing_external_providers_models.js.j2
  docs/developeurs/vitamui-conf-dev/README.md
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/sso-tab/identity-provider.service.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/sso-tab/identity-provider.service.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: bug, documentation, enhancement, VAS

#1945 CP V7.1: Story #12364: improve saml documentation & #13112: upgrade external providers
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/service/IdentityProviderExternalService.java
  cas/cas-server/README.md
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/provider/Pac4jClientIdentityProviderDto.java
  deployment/scripts/mongod/v7.1/62_update_existing_external_providers_models.js.j2
  docs/developeurs/vitamui-conf-dev/README.md
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/sso-tab/identity-provider.service.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-preview/sso-tab/identity-provider.service.ts
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
Labels: bug, enhancement, small, Cherry-Pick, OPS REVIEW

#1959 Bug #13161: make possible the control on DUA with date only
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/management-rules.component.ts
Labels: bug, javascript, small

#1965 Story #13085: minor fixes
  api/api-referential/referential-external/src/main/resources/static/import-ingest-contracts-model.csv
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/ExportIngestContracts.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/service/IngestContractInternalServiceTest.java
Labels: small
