Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-02, with the labels that each got.

#2430 bug #13574 : Ingest error detail tab - wrong icon
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
Labels: small

#2431 CP V8.0 - bug #13574 : Ingest error detail tab - wrong icon
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
Labels: small, Cherry-Pick

#2432 CP V7.1 - bug #13574 : Ingest error detail tab - wrong icon
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
Labels: small, Cherry-Pick

#2434 Bug #14235: [BUG/Regression] [Collection] Missing ZIP name when creating a project on Collect.
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/zip/zip-file-status.interface.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/zip/zip-file.class.ts
Labels: bug, small

#2438 bug #14209 : rename action button in Ontology app
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2433 bug #14207 : Reclassification pull error
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/reclassification/reclassification.component.ts
Labels: small

#2437 bug #13916 : spelling mistakes
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.html
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug

#2440 CP 7.0 - bug #13574 : Ingest error detail tab - wrong icon
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
Labels: small, Cherry-Pick

#2441 bug #13574 : change icon
  ui/ui-frontend/projects/ingest/src/app/ingest/ingest-preview/ingest-errors-details-tab/ingest-errors-details-tab.component.html
Labels: bug, small

#2443 Story #12310: Fix VitamUI deployment since archive-search merged into one layer.
  Architecture.md
  README.md
  deployment/ansible-vitamui-exploitation/troubleshoot.yml
  deployment/environments/group_vars/all/jvm_opts.yml
  docs/fr/architecture/sections/architecture.md
  docs/fr/installation/sections/prerequis.md
Labels: OPS REVIEW

#2414 Bug #14108 [Collection] - [Issues with Adding Directory to a Deposit Project]
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/design-system/src/app/app-routing.module.ts
  ui/ui-frontend/projects/design-system/src/app/components/miscellaneous/miscellaneous.component.html
  ui/ui-frontend/projects/design-system/src/app/components/upload/upload.component.html
  ui/ui-frontend/projects/design-system/src/app/components/upload/upload.component.scss
  ui/ui-frontend/projects/design-system/src/app/components/upload/upload.component.ts
  ui/ui-frontend/projects/design-system/src/assets/i18n/en.json
  ui/ui-frontend/projects/design-system/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/custom-file.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/zip/zip-file.class.ts
Labels: bug

#2450 Story #14127 : fix bug on certs configuration due to merging Ingest service
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/server/config/ApiIngestServerConfig.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/server/rest/IngestController.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/server/service/IngestExternalParametersService.java
  api/api-ingest/ingest-external/src/main/java/fr/gouv/vitamui/ingest/server/service/IngestExternalService.java
  api/api-ingest/ingest-external/src/test/java/fr/gouv/vitamui/ingest/server/service/IngestExternalServiceTest.java
  deployment/ansible-vitamui/app_ingest.yml
Labels: bug, small, VAS

#2384 story #13987: launch elimination on tree archive unit
  api/api-archive-search/archive-search-commons/src/main/java/fr/gouv/vitamui/archives/search/common/rest/RestApi.java
  api/api-archive-search/archive-search-external/src/main/java/fr/gouv/vitamui/archives/search/external/server/rest/ArchivesSearchExternalController.java
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/common-services/archive-unit-elimination.service.ts
  ui/ui-frontend/projects/archive-search/src/app/core/api/archive-api.service.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/alert-dialog/alert-dialog.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/alert-dialog/alert-dialog.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/alert-dialog/alert-dialog.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/index.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/projects/vitamui-library/src/sass/material/_dialog.scss
Labels: VAS

#2447 bug #14260 : Reclassification - Pull and Replace options
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/reclassification/reclassification.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug

#2452 Story #14127: fix path to spring application for ingest in local mode
  intellij-conf/.run/Spring/ingest external.run.xml
Labels: bug, small

#2455 Bug #14254 [COLLECTE] - The modification of a disbursement project by flow results in the disappearance of the Configuration tab and the switch to a manual project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small

#2456 CP V8.0 - Bug #14254 [COLLECTE] - The modification of a disbursement project by flow results in the disappearance of the Configuration tab and the switch to a manual project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, Cherry-Pick

#2457 CP V7.1 - Bug #14254 [COLLECTE] - The modification of a disbursement project by flow results in the disappearance of the Configuration tab and the switch to a manual project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, Cherry-Pick

#2444 Bug #13492 [Collection] - [The folder without attachment is missing in the case of an attachment project by key-value.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small

#2454 Bugs #14132: disable spring security for pastis standalone
  api/api-pastis/pastis-standalone/README.md
  api/api-pastis/pastis-standalone/src/main/java/fr/gouv/vitamui/pastis/standalone/ApiPastisStandaloneApplication.java
Labels: bug

#2458 CP V8.0 - Bug #13492 [Collection] - The folder without attachment is missing in the case of an attachment project by key-value.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, Cherry-Pick

#2459 Bug #14312: Reset mongo_nodes facts.
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo_init/tasks/main.yml
  deployment/roles/reinit_security_certificates/tasks/main.yml
Labels: OPS REVIEW

#2449 Bug #11665 [COLLECTE] - Modification of project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug

#2461 CP V7.1 - Bug #14312: Reset mongo_nodes facts.
  deployment/roles/mongo/tasks/main.yml
  deployment/roles/mongo_init/tasks/main.yml
  deployment/roles/reinit_security_certificates/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2446 story #14124: Uploading the configuration file (jslt) for a deposit project.
  api/api-collect/collect-commons/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectProjectDto.java
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/collect/project.ts
Labels: enhancement, VAS

#2463 Bug #14336 [Collection] - JSLT data not saved in the backend.
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/converters/ProjectConverter.java
Labels: bug, small

#2465 Bug #13184: Set Filebeat ignore_older's limitation
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
Labels: small, OPS REVIEW

#2469 Bug #14353: Add missing iam-external component from container build.
  Jenkinsfile.containers
Labels: bug, small, OPS REVIEW

#2466 CP V7.1 - Bug #13184: Set Filebeat ignore_older's limitation
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
Labels: small, Cherry-Pick, OPS REVIEW

#2471 CP V7.1 - Bug #14353: Add missing iam-external component from container build.
  Jenkinsfile.containers
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2475 Bug #14358: Do not build pastis-standalone in rpm or deb format.
  api/api-pastis/pastis-standalone/pom.xml
Labels: small, OPS REVIEW

#2476 CP V8.0 - Bug #14358: Do not build pastis-standalone in rpm or deb format.
  api/api-pastis/pastis-standalone/pom.xml
Labels: small, Cherry-Pick, OPS REVIEW

#2477 CP V7.1 - Bug #14358: Do not build pastis-standalone in rpm or deb format.
  api/api-pastis/pastis-standalone/pom.xml
Labels: small, Cherry-Pick, OPS REVIEW

#2483 Bug #14056 [MetaData] - [Bug][APP Recherche] All tags are expanded, not just "GÉNÉRALITÉS".
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/group/group.component.ts
Labels: bug, small

#2487 Bug #14221: Fix wrong drop message.
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
Labels: small, OPS REVIEW

#2486 Story #13791: Clean Code - Fix vitamui_defaults variable.
  .gitignore
  deployment/roles/nginx_webapp/defaults/main.yml
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/vitamui/defaults/main.yml
  docs/fr/exploitation/sections/pré_installation.md
  docs/fr/migration/upgrade_v7_1.md
Labels: bug, small, OPS REVIEW, clean Code

#2472 CP V8.0 - bug #13916 : spelling mistakes
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.html
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: small, Cherry-Pick

#2474 CP V7.0 - bug #13916 : spelling mistakes
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.html
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: small, Cherry-Pick

#2488 CP V8.0 - Story #13791: Clean Code - Fix vitamui_defaults variable.
  .gitignore
  deployment/roles/nginx_webapp/defaults/main.yml
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/vitamui/defaults/main.yml
  docs/fr/exploitation/sections/pré_installation.md
  docs/fr/migration/upgrade_v7_1.md
Labels: bug, small, Cherry-Pick, OPS REVIEW, clean Code

#2489 CP V7.1 - Story #13791: Clean Code - Fix vitamui_defaults variable.
  .gitignore
  deployment/roles/nginx_webapp/defaults/main.yml
  deployment/roles/reverse/defaults/main.yml
  deployment/roles/vitamui/defaults/main.yml
  docs/fr/exploitation/sections/pré_installation.md
  docs/fr/migration/upgrade_v7_1.md
Labels: bug, small, Cherry-Pick, OPS REVIEW, clean Code

#2479 CP V8.0 - Bug #14221: Renaming Filebeat fields
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
Labels: small, Cherry-Pick, OPS REVIEW

#2480 CP V7.1 - Bug #14221: Renaming Filebeat fields
  deployment/roles/filebeat/templates/inputs/cots.yml.j2
  deployment/roles/filebeat/templates/inputs/vitamui_services.yml.j2
Labels: small, Cherry-Pick, OPS REVIEW

#2485 Cp V8.0 - Bug #14056 [MetaData] - [Bug][APP Recherche] All tags are expanded, not just "GÉNÉRALITÉS".
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/components/group/group.component.ts
Labels: bug, small, Cherry-Pick

#2484 CP V7.1 - Bug #14056 [MetaData] - [Bug][APP Recherche] All tags are expanded, not just "GÉNÉRALITÉS".
  ui/ui-frontend-common/src/app/modules/object-viewer/components/group/group.component.ts
Labels: bug, small, Cherry-Pick

#2492 Story #13791: Clean Code - Fix multiple bug typos
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/ontology/ontology.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2493 CP V7.0 - Bug #14358: Do not build pastis-standalone in rpm or deb format.
  api/api-pastis/pastis-standalone/pom.xml
Labels: small, Cherry-Pick, OPS REVIEW
