Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-01, with the labels that each got.

#2345 bugs #14100 fix(schema-api): external to internal casting
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/schema/SchemaExternalService.java
Labels: bug

#2356 CP 8.0 - Bugs #11662: collect app needs ROLE_GET_UNITS to access trees and plans
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/v7.1/63_collect_missing_role.js.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#2357 CP 7.1 - Bugs #11662: collect app needs ROLE_GET_UNITS to access trees and plans
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/v7.1/63_collect_missing_role.js.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#2355 Bugs #11662: collect app needs ROLE_GET_UNITS to access trees and plans
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/v7.1/63_collect_missing_role.js.j2
Labels: bug, OPS REVIEW

#2351 DS #14097: Fix start/stop vitamui playbooks for mongo-express component
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, OPS REVIEW

#2353 CP V8.0 - DS #14097: Fix start/stop vitamui playbooks for mongo-express component
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2358 CP V8.0 - Story #14076: add vitamui_container_version variable
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/vitamui/templates/vitamui-container-componentid.service.j2
Labels: bug, small, OPS REVIEW

#2352 CP V7.1 - DS #14097: Fix start/stop vitamui playbooks for mongo-express component
  deployment/ansible-vitamui-exploitation/start_vitamui.yml
  deployment/ansible-vitamui-exploitation/stop_vitamui.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2359 CP V7.1 - Story #14076: add vitamui_container_version variable
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/vitamui/templates/vitamui-container-componentid.service.j2
Labels: bug, small, VAS, OPS REVIEW

#2361 Bugs #11662: Also change COLLECT_APP role for development mode
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
Labels: bug, small

#2363 Bugs #14101: return 400 on error from backend instead of 200
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ProfileInternalRestClient.java
Labels: bug

#2365 CP 6 - Bugs #14101: return 400 on error from backend instead of 200
  api/api-referential/referential-internal-client/src/main/java/fr/gouv/vitamui/referential/internal/client/ProfileInternalRestClient.java
Labels: bug, Cherry-Pick

#2367 BUG #14123: fix agency bug
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AgencyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/IngestContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
Labels: bug, small

#2343 Story #13791 cc: create project with zip file class and file selector
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/zip/zip-file-status.interface.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/models/zip/zip-file.class.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
Labels: clean Code

#2373 Bug #13909: Refreshing issue with the title when creating a PA or PUA.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small

#2380 BUG #14140: fix set tenant on creation
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/AgencyExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/IngestContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/ManagementContractExternalController.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/OntologyExternalController.java
Labels: bug, small

#2381 Bug #13152: Refactor the test for reset input.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.spec.ts
Labels: bug, small

#2386 CP V8.0 - Story #13791 clean code: fix GitHub Actions build issue with timezone
  .github/workflows/build-and-test.yml
Labels: Cherry-Pick, clean Code

#2388 CP V7.0 - Story #13791 clean code: fix GitHub Actions build issue with timezone
  .github/workflows/build-and-test.yml
Labels: Cherry-Pick, clean Code

#2385 CP V8.0 - Bug #13152: Problem with re-displaying a directory after deletion and attempting to re-import it in the upload area.
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
Labels: bug, Cherry-Pick

#2390 CP V7.1 - Bug #13152: Problem with re-displaying a directory after deletion and attempting to re-import it in the upload area
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: bug, small, Cherry-Pick

#2383 Bug #14111: Absence of a "VIEW OPERATIONS LOG" button when importing …
  ui/ui-frontend/projects/referential/src/app/shared/import-dialog/import-dialog.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug

#2346 story #13986 feat(archive-search|collect): add dynamic agencies and archive unit profiles to search forms (task #14021)
  api/api-gateway/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/main/resources/dev/customer-init.yml
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/roles/nginx_webapp/templates/frontend/config.json.j2
  deployment/roles/vitamui/files/customer-init.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/scripts/mongod/v8.1/004_add_read_agencies_and_aups_to_archive_search_and_collect.j2
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/pua-update-dialog/pua-update-dialog.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.css
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.css
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.ts
  ui/ui-frontend/projects/collect/src/assets/config-dev.json
  ui/ui-frontend/projects/design-system/src/app/components/tokens/typography/typography.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-create/access-contract-create.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.validators.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-list/agency-list.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-information-tab/agency-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency-preview/agency-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
  ui/ui-frontend/projects/referential/src/app/agency/view-agency/view-agency.component.ts
  ui/ui-frontend/projects/referential/src/app/core/api/context-api.service.spec.ts
  ui/ui-frontend/projects/referential/src/app/core/api/security-profile-api.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/agencies/agencies.module.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/agencies/agency-api.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/agencies/agency-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/agencies/agency.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit-profiles/archive-unit-profiles.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/app.configuration.interface.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/criteria/search-criteria-configs.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select/select.component.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
  ui/ui-frontend/projects/vitamui-library/src/sass/base/_utilities.scss
Labels: enhancement, javascript, VAS, OPS REVIEW

#2394 DS #14157: Fix lookup syntax.
  deployment/roles/uninstall/tasks/main.yml
  deployment/roles/vitamui/tasks/main.yml
Labels: small, OPS REVIEW, clean Code

#2401 CP V8.0 - Bug #13909: Refreshing issue with the title when creating a PA or PUA.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small, Cherry-Pick

#2395 CP V8.0 - DS #14157: Fix lookup syntax.
  deployment/roles/uninstall/tasks/main.yml
  deployment/roles/vitamui/tasks/main.yml
Labels: small, Cherry-Pick, OPS REVIEW, clean Code

#2396 CP V7.1 - DS #14157: Fix lookup syntax.
  deployment/roles/uninstall/tasks/main.yml
  deployment/roles/vitamui/tasks/main.yml
Labels: small, Cherry-Pick, OPS REVIEW, clean Code

#2400 BUG #14180: fix browser installation on Almalinux
  deployment/roles/browser/handlers/main.yml
  deployment/roles/browser/tasks/main.yml
Labels: bug, small, OPS REVIEW

#2404 CP V8.0 - BUG #14180: fix browser installation on Almalinux
  deployment/roles/browser/handlers/main.yml
  deployment/roles/browser/tasks/main.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2405 CP V7.1 - BUG #14180: fix browser installation on Almalinux
  deployment/roles/browser/handlers/main.yml
  deployment/roles/browser/tasks/main.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2402 CP V8.0 - Story #14016 Add troubleshoot playbook for VitamUI
  deployment/ansible-vitamui-exploitation/troubleshoot.yml
  deployment/roles/check_parent_structure/tasks/main.yml
  deployment/roles/end_troubleshoot/tasks/main.yml
  deployment/roles/gather_host/tasks/main.yml
  deployment/roles/init_troubleshoot/tasks/mail.yml
  deployment/roles/resolvconf/tasks/main.yml
  deployment/roles/tree_deployment/tasks/main.yml
  deployment/roles/vitamui_log_files/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2403 CP V7.1 - Story #14016: Add troubleshoot playbook for VitamUI
  deployment/ansible-vitamui-exploitation/troubleshoot.yml
  deployment/roles/check_parent_structure/tasks/main.yml
  deployment/roles/end_troubleshoot/tasks/main.yml
  deployment/roles/gather_host/tasks/main.yml
  deployment/roles/init_troubleshoot/tasks/mail.yml
  deployment/roles/resolvconf/tasks/main.yml
  deployment/roles/tree_deployment/tasks/main.yml
  deployment/roles/vitamui_log_files/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2406 Bug #14187: schema api error
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, small

#2397 Bug #14090: put back access contract id in filling plan service
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/ReferentialExternalRestClientFactory.java
  api/api-referential/referential-external-client/src/main/java/fr/gouv/vitamui/referential/external/client/UnitExternalRestClient.java
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/service/unit/UnitExtternalService.java
  api/api-referential/referential-external/src/test/java/fr/gouv/vitamui/referential/external/server/service/UnitInternalServiceTest.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-collect.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug

#2408 BUG #14109: fix checkbox side effect on archive search
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, small

#2418 CP V8.0 - Bug #13962: import CSV agencies error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamAgencyServiceTest.java
  api/api-referential/referential-commons/src/test/resources/agency/agency_with_additional_properties.csv
  api/api-referential/referential-commons/src/test/resources/agency/agency_with_additional_properties_and_others.csv
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtils.java
Labels: bug, Cherry-Pick

#2419 CP V7.0 - Bug #13962: import CSV agencies error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamAgencyServiceTest.java
  api/api-referential/referential-commons/src/test/resources/agency/agency_with_additional_properties.csv
  api/api-referential/referential-commons/src/test/resources/agency/agency_with_additional_properties_and_others.csv
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtils.java
Labels: bug, Cherry-Pick

#2417 CP V7.1 - Bug #13962: import CSV agencies error
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamAgencyService.java
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/service/VitamRuleService.java
  api/api-referential/referential-commons/src/test/java/fr/gouv/vitamui/referential/common/service/VitamAgencyServiceTest.java
  api/api-referential/referential-commons/src/test/resources/agency/agency_with_additional_properties.csv
  api/api-referential/referential-commons/src/test/resources/agency/agency_with_additional_properties_and_others.csv
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtils.java
Labels: bug, Cherry-Pick

#2375 Story #14016: Add troubleshoot playbook for VitamUI
  deployment/ansible-vitamui-exploitation/troubleshoot.yml
  deployment/roles/check_parent_structure/tasks/main.yml
  deployment/roles/end_troubleshoot/tasks/main.yml
  deployment/roles/gather_host/tasks/main.yml
  deployment/roles/init_troubleshoot/tasks/mail.yml
  deployment/roles/resolvconf/tasks/main.yml
  deployment/roles/tree_deployment/tasks/main.yml
  deployment/roles/vitamui_log_files/tasks/main.yml
Labels: OPS REVIEW

#2421 Story #14089: Monitoring COTS upgrade
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/customer/service/InitCustomerServiceIntegrationTest.java
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
  deployment/ansible-vitamui-migration/migration_mongodb_80.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/logstash/defaults/main.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW
