Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-09, with the labels that each got.

#3022 bug #14924 : Missing Id - Operations Log
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
Labels: bug, small

#3034 CP V8.0 - #14766 & #13462 #13917 : Pastis Design Issues
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.html
Labels: bug, small, Cherry-Pick

#3031 Story #15081 [Collection] - Adaptation of the frontend to the new VALIDATED status.
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.html
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: enhancement

#3033 Bug #15053 [Collection - SAE connection] - 400 error when creating a project after switching the mode "connected to the local SAE" during the process.
  api/api-iam/iam/src/main/resources/dev/customer-init.yml
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: bug

#3026 CP 8.1 - Bug #15035 [Referentials] - 500 error when exporting an empty list in the "Management Rules" and "Agent Services" applications.
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
Labels: bug, Cherry-Pick

#3027 CP 8.0 - Bug #15035 [Referentials] - 500 error when exporting an empty list in the "Management Rules" and "Agent Services" applications.
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
Labels: bug, Cherry-Pick

#3028 CP 7.1 - Bug #15035 [Referentials] - 500 error when exporting an empty list in the "Management Rules" and "Agent Services" applications.
  ui/ui-frontend/projects/referential/src/app/agency/agency.component.html
  ui/ui-frontend/projects/referential/src/app/rule/rule.component.html
Labels: bug, Cherry-Pick

#3037 [CP - 8.1] bugs #14925 (archive-search): fix infinite scroll top
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/scroll-top/scroll-top.component.ts
Labels: Cherry-Pick

#3039 [CP - 7.1] bugs #14925 (archive-search): fix infinite scroll top
  ui/ui-frontend-common/src/app/modules/components/scroll-top/scroll-top.component.ts
Labels: Cherry-Pick

#3040 CP V7.1 Bug #14832 [Collection] The confirmation pop-up for updating submissions is not displayed when exiting the side panel without saving.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small

#3042 CP V8.1 Bug #14832 [Collection] The confirmation pop-up for updating submissions is not displayed when exiting the side panel without saving.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small

#3043 Bug #14369 [Collect] Pressing Enter removes the attachment.
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
Labels: bug, small

#3045 CP 8.0 - Bug #14369 [Collect] Pressing Enter removes the attachment.
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
Labels: bug, small, Cherry-Pick

#3047 CP V8.1 - Bug #14851 [Collect] The "Edit" and "Cancel" buttons remain active after validating a transaction in automatic flow.
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
Labels: bug, Cherry-Pick

#3046 Bug #14851 [Collect] The "Edit" and "Cancel" buttons remain active after validating a transaction in automatic flow.
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
Labels: bug

#3054 CP V8.1 - Bug #14369 [Collect] Pressing Enter removes the attachment.
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
Labels: small, Cherry-Pick

#3048 CP V8.0 - Bug #14851 [Collect] The "Edit" and "Cancel" buttons remain active after validating a transaction in automatic flow.
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
Labels: bug, Cherry-Pick

#3060 Story #15087: upgrade dependencies to fix security issues
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/IamClientUserAuthenticationService.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/security/IamUserAuthentificationService.java
  bom/pom.xml
Labels: small

#3067 CP V8.0 - bug #14924 : Missing Id - Operations Log
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-operation-detail/logbook-operation-detail.component.html
Labels: bug, Cherry-Pick

#3064 CP V8.1 - Bug #14873 : blocked rules not displayed
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.html
Labels: bug, Cherry-Pick

#3075 CP V8.1 - Bugs #14906: missing placeholders and translations
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-authorizations-tab/access-contract-authorizations-update/access-contract-authorizations-update.component.html
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, Cherry-Pick

#3077 Bug #14873 : blocked rules not displayed - Collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.html
Labels: bug, small

#3092 CP V7.1 - bug #14923 : Ingest contract creation - identifier mandatory
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-create/ingest-contract-create.component.ts
Labels: bug, Cherry-Pick

#3059 Story #15029: alert on system limit on virtual nodes
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/design-system/src/app/components/atoms/tooltip/tooltip.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/common-tooltip/common-tooltip.component.scss
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: enhancement, VAS

#3106 CP V7.1 - Bug #15121 - [Access Contracts] Display issue: producer services selector.
  ui/ui-frontend-common/src/app/modules/components/autocomplete/vitamui-autocomplete-multi-select/vitamui-autocomplete-multi-select.component.ts
Labels: bug, small, Cherry-Pick

#3086 Fix #14961: do not display report download button when no audit report
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-information-tab/audit-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-preview.component.html
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-preview.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-preview.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-preview/audit-preview.module.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit.module.ts
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
Labels: bug

#3107 CP V8.1 - Fix #9434: order units hierarchically when computing path
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, Cherry-Pick

#3108 CP V8.0 - Fix #9434: order units hierarchically when computing path
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, Cherry-Pick

#3109 CP V7.1 - Fix #9434: order units hierarchically when computing path
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.service.ts
Labels: bug, Cherry-Pick

#3110 CP V8.1 - Story #14559: [CC] Ensure Ansible 12 (2.19) compatibility
  deployment/scripts/mongod/v8.1/0-00_security.populate_certificates.js.j2
Labels: bug, Cherry-Pick

#3114 CP V8.1 - Story #15087: upgrade ngx-toaster to avoid malicious version
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: bug, Cherry-Pick, Security

#3115 CP V8.0 - Story #15087: upgrade ngx-toaster to avoid malicious version
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: bug, Cherry-Pick, Security

#3113 Story #15087: upgrade ngx-toaster to avoid malicious version
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
Labels: bug, Security

#3123 Bug #14713 - [Collect && SEARCH] - Filters not translated after switching to English.
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/criteria/search-criteria.service.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug

#3149 Bugs #14188: vitamui-library-filing-plan does not work correctly when its previous value is not available anymore
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
Labels: bug

#3138 bugs #13604 (referential/archive-unit-profile): fixes error handling at create and update
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/archivalprofileunit/ArchivalProfileUnitService.java
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, javascript, java, VAS

#3157 CP V8.1 - bugs #14274 (archive-search/collect): fix the restoration of rule categories from saved search criteria
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, Cherry-Pick

#3151 CP V8.1 - Bugs #14188: vitamui-library-filing-plan does not work correctly when its previous value is not available anymore
  ui/ui-frontend/projects/vitamui-library/src/lib/components/filing-plan/filing-plan.component.ts
Labels: bug, Cherry-Pick

#3140 CP V8.0 - Bugs #14867: enforce specific identifier validation rules
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-information-tab/profile-information-tab/profile-information-tab.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, Cherry-Pick

#3147 Bug #14991 - [Security Operations] Missing tooltip when hovering over information icons in the "Operations Management" app.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.component.html
Labels: bug

#3161 Bug #14848 - [Archive-Search, Collect] Date picker display issue.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/simple-criteria-search/simple-criteria-search.component.html
Labels: bug

#3146 CP V8.0 - Bug #14991 - [Security Operations] Missing tooltip when hovering over information icons in the "Operations Management" app.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.component.html
Labels: bug, Cherry-Pick

#3141 CP V8.1 - bugs #13604 (referential/archive-unit-profile): fixes error handling at create and update
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/archivalprofileunit/ArchivalProfileUnitService.java
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, Cherry-Pick

#3156 Bug #15156: fix wrong behaviour on leaves tree
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/services/leaves-tree-api.service.ts
Labels: bug, small, VAS

#3164 Bugs #14866: fix change detection for contexts
  ui/ui-frontend/projects/referential/src/app/context/context-preview/context-information-tab/context-information-tab.component.ts
Labels: bug, small

#3167 CP V8.1 - Bug #14756 - [Collect] Premature display of the confirmation message when editing a project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small

#3169 CP V7.1 - Bug #14756 - [Collect] Premature display of the confirmation message when editing a project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
Labels: bug, small, Cherry-Pick

#3171 Bug #14852 - [Collect] The help text in the metadata search field is truncated.
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select-with-tree/select-with-tree.component.html
Labels: bug, small
