Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-03, with the labels that each got.

#2497 Bug #14380: Fix replay message in french translation
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2496 Bug #14379: Fix event when the step is empty.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/logbook/event-type-label/event-type-label.component.html
Labels: bug, small

#2498 Bug #14382: Fix SP and PUA translation in french.
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2502 Bug #14387: Add missing translation for csv limit in collect.
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
Labels: bug, small

#2499 CP V8.0 - Bug #14379: Fix event when the step is empty.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/logbook/event-type-label/event-type-label.component.html
Labels: bug, small, Cherry-Pick

#2500 CP V7.1 - Bug #14379: Fix event when the step is empty.
  ui/ui-frontend-common/src/app/modules/logbook/event-type-label/event-type-label.component.html
Labels: bug, small, Cherry-Pick

#2501 CP V7.0 - Bug #14379: Fix event when the step is empty.
  ui/ui-frontend-common/src/app/modules/logbook/event-type-label/event-type-label.component.html
Labels: bug, small, Cherry-Pick

#2504 Bug #13192 [MetaData] - Multiple display anomalies or bugs.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-fields.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-template.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug

#2506 bug #14372 : Failure to pause an operation
  api/api-referential/referential-external/src/main/java/fr/gouv/vitamui/referential/external/server/rest/LogbookManagementOperationExternalController.java
Labels: small

#2509 Bug #14387: Fix collect traduction for snackbar.
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: clean Code

#2495 Story #14223: show other search types than strict without translation
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/simple-criteria-search/simple-criteria-search.component.ts
Labels: enhancement, small, VAS

#2513 Story #14267: fix regression for local dev
  deployment/scripts/mongod/v7.1/039_enable_oidc_code_grant_type_on_archive_search_service_ref.js.j2
  deployment/scripts/mongod/v7.1/040_enable_oidc_code_grant_type_on_pastis_service_ref.js.j2
  deployment/scripts/mongod/v7.1/041_enable_oidc_code_grant_type_on_ingest_service_ref.js.j2
  deployment/scripts/mongod/v7.1/042_enable_oidc_code_grant_type_on_collect_service_ref.js.j2
  tools/docker/mongo/mongo_vars_dev.yml
Labels: bug, OPS REVIEW

#2515 Story #14128: fix subrogation
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/dto/SubrogationDto.java
Labels: bug

#2507 CP V8.0 - Bug #13192 [MetaData] - Multiple display anomalies or bugs.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-fields.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-template.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, Cherry-Pick

#2508 CP V7.1 - Bug #13192 [MetaData] - Multiple display anomalies or bugs.
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-fields.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/archive-unit-template.ts
  ui/ui-frontend-common/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.component.ts
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.scss
  ui/ui-frontend-common/src/app/modules/object-editor/components/group-editor/group-editor.component.ts
  ui/ui-frontend-common/src/app/modules/object-editor/models/edit-object.model.ts
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
  ui/ui-frontend-common/src/app/modules/object-viewer/types/index.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.html
Labels: bug, Cherry-Pick, Squash before merge

#2522 Story #14381: Ultimate COTS upgrade
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/customer/service/InitCustomerServiceIntegrationTest.java
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
  deployment/ansible-vitamui-migration/migration_mongodb_80.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/logstash/defaults/main.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW

#2524 Bugs #14437: submit action must be inside form
  ui/ui-frontend/projects/referential/src/app/access-contract/access-contract-preview/access-contract-nodes-tab/access-contract-nodes-update/access-contract-node-update.component.html
Labels: bug, small

#2520 Story #13791: Fix spelling mistakes
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/block-rules-inheritance/block-rules-inheritance.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/block-rules-inheritance/block-rules-inheritance.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/delete-unit-rules/delete-unit-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/unlock-category-inheritance/unlock-category-inheritance.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/unlock-rules-inheritance/unlock-rules-inheritance.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/assets/i18n/en.json
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/identity/src/app/user/user-preview/user-preview.component.html
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/fr.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.html
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
Labels: clean Code

#2526 Bugs #14440: collections is multi-valued in ontology
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.html
Labels: bug, small

#2521 Fix #14430: tree-node doesn't accept null data
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
Labels: bug

#2528 CP V8.0 - Story #14280: Migration playbook to switch from legacy to container installation
  deployment/ansible-vitamui-migration/remove_legacy_packages.yml 
  docs/fr/migration/index.rst
  docs/fr/migration/migration_container.md
Labels: documentation, Cherry-Pick, OPS REVIEW

#2529 CP V7.1 - Story #14280: Migration playbook to switch from legacy to container installation
  deployment/ansible-vitamui-migration/remove_legacy_packages.yml 
  docs/fr/migration/index.rst
  docs/fr/migration/migration_container.md
Labels: documentation, Cherry-Pick, OPS REVIEW

#2530 Bugs #14402: do not filter out ONE_REQUIRED elements
  ui/ui-frontend/projects/pastis/src/app/core/services/seda.service.ts
Labels: bug, small

#2532 CP V8.0 - Bug #14060 & #14059 [MetaData] - Browser pop-up blocks saving & The "SAVE" button is not clickable.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/directives/click-outside/click-outside.directive.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
Labels: bug, Cherry-Pick

#2536 Bugs #14129: these two modules do not exist anymore
  api/api-collect/collect/pom.xml
  api/api-ingest/ingest/pom.xml
  bom/pom.xml
Labels: bug, small

#2537 Bugs #14422: transaction not mandatory to switch language...
  commons/commons-logbook/src/main/java/fr/gouv/vitamui/commons/logbook/service/EventService.java
Labels: bug, small

#2539 Bug #13821: Enable hostname verification for inter-app communication
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect/application.yml.j2
  deployment/roles/vitamui/templates/iam/application.yml.j2
  deployment/roles/vitamui/templates/ingest/application.yml.j2
  deployment/roles/vitamui/templates/pastis/application.yml.j2
  deployment/roles/vitamui/templates/referential/application.yml.j2
Labels: bug, small, OPS REVIEW, clean Code

#2540 Bug #14413 [Metadata] Remove secondary action buttons for DeathPlace and BirthPlace.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, small

#2547 CP V8.0 - Bugs #14421: disable some buttons when transaction is validated
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2548 CP V7.1 - Bugs #14421: disable some buttons when transaction is validated
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2549 CP V7.0 - Bugs #14421: disable some buttons when transaction is validated
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2544 CP 8.0 Bug #14413 [Metadata] Remove secondary action buttons for DeathPlace and BirthPlace.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, small, Cherry-Pick

#2546 CP 7.1 Bug #14413 [Metadata] Remove secondary action buttons for DeathPlace and BirthPlace.
  ui/ui-frontend-common/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, small, Cherry-Pick

#2534 US #14255 [COLLECTE] - Manage UpdateOperation tags in the collection CSV file.
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/leaves-tree/leaves-tree.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/nodes/filing-holding-scheme.handler.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/units/unit-type.enum.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/units/unit.interface.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: enhancement

#2543 CP 7.1 Bug #14410 [Collecte] - UA types "Static Attachment" and "Dynamic Attachment" should no longer appear in the Collection panels.
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, Cherry-Pick

#2556 Bugs #14300: send sedaVersion on create
  ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, small

#2553 CP V7.1 - Bug #13821: Enable hostname verification for inter-app communication
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2551 CP V8.0 - Bug #13821: Enable hostname verification for inter-app communication
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2552 Story #14130: add new labels translations
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: enhancement, small

#2558 Bugs #14166: adapt diff to support arrays in diff
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/utils/diff.util.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/utils/diff.util.ts
Labels: bug

#2557 Bug #13478 [Modify AU with PUA] Monovalue tag incorrectly allows adding another tag.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
Labels: bug, small

#2566 story #14130 : Reclassification roles fix
  api/api-archive-search/archive-search/src/main/java/fr/gouv/vitamui/archives/search/server/rest/ArchivesSearchController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
Labels: small

#2554 Bugs #14366 #14367: fix schema import error detection and display
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/schema/ImportSchemaCSVUtils.java
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/utils/ImportCSVUtils.java
  api/api-referential/referential/src/test/java/fr/gouv/vitamui/referential/server/service/schema/ImportSchemaCSVUtilsTest.java
  api/api-referential/referential/src/test/resources/data/import_schema_invalid.csv
  ui/ui-frontend/projects/referential/src/app/shared/import-dialog/import-dialog.component.ts
Labels: bug

#2567 Cp 8.0 Bug #14066 [MDD Display] Issue with displaying the producer service responsible for the entry.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
Labels: bug, small, Cherry-Pick

#2562 Bug #14066 [MDD Display] Issue with displaying the producer service responsible for the entry.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/archive-unit-edit-object.service.ts
Labels: bug, small

#2559 CP V8.0 - Bugs #14166: adapt diff to support arrays in diff
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/utils/diff.util.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/utils/diff.util.ts
Labels: bug, Cherry-Pick

#2563 Bug #14028: Redirect to agencies list after agency update
  ui/ui-frontend/projects/referential/src/app/agency/edit-agency/edit-agency.component.ts
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2542 CP 8.0 Bug #14410 [Collecte] - UA types "Static Attachment" and "Dynamic Attachment" should no longer appear in the Collection panels.
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2564 CP 8.0 Bug #13477 [Modify AU with PUA] Alert messages are neither identical nor compliant.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-input.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-list-date.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-textarea.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/list-editor/list-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, Cherry-Pick

#2555 Bug #13477 [Modify AU with PUA] Alert messages are neither identical nor compliant.
  ui/ui-frontend/projects/design-system/src/app/components/molecules/inputs/repeatable-input/design-system-repeatable-input.component.html
  ui/ui-frontend/projects/design-system/src/app/components/molecules/inputs/repeatable-input/design-system-repeatable-input.component.ts
  ui/ui-frontend/projects/referential/src/app/audit/audit-create/audit-create.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-input.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-list-date.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/editor-textarea.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/list-editor/list-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/primitive-editor/primitive-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2573 Bugs #14435: fix the dynamic attachment query
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug

#2575 Bug #14464: Fix report download filename
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/rest/LogbookController.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtils.java
Labels: bug

#2570 Bug #14457 : Fix api-gateway certificate validation
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, OPS REVIEW

#2577 Bug #14316 [Archiving Profile] Unable to save a PA modification.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small

#2581 Bugs #14276: fix CSV export to correctly quote fields
  api/api-archive-search/archive-search/src/main/java/fr/gouv/vitamui/archives/search/server/service/ArchiveSearchUnitExportCsvService.java
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/filing-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/holding-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/unit-with-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/unit-without-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/vitam_archive_units_response_correctly_encoded.csv
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/vitam_archive_units_response_en.csv
  api/api-archive-search/archive-search/src/test/resources/data/export-csv/vitam_archive_units_response_fr.csv
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/service/TransactionArchiveUnitService.java
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/accessionregister/AccessionRegisterService.java
Labels: bug, small

#2571 Bugs #14394: fix collect profiles and groups
  deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
  deployment/scripts/mongod/v8.0/007_fix_groups_for_collect_profiles.js.j2
Labels: bug, OPS REVIEW

#2572 CP V8.0 - Bugs #14394: fix collect profiles and groups
  deployment/scripts/mongod/v8.0/005_create_new_collect_profiles_for_exist_customers.js.j2
  deployment/scripts/mongod/v8.0/007_fix_groups_for_collect_profiles.js.j2
Labels: bug, OPS REVIEW

#2586 CP V8.0 - Bugs #14394: fix syntax...
  deployment/scripts/mongod/v8.0/007_fix_groups_for_collect_profiles.js.j2
Labels: bug, small, Cherry-Pick

#2585 Bugs #14394: fix syntax...
  deployment/scripts/mongod/v8.0/007_fix_groups_for_collect_profiles.js.j2
Labels: bug, small

#2579 CP V8.0 - Bugs #14435: fix the dynamic attachment query.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2578 Bug #14461 [Archive Search] Loss of metadata modifications.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/directives/click-outside/click-outside.directive.ts
Labels: bug, small

#2598 CP 8.0 Bug #14461 [Archive Search] Loss of metadata modifications.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/directives/click-outside/click-outside.directive.ts
Labels: bug, small, Cherry-Pick

#2584 DS #14097: Update consul configuration.
  deployment/roles/consul/templates/consul.json.j2
Labels: small, OPS REVIEW

#2587 Bug #14476: Fix getDcName function.
  deployment/pki/scripts/lib/certs.sh
Labels: bug, small, OPS REVIEW

#2600 Bugs #14376: orphan count is sometimes undefined in leaves-tree component
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small

#2594 Bug #13835 [Metadata] Missing selector when editing metadata with an Enum list.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/services/edit-object.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-viewer/models/ui.model.ts
Labels: bug

#2601 Bug #14477 [Operation Management] Restart buttons not activated when an operation is paused.
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.html
Labels: bug, small

#2602 CP V8.0 - Bugs #14376: orphan count is sometimes undefined in leaves-tree component
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small, Cherry-Pick

#2603 CP V7.1 - Bugs #14376: orphan count is sometimes undefined in leaves-tree component
  ui/ui-frontend/projects/archive-search/src/app/archive/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, small, Cherry-Pick

#2605 Bug #14485 [Archive Search] Loss of edit mode when clicking outside the tab.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
Labels: bug, small

#2606 Cp 8.0 Bug #14485 [Archive Search] Loss of edit mode when clicking outside the tab.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-description-tab/archive-unit-description-tab.component.ts
Labels: bug, small, Cherry-Pick

#2588 CP V8.0 - Bug #14476: Fix getDcName function.
  deployment/pki/scripts/lib/certs.sh
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2589 CP V7.1 - Bug #14476: Fix getDcName function.
  deployment/pki/scripts/lib/certs.sh
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2609 CP V7.1 - Bug #13492 [Collection] - The folder without attachment is missing in the case of an attachment project by key-value.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
Labels: bug, Cherry-Pick

#2604 CP V8.0 - Bugs #14300: send sedaVersion on create
  ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
Labels: bug, small, Cherry-Pick

#2574 CP V8.0 - Bug #13477 [Modify AU with PUA] Alert messages are neither identical nor compliant.
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.html
  ui/ui-frontend/projects/design-system/src/app/components/inputs/inputs.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/multiple-options-datepicker/multiple-options-datepicker.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-repeatable-input/vitamui-repeatable-input.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/abstract-form-input.directive.ts
Labels: bug, Cherry-Pick

#2610 Bug #14450 [Search] Error 500 when calculating inheritance without write permissions on management metadata.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
Labels: bug, small

#2591 CP V8.0 - DS #14097: Update consul configuration.
  deployment/roles/consul/templates/consul.json.j2
Labels: small, Cherry-Pick, OPS REVIEW

#2599 Story #13791: Remove duplicated swagger docs.
  docs/swagger/api-external/archive-search/index.html
  docs/swagger/api-external/archive-search/index.pdf
  docs/swagger/api-external/archive-search/swagger.json
  docs/swagger/api-external/iam/index.html
  docs/swagger/api-external/iam/index.pdf
  docs/swagger/api-external/iam/swagger.json
  docs/swagger/api-external/ingest/index.html
  docs/swagger/api-external/ingest/index.pdf
  docs/swagger/api-external/ingest/swagger.json
  docs/swagger/api-external/referential/index.html
  docs/swagger/api-external/referential/index.pdf
  docs/swagger/api-external/referential/swagger.json
  docs/swagger/api-internal/iam-internal/index.html
  docs/swagger/api-internal/iam-internal/index.pdf
  docs/swagger/api-internal/iam-internal/swagger.json
  docs/swagger/api-internal/ingest-internal/index.html
  docs/swagger/api-internal/ingest-internal/index.pdf
  docs/swagger/api-internal/ingest-internal/swagger.json
  docs/swagger/api-internal/security/index.html
  docs/swagger/api-internal/security/index.pdf
  docs/swagger/api-internal/security/swagger.json
  docs/swagger/ui/ui-archive-search/index.html
  docs/swagger/ui/ui-archive-search/index.pdf
  docs/swagger/ui/ui-archive-search/swagger.json
  docs/swagger/ui/ui-identity/index.html
  docs/swagger/ui/ui-identity/index.pdf
  docs/swagger/ui/ui-identity/swagger.json
  docs/swagger/ui/ui-ingest/index.html
  docs/swagger/ui/ui-ingest/index.pdf
  docs/swagger/ui/ui-ingest/swagger.json
  docs/swagger/ui/ui-portal/index.html
  docs/swagger/ui/ui-portal/index.pdf
  docs/swagger/ui/ui-portal/swagger.json
  docs/swagger/ui/ui-referential/index.html
  docs/swagger/ui/ui-referential/index.pdf
  docs/swagger/ui/ui-referential/swagger.json
  tools/swagger/docs/api-internal/iam-internal/swagger.json
Labels: documentation, clean Code

#2595 CP V8.0 - Bugs #14276: fix CSV export to correctly quote fields
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/filing-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/holding-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/unit-with-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/unit-without-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_correctly_encoded.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_en.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_fr.csv
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
Labels: bug, Cherry-Pick

#2596 CP V7.1 - Bugs #14276: fix CSV export to correctly quote fields
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/filing-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/holding-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/unit-with-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/unit-without-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_correctly_encoded.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_en.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_fr.csv
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
Labels: bug, Cherry-Pick

#2597 CP V7.0 - Bugs #14276: fix CSV export to correctly quote fields
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchUnitExportCsvInternalService.java
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/filing-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/holding-unit/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/unit-with-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/unit-without-object/vitam_archive_units_response_fr.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_correctly_encoded.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_en.csv
  api/api-archive-search/archive-search-internal/src/test/resources/data/export-csv/vitam_archive_units_response_fr.csv
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accessionregister/AccessionRegisterInternalService.java
Labels: bug, Cherry-Pick

#2616 CP V7.1 - Bugs #14307: incorrect column name for access and ingest contract CSV import
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/IngestContractDto.java
  api/api-referential/referential-external/src/main/resources/static/import-access-contracts-model.csv
  api/api-referential/referential-external/src/main/resources/static/import-ingest-contracts-model.csv
  api/api-referential/referential-external/src/test/resources/data/import_access_contracts_valid.csv
  api/api-referential/referential-external/src/test/resources/data/import_ingest_contracts_valid.csv
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractCSVUtils.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractCSVUtils.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractUtilsTest.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractCSVUtilsTest.java
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_bad_rows.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_bad_rows_length.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_headers_order_not_matching.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_not_enough_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_only_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_rejected_by_vitam.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_too_much_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_valid.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_bad_rows.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_headers_order_not_matching.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_only_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_wrong_ids.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_valid.csv
Labels: bug, Cherry-Pick

#2615 CP V8.0 - Bugs #14307: incorrect column name for access and ingest contract CSV import
  api/api-referential/referential-commons/src/main/java/fr/gouv/vitamui/referential/common/dto/IngestContractDto.java
  api/api-referential/referential-external/src/main/resources/static/import-access-contracts-model.csv
  api/api-referential/referential-external/src/main/resources/static/import-ingest-contracts-model.csv
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractCSVUtils.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractCSVUtils.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractUtilsTest.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractCSVUtilsTest.java
  api/api-referential/referential-internal/src/test/resources/access-contract/expected-access-contracts-exported.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_bad_rows.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_bad_rows_length.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_headers_order_not_matching.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_not_enough_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_only_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_rejected_by_vitam.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_invalid_too_much_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_access_contracts_valid.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_bad_rows.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_headers_order_not_matching.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_only_headers.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_invalid_wrong_ids.csv
  api/api-referential/referential-internal/src/test/resources/data/import_ingest_contracts_valid.csv
Labels: bug, Cherry-Pick

#2608 Bugs #13226: validate required and non blank fields for groups and collect
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/identity/src/app/group/group-create/group-create.component.html
  ui/ui-frontend/projects/identity/src/app/group/group-create/group-create.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/validators/misc.validators.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/validators/misc.validators.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
Labels: bug

#2592 CP V7.1 - DS #14097: Update consul configuration.
  deployment/roles/consul/templates/consul.json.j2
Labels: small, Cherry-Pick, OPS REVIEW

#2538 Story #14452: Fix i18n translations.
  .github/workflows/i18n-check.yml
  ui/ui-frontend/projects/archive-search/src/assets/i18n/fr.json
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/design-system/src/assets/i18n/en.json
  ui/ui-frontend/projects/design-system/src/assets/i18n/fr.json
  ui/ui-frontend/projects/identity/src/assets/i18n/en.json
  ui/ui-frontend/projects/identity/src/assets/i18n/fr.json
  ui/ui-frontend/projects/ingest/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
  ui/ui-frontend/projects/portal/src/assets/i18n/en.json
  ui/ui-frontend/projects/portal/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: clean Code, Squash before merge
