Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-08, with the labels that each got.

#2987 Story #14559: fix eslint config
  .husky/pre-commit
  ui/ui-frontend/.eslintrc.json
  ui/ui-frontend/angular.json
  ui/ui-frontend/eslint.config.mjs
  ui/ui-frontend/package-lock.json
  ui/ui-frontend/package.json
  ui/ui-frontend/projects/archive-search/src/app/app.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/app.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/app.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/customer/customer-list/customer-list.component.spec.ts
  ui/ui-frontend/projects/identity/src/app/group/group-list/group-list.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/app.component.spec.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/load-profile/load-profile.component.ts
Labels: clean Code

#2990 Story #14858: fix broken referential startup in dev (if keystore/truststore not found)
  api/api-referential/referential/src/main/resources/application-dev.yml
Labels: bug, small

#2979 Story #14911: Collect - attachment tab updates
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/common/dto/CollectProjectAttachmentsDto.java
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/rest/ProjectController.java
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/service/ProjectService.java
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/project.module.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.service.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/collect/project.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/pipes/empty.pipe.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/schema/schema.service.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select-with-tree/select-with-tree.component.ts
Labels: enhancement, VAS

#3002 bug #15016 : Metadata update in Collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug

#3006 Bugs #15047: initialise controlSchema with valid value
  ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.ts
Labels: bug

#3004 CP V8.1 - Bug #15016 : Metadata update in Collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, Cherry-Pick

#3005 CP V8.0 - Bug #15016 : Metadata update in Collect
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, Cherry-Pick

#3012 CP V8.0 - Bugs #14885: missing api gateway rewrite rules
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, Cherry-Pick

#3013 CP V7.1 - Bugs #14885: missing api gateway rewrite rules
  api/api-gateway/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, Cherry-Pick

#3015 Bug #14873 : blocked rules not displayed
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-unit-rules-details-tab/archive-unit-rules-informations-tab/archive-unit-rules-informations-tab.component.html
Labels: bug

#3016 bug #14918 : Rules update
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/add-management-rules/add-management-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/archive-unit-rules.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/archive-unit-rules.component.ts
  ui/ui-frontend/projects/archive-search/src/app/core/management-rules-shared-data.service.ts
Labels: bug

#3018 bug #14982 : Groups rights - form design
  ui/ui-frontend/projects/identity/src/app/shared/profiles-form/profiles-form.component.html
Labels: bug, small

#3019 bug #14766 : Pastis - Poorly positioned button
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.html
Labels: bug, small

#3021 CP V8.0 - #14766 & #13462 #13917 : Pastis Design Issues
  ui/ui-frontend/projects/pastis/src/app/profile/profile-preview/profile-preview.component.html
Labels: bug, small, Cherry-Pick
