Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-07, with the labels that each got.

#2902 Story #13529: Fixing missed JDK21 update.
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis-standalone/src/main/assembly/packaging-zip.xml
  pom.xml
Labels: bug, clean Code

#2914 Fix #12346: do not apply titlecase on profile name
  ui/ui-frontend/projects/identity/src/app/group/group-preview/profiles-tab/profiles-tab.component.html
  ui/ui-frontend/projects/identity/src/app/group/group-preview/profiles-tab/profiles-tab.component.spec.ts
Labels: small

#2915 CP V8.1 - Fix #12346: do not apply titlecase on profile name
  ui/ui-frontend/projects/identity/src/app/group/group-preview/profiles-tab/profiles-tab.component.html
  ui/ui-frontend/projects/identity/src/app/group/group-preview/profiles-tab/profiles-tab.component.spec.ts
Labels: Cherry-Pick

#2916 CP V8.0 - Fix #12346: do not apply titlecase on profile name
  ui/ui-frontend/projects/identity/src/app/group/group-preview/profiles-tab/profiles-tab.component.html
  ui/ui-frontend/projects/identity/src/app/group/group-preview/profiles-tab/profiles-tab.component.spec.ts
Labels: Cherry-Pick

#2907 CP V8.0 - Story #14907: Do not compile already executed scripts during mongo_init.
  deployment/roles/checks/tasks/check_mongo_express.yml
  deployment/roles/mongo_init/tasks/check_auth.yml
  deployment/roles/mongo_init/tasks/main.yml
  deployment/roles/mongo_init/tasks/prepare_script.yml
Labels: Cherry-Pick, OPS REVIEW

#2908 CP V7.1 - Story #14907: Do not compile already executed scripts during mongo_init.
  deployment/roles/checks/tasks/check_mongo_express.yml
  deployment/roles/mongo_init/tasks/check_auth.yml
  deployment/roles/mongo_init/tasks/main.yml
  deployment/roles/mongo_init/tasks/prepare_script.yml
Labels: Cherry-Pick, OPS REVIEW

#2926 CP V7.1 - Bug #14831 - [Collect] The 'Submit' button remains active after validating a transaction in automatic flow mode with the 'Automatic transaction management' option enabled, until the page is refreshed.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug

#2936 CP V8.1 - Bug #14940: Small typo in translation.
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small, Cherry-Pick

#2934 Bug #14918 : Archive-Search - failed to update rules for Access and Reuse
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/archive-unit-rules.component.ts
Labels: bug

#2940 CP V8.1 - Bugs #14552: fix link to report download for securisation audit
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
Labels: bug, small, Cherry-Pick

#2941 CP V8.0 - Bugs #14552: fix link to report download for securisation audit
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
Labels: bug, small, Cherry-Pick

#2942 CP V7.1 - Bugs #14552: fix link to report download for securisation audit
  ui/ui-frontend/projects/referential/src/app/logbook-operation/logbook-download.service.ts
Labels: bug, small, Cherry-Pick

#2938 Bug #14948: Fixed editing errors in archive unit metadata with repeatable entries.
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/common/exception/ArchiveUnitUpdateException.java
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/service/ArchiveUnitServiceImpl.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/converter/JsonPatchToSetActionConverter.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/converter/JsonPatchToUnsetActionConverter.java
Labels: bug, VAS

#2948 Bugs #14835: ontology id is not part of the form
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.ts
Labels: bug, small

#2954 CP V8.0 - Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2953 CP V7.1 - Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2142 bug #13347 : modify user email with dash
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/utils/MongoUtils.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/utils/MongoUtilsTest.java
Labels: bug, VAS

#2957 CP V7.1 - bug #13347 : modify user email with dash
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/utils/MongoUtils.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/utils/MongoUtilsTest.java
Labels: bug, Cherry-Pick

#2955 CP V8.1 - bug #13347 : modify user email with dash
  commons/commons-mongo/src/main/java/fr/gouv/vitamui/commons/mongo/utils/MongoUtils.java
  commons/commons-mongo/src/test/java/fr/gouv/vitamui/commons/mongo/utils/MongoUtilsTest.java
Labels: bug, Cherry-Pick

#2959 CP V8.0 - Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, Cherry-Pick

#2943 CP V8.0 - Bug #14853: Add missing translation keys for preservation operations.
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small, Cherry-Pick

#2968 CP V8.0 - Bugs #14972: remove sort button on id
  ui/ui-frontend/projects/referential/src/app/securisation/securisation-list/securisation-list.component.html
Labels: bug, small, Cherry-Pick

#2963 CP V7.1 - Bugs #14971: fix agency creation form
  ui/ui-frontend/projects/referential/src/app/agency/agency-create/agency-create.component.html
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2971 Bump version from 8.0.1-SNAPSHOT to 8.0.2-SNAPSHOT on master_8.0.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search-external-client/pom.xml
  api/api-archive-search/archive-search-external/pom.xml
  api/api-archive-search/archive-search-internal-client/pom.xml
  api/api-archive-search/archive-search-internal/pom.xml
  api/api-archive-search/pom.xml
  api/api-collect/collect-commons/pom.xml
  api/api-collect/collect-external-client/pom.xml
  api/api-collect/collect-external/pom.xml
  api/api-collect/collect-internal-client/pom.xml
  api/api-collect/collect-internal/pom.xml
  api/api-collect/pom.xml
  api/api-gateway/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-external-client/pom.xml
  api/api-iam/iam-external/pom.xml
  api/api-iam/iam-internal-client/pom.xml
  api/api-iam/iam-internal/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest-commons/pom.xml
  api/api-ingest/ingest-external-client/pom.xml
  api/api-ingest/ingest-external/pom.xml
  api/api-ingest/ingest-internal-client/pom.xml
  api/api-ingest/ingest-internal/pom.xml
  api/api-ingest/pom.xml
  api/api-pastis/pastis-client/pom.xml
  api/api-pastis/pastis-commons/pom.xml
  api/api-pastis/pastis-external/pom.xml
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential-external-client/pom.xml
  api/api-referential/referential-external/pom.xml
  api/api-referential/referential-internal-client/pom.xml
  api/api-referential/referential-internal/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security-internal/pom.xml
  api/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-mongo-express/pom.xml
  deployment/environments/group_vars/all/repositories.yml
  deployment/pom.xml
  integration-tests/pom.xml
  packaging/pom.xml
  pom.xml
Labels: OPS REVIEW

#2974 Bugs #14912: fix problem when managementContractId is deselected
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
Labels: bug, small

#2975 CP V8.1 - Bugs #14912: fix problem when managementContractId is deselected
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
Labels: bug, Cherry-Pick

#2983 Bugs #14962: fix path for Pastis API call
  ui/ui-frontend/projects/pastis/src/app/core/services/archival-profile-unit-api.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/archive-profile-api.service.ts
Labels: bug, small

#2982 Story #14858: Fix external archiving system configuration
  deployment/roles/vitamui/tasks/referential.yml
  deployment/roles/vitamui/templates/referential/application.yml.j2
  docs/fr/exploitation/sections/external_archiving_systems.md
Labels: bug, OPS REVIEW
