Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-04, with the labels that each got.

#2621 CP 8.0 - Bug #14316 [Archiving Profile] Unable to save a PA modification.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small, Cherry-Pick

#2582 Bug #14462: Fix multi-select and ingest contract tabs
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select/select.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select/select.component.ts
Labels: bug

#2627 Bug #14462: Fix form when formatType is null
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select/select.component.ts
Labels: bug

#2629 CP V7.1 - Bug #13821: Fix host-name certificate migration
  deployment/environments/group_vars/all/vitamui_vars.yml
  deployment/pki/scripts/lib/certs.sh
  deployment/roles/nginx_webapp/tasks/install.yml
  deployment/roles/vitamui/handlers/main.yml
  deployment/roles/vitamui/tasks/archive-search-internal.yml
  deployment/roles/vitamui/tasks/collect-internal.yml
  deployment/roles/vitamui/tasks/copy_internal_ontology_fields.yml
  deployment/roles/vitamui/tasks/copy_ontologies.yml
  deployment/roles/vitamui/tasks/iam-internal.yml
  deployment/roles/vitamui/tasks/ingest-internal.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/referential-internal.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-external/application.yml.j2
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/collect-external/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-external/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
  docs/fr/migration/index.rst
  docs/fr/migration/update_v7_1.md
  docs/fr/migration/upgrade_v7_1.md
Labels: bug, Cherry-Pick, OPS REVIEW

#2635 Story #14381: Update COTS to latest available versions.
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/customer/service/InitCustomerServiceIntegrationTest.java
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
  deployment/ansible-vitamui-migration/migration_mongodb_80.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/logstash/defaults/main.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW

#2620 Bugs #14491: correctly enable security
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/security/IamApiAuthenticationProvider.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/security/WebSecurityConfig.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/ExternalParamProfileControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/ExternalParamProfileExternalControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/ProfileControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/TenantControllerTest.java
Labels: bug

#2633 Bug #13168: fix duplicate profiles
  deployment/scripts/mongod/1.0.0/222_pastis_profiles_ref.js.j2
Labels: bug, small

#2634 Story #13791: Cleanup mongo scripts for V8.1.0
  deployment/scripts/mongod/v8.1/0-00_security.populate_certificates.js.j2
  deployment/scripts/mongod/v8.1/0-01_update_iam_context.js.j2
  deployment/scripts/mongod/v8.1/0-02_update_archive_search_app.js.j2
  deployment/scripts/mongod/v8.1/0-03_update_ontology_app.js.j2
  deployment/scripts/mongod/v8.1/0-04_update_collect_app.js.j2
  deployment/scripts/mongod/v8.1/001_add_import_schema_role.js.j2
  deployment/scripts/mongod/v8.1/002_add_role_get_archive_profiles_unit_on_archive_search.js.j2
  deployment/scripts/mongod/v8.1/003_update_ontology_with_role_get_schema.js.j2
  deployment/scripts/mongod/v8.1/004_add_read_agencies_and_aups_to_archive_search_and_collect.js.j2
  deployment/scripts/mongod/v8.1/005_add_ontology_consultation_and_schema_management_roles.js.j2
  deployment/scripts/mongod/v8.1/006_add_delete_schema_role.js.j2
  deployment/scripts/mongod/v8.1/007_add_role_get_filling_plan_access_on_archive_search.js.j2
  deployment/scripts/mongod/v8.1/008_add_iam_context_ref.js.j2
  deployment/scripts/mongod/v8.1/008_update_collect_context_to_add_reclassification_role.js.j2
  deployment/scripts/mongod/v8.1/009_add_delete_archive_unit_role_on_collect.js.j2
Labels: OPS REVIEW, clean Code

#2639 Bug #14486 [COLLECTE | Reclassification ] : The 'Unassigned' folder does not appear after removing the parent folder.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#2632 CP V7.1 - Bug #14486 [COLLECTE | Reclassification ] : The 'Unassigned' folder does not appear after removing the parent folder.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/services/archive-shared-data.service.ts
Labels: bug, Cherry-Pick

#2642 Bugs #14245: remove two useless actions from menu
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2649 Bug #13168: fix duplicate profiles identifier
  deployment/scripts/mongod/7.0/02_fix_duplicate_profiles_identifier.js.j2
Labels: bug, small, VAS

#2645 CP V7.1 - Bug #13168: fix duplicate profiles identifier
  deployment/scripts/mongod/1.0.0/222_pastis_profiles_ref.js.j2
  deployment/scripts/mongod/7.0/02_fix_duplicate_profiles_identifier.js.j2
Labels: bug, small, VAS, Cherry-Pick

#2641 CP V8.0 - Bug #13168: fix duplicate profiles identifier
  deployment/scripts/mongod/1.0.0/222_pastis_profiles_ref.js.j2
  deployment/scripts/mongod/7.0/02_fix_duplicate_profiles_identifier.js.j2
Labels: bug, small, VAS, Cherry-Pick

#2580 story #14373: fix action boutton
  ui/ui-frontend/projects/referential/src/app/logbook-management-operation/logbook-management-operation-preview/logbook-management-operation-preview.component.html
Labels: small, VAS

#2647 CP V7.1 - Bugs #14245: remove two useless actions from menu
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
Labels: bug, small, Cherry-Pick

#2648 CP V7.0 - Bugs #14245: remove two useless actions from menu
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
Labels: bug, small, Cherry-Pick

#2618 Bug #14398: Prevent modifying internal ontology and fix multiselect when selected options are set before all options
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ontology/ontology-preview/ontology-information-tab/ontology-information-tab.component.ts
  ui/ui-frontend/projects/vitamui-library/src/lib/components/select/select.component.ts
Labels: bug

#2638 Bug #14462: Fix tabs validation for ingest contract update
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
Labels: bug

#2658 Bugs #14543: allow MD edition after closing preview pane
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
Labels: bug, small

#2659 CP V8.0 - Bugs #14543: allow MD edition after closing preview pane
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
Labels: bug, small, Cherry-Pick

#2660 CP V7.1 - Bugs #14543: allow MD edition after closing preview pane
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/archive-preview.component.ts
Labels: bug, small, Cherry-Pick

#2666 bug #14556 : Word Typo
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: small

#2667 Bugs #14334: reactivate external identifiers configuration
  deployment/roles/vitamui/templates/iam/application.yml.j2
Labels: bug, small, OPS REVIEW

#2672 Bugs #14334: list-enable-external-identifiers should be configured on iam-internal, not iam-external
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
Labels: bug, small, OPS REVIEW

#2673 CP V7.1 - Bugs #14334: list-enable-external-identifiers should be configured on iam-internal, not iam-external
  deployment/roles/vitamui/templates/iam-external/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#2652 Bug #13371: Accept user email ignoring cases
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/IamUtils.java
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/IdentityProviderHelper.java
  api/api-iam/iam-commons/src/test/java/fr/gouv/vitamui/iam/common/utils/IdentityProviderHelperTest.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/common/ApiIamExternalConstants.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/user/service/UserService.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/user/service/UserServiceTest.java
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolver.java
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/ListCustomersAction.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolverTest.java
Labels: bug, small, VAS

#2682 Bug #13371: Accept user email ignoring cases
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolverTest.java
Labels: bug, small, VAS, Cherry-Pick

#2684 bug #14602 : Missing translation key in Collect
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: small

#2679 Bugs #14579: avoid CSV formula injection
  api/api-referential/referential/pom.xml
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/utils/ExportCSVUtils.java
  api/api-referential/referential/src/test/java/fr/gouv/vitamui/referential/server/service/utils/ExportCSVUtilsTest.java
Labels: bug

#2680 CP V8.0 - Bugs #14579: avoid CSV formula injection
  api/api-referential/referential-internal/pom.xml
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ExportCSVUtils.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/utils/ExportCSVUtilsTest.java
Labels: bug, Cherry-Pick

#2681 CP V7.1 - Bugs #14579: avoid CSV formula injection
  api/api-referential/referential-internal/pom.xml
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/utils/ExportCSVUtils.java
  api/api-referential/referential-internal/src/test/java/fr/gouv/vitamui/referential/internal/server/utils/ExportCSVUtilsTest.java
Labels: bug, Cherry-Pick

#2683 Bugs #14576: modify snackbar message for operation status change request
  ui/ui-frontend/projects/referential/src/assets/i18n/en.json
  ui/ui-frontend/projects/referential/src/assets/i18n/fr.json
Labels: bug, small

#2677 bug #14532 : Reclassification error
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug

#2687 bug #14504: fix error 500 on search collect
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/service/TransactionArchiveUnitService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug

#2688 Bugs #14245: remove yet another useless action from menu
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2689 CP V8.0 - Bugs #14245: remove yet another useless action from menu
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small, Cherry-Pick

#2691 CP V7.0 - Bugs #14245: remove yet another useless action from menu
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
Labels: bug, small, Cherry-Pick

#2675 bug #14554 : Missing filter boxes
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-by-mgt-rules/access-rule-search/access-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-by-mgt-rules/appraisal-rule-search/appraisal-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-by-mgt-rules/dissemination-rule-search/dissemination-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-by-mgt-rules/reuse-rule-search/reuse-rule-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search-by-mgt-rules/storage-rule-search/storage-rule-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/access-rule-search/access-rule-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/appraisal-rule-search/appraisal-rule-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/dissemination-rule-search/dissemination-rule-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/reuse-rule-search/reuse-rule-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/storage-rule-search/storage-rule-search.component.ts
Labels: bug

#2669 CP V7.1 - Bug #14462: Fix multi-select and ingest contract tabs
  ui/ui-frontend-common/src/app/modules/components/autocomplete/vitamui-autocomplete-multi-select/vitamui-autocomplete-multi-select.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
Labels: bug

#2678 CP V8.0 - Bug #14462: Fix multi-select and ingest contract tabs
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-format-tab/ingest-contract-format-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-heritage-tab/ingest-contract-heritage-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-information-tab/ingest-contract-information-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-object-tab/ingest-contract-object-tab.component.ts
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.html
  ui/ui-frontend/projects/referential/src/app/ingest-contract/ingest-contract-preview/ingest-contract-preview.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/autocomplete/vitamui-autocomplete-multi-select/vitamui-autocomplete-multi-select.component.ts
Labels: bug, Cherry-Pick

#2625 Bug #14273: Prevent overflow of table results in archive search app
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive.module.ts
  ui/ui-frontend/projects/design-system/src/app/components/atoms/buttons/buttons.component.ts
  ui/ui-frontend/projects/design-system/src/app/components/organisms/table/table.component.html
  ui/ui-frontend/projects/design-system/src/assets/i18n/en.json
  ui/ui-frontend/projects/design-system/src/assets/i18n/fr.json
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-menu-button/vitamui-menu-button.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/object-editor/components/group-editor/group-editor.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/pipes/unitI18n.pipe.ts
  ui/ui-frontend/projects/vitamui-library/src/sass/_button.scss
  ui/ui-frontend/projects/vitamui-library/src/sass/_table.scss
Labels: bug

#2685 Bugs #14474: ensure that client certificate is sent to IAM and do not allow anonymous authentication
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/ApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/service/SecurityService.java
  deployment/roles/vitamui/templates/archive-search/application.yml.j2
  deployment/roles/vitamui/templates/collect/application.yml.j2
  deployment/roles/vitamui/templates/ingest/application.yml.j2
  deployment/roles/vitamui/templates/pastis/application.yml.j2
  deployment/roles/vitamui/templates/referential/application.yml.j2
Labels: bug, OPS REVIEW

#2701 Bug #14273: fix infinite scroll
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
Labels: bug

#2671 CP V8.0 - Bug #14457 : Fix api-gateway certificate validation
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW

#2676 Bug #14486 [External MDD] MDDs are not saved after modification in the Search APP; a required field appears in edit mode.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/archive-unit/components/archive-unit-editor/archive-unit-editor.service.ts
Labels: bug, small

#2714 Bug #14532 [Collect Reclassement] When UAs have no parent, the 'Move' and 'Remove to another parent folder' actions should be greyed out.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#2707 Bug #14530 [Collect] The number of UAs linked to a position is not visible in the tree structure.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/archive-shared-data.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/nodes/filing-holding-scheme.handler.ts
Labels: bug

#2715 Bug #14467: display object information if archive unit is RecordGrp
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-preview/collect-object-group-details-tab/collect-object-group-details-tab.component.ts
Labels: bug

#2717 Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#2705 CP V8.0 - bug #14504: fix error 500 on search collect
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, Cherry-Pick

#2706 CP V7.1 - bug #14504: fix error 500 on search collect
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
Labels: bug, Cherry-Pick

#2700 Bug #14578: add controls to check the access to tenants
  api/api-archive-search/archive-search/src/main/java/fr/gouv/vitamui/archives/search/server/security/WebSecurityConfig.java
  api/api-archive-search/archive-search/src/main/resources/application-dev.yml
  api/api-archive-search/archive-search/src/test/java/fr/gouv/vitamui/archives/search/server/rest/ApiArchiveSearchControllerTest.java
  api/api-collect/collect/src/main/java/fr/gouv/vitamui/collect/server/security/WebSecurityConfig.java
  api/api-collect/collect/src/main/resources/application-dev.yml
  api/api-collect/collect/src/test/java/fr/gouv/vitamui/collect/server/rest/ApiCollectControllerTest.java
  api/api-collect/collect/src/test/java/fr/gouv/vitamui/collect/server/rest/TransactionArchiveUnitControllerTest.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/ApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/security/WebSecurityConfig.java
  api/api-iam/iam/src/main/resources/application-dev.yml
  api/api-iam/iam/src/main/resources/application.yml
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/common/rest/ApiIamControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/GroupExternalControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/ProfileControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/ProfileExternalControllerTest.java
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/rest/UserExternalControllerTest.java
  api/api-iam/iam/src/test/resources/application.yml
  api/api-ingest/ingest/src/main/java/fr/gouv/vitamui/ingest/server/security/WebSecurityConfig.java
  api/api-ingest/ingest/src/main/resources/application-dev.yml
  api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/security/WebSecurityConfig.java
  api/api-pastis/pastis/src/main/resources/application-dev.yml
  api/api-pastis/pastis/src/test/java/fr/gouv/vitamui/pastis/server/rest/ControllerTest.java
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/security/WebSecurityConfig.java
  api/api-referential/referential/src/main/resources/application-dev.yml
  api/api-referential/referential/src/test/java/fr/gouv/vitamui/referential/server/rest/ApiReferentialControllerTest.java
  deployment/roles/vitamui/templates/archive-search/application.yml.j2
  deployment/roles/vitamui/templates/collect/application.yml.j2
  deployment/roles/vitamui/templates/iam/application.yml.j2
  deployment/roles/vitamui/templates/ingest/application.yml.j2
  deployment/roles/vitamui/templates/pastis/application.yml.j2
  deployment/roles/vitamui/templates/referential/application.yml.j2
Labels: bug, VAS

#2704 Bug #14316: fix archive profile update
  ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
Labels: bug

#2712 Story #14381: Update COTS to latest available versions before releasing.
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/customer/service/InitCustomerServiceIntegrationTest.java
  commons/commons-test/src/test/java/fr/gouv/vitamui/commons/test/AbstractMongoTests.java
  deployment/ansible-vitamui-migration/migration_mongodb_80.yml
  deployment/roles/consul/vars/main.yml
  deployment/roles/filebeat/defaults/main.yml
  deployment/roles/logstash/defaults/main.yml
  deployment/roles/mongo/templates/vitamui-container-mongod.service.j2
  tools/docker/mongo/mongo_cluster.yml
  tools/docker/mongo/mongo_dev.yml
Labels: OPS REVIEW

#2709 Bug #14273: improve new table style
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-preview/archive-preview.component.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.html
  ui/ui-frontend/projects/design-system/src/app/components/organisms/table/table.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sup-header/vitamui-sup-header.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sup-header/vitamui-sup-header.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sup-header/vitamui-sup-header.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sup-header/vitamui-sup-header.module.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/vitamui-common.module.ts
  ui/ui-frontend/projects/vitamui-library/src/public-api.ts
  ui/ui-frontend/projects/vitamui-library/src/sass/_table.scss
Labels: clean Code

#2662 CP V7.1 - Bug #13371: Accept user email ignoring cases
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/IamUtils.java
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/utils/IdentityProviderHelper.java
  api/api-iam/iam-commons/src/test/java/fr/gouv/vitamui/iam/common/utils/IdentityProviderHelperTest.java
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolver.java
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/ListCustomersAction.java
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/authentication/UserPrincipalResolverTest.java
Labels: bug, small, VAS, Cherry-Pick

#2718 Bug #14532 [Collect Reclassement] When UAs have no parent, the 'Move' and 'Remove to another parent folder' actions should be greyed out. (have the same behavior as in the Search app)
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small

#2613 CP V7.1 - Bug #11665 [COLLECTE] - Modification of project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, Cherry-Pick

#2614 CP V7.0 - Bug #11665 [COLLECTE] - Modification of project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, Cherry-Pick

#2611 CP V8.0 - Bug #11665 [COLLECTE] - Modification of project.
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.component.html
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, Cherry-Pick

#2713 CP V7.1 - Bug #14457 : Fix api-gateway certificate validation
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
  deployment/roles/vitamui/templates/api-gateway/application.yml.j2
Labels: bug, Cherry-Pick, OPS REVIEW
