Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-06, with the labels that each got.

#2803 Bug #14677 - [Collect] The 'Submit' button remains active after validating a transaction in automatic flow mode with the 'Automatic transaction management' option enabled, until the page is refreshed.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, small

#2807 CP V7.0 - Bug #14677 - [Collect] The 'Submit' button remains active after validating a transaction in automatic flow mode with the 'Automatic transaction management' option enabled, until the page is refreshed.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, small, Cherry-Pick

#2805 CP V8.0 - Bug #14677 - [Collect] The 'Submit' button remains active after validating a transaction in automatic flow mode with the 'Automatic transaction management' option enabled, until the page is refreshed.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, small, Cherry-Pick

#2809 CP V8.1 - Bug #14763 : Pastis Notice creation - cancel button
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
Labels: Cherry-Pick

#2815 CP V7.1 - Bug #14725: fix Jenkinsfile
  Jenkinsfile
  Jenkinsfile.containers
  pom.xml
Labels: bug, Cherry-Pick

#2816 CP V7.0 - BUG #14754 - [Collect] KO when modifying a PUA with metadata addition.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small, Cherry-Pick

#2821 CP V8.1 - Bug #14582 : Control button - rollback
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Labels: Cherry-Pick

#2822 CP V8.0 - Bug #14582 : Control button - rollback
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Labels: Cherry-Pick

#2824 CP V7.1 - Bug #14582 : Control button - rollback
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Labels: Cherry-Pick

#2830 CP V8.1 - Bug #14804: Properly update ressources for ui-identity-admin during upgrade.
  deployment/roles/nginx_webapp/tasks/install.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2832 CP V7.1 - Bug #14804: Properly update ressources for ui-identity-admin during upgrade.
  deployment/roles/nginx_webapp/tasks/install.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2841 Bug #14822: Execute api-gw configuration after creating expected directories.
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
Labels: bug, small, OPS REVIEW

#2813 Bug #14456 : Collect navigation issue between projects
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.service.ts
Labels: bug

#2844 CP V8.1 - Bug #14822: Execute api-gw configuration after creating expected directories.
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2845 CP V8.0 - Bug #14822: Execute api-gw configuration after creating expected directories.
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2846 CP V7.1 - Bug #14822: Execute api-gw configuration after creating expected directories.
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2854 CP V8.1 - Bugs #14834: do not clear managementContractId if not sent in patch query
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/ingestcontract/IngestContractService.java
Labels: bug, Cherry-Pick

#2855 CP V8.0 - Bugs #14834: do not clear managementContractId if not sent in patch query
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
Labels: bug, Cherry-Pick

#2857 CP V7.0 - Bugs #14834: do not clear managementContractId if not sent in patch query
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/ingestcontract/IngestContractInternalService.java
Labels: bug, Cherry-Pick

#2862 Bug #14840 - [Collect] Unable to create a key/value project in Collect – error at step 6/7.
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: bug, small

#2849 CP V7.0 - Bug #14677 & #14831 - [Collect] The 'Submit' button remains active after validating a transaction in automatic flow mode with the 'Automatic transaction management' option enabled, until the page is refreshed.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
Labels: bug, Cherry-Pick

#2850 CP V7.1 - Bug #14677 & #14831 - [Collect] The 'Submit' button remains active after validating a transaction in automatic flow mode with the 'Automatic transaction management' option enabled, until the page is refreshed.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.html
  ui/ui-frontend/projects/collect/src/app/collect/transactions/transaction-list/transaction-list.component.ts
Labels: bug, Cherry-Pick

#2860 CP V7.0 - Bug #14492: Prevent using patch_me API
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/rest/RestApi.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  ui/ui-frontend-common/src/app/modules/account/account-api.service.spec.ts
  ui/ui-frontend-common/src/app/modules/account/account-api.service.ts
  ui/ui-frontend-common/src/app/modules/account/account-information-tab/account-information-tab.component.ts
  ui/ui-frontend-common/src/app/modules/account/account.service.ts
Labels: bug, Cherry-Pick

#2858 CP V8.0 - Bug #14492: Prevent using patch_me API
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/rest/RestApi.java
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account-api.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account-information-tab/account-information-tab.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account.service.ts
Labels: bug, Cherry-Pick

#2852 Bug #14833: ui components are not properly installed in expected directories.
  deployment/roles/nginx_webapp/tasks/install.yml
  deployment/roles/nginx_webapp/tasks/uninstall.yml
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
  tools/packaging/Makefile-fronts
Labels: bug, small, VAS, OPS REVIEW

#2863 CP V8.1 - Bug #14456 : Collect navigation issue between projects
  ui/ui-frontend/projects/collect/src/app/collect/projects/project-preview/project-preview.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/projects.service.ts
Labels: bug, Cherry-Pick

#2864 CP V8.1 - Bug #14833: ui components are not properly installed in expected directories.
  deployment/roles/nginx_webapp/tasks/install.yml
  deployment/roles/nginx_webapp/tasks/uninstall.yml
  deployment/roles/nginx_webapp/templates/frontend/vhost.conf.j2
  tools/packaging/Makefile-fronts
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2875 Bug #14813: CAS Token configuration
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/provider/ApiAuthenticationProvider.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/security/IamAuthentificationService.java
  api/api-iam/iam/src/main/resources/application-dev.yml
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/user/service/UserServiceIntegrationTest.java
  api/api-iam/iam/src/test/resources/application.yml
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/AppConfig.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/AbstractUiRestController.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/HttpContext.java
  deployment/environments/group_vars/all/vault-vitamui.yml
  deployment/environments/group_vars/all/vault-vitamui.yml.example
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/iam/application.yml.j2
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
  deployment/scripts/mongod/1.0.0/321_delete_cas_token.js.j2
  docs/fr/migration/update_v7_1.md
  docs/fr/migration/update_v8_0.md
  docs/fr/migration/upgrade_v7_1.md
  docs/fr/migration/upgrade_v8_0.md
  docs/fr/migration/upgrade_v8_1.md
Labels: bug

#2833 Bug #14760: Fix export users missing role
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/rest/UserController.java
Labels: bug

#2876 Bug #14765: Fix IDP config update missing role
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/rest/IdentityProviderController.java
Labels: bug

#2871 CP V8.1 - Story #14814: Add Rocky Linux 9 support.
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/docker/tasks/RedHat.yml
  deployment/roles/docker/tasks/main.yml
  deployment/roles/merge_index_apache/tasks/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo_common/tasks/main.yml
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/vitamui/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2872 CP V8.0 - Story #14814: Add Rocky Linux 9 support.
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/docker/tasks/RedHat.yml
  deployment/roles/docker/tasks/main.yml
  deployment/roles/merge_index_apache/tasks/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo_common/tasks/main.yml
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/vitamui/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2873 CP V7.1 - Story #14814: Add Rocky Linux 9 support.
  deployment/environments/group_vars/all/repositories.yml
  deployment/roles/bootstrap_repo/tasks/main.yml
  deployment/roles/consul/tasks/main.yml
  deployment/roles/docker/tasks/RedHat.yml
  deployment/roles/docker/tasks/main.yml
  deployment/roles/merge_index_apache/tasks/main.yml
  deployment/roles/mongo-express/tasks/main.yml
  deployment/roles/mongo_common/tasks/main.yml
  deployment/roles/mongodb_upgrade_package/tasks/update_packages_mongod.yml
  deployment/roles/reverse/tasks/apache/apache.yml
  deployment/roles/vitamui/tasks/main.yml
Labels: Cherry-Pick, OPS REVIEW

#2879 CP V8.1 - Bug #14760: Fix export users missing role
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/rest/UserController.java
Labels: bug, Cherry-Pick

#2878 CP V8.1 - Bug #14813: CAS Token configuration
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/provider/ApiAuthenticationProvider.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/security/IamAuthentificationService.java
  api/api-iam/iam/src/main/resources/application-dev.yml
  api/api-iam/iam/src/test/java/fr/gouv/vitamui/iam/server/user/service/UserServiceIntegrationTest.java
  api/api-iam/iam/src/test/resources/application.yml
  cas/cas-server/src/main/config/cas-server-application-dev.yml
  cas/cas-server/src/main/config/cas-server-application-recette.yml
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/config/AppConfig.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/AbstractUiRestController.java
  commons/commons-rest/src/main/java/fr/gouv/vitamui/commons/rest/client/HttpContext.java
  deployment/environments/group_vars/all/vault-vitamui.yml
  deployment/environments/group_vars/all/vault-vitamui.yml.example
  deployment/roles/vitamui/templates/cas-server/application.yml.j2
  deployment/roles/vitamui/templates/iam/application.yml.j2
  deployment/scripts/mongod/1.0.0/01_iam_ref.js.j2
  deployment/scripts/mongod/1.0.0/321_delete_cas_token.js.j2
  docs/fr/migration/update_v7_1.md
  docs/fr/migration/update_v8_0.md
  docs/fr/migration/upgrade_v7_1.md
  docs/fr/migration/upgrade_v8_0.md
  docs/fr/migration/upgrade_v8_1.md
Labels: bug, Cherry-Pick

#2888 CP V8.0 - Bug #14760: Fix export users missing role
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/UserExternalController.java
Labels: bug, Cherry-Pick

#2890 Story #14820: Add deployment check for cas secret token.
  deployment/roles/checks/tasks/check_passwords.yml
Labels: small, OPS REVIEW

#2882 Bug #14872: Missing translation keys for security operations.
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2891 CP V8.1 - Bug #14872: Missing translation keys for security operations.
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small, Cherry-Pick

#2894 CP V7.1 - Bug #14765: Fix IDP config update missing role
  api/api-iam/iam-external/src/main/java/fr/gouv/vitamui/iam/external/server/rest/IdentityProviderExternalController.java
Labels: bug, Cherry-Pick

#2896 CP V7.1 - Bug #14813: Remove old dropIndex commands.
  deployment/scripts/mongod/v7.1/002_TRV-389_add_index_on_updatedDate_field_of_tokens_collection_ref.js
Labels: bug, small, Cherry-Pick, OPS REVIEW

#2898 CP V8.1 - Bug #14853: Add missing translation keys for preservation operations.
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small, Cherry-Pick

#2900 Story #14811: Bump version from 8.1.1-SNAPSHOT to 8.1.2-SNAPSHOT on master_8.1.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search/pom.xml
  api/api-archive-search/pom.xml
  api/api-collect/collect/pom.xml
  api/api-collect/pom.xml
  api/api-gateway/pom.xml
  api/api-iam/iam-client/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/iam/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest/pom.xml
  api/api-ingest/pom.xml
  api/api-pastis/pastis-commons/pom.xml
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis/pom.xml
  api/api-pastis/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security/pom.xml
  api/pom.xml
  bom/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-mongo-express/pom.xml
  deployment/environments/group_vars/all/repositories.yml
  deployment/pom.xml
  packaging/pom.xml
  pom.xml
Labels: OPS REVIEW

#2901 Story #14907: Do not compile executed scripts during mongo_init.
  deployment/roles/mongo_init/tasks/main.yml
  deployment/roles/mongo_init/tasks/prepare_script.yml
Labels: OPS REVIEW
