Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-05, with the labels that each got.

#2724 CP V7.0 - Bug #14578: add controls to check the access to tenants
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/security/WebSecurityConfig.java
  api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalControllerTest.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/security/WebSecurityConfig.java
  api/api-collect/collect-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/security/WebSecurityConfig.java
  api/api-iam/iam-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/common/rest/ApiIamControllerTest.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/AbstractApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/ExternalApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/InternalApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/security/WebSecurityConfig.java
  api/api-ingest/ingest-internal/src/main/resources/application-dev.yml
  api/api-ingest/ingest-internal/src/test/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalControllerTest.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/security/WebSecurityConfig.java
  api/api-referential/referential-internal/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
Labels: bug, VAS, Cherry-Pick

#2710 CP V8.0 - Bug #14578: add controls to check the access to tenants
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/security/WebSecurityConfig.java
  api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalControllerTest.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/security/WebSecurityConfig.java
  api/api-collect/collect-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/security/WebSecurityConfig.java
  api/api-iam/iam-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/common/rest/ApiIamControllerTest.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/AbstractApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/ExternalApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/InternalApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/security/WebSecurityConfig.java
  api/api-ingest/ingest-internal/src/main/resources/application-dev.yml
  api/api-ingest/ingest-internal/src/test/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalControllerTest.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/security/WebSecurityConfig.java
  api/api-referential/referential-internal/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
Labels: bug, VAS, Cherry-Pick

#2723 CP V7.1 - Bug #14578: add controls to check the access to tenants
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/security/WebSecurityConfig.java
  api/api-archive-search/archive-search-internal/src/main/resources/application-dev.yml
  api/api-archive-search/archive-search-internal/src/test/java/fr/gouv/vitamui/archive/internal/server/rest/ArchiveSearchInternalControllerTest.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/security/WebSecurityConfig.java
  api/api-collect/collect-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/main/java/fr/gouv/vitamui/iam/internal/server/security/WebSecurityConfig.java
  api/api-iam/iam-internal/src/main/resources/application-dev.yml
  api/api-iam/iam-internal/src/test/java/fr/gouv/vitamui/iam/internal/server/common/rest/ApiIamControllerTest.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/AbstractApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/ExternalApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/config/InternalApiWebSecurityConfig.java
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
  api/api-ingest/ingest-internal/src/main/java/fr/gouv/vitamui/ingest/internal/server/security/WebSecurityConfig.java
  api/api-ingest/ingest-internal/src/main/resources/application-dev.yml
  api/api-ingest/ingest-internal/src/test/java/fr/gouv/vitamui/ingest/internal/server/rest/IngestInternalControllerTest.java
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/security/WebSecurityConfig.java
  api/api-referential/referential-internal/src/main/resources/application-dev.yml
  deployment/roles/vitamui/templates/archive-search-internal/application.yml.j2
  deployment/roles/vitamui/templates/collect-internal/application.yml.j2
  deployment/roles/vitamui/templates/iam-internal/application.yml.j2
  deployment/roles/vitamui/templates/ingest-internal/application.yml.j2
  deployment/roles/vitamui/templates/pastis-external/application.yml.j2
  deployment/roles/vitamui/templates/referential-internal/application.yml.j2
Labels: bug, VAS, Cherry-Pick

#2719 Bug #14492: Prevent using patch_me API
  api/api-iam/iam-commons/src/main/java/fr/gouv/vitamui/iam/common/rest/RestApi.java
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/rest/UserController.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/domain/ServicesData.java
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account-api.service.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account-api.service.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account-information-tab/account-information-tab.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/account/account.service.ts
Labels: bug

#2727 bug #14697 : Missing translation keys
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug

#2729 Bug #14704: Fix typo in Pastis role.
  deployment/roles/vitamui/files/customer-init.yml
  deployment/scripts/mongod/2.0.0/57_fix_typo_pastis_role.js.j2
  docs/fr/architecture/sections/architecture.md
Labels: bug, small, Security

#2731 CP V7.0 - Bug #14410 [Collecte] - UA types "Static Attachment" and "Dynamic Attachment" should no longer appear in the Collection panels.
  api/api-archive-search/archive-search-internal/src/main/java/fr/gouv/vitamui/archive/internal/server/service/ArchiveSearchInternalService.java
  api/api-collect/collect-internal/src/main/java/fr/gouv/vitamui/collect/internal/server/service/TransactionArchiveUnitInternalService.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/ArchiveSearchConsts.java
  commons/commons-api/src/main/java/fr/gouv/vitamui/commons/api/utils/MetadataSearchCriteriaUtils.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, Cherry-Pick

#2730 Bug #14578: improve exception mgt on getting expired context
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
Labels: bug, small, VAS

#2739 CP V7.0 - Bug #14578: improve exception mgt on getting context
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
Labels: bug, small, VAS, Cherry-Pick

#2738 CP V7.1 - Bug #14578: improve exception mgt on getting context
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
Labels: bug, small, VAS, Cherry-Pick

#2736 CP V8.0 - Bug #14578: improve exception mgt on getting context
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
Labels: bug, small, VAS, Cherry-Pick

#2740 Bug #14694: fix wrong behavior on track total hits settings for collect
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/collect/CollectService.java
  commons/commons-vitam/src/main/java/fr/gouv/vitamui/commons/vitam/api/util/VitamRestUtils.java
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, small, VAS

#2726 bug #14582 : control button bug
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Labels: bug

#2732 Bug #14663: translate others criteria chips in archive search app
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.html
  ui/ui-frontend/projects/archive-search/src/app/archive/criteria-search/criteria-search.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/criteria/search-criteria.service.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug

#2741 Bug #14530 [Collect] The number of UAs linked to a position is not visible in the tree structure.
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-criteria/components/filing-holding-scheme/filing-holding-scheme.component.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/nodes/filing-holding-scheme.handler.ts
Labels: bug, small

#2742 bug #14702 : Access contracts toggle bug
  api/api-referential/referential/src/main/java/fr/gouv/vitamui/referential/server/service/accesscontract/AccessContractService.java
Labels: bug

#2725 Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, small

#2744 Bugs #14707: use correct message key on notice creation
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
Labels: bug, small

#2746 CP V7.1 - Bugs #14707: use correct message key on notice creation
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
Labels: bug, small, Cherry-Pick

#2745 CP V8.0 - Bugs #14707: use correct message key on notice creation
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
Labels: bug, small, Cherry-Pick

#2747 Bug #14650: get the right version of seda from uploaded PUA
  api/api-pastis/pastis/src/main/java/fr/gouv/vitamui/pastis/server/service/PastisService.java
Labels: bug

#2752 CP V7.1 - bug #14582 : control button bug
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Labels: bug, small, Cherry-Pick

#2751 CP V8.0 - bug #14582 : control button bug
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/additional-actions-search/management-rules/archive-unit-rules/update-unit-rules/update-unit-rules.component.html
Labels: bug, small, Cherry-Pick

#2749 Bug #14669 - [PASTIS] The "Allow metadata" toggle is not saved when creating/updating a PUA.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug

#2748 bug #14370 : Reclassification popup treshold
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.spec.ts
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.scss
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.spec.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug

#2750 CP V8.0 - bug #14702 : Access contracts toggle bug
  api/api-referential/referential-internal/src/main/java/fr/gouv/vitamui/referential/internal/server/accesscontract/AccessContractInternalService.java
Labels: bug, small, Cherry-Pick

#2756 AP #14711: Set up version from 8.1.0-SNAPSHOT to 9.0.0-SNAPSHOT
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search/pom.xml
  api/api-archive-search/pom.xml
  api/api-collect/collect/pom.xml
  api/api-collect/pom.xml
  api/api-gateway/pom.xml
  api/api-iam/iam-client/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/iam/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest/pom.xml
  api/api-ingest/pom.xml
  api/api-pastis/pastis-commons/pom.xml
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis/pom.xml
  api/api-pastis/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security/pom.xml
  api/pom.xml
  bom/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-mongo-express/pom.xml
  deployment/environments/group_vars/all/repositories.yml
  deployment/pom.xml
  packaging/pom.xml
  pom.xml
Labels: OPS REVIEW

#2757 AP #14711: Bump version from 8.1.0-SNAPSHOT to 8.1.1-SNAPSHOT on master_8.1.x
  api/api-archive-search/archive-search-commons/pom.xml
  api/api-archive-search/archive-search/pom.xml
  api/api-archive-search/pom.xml
  api/api-collect/collect/pom.xml
  api/api-collect/pom.xml
  api/api-gateway/pom.xml
  api/api-iam/iam-client/pom.xml
  api/api-iam/iam-commons/pom.xml
  api/api-iam/iam-security/pom.xml
  api/api-iam/iam/pom.xml
  api/api-iam/pom.xml
  api/api-ingest/ingest/pom.xml
  api/api-ingest/pom.xml
  api/api-pastis/pastis-commons/pom.xml
  api/api-pastis/pastis-standalone/pom.xml
  api/api-pastis/pastis/pom.xml
  api/api-pastis/pom.xml
  api/api-referential/pom.xml
  api/api-referential/referential-commons/pom.xml
  api/api-referential/referential/pom.xml
  api/api-security/pom.xml
  api/api-security/security-client/pom.xml
  api/api-security/security-commons/pom.xml
  api/api-security/security/pom.xml
  api/pom.xml
  bom/pom.xml
  cas/cas-server/pom.xml
  cas/pom.xml
  commons/commons-api/pom.xml
  commons/commons-logbook/pom.xml
  commons/commons-mongo/pom.xml
  commons/commons-rest/pom.xml
  commons/commons-security/pom.xml
  commons/commons-test/pom.xml
  commons/commons-utils/pom.xml
  commons/commons-vitam/pom.xml
  commons/pom.xml
  cots/pom.xml
  cots/vitamui-mongo-express/pom.xml
  deployment/environments/group_vars/all/repositories.yml
  deployment/pom.xml
  packaging/pom.xml
  pom.xml
Labels: OPS REVIEW

#2753 CP V8.0 - Bug #14669 - [PASTIS] The "Allow metadata" toggle is not saved when creating/updating a PUA.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, Cherry-Pick

#2754 CP V7.1 - Bug #14669 - [PASTIS] The "Allow metadata" toggle is not saved when creating/updating a PUA.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, Cherry-Pick

#2755 CP V7.0 - Bug #14669 - [PASTIS] The "Allow metadata" toggle is not saved when creating/updating a PUA.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/profile/list-profile/list-profile.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, Cherry-Pick

#2762 CP V8.1 - bug #14383 : Collect wording
  ui/ui-frontend/projects/collect/src/assets/i18n/en.json
  ui/ui-frontend/projects/collect/src/assets/i18n/fr.json
Labels: bug, small, Cherry-Pick

#2763 Bug #14724: Upgrade to proper <vitam.version> on bom/pom.xml.
  bom/pom.xml
Labels: bug, small

#2764 CP V8.1 - Bug #14724: Upgrade to proper <vitam.version> on bom/pom.xml.
  bom/pom.xml
Labels: bug, small

#2765 CP V8.0 - bug #14643 : Confirmation pop-in activation
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.spec.ts
  ui/ui-frontend/projects/referential/src/app/management-contract/management-contract-preview/management-contract-information-tab/management-contract-information-tab.component.ts
Labels: bug, Cherry-Pick

#2766 CP V7.0 - Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, Cherry-Pick

#2767 CP V7.1 - Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend-common/src/assets/shared-i18n/en.json
  ui/ui-frontend-common/src/assets/shared-i18n/fr.json
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
Labels: bug, Cherry-Pick

#2768 CP V8.0 - Bug #14420 [Collect & App Search] Saved filters are displayed as keys instead of being translated.
  ui/ui-frontend/projects/archive-search/src/app/archive/archive-search/archive-search.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: Cherry-Pick

#2776 CP V7.0 - Bug #13152: Problem with re-displaying a directory after deletion and attempting to re-import it in the upload area
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
Labels: bug, small, Cherry-Pick

#2774 CP V8.0 - Bug #14316: fix archive profile update
  ui/ui-frontend/projects/pastis/src/app/core/services/notice.service.ts
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
  ui/ui-frontend/projects/pastis/src/app/shared/pastis-popup-option/pastis-popup-option.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.html
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
  ui/ui-frontend/projects/pastis/src/app/user-actions/save-profile/save-profile.component.ts
  ui/ui-frontend/projects/pastis/src/assets/i18n/en.json
  ui/ui-frontend/projects/pastis/src/assets/i18n/fr.json
Labels: bug, Cherry-Pick

#2784 CP V7.0 - Bug #14578: update role name to access to another tenants due to existing role with same name
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
Labels: bug, small, VAS, Cherry-Pick

#2783 CP V7.1- Bug #14578: update role name to access to another tenants due to existing role
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
Labels: bug, small, VAS, Cherry-Pick

#2782 CP V8.0 - Bug #14578: update role name to access to another tenants due to exisitng same role
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
Labels: bug, small, VAS, Cherry-Pick

#2780 Bug #14578: update role name to access to another tenants due to existing role with same name
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
Labels: bug, small, VAS

#2781 CP V8.1- Bug #14578: update role name to access to another tenants due to existing role
  api/api-iam/iam-security/src/main/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilter.java
  api/api-iam/iam-security/src/test/java/fr/gouv/vitamui/iam/security/filter/TenantHeaderFilterTest.java
Labels: bug, small, VAS, Cherry-Pick

#2777 Bug #14739: Handle exceptions in collect when selecting more than 10,000 units to delete
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, VAS

#2772 CP V8.1 - Bug #14669 - [PASTIS] The "Allow metadata" toggle is not saved when creating/updating a PUA.
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, small, Cherry-Pick

#2771 CP V7.1 - Bug #14669 - [PASTIS] The "Allow metadata" toggle is not saved when creating/updating a PUA.
  ui/ui-frontend/projects/pastis/src/app/user-actions/create-notice/create-notice.component.ts
Labels: bug, small, Cherry-Pick

#2775 Bugs #14734: fix subrogation after openapi client migration
  api/api-iam/iam/src/main/java/fr/gouv/vitamui/iam/server/rest/CasController.java
Labels: bug, small

#2793 Bug #14744: Fix others ansible errors.
  deployment/roles/check_parent_structure/tasks/main.yml
  deployment/roles/init_troubleshoot/tasks/main.yml
Labels: bug, small, OPS REVIEW

#2796 CP V8.0 - Bug #14754 - [PASTIS] Creation of a PUA with archiving in the SAE is not possible.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small, Cherry-Pick

#2795 CP V7.1 - Bug #14754 - [PASTIS] Creation of a PUA with archiving in the SAE is not possible.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small, Cherry-Pick

#2798 CP V7.0 - Bug #14754 - [PASTIS] Creation of a PUA with archiving in the SAE is not possible.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small, Cherry-Pick

#2794 Bug #14754 - [PASTIS] Creation of a PUA with archiving in the SAE is not possible.
  ui/ui-frontend/projects/pastis/src/app/core/services/profile.service.ts
Labels: bug, small

#2769 Story #13529 [VITAM-UI] - Upgrade Java 17 -> 21.
  .github/workflows/build-and-test.yml
  Jenkinsfile
  Jenkinsfile.containers
  api/api-iam/iam-client/pom.xml
  api/api-pastis/pastis-commons/pom.xml
  api/api-pastis/pastis-commons/src/test/java/fr/gouv/vitamui/pastis/common/service/JsonFromPuaTest.java
  api/api-pastis/pastis-standalone/src/test/java/fr/gouv/vitamui/pastis/standalone/ProfileControllerTest.java
  bom/pom.xml
  cas/cas-server/pom.xml
  cas/cas-server/src/test/java/fr/gouv/vitamui/cas/webflow/actions/DispatcherActionTest.java
  deployment/roles/normalize/tasks/check_java.yml
  pom.xml
  tools/docker/vitamui-base/Dockerfile
Labels: enhancement, dependencies, java, Squash before merge

#2789 CP V8.1 - Bug #14744: Fix ansible errors.
  deployment/ansible-vitamui-exploitation/troubleshoot.yml
  deployment/roles/check_parent_structure/tasks/main.yml
  deployment/roles/init_troubleshoot/tasks/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW

#2790 CP V8.0 - Bug #14744: Fix ansible errors.
  deployment/ansible-vitamui-exploitation/troubleshoot.yml
  deployment/roles/check_parent_structure/tasks/main.yml
  deployment/roles/init_troubleshoot/tasks/main.yml
  deployment/roles/vitamui/tasks/main.yml
  deployment/roles/vitamui/tasks/prepare_api_gateway_conf.yml
Labels: bug, small, VAS, Cherry-Pick, OPS REVIEW
