Repository ProgrammeVitam/vitam-ui, pull requests merged in 2025-10, with the labels that each got.

#3172 Bugs #15055: 'DateType' is not supported, use 'date' instead
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.1.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pa_2.2.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pa_2.2_with_external_schema.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pua_2.3.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pua_2.3_with_external_schema.json
Labels: bug

#3181 Bugs #15172: ignore case for email comparison for password reset
  cas/cas-server/src/main/java/fr/gouv/vitamui/cas/webflow/actions/I18NSendPasswordResetInstructionsAction.java
Labels: bug, small

#3182 Bug #14974: prevent empty filter after clearing input
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-multi-inputs/vitamui-multi-inputs.component.ts
Labels: bug

#3173 CP V8.1 - Bugs #15055: 'DateType' is not supported, use 'date' instead
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.1.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.2.json
  api/api-pastis/pastis-commons/src/main/resources/metamodel/metamodel-2.3.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pa_2.2.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pa_2.2_with_external_schema.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pua_2.3.json
  api/api-pastis/pastis/src/test/resources/metamodel/expected_pua_2.3_with_external_schema.json
Labels: bug, Cherry-Pick

#3174 Bugs #14113: PreventInheritance and RefNonRuleId are mutually exclusive
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
Labels: bug

#3175 CP V8.1 - Bugs #14113: PreventInheritance and RefNonRuleId are mutually exclusive
  ui/ui-frontend/projects/pastis/src/app/user-actions/add-metadata/add-metadata.component.ts
Labels: bug, Cherry-Pick

#3183 CP V8.1 - Bug #15153: handle file selector max size validation
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/add-units/add-units.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.html
  ui/ui-frontend/projects/collect/src/app/collect/projects/create-project/create-project.component.ts
  ui/ui-frontend/projects/design-system/src/app/components/upload/upload.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.html
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.scss
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.spec.ts
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/file-selector/file-selector.component.ts
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/en.json
  ui/ui-frontend/projects/vitamui-library/src/assets/shared-i18n/fr.json
Labels: bug, Cherry-Pick

#3199 Bug #15180 : Translation, selection and results issues on Archive-search
  ui/ui-frontend/projects/vitamui-library/src/app/modules/models/criteria/search-criteria-configs.ts
Labels: bug, small

#3198 bugs #15192 fix(collect): transaction actions states
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.html
  ui/ui-frontend/projects/collect/src/app/collect/archive-search-collect/archive-search-collect.component.ts
  ui/ui-frontend/projects/collect/src/app/collect/core/api/project-api.service.ts
Labels: bug, VAS

#3178 CP V8.1 - Bug #14991 - [Security Operations] Missing tooltip when hovering over information icons in the "Operations Management" app.
  ui/ui-frontend/projects/vitamui-library/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.component.html
Labels: bug, small, Cherry-Pick

#3148 CP V7.1 - Bug #14991 - [Security Operations] Missing tooltip when hovering over information icons in the "Operations Management" app.
  ui/ui-frontend-common/src/app/modules/components/vitamui-sidenav-header/vitamui-sidenav-header.component.html
Labels: bug, Cherry-Pick

#3205 Story #14559 : Clean code - Avoid table overflow
  ui/ui-frontend/projects/vitamui-library/src/sass/_table.scss
Labels: javascript, small, VAS
